### ISSUE TITLE
Home page of https://site-patternfly.rhcloud.com/ doesn't look good with a dark desktop theme

### ISSUE THREAD

**Issue by metlos** [patternfly/patternfly-3#1]
Not sure if that is an issue with the theme itself or just that concrete page. 

The rest of the pages on the site look good - i.e. the background is white despite the default dark color of the desktop theme.

![snapshot2](https://f.cloud.github.com/assets/19999/2098954/83c71d8e-8f35-11e3-8985-83ad8b9ce31a.png)

**Comment by rhamilto** [comment]
Thanks, Lukas!  I think I fixed it.  Can you try refreshing your browser to confirm?

**Comment by metlos** [comment]
Fixed! :)

**Comment by rhamilto** [comment]
Awesome.  Thanks for the heads up!
