### ISSUE TITLE
Alignment of .badge looks off in .nav-tabs

### ISSUE THREAD

**Issue by waldenraines** [patternfly/patternfly-3#10]
Noticed in https://github.com/Katello/katello/pull/3881, filing this for @ehelms.

The alignment of `.badge` apperas to be off when used in a `.nav-tab`.

Markup:

``` html
<ul class="nav nav-tabs">
  <li class="active">
    <a>
      Affected repositories
      <span class="badge">3</span>
    </a>
  </li>
</ul>
```

Latest Patternfly:
![screen shot 2014-03-28 at 11 11 48 am](https://cloud.githubusercontent.com/assets/4116405/2551183/8b946fee-b68b-11e3-99fc-cb0dc075808b.png)

Just bootstrap3:
![screen shot 2014-03-28 at 11 18 07 am](https://cloud.githubusercontent.com/assets/4116405/2551244/32333736-b68c-11e3-8c58-dd92bb585fe0.png)

**Comment by waldenraines** [comment]
This could very well be a duplicate of https://github.com/patternfly/patternfly/issues/3

**Comment by rhamilto** [comment]
Walden, v0.2.1 increases the base font size to 12px.  Here is a screenshot of what badges in tabs look like now.

![badges-in-tabs](https://cloud.githubusercontent.com/assets/895728/2699568/1dad5cae-c408-11e3-8e58-b4683f36ee9c.png)

Does that look better to you?

**Comment by waldenraines** [comment]
It does, thanks.

**Comment by rhamilto** [comment]
Awesome.  Closing the issue.
