### ISSUE TITLE
Add sort icons

### ISSUE THREAD

**Issue by LHinson** [patternfly/patternfly-3#1011]
Original story link: https://patternfly.atlassian.net/browse/PTNFLY-2853

Two new icons need to be added to PatternFly. They have been reviewed and vetted with dingna, Matt Carrano, and Leslie Hinson. @jhaines will get them into the icon table on the website after they are added to PF. Thank you! 

- sort-common-asc
- sort-common-desc

**Comment by andresgalante** [comment]
done on #1016
