### ISSUE TITLE
update popover on bottom with title

### ISSUE THREAD

**Issue by matthewcarleton** [patternfly/patternfly-3#1014]
The top triangle on the popover on bottom with title is white but it looks a little odd. It should be updated to use the same grey that the title uses as a background colour. 

https://rawgit.com/patternfly/patternfly/master-dist/dist/tests/popovers.html
<img width="345" alt="screen shot 2018-04-04 at 2 19 15 pm" src="https://user-images.githubusercontent.com/287880/38323298-40293e3c-3813-11e8-86d1-9914378e0ca2.png">

**Comment by AdamJ** [comment]
From what I can tell, this also involves JS (jQuery), as the popover needs to know when the title is absent. When absent, the background-color of the triangle would stay white.

**Comment by matthewcarleton** [comment]
Hey @mindreeper2420  I think this can be achieved with CSS. Try 
```
.popover.bottom {
    .popover-title:before{
      content:'';
      position: absolute;
      top: -20px;
      left: 50%;
      transform: translateX(-50%);
      border-top-width: 0;
      border-width: 10px;
      border-color: transparent;
      border-bottom-color: @color-pf-black-150;
      border-style: solid;
    }
  }
```
I did this quickly in the browser but if you want, give it try and see if it breaks. Let me know if you need any help with it.

**Comment by AdamJ** [comment]
@matthewcarleton that worked :-) I didn't nest my elements properly, so I had the grey applied to the triangle with bottom popovers, but it was still applied on the bottom popover even when the title was not present.

I filed a PR and added you as a co-contributor.

**Comment by matthewcarleton** [comment]
@mindreeper2420 awesome!
