### ISSUE TITLE
All example that include Masthead should be updated to reflect latest design changes

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-3#1015]
Design changes for Masthead have been recently merged to improve consistency of the way utility items appear and behave. Updated design document can be found here: http://www.patternfly.org/pattern-library/application-framework/masthead/#design as a result of this PR: https://github.com/patternfly/patternfly-design/issues/622

In summary:
* Menu items with only an icon should not have a dropdown arrow.
* All menus should use a drop-down rather than info tip styling.
* All items should have a consistent selected state when open.

Additionally we want to vertically center utility items in the tall masthead so that all items in the masthead (including the logotype and context selector, if present) are aligned.

This affects the following test pages:
* Context Selector
* Application Launcher
* All versions of vertical and horizontal nav
* Notification Drawer

It would also seem to make sense to create a Masthead test page in case a developer just wants to grab the masthead code.

**Comment by mcarrano** [comment]
@matthewcarleton @LHinson I have created this issue to summarize the changes that are needed to bring the masthead core implementation in line with recent design changes. I tried to identify all of the relevant test pages, but you may think of others.

**Comment by matthewcarleton** [comment]
@mcarrano @LHinson I am assuming we will break this out into separate PR's?

**Comment by mcarrano** [comment]
I think that makes sense @matthewcarleton

**Comment by LHinson** [comment]
@mcarrano @matthewcarleton to identify how we can break this down into smaller issues before pulling anything in.

**Comment by mcarrano** [comment]
Per meeting on 4/18 with @matthewcarleton Want to create the following separate issues:
* Context Selector
* Notification Drawer
* App Launcher
* User Menu
* Horizontal Nav
* Vertical Nav

Will do a deeper dive on each of these to identify changes that must be addressed per the high level check list and design changes referenced above.

**Comment by mcarrano** [comment]
I have created separate issues to chunk this into smaller tasks. These are:

Context Selector - https://github.com/patternfly/patternfly/issues/1029
Notification Drawer - https://github.com/patternfly/patternfly/issues/1030
Application Launcher - https://github.com/patternfly/patternfly/issues/1031
Navigation - https://github.com/patternfly/patternfly/issues/1032

Note that there are many more examples that include a masthead, but these are the major ones. Most of these include the Help and User menu on Horizonal nav so not sure if there's a good way to update these in a global way. Otherwise addressing the above list should suffice. I will close this in favor of tracking these smaller issues moving forward.
