### ISSUE TITLE
Update List View styling to remove "selected" highlight color

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-3#1020]
Per design issue https://github.com/patternfly/patternfly-design/issues/633 we want to remove the blue background color for selected rows and use only the checkbox state to indicate selection. All other styling should remain as currently implemented.

**Comment by mcarrano** [comment]
@mindreeper2420 @LHinson I think we may be able to close this one out. Jenny Haines and I did make some updates/clarifications to states and colors on the Design page here: http://www.patternfly.org/pattern-library/content-views/list-view/#design

@mindreeper2420 can you just verify that this is consistent with what we currently have implemented? If so, there's nothing more to do here.

**Comment by AdamJ** [comment]
@mcarrano @LHinson The only difference I can see is in the List View with Compound Expansion example.

The design has it that when "8 Hosts" is selected/expanded, an underline appears under that name and only the icon is highlighted blue. In the code, that is not the case - the entire item is highlighted in blue (icon and text), with no underline.

**Design**
<img width="143" alt="screen shot 2018-06-25 at 9 49 53 am" src="https://user-images.githubusercontent.com/4032718/41854018-2ef1fc6e-785d-11e8-805f-f903f8fa633d.png">
**Code**
<img width="163" alt="screen shot 2018-06-25 at 9 50 07 am" src="https://user-images.githubusercontent.com/4032718/41854038-384c2ec4-785d-11e8-917e-f85e1291bbf7.png">

**Comment by mcarrano** [comment]
This has been this way for a while. The implementation never exactly matched the visual design. Not sure I wanted to invest effort in fixing this if no one is complaining. @LHinson what do you think?

**Comment by LHinson** [comment]
@mindreeper2420 @mcarrano when looking at the rawgit pages and the examples on pf-org, I still see the blue color background on selected.

**Comment by mcarrano** [comment]
Yes, I know this is a bit confusing @LHinson . But after some further discussion we decided to keep the blue background for selected rows.

**Comment by LHinson** [comment]
OK thanks @mcarrano, I'll close this issue then.
