### ISSUE TITLE
Lock Down Dependencies

### ISSUE THREAD

**Issue by AdamJ** [patternfly/patternfly-3#1021]
In order to lock down the dependencies of PatternFly, we should be using a lock file of sorts. The recommended method for those that publish packages is to use `npm-shrinkwrap.json`.

This should prevent the issues where dependent dependencies cause build failures, even when packages were not updated by PatternFly.

https://docs.npmjs.com/files/shrinkwrap.json

**Comment by AdamJ** [comment]
outdated - closing

**Comment by priley86** [comment]
getting some questions about this - any reason we are no longer locking the dependencies here with `package-lock.json` or `yarn.lock`? I think there is concern about matching the exact version or a semantically compatible version of `bootstrap` dependency version used in `patternfly`.

cc: @dgutride @vojtechszocs
