### ISSUE TITLE
Regression Tests are Failing

### ISSUE THREAD

**Issue by AdamJ** [patternfly/patternfly-3#1023]
On the current version of master, regression tests are failing when run locally using `npm run regression`. BackstopJS states that there are 3 failures:
- Alerts (backstop_default_alerts_0_document_0_large-device.png)
- Buttons (backstop_default_buttons_0_document_0_large-device.png)
- Typography 2 (backstop_default_typography-2_0_document_0_large-device.png)

**Comment by jeff-phillips-18** [comment]
Pulled and ran the tests. They are passing for me

**Comment by LHinson** [comment]
@mindreeper2420 are you still running into this issue?

**Comment by AdamJ** [comment]
@LHinson @jeff-phillips-18 I'm rerunning the tests again with a clean clone of the repo. I'll report back any findings.

**Comment by AdamJ** [comment]
I still have 3 failures:
![screen shot 2018-04-17 at 11 17 54 am](https://user-images.githubusercontent.com/4032718/38879332-12663252-4231-11e8-864a-f91aa72c4ce0.png)

**Comment by AdamJ** [comment]
I've downgraded to Node v6.11.5 (from v8.3.0), and the tests failed again. I'll downgrade further to v6.8.0 and run the tests again. I know that the configuration is using v6, but not what minor version.

**Comment by AdamJ** [comment]
I've tried with node v6.8.0 and node v6.0.0 and I still have 3 regression test failures. I sat with Dana earlier today, and he had 0 failures when running the tests. At this point, I'm not sure what the issue is, but I will close this as it is clearly a local environment problem.

**Comment by LHinson** [comment]
ok, thanks for diving into this further @mindreeper2420 and @dgutride
