### ISSUE TITLE
Update Node Dependency to LTS

### ISSUE THREAD

**Issue by AdamJ** [patternfly/patternfly-3#1025]
Update the NodeJS dependency to LTS, which is currently 8.11.1. Currently, the `.travis.yml` file requires Node v6, which is in the maintenance phase of support.

**Comment by dgutride** [comment]
We should do this across all patternfly repos.

**Comment by AdamJ** [comment]
@dgutride I've created a PR (see linked PR above) to update to NodeJS v8.x (LTS) and replace the `package-lock.json` file with `npm-shrinkwrap.json`.

Do all of the repos (including release) need to be updated at the same time, or can they use 6.x for the time being?

**Comment by AdamJ** [comment]
Repos that need updating:
- [x] patternfly/patternfly (v6)
- [x] patternfly/patternfly-angular (v4)
- [x] patternfly/patternfly-react (`.travis.yml` file only)

Repos that already use v8:
- patternfly/patternfly-ng
- patternfly/patternfly-react
- patternfly/patternfly-next

**Comment by AdamJ** [comment]
patternfly/patternfly-eng-release has also been updated to use NodeJS v8

**Comment by AdamJ** [comment]
This was completed by PR https://github.com/patternfly/patternfly/pull/1100
