### ISSUE TITLE
Icon button size

### ISSUE THREAD

**Issue by jgiardino** [patternfly/patternfly-3#1027]
When an icon button displays with a background, as shown in the [inline edit designs](http://www.patternfly.org/pattern-library/forms-and-controls/inline-edit/#design), should we be applying styles so that the sizes (i.e. widths) are consistent?

If the icons we use are slightly different in width, the buttons will end up having different widths. This is something we noticed in the inline edit component in patternfly-react: https://github.com/patternfly/patternfly-react/pull/240

**Comment by jgiardino** [comment]
Also, in reviewing the pf core test page for [inline edit in a form](https://rawgit.com/patternfly/patternfly/master-dist/dist/tests/inline-edit-for-form.html), the icons used in this example are different from the ones in the pf-react example. In pf core, we're using glyphicons, which appear to be consistent in size. In pf-react, we use one font awesome icon and one pf icon, which are not consistent in size. 

Is the glypfhicon set an icon set that we're using throughout patternfly?

**Comment by LHinson** [comment]
@jgiardino I'm going to close this issue, please reach out if you have any concerns though.
