### ISSUE TITLE
Please post community call videos to video sharing site, such as Internet Archive

### ISSUE THREAD

**Issue by brylie** [patternfly/patternfly-3#1028]
It is currently difficult/impossible to view the Patternfly community call videos without Flash player. Flash is being slowly deprecated, and so will not be available in as many browsers as it once was.

Please post copies of the Patternfly community call videos to a video hosting site, such as [Internet Archive](https://archive.org), that supports non-proprietary video formats.

**Comment by LHinson** [comment]
Hey @brylie, apologies for the difficulties that you've had! Let me look into this. I think we can leverage our YouTube channel for posting these recordings.

**Comment by LHinson** [comment]
@brylie we are moving forward with youtube to host meetings and will post meetings there. See: https://www.youtube.com/channel/UCqLT0IEvYmb8z__9IFLSVyQ?view_as=subscriber
