### ISSUE TITLE
forms.less in patternfly-additions for inline-edit example for pf-org consumption

### ISSUE THREAD

**Issue by amarie401** [patternfly/patternfly-3#1036]
When trying to display the inline-edit example on pf-org the `forms.less` style cannot be consumed. I believe it should also be added to the `patternfly-additions.less` since that is what pf-org pulls in. 

Related to this issue in pf-org: https://github.com/patternfly/patternfly-org/issues/556

@dabeng since you worked on the inline-edit is it correct to assume that this also needs to be added in the `patternfly-additions.less` file?

**Comment by dabeng** [comment]
Hi @amarie401 I find that forms.less has been imported by patternfly-adjusted.less  - https://github.com/patternfly/patternfly-org/blob/master/source/_less/patternfly-adjusted.less#L19

**Comment by amarie401** [comment]
Will close this issue. Thanks @dabeng
