### ISSUE TITLE
Inline edit for list view example missing from core

### ISSUE THREAD

**Issue by dabeng** [patternfly/patternfly-3#1038]
I created a demo page of inline edit for standard list view. Please review it and tell me your concerns 😊 @beanh66 @jgiardino @mcarrano @andresgalante 

- [Demo page](https://rawgit.com/dabeng/patternfly/ie-list-view-dist/dist/tests/inline-edit-for-list-view.html)
- [design doc](http://www.patternfly.org/pattern-library/forms-and-controls/inline-edit/#inline-create-and-edit)
- [source code](https://github.com/dabeng/patternfly/commit/46d4d8c7a39f40d105e7765cb874a1db68d0fa9d)

Additional Info:
1.  sorry @beanh66, I didn't adopt your confirm window solution because Window.confirm() doesn't allow developers to customize UI contents and add aria properties.
2. By reading this doc - https://www.w3.org/TR/wai-aria-practices-1.1/#alertdialog, I find that role "alertdialog" is the best choice to build confirm window in current use case(inline edit in a list view)

**Comment by beanh66** [comment]
Thanks @dabeng, I have a couple comments below:

1 - The icons for save and cancel look a little small to me. Wondering if we can bump them up just a little and I also wonder about the color. The blue icons on a blue row seems difficult to see. I would suggest using pf-black-900 when the icon is active and pf-black-500 when it is disabled. 

2 - I don't think the toast notification should be used as confirmation. Currently we don't have a confirmation dialog in PF, but it is in the works [here](https://github.com/patternfly/patternfly-design/issues/632) Is it possible to at least use the PF modal pattern instead of a toast notification? Could we also change that dialog text to something closer to... "continue without saving your changes?"

**Comment by dabeng** [comment]
@beanh66 PF modal pattern has the fixed role "dialog". In the user story of inline edit in a list view, we need role "alertdialog". From the point of view of ARIA, we'd better to distinguish different roles. Please refer to https://www.w3.org/TR/wai-aria-practices-1.1/#alertdialog

**Comment by LHinson** [comment]
@jgiardino do you mind helping to weigh in on this one? I'm not quite clear on the accessibility concern.

**Comment by mcarrano** [comment]
@dabeng Overall this is looking good. I agree with @beanh66 's comments. I also wanted to question the switch in your example. This does not seem to be following the styling for a standard PatternFly Switch widget as shown here http://www.patternfly.org/pattern-library/widgets/#bootstrap-switch

As for the confirmation dialog, while it is appropriate to warning the user if they try to click away from an item after making changes, should we including validation code (JS) as part of this test page? @matthewcarleton @andresgalante can you comment? Seems like this should be left to the consumer on this pattern to implement according to standards we specify elsewhere for these dialogs.

**Comment by jeff-phillips-18** [comment]
I don't think the accessibility for hte confirm dialog is part of functionality of list view inline edit. I think its OK to use a simple modal dialog or even a native alert. Using a toast notification for confirmation is not something we want to include here.

**Comment by mcarrano** [comment]
Just a heads up - there is currently an ongoing discussion here about row styling in list views that I think may impact how we want to represent the visual appearance of a row in edit mode. https://github.com/patternfly/patternfly-design/pull/651

Please continue to review and work out any coding or behavior issues, but I would ask to hold on merging this until the referenced PR has been resolved.

**Comment by jgiardino** [comment]
I share similar thoughts as @mcarrano and @jeff-phillips-18. I don't think how we handle the confirmation should be part of this test page. 

I also agree with @beanh66 that a toast notification isn't appropriate as a confirmation prompt.

As for what ARIA role is most appropriate, this is something we're currently investigating for patternfly next.

**Comment by mcarrano** [comment]
@dabeng We have resolved issues referenced above and I think we are OK to continue forward with this. I do think we need some refinement to the visual styling in your implementation. The background color to use for the editable row should be pf-blue-50 (#def3ff).  @kybaker @jennyhaines can you take a look at this and make some recommendations and/or provide a hi-fi mockup?

**Comment by jennyhaines** [comment]
Hi @dabeng - Right now on the demo site, this is what I'm seeing:

**Hover State**
![1](https://user-images.githubusercontent.com/24898297/39545403-1d54cd8c-4e1f-11e8-8363-b64f1ef30962.png)
- In the implementation, the hover state is #edf8ff, but should be #def3ff

**Edit State and Hover State side-by-side**
![2](https://user-images.githubusercontent.com/24898297/39545493-5735fde6-4e1f-11e8-9358-e5683ded6d73.png)
- Right now the row with the edit state is #def3ff (which is correct), but the row underneath it that is hovered over is #edf8ff, when it should also be #def3ff

**Hover State over an Row Being Edited**
![3](https://user-images.githubusercontent.com/24898297/39545554-86395eb2-4e1f-11e8-9a1f-8b915bf8d419.png)
- Right now when hovering over an edit state row, the color is #edf8ff, but should be #def3ff

(So all this to say that The hover state should just be changed to #def3ff)

**Comment by jennyhaines** [comment]
@mcarrano - I'll work on new hi-fi images for the overview and design tabs, and create a PR to get those updated.

**Comment by mcarrano** [comment]
That's great @jennyhaines Thanks for helping out with this!

**Comment by dabeng** [comment]
@mcarrano @jennyhaines Thanks a lot for your recommendations. FYI, I built up "inline edit in a list view" based on standard list view - https://rawgit.com/patternfly/patternfly/master-dist/dist/tests/list-view.html. If we decide to do some background color adjustments, do we need to do refinements of background color on list view page firstly ?

**Comment by mcarrano** [comment]
Good question @dabeng There is currently another PR open for updating these styles (https://github.com/patternfly/patternfly/issues/1020). Yes, we should be sure to pick up these changes in this example to make sure all of our test pages are in sync.

**Comment by dabeng** [comment]
Hi @mcarrano . Before the associated PR is merged, we still have the following issues to handle:

1. Whether or not to remove confirm window

2. Whether or not build up confirm window based on pf-modal

**Comment by mcarrano** [comment]
@dabeng The confirmation dialog that appears when you click away with unsaved changes should be just a standard modal. @deernano is currently working on a new pattern for these types of message dialogs so perhaps she can offer a design for this.

**Comment by dabeng** [comment]
Thanks @mcarrano I'll work with @deernano and introduce [message dialog](https://docs.google.com/document/d/1mw2zdbkdgIXxpvS2oY5JfsD9j3dLTnmC8769pdKg3e0/edit#) firstly.

**Comment by deernano** [comment]
<img width="294" alt="msg-dialog" src="https://user-images.githubusercontent.com/5396309/40602372-e284a7c4-628a-11e8-8ae8-7c2f9bf934db.png">
@dabeng Please refer to the msg dialog design

**Comment by dabeng** [comment]
Great Job @deernano I have introduced message dialog into current demo page.

**Comment by mcarrano** [comment]
@deernano @stacymcauliffe I wanted to get your opinion about the confirmation dialog here. If you run the demo here, you can see it if you put one of the rows into edit mode, change something, and then click away - https://rawgit.com/dabeng/patternfly/ie-list-view-dist/dist/tests/inline-edit-for-list-view.html

There are two questions. 1- what should the wording of the message be? 2- In the proposed design for confirmation dialogs, we said we wanted to avoid a Yes/No dialog like this for confirmation. But I don't really see how to avoid it in this case. What are your thoughts?

**Comment by deernano** [comment]
@mcarrano @stacymcauliffe 
For this case, I think we could use 'save' & 'Cancel'.
I have an example in the previous doc:
https://docs.google.com/document/d/1SSv4YPU1b2qlLGJSBnLxsI2BboFdJlWySqIwA0T7nfE/edit?ts=5b001e5e#heading=h.my0mh3snt0cr
<img width="293" alt="1" src="https://user-images.githubusercontent.com/5396309/40706950-d7590924-6421-11e8-83d4-4c7d65017258.png">
Use affirmative text to clearly indicate the consequence of the decision. 
Use the text related to the action or content.
Do not use ‘yes’ or ‘no’ for the button text.
<img width="561" alt="2" src="https://user-images.githubusercontent.com/5396309/40706983-f347edbc-6421-11e8-95ce-a74bc22c91d7.png">

Maybe we can have something like this?

**Comment by stacymcauliffe** [comment]
@mcarrano I agree with @deernano that save and cancel would work - the wording of the message itself makes the button labels tough. We could change the message text to say "Do you want to save your changes?" and have the primary button be Save and the Secondary button be Cancel.

**Comment by mcarrano** [comment]
@deernano @stacymcauliffe The problem is that's not actually what this action does. The confirmation dialog appears only when the user clicks away from the row, so the options are either to ignore the action and stay in edit mode or exit edit mode. Nothing would actually be saved in either case. It's not clear what the affirmative action would be.

**Comment by stacymcauliffe** [comment]
Oh yes, good point. Ok. What about ...
"Are you sure you want to leave without saving your changes?" and the buttons are "Yes, Leave" and "No, Cancel" or simply, Leave and Cancel. @mcarrano @deernano

**Comment by dabeng** [comment]
I agree with @stacymcauliffe . @mcarrano Any thoughts?

**Comment by mcarrano** [comment]
@dabeng @stacymcauliffe I still think this is one of the few cases where a simple Yes or No question is the clearest messaging. When I see something like you suggest, I always need to stop and think about what cancel will do because in this case cancel means to continue with the edit vs. clicking cancel within edit (which actually means cancel the edit). So the difference between Leave and Cancel becomes very subtle.

Is there an objection to "Are you sure you want to leave without saving your changes?" with the actions being Yes or No?

**Comment by dabeng** [comment]
@mcarrano I'm OK with captions "Yes or No"

**Comment by dabeng** [comment]
Hi @mcarrano @stacymcauliffe I have updated [demo page](https://rawgit.com/dabeng/patternfly/ie-list-view-dist/dist/tests/inline-edit-for-list-view.html) with new confirm dialog design:

<img width="726" alt="screen shot 2018-06-11 at 1 02 12 pm" src="https://user-images.githubusercontent.com/5689075/41213438-0d09f678-6d78-11e8-8ae4-6bd5fbc90387.png">

**Comment by stacymcauliffe** [comment]
Looks good to me! Thanks @dabeng

**Comment by mcarrano** [comment]
@deernano I believe we settled on the styling for this to be consistent with the existing pf modal styling, correct?  In this case the messaging is fine, @dabeng . But this should not have the horizontal separators and be build from a standard modal.

**Comment by deernano** [comment]
@mcarrano yes, already talked with @dabeng , please refer to the  https://rawgit.com/michaelkro/patternfly-react/confirm-dialog-storybook/?knob-With%20Secondary%20Button=true&knob-With%20Body=true&knob-With%20Body%20Heading=true&knob-With%20Primary%20Text=true&knob-Icon=info&knob-With%20Title=true&knob-With%20Icon=true&knob-With%20Secondary%20Text=true&knob-With=&selectedKind=patternfly-react%2FCommunication%2FMessage%20Dialog&selectedStory=Message%20Dialog%20with%20Toggleable%20Options&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybooks%2Fstorybook-addon-knobs

**Comment by dabeng** [comment]
Hi @mcarrano . Are we ready to send "inline edit in list view" PR if the PR of background colors of list view is merged.

**Comment by mcarrano** [comment]
Yes, I think so @dabeng

**Comment by LHinson** [comment]
Closing as the PR has been merged to add inline edit for list view. I've created an issue to get this posted to the site. see: https://github.com/patternfly/patternfly-org/issues/592
