### ISSUE TITLE
Notification Drawer Dropdown Items are hidden by Clear/Read All Buttons

### ISSUE THREAD

**Issue by glekner** [patternfly/patternfly-3#1039]
I'm not sure this is the intended behaviour.

Whenever trying to open the dropdown menu of the closest notification to the Clear/Read buttons (the last notification in each panel), its hidden behind it, creating a scrollable div to get to the menu items.

<img width="367" alt="screen shot 2018-04-26 at 14 29 53" src="https://user-images.githubusercontent.com/24938324/39304191-91d693ec-4961-11e8-98ae-7a540b1553df.png">

I managed to fix this by adding the following attributes to the `.dropdown` class:
```
.dropdown {
    position: absolute;
    right: 0;
    margin-right: 15px;
}
```

This is the result:
<img width="349" alt="screen shot 2018-04-26 at 14 36 46" src="https://user-images.githubusercontent.com/24938324/39304244-c1911e36-4961-11e8-8070-5cd3e23756f4.png">

This is nice but now the dropdown overlaps other items of the drawer that it shouldn't, added a GIF to show it (With the PF-React Drawer using Flexbox)

![dropdown](https://user-images.githubusercontent.com/24938324/39304309-eee58746-4961-11e8-8769-737d539369cb.gif)

Please let me know what you think of this, @Rohoover @jgiardino @serenamarie125 @ohadlevy 

Thanks!

**Comment by mcarrano** [comment]
Thanks for flagging this issue @gilad215 . Definitely seems like a problem with the way kabob menus work. I wonder if this also shows up in other places where kabobs are used. From a design perspective the menu should always be on top of other content, but the icon itself should not. @matthewcarleton can you take a look?

**Comment by jgiardino** [comment]
I had opened a similar issue before: https://github.com/patternfly/patternfly/issues/553

This issue was closed. Since you can scroll to get to the menu items, the decision was to fix it in the next version of patternfly.

**Comment by matthewcarleton** [comment]
@mcarrano @gilad215 I agree with what @jgiardino states above 👍

**Comment by matthewcarleton** [comment]
@mcarrano are you ok to close this and mark it as a "fix in pf-next" issue?

**Comment by lina-is-here** [comment]
There is a BZ and we need to fix this https://bugzilla.redhat.com/show_bug.cgi?id=1658542
