### ISSUE TITLE
How can I contribute?

### ISSUE THREAD

**Issue by antoniojunyor** [patternfly/patternfly-3#1051]
Hi, my name is Antonio Junior and I'm a front-end developer guys, I really want to contribute to this project, but the project don't have some topic on README about some rules to commits and PR. I noticed that have a section "Frequently Asked Questions", but the "contribute" link doesn't exist.

![Page 404](https://user-images.githubusercontent.com/1471456/40007333-d6826ad8-5772-11e8-8442-429683ac48a8.png)

So ... first I want to do some (small) things about accessibility, so, what do you think about add some topic about Pull Request/contribute on README?

**Comment by LHinson** [comment]
Hey @antoniojunyor! Thanks for reaching out. Did you find the information that you need? Happy to share some helpful links if not.
