### ISSUE TITLE
3.46 breaks login screen background

### ISSUE THREAD

**Issue by himdel** [patternfly/patternfly-3#1057]
Upgrading [ManageIQ/manageiq-ui-service](https://github.com/ManageIQ/manageiq-ui-service) from patternfly 3.45.0 to 3.46.0, the login screen changed:

before:

![good](https://user-images.githubusercontent.com/289743/40242068-223042fc-5aac-11e8-8241-d41e13b5a0b9.png)

after:

![bad](https://user-images.githubusercontent.com/289743/40242077-26fe7e0c-5aac-11e8-8895-45f90c6b937f.png)

**Comment by himdel** [comment]
Still present in 3.46.1.

(3.46.2 was released 8 minutes ago, but is not available on npm yet)

**Comment by terezanovotna** [comment]
@LHinson any idea what happened here?

**Comment by jeff-phillips-18** [comment]
Is there a system I can look at that shows this problem? I haven't setup/run the service UI in a while so might be easier if there is a system I could just poke at.

**Comment by himdel** [comment]
Sorry, we don't have any public-facing test instances, you'll have to pull the latest manageiq-ui-service.

**Comment by himdel** [comment]
..But if it helps, if I comment out:

```
.login-pf {
  background: $login-bg-color url(if($bootstrap-sass-asset-helper, twbs-image-path("#{$img-path}#{$img-bg-login}"), "#{$img-path}#{$img-bg-login}")) repeat-x 50% 0;
}
```

(in patternfly css), it works as before.

**Comment by jeff-phillips-18** [comment]
This broke due to a change made in https://github.com/patternfly/patternfly/pull/1024

The background image is now set on the .login-pf selector (used to only be on `.login-pf body`).

@himdel Is this something you need PF to fix or can it be done easily enough in [ManageIQ/manageiq-ui-service](https://github.com/ManageIQ/manageiq-ui-service)

**Comment by himdel** [comment]
We can override the style in ui-service, as long as we know that this was not indended for us :) thanks :).

Can you maybe take care of the other side and add the login screen styling to the regression tests so that this doesn't happen again?

**Comment by jeff-phillips-18** [comment]
The problem is this particular change didn't break the regression tests since our login page uses the PF background image. We are working towards making our regression tests more robust in the future.

**Comment by himdel** [comment]
Thanks! :)

I guess I can close now..
