### ISSUE TITLE
pf-select breaks showing default values

### ISSUE THREAD

**Issue by d-m-u** [patternfly/patternfly-3#1058]
Dropdowns appear with nothing selected when defaults are clearly set in backend.

**Comment by jeff-phillips-18** [comment]
Could you give more information please? Is this issue visible on the test pages? Maybe the HTML that produces this error?

**Comment by LHinson** [comment]
@d-m-u reach out if you have more specifics on the issue. I'm going to close this one until then as we don't have enough information to address.
