### ISSUE TITLE
Introduce Dual List Selector

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-3#1059]
The [Dual List Selector](http://www.patternfly.org/pattern-library/forms-and-controls/dual-list-selector/#overview) pattern was recently introduced to the design pattern library and a core implementation is needed.

**Comment by Ron-Lavi** [comment]
Going to start to work on it soon in Patternfly-react, just opened an [issue](https://github.com/patternfly/patternfly-react/issues/379) there.

**Comment by LHinson** [comment]
Created an issue over on PF4 for core. Will close it here. See: https://github.com/patternfly/patternfly-next/issues/359

@mcarrano please let me know if there is any questions/concerns.
