### ISSUE TITLE
icon-trend-down & icon-trend-up has the wrong description

### ISSUE THREAD

**Issue by Mikewaite** [patternfly/patternfly-3#1065]
Small but...

Looks like trend-down and trend-up icons have switched descriptions.

**Comment by dabeng** [comment]
I sent [PR](https://github.com/patternfly/patternfly-design/pull/690) to fix this issue.

**Comment by LHinson** [comment]
Closing this issue since its been addressed with the referenced PR. Thanks @dabeng
