### ISSUE TITLE
Remove PatternFly from Automated RCUE Build

### ISSUE THREAD

**Issue by AdamJ** [patternfly/patternfly-3#1069]
Now that RCUE is built into PatternFly, the automated build triggers need to be turned off for RCUE.

CC: @dgutride @dlabrecq

**Comment by dlabrecq** [comment]
Just need to remove one line from patternfly's travis.yml file.

https://github.com/patternfly/patternfly/blob/master/.travis.yml#L39

**Comment by dlabrecq** [comment]
Thinking we should we also add a note in RCUE's README. Something to indicate that the RCUE repo has been deprecated in favor of the CSS being available in PatternFly.
