### ISSUE TITLE
Introduce new test page for Date and Time

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-3#1078]
Introduce a new Date and Time test page to replace the old Datepicker that is consistent with the updated design pattern. This implementation must continue to be based on the Boostrap Datepicker.

Ref https://github.com/patternfly/patternfly-design/issues/459 for design details.

**Comment by mcarrano** [comment]
@LHinson @matthewcarleton I've created this new issue and assigned to @dabeng for him to contribute the Core examples for the revised Date and Time pickers. We are in the process of also adding this to the design library.

**Comment by LHinson** [comment]
Closing as this has been addressed with PR 1080
