### ISSUE TITLE
Remove Background Color & Border from Empty State

### ISSUE THREAD

**Issue by AdamJ** [patternfly/patternfly-3#1079]
Per a discussion in the uxd-visual Slack channel with @serenamarie125 and @jennyhaines, the empty state pattern should not have a set background color or border. As such, the background should be set as transparent and the border removed.

http://www.patternfly.org/pattern-library/communication/empty-state/#code

The design document needs to be updated as well, as that shows a background with color and a border. Issue created here for that update: https://github.com/patternfly/patternfly-design/issues/682

**Comment by jeff-phillips-18** [comment]
This could be problematic for applications that are already using the empty state pattern and expect to have the color and border. I'm not sure how we determine if so.

**Comment by mcarrano** [comment]
Is this something that can be deferred? It's always been this way and has not been raised as a problem until now.  @LHinson FYI.

**Comment by jeff-phillips-18** [comment]
I'm not disagreeing with the change. For sure I've over-ridden most of the blank-slate-pf values in a couple of different applications. I would actually like to see the change made in PF3 (where it will have the biggest impact), I just want to kno if there is some way to determine if it is `breaking`.

**Comment by AdamJ** [comment]
I think that it would be "breaking" only in the case where users have specifically changed the background of their page to match the background of this component. 

I, like Jeff, have changed it to white or transparent everywhere that I've used it. For those that have done the same (or changed it to another color), this would have no negative impact.

I'd like to see this in PF3.

**Comment by dgutride** [comment]
we should try to do this if there is a way to introduce a change without breaking users that have already customized the background  - @mindreeper2420 , @jeff-phillips-18: would that be possible?

**Comment by AdamJ** [comment]
@dgutride If a user changed it to be transparent or white (like OpenShift.io, for example), then this won't necessarily have a negative impact on them (other than now their code duplicates PatternFly). If they matched their background to the empty state color, then that will definitely cause issues.

Unfortunately, that is hard to tell until the change actually happens and people update their UIs...

**Comment by LHinson** [comment]
Thanks for that additional information @mindreeper2420 We are trying to be very mindful of breaking changes. Therefore, I'd like to understand the value of this change. 

@serenamarie125 @mindreeper2420 What's the issue/concern that is introduced when the empty state pattern has a set background color and border?

**Comment by LHinson** [comment]
Per @lizsurette on https://github.com/patternfly/patternfly-design/issues/682

> Looking closer at this for oVirt with dev, just the two CSS properties 'background-color' and 'border' would need to be removed from the blank-slate-pf class. The current workaround is to override these PatternFly values with project-specific CSS.

Since this is not a large effort to override, I'm closing this issue due to the risk it presents to breaking change. That said, we will add dev notes to the empty state code page to identify/ack this as an option. See: https://github.com/patternfly/patternfly-org/issues/615

Please let me know if you have concerns.

**Comment by jeff-phillips-18** [comment]
Could we add an optional class that would then override the border and bg color thus providing the optional styling?

**Comment by LHinson** [comment]
@jeff-phillips-18 It seems like this is a non-breaking solution? If so, I'm ok with this therefore re-opening.
