### ISSUE TITLE
.border styles from bootstrap not working

### ISSUE THREAD

**Issue by terefang** [patternfly/patternfly-3#1081]
since the bootstrap.css is not included in patternfly.css the border group of styles are not working

**Comment by dgutride** [comment]
Requires more details - @andresgalante, any idea what this is referring to?

**Comment by andresgalante** [comment]
Hi @terefang Bootstrap's CSS is included in patternfly, it's been imported[ here](https://github.com/patternfly/patternfly/blob/master/src/less/patternfly.less#L6)

Remember that Patternfly 3 is based on Bootstrap 3. Maybe I am wrong but unlike Bootstrap 4, Bootstrap 3 doesn't have [border utility classes](http://getbootstrap.com/docs/4.1/utilities/borders/).

**Comment by LHinson** [comment]
Thanks for your input @andresgalante. I'm closing this issue based on that information. @terefang feel free to follow up if this does not address the issue!

**Comment by QiWang19** [comment]
I used reactstrap in my cockpit project. reactstrap uses bootstrap v4, but patternflt uses bootstrap v3. Something wrong with that. The newest version of patternfly uses bootstrap v4?

```
├── bootstrap@4.1.3
└─┬ patternfly@3.53.0
  ├── bootstrap@3.3.7
```

**Comment by LHinson** [comment]
No, @QiWang19 PatternFly is based on BootStrap 3. Check out our dependencies here: https://github.com/patternfly/patternfly/blob/master/bower.json
