### ISSUE TITLE
Correct RGB colors of list view doesn't take effect

### ISSUE THREAD

**Issue by dabeng** [patternfly/patternfly-3#1082]
It seems that the css code of  “States and Row Styling” section has not been merged into the master branch.

<img width="1114" alt="screen shot 2018-06-21 at 11 35 33 am" src="https://user-images.githubusercontent.com/5689075/41754301-6d65da16-7604-11e8-8e6c-5f38db63c627.png">

<img width="1063" alt="screen shot 2018-06-22 at 10 10 30 am" src="https://user-images.githubusercontent.com/5689075/41754347-9b51bddc-7604-11e8-8883-a91bdce7b671.png">

**Comment by mcarrano** [comment]
@matthewcarleton I thought we were all set with this but perhaps not. I know there was an earlier PR that @mindreeper2420 was working on that we closed. If this is something we need to fix, can you pick this up @dabeng ?

**Comment by dabeng** [comment]
@mcarrano I made a [commit](https://github.com/dabeng/patternfly/commit/cf071ff0ced4b8998f46bdcd96b49a755d047b79) to fix this issue. You can find the expected colors on the [demo pages](https://rawgit.com/dabeng/patternfly/list-view-colors-dist/dist/tests/index.html) with keyword "list" or "list view"

<img width="1124" alt="screen shot 2018-06-25 at 3 07 51 pm" src="https://user-images.githubusercontent.com/5689075/41835307-aeab4254-7889-11e8-8d68-282badebb518.png">

**Comment by mcarrano** [comment]
Hmmm... This does not look right. I thought that the hover state was intended to be the lighter blue. It's possible that we got these reversed in the design doc. @jennyhaines can you confirm this? Please double check the color values entered here: http://www.patternfly.org/pattern-library/content-views/list-view/#design

**Comment by jennyhaines** [comment]
@mcarrano - they aren't looking right to me either. Currently, the color values in the design documentation say:

_"Hover - when the user hovers over a row (pf-blue-50, #def3ff)
Selected - when the user selects a row via single click or selecting the checkbox (#edf8ff)
Open - when a row is expanded (##edf8ff)
Edit - when a row is in edit mode via inline edit (##edf8ff)
Disabled - when a row is disabled (pf-black-100, #fafafa)"_

I don't believe this is correct, though. The hover state should always be lighter than the selected, open, and edit states, (This keeps consistency with our [single and multiple select](http://www.patternfly.org/pattern-library/widgets/#bootstrap-select) designs that use darker blue for selected vs. lighter blue for hover) so the design documentation should read:

_"Hover - when the user hovers over a row **(#edf8ff)**
Selected - when the user selects a row via single click or selecting the checkbox **(pf-blue-50, #def3ff)**
Open - when a row is expanded **(pf-blue-50, #def3ff)**
Edit - when a row is in edit mode via inline edit **(pf-blue-50, #def3ff)**
Disabled - when a row is disabled (pf-black-100, #fafafa)"_

Thank you for taking a look at this @dabeng !

**Comment by dabeng** [comment]
Hi @mcarrano @jennyhaines Could you tell me which is the final color solution for list view ?
solution A. https://github.com/patternfly/patternfly/issues/1038#issuecomment-386097899
solution B. 
> Hover - when the user hovers over a row (#edf8ff)
Selected - when the user selects a row via single click or selecting the checkbox (pf-blue-50, #def3ff)
Open - when a row is expanded (pf-blue-50, #def3ff)
Edit - when a row is in edit mode via inline edit (pf-blue-50, #def3ff)
Disabled - when a row is disabled (pf-black-100, #fafafa)

**Comment by jennyhaines** [comment]
@dabeng - Let's go with solution B! Once @mcarrano pointed out that hover should be lighter, I whole-heartedly agree. It is more consistent with other PF UI experiences (Like single and multiple select, for example)! Sorry for changing things around on you.

**Comment by mcarrano** [comment]
I just opened a design PR to correct the documentation. See https://github.com/patternfly/patternfly-design/pull/687.  I think that should resolve this issue.

**Comment by LHinson** [comment]
Closing this issue since it's been addressed. Thanks @dabeng!
