### ISSUE TITLE
Need README instructions on using RCUE CSS, Less, and Sass

### ISSUE THREAD

**Issue by jeff-phillips-18** [patternfly/patternfly-3#1088]
RCUE styling is now available in this repository but I don't see instructions on how a product would import in order to gain RCUE styling for the 3 supported mechanisms.

RCUE support was added in #1022

**Comment by mtho11** [comment]
Hi, is there any progress on this issue?

**Comment by LHinson** [comment]
Hey @mtho11, this is currently still on our backlog. Is this currently a blocking issue for you?

**Comment by mtho11** [comment]
Hi @LHinson, I'm currently finding out with PM how blocking this is. I will have a definitive answer shortly.

**Comment by LHinson** [comment]
ok great, that will be super helpful for me to understand how to prioritize this. thanks for the additional insight @mtho11

**Comment by AdamJ** [comment]
@LHinson I can take this on, as I did the conversion work.

**Comment by LHinson** [comment]
Closing this issue as the quick start has been merged. @mtho11 please file any issues that you might have when using the quick start so we can continue to improve it!

**Comment by mtho11** [comment]
Ok thanks @LHinson @mindreeper2420 !
(I'm going on vacation for little over a week just FYI)
