### ISSUE TITLE
Horizontal Navigation secondary level menus are not legible when opened.

### ISSUE THREAD

**Issue by jeff-phillips-18** [patternfly/patternfly-3#1091]
From PF.org 

http://www.patternfly.org/pattern-library/navigation/horizontal-navigation/#code

![image](https://user-images.githubusercontent.com/11633780/42400156-7cd1a490-813e-11e8-9def-835a367a894b.png)

**Comment by mcarrano** [comment]
We actually decided a while back to no longer recommend this configuration (secondary nav with dropdowns) so I'd like to just remove this from the code page, if possible.

**Comment by LHinson** [comment]
Thanks @mcarrano. I've filed an issue against pf-org to remove. see: https://github.com/patternfly/patternfly-org/issues/598

Therefore i'm closing here.

**Comment by jeff-phillips-18** [comment]
The CSS that exists is still incorrect. For any application using Patternfly and using this pattern, the secondary nav is not legible.  I believe we should fix the CSS for those applications which might use it even if it is now removed from PF.org

**Comment by LHinson** [comment]
@jeff-phillips-18 there are no known concerns with product regarding this issue. I'm going to close. Let me know if you have any concerns.
