### ISSUE TITLE
DateTimePicker does not look good on resize of browser

### ISSUE THREAD

**Issue by kedark3** [patternfly/patternfly-3#1096]
![image](https://user-images.githubusercontent.com/8180469/42888228-cc7f2a86-8a75-11e8-898b-cffe8dd06719.png)
Reference to: https://github.com/ManageIQ/miq_v2v_ui_plugin/issues/498

**Comment by LHinson** [comment]
Issue can also be seen on DateTimePicker on the patternfly test page here: https://rawgit.com/patternfly/patternfly/master-dist/dist/tests/date-and-time.html#

**Comment by bthurber** [comment]
@kedark3 do we have a BZ open for this?  If so please link.

**Comment by kedark3** [comment]
@bthurber we have one in V2V, would that work?

**Comment by bthurber** [comment]
@kedark3 sure.

**Comment by kedark3** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1602792

**Comment by LHinson** [comment]
Closed with issue #1120
