### ISSUE TITLE
Patternfly available in maven repository?

### ISSUE THREAD

**Issue by psiroky** [patternfly/patternfly-3#110]
Hello,

I would like to ask if there are any plans to make PatternFly releases available through Maven repository? 

I know PatternFly is not a Java project. However, I believe it would make it much easier for Java users (using Maven) to consume the zips since lot of them are using Maven for managing dependencies.

Thanks for any response,
Petr

**Comment by rhamilto** [comment]
Hi, Petr.

We do not have any plans to make PatternFly available through Maven at this time.  But, if you or someone else would like to lead such an effort, we will certainly entertain the option.

Thanks,
Robb.

**Comment by psiroky** [comment]
There is a quite nice service at http://www.webjars.org/npm which lets you create jars from the NPM packages with just few clicks of mouse. I've created one for patternfly 2.1.0 and it was uploaded to Maven Central: http://search.maven.org/#artifactdetails%7Corg.webjars.npm%7Cpatternfly%7C2.1.0%7Cjar.

This could be a way to easily distribute the PatternFly release fro consumption by Maven. The contents is bit hidden under META-INF/resources, but it can easily extracted from there.

**Comment by rhamilto** [comment]
That's great, Peter!  Given that this tool exists and we already publish PatternFly via npm and Bower, it seems like anyone can add new versions of PatternFly to Maven Central?  Is there anything more for us to do to support this?

**Comment by rhamilto** [comment]
^ @psiroky

**Comment by psiroky** [comment]
@rhamilto sorry, I forgot about this one. I think the above solution if more than fine (at least for now), so I am closing this issue.

**Comment by ceefour** [comment]
Latest Patternfly in http://www.webjars.org/bower is now 2.8.0 :(

It'd be great if release process also do the release to webjars/Maven.

**Comment by ceefour** [comment]
I just deployed 3.3.2 :)

`patternfly-bootstrap-combobox` also deployed
