### ISSUE TITLE
Trying to install patternfly via npm fails on older node

### ISSUE THREAD

**Issue by himdel** [patternfly/patternfly-3#1113]
Caused by https://github.com/patternfly/patternfly/pull/1100.

Doing `yarn install` in any repository which depends on the `patternfly` npm package now fails when using older node than 8.9.0:

```
...
[3/5] Fetching packages...
error patternfly@3.53.1: The engine "node" is incompatible with this module. Expected version ">=8.9.0".
error An unexpected error occurred: "Found incompatible module".
info If you think this is a bug, please open a bug report with the information provided in "/home/hstastna/manageiq/manageiq-ui-classic/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

== yarn failed in /home/hstastna/manageiq/manageiq-ui-classic ==
...
```

The problem with that is: there is no reason this should block the install. We're not running any patternfly scripts, we're not trying to rebuild patternfly using your configuration, we're just serving static files.

We're supporting `node >= 6.9.1` and patternfly should not be affecting that.

IMO the solution is simple - frontend libraries should never use `engines` in `package.json`, the correct way to communicate that dependency is via `devEngines`. (Similar to how [react](https://github.com/ndresx/react/blob/7acdfd64a4e0b8ad2bd66cdf3780414d60c68316/package.json#L103) does it.)

@mindreeper2420 @jeff-phillips-18 WDYT?

**Comment by AdamJ** [comment]
My thinking around requiring that engine was to specify which versions of node are compatible with PatternFly, in order to decrease the amount of conflicts. Additionally, v6.9.1 is in "maintenance" mode for NodeJS (as of April 30, 2018) and we wanted to keep PatternFly on the latest active LTS.

When I run `npm install` (I do not use `yarn`) on a project that consumes PatternFly and then run said project, I am not running into any issues with the build. It works as expected.

**Comment by himdel** [comment]
> we wanted to keep PatternFly on the latest active LTS.

What this is doing is forcing every single project using patternfly to use that same version of node (or newer).

Not sure that was something you intended... ;)

Note: for comparison, react still supports node 4, precisely for that reason.

**Comment by himdel** [comment]
@jeff-phillips-18 This is currently breaking manageiq builds, please assign appropriate priority ;)

**Comment by martinpovolny** [comment]
ping @simaishi

**Comment by martinpovolny** [comment]
@mindreeper2420 we do not have unlimited menpower on manageiq. Can you revert #1100 ?

**Comment by AdamJ** [comment]
I cannot revert PRs - @dgutride is this something that you can take a look at?

**Comment by AdamJ** [comment]
A PR has been filed to remove the engine requirements. Of note, this is the only PatternFly repo (React, NG, Angular, Next) that does not have engine requirements.

**Comment by dgutride** [comment]
@himdel - please use release 3.54.1

**Comment by himdel** [comment]
Thanks for the quick fix everyone! :)

> A PR has been filed to remove the engine requirements. Of note, this is the only PatternFly repo (React, NG, Angular, Next) that does not have engine requirements.

Just to be clear, I'm not really objecting to having engine requirements, only to forcing us to use newer version than available to us :). (I question the point for libraries with no node-run code, but that's another matter :).)
