### ISSUE TITLE
Introduce File Upload core implementation

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-3#1121]
[File Upload](https://www.patternfly.org/pattern-library/forms-and-controls/file-upload/) has been added as a new pattern. Requires core CSS implementation and test page.

**Comment by ajacobs21e** [comment]
@mcarrano do you know who did the design for this pattern?

**Comment by mcarrano** [comment]
@ajacobs21e A couple of different people worked on it. But Brie Mignano was the one who finalized it.
