### ISSUE TITLE
questions about Login screen design and implementation

### ISSUE THREAD

**Issue by jgiardino** [patternfly/patternfly-3#1125]
A couple of questions came up during implementation of the [Login screen for pf-react](https://github.com/patternfly/patternfly-react/pull/362).

1. The [design documentation](https://www.patternfly.org/pattern-library/application-framework/login-page/#design) shows a divider during the responsive state after the Log In button, but this isn't present in the [core example](https://rawgit.com/patternfly/patternfly/master-dist/dist/tests/login-social-account-two-column.html). If it isn't intended to be there, then an issue should be opened for both patternfly-design and patternfly-react to remove the divider.
2. The [design documentation](https://www.patternfly.org/pattern-library/application-framework/login-page/#design) shows a warning message at the top, with spacing above the message, but there isn't an example of this in the core implementation. Guidance is needed on how to handle that spacing (e.g. do we want to add classes and css in patternfly core for that, or address it only in pf-react). This also will require an issue in pf-react based on how we want to move forward. 
3. The css defines a background image that seems very specific to PatternFly and not useful for any project that would use this pattern. Should the background image be removed? The react implementation was altered to allow the consumer to specify their own background image. 
4. The test pages in core include 100px padding at the bottom of the page. If this spacing is expected in the react implementation, then it should be added to the core css.
5. The design documentation includes inline messages directly above the form. Examples for these messages are needed in core so that we can later add them to the react implementation. 

When these items are resolved, any changes needed in the react implementation will need a new issue to capture those updates.

**Comment by mcarrano** [comment]
@matthewcarleton These questions came out of a review of the React implementation I was doing with @jgiardino today. I remember discussing some of these topics during Core implementation. Would be good for the 3 of us to sync on these issues and decide whether updates are needed to the core CSS. 

In addition to the above, I also noticed that the More/Less link exists in the Core example for responsive state (though we decided to remove that). We will ask that it be removed from React.

@LHinson FYI.

**Comment by matthewcarleton** [comment]
Just spoke with @jgiardino and @mcarrano here is where this stands:
1. The design doc should be updated to reflect what is shown in core ( no separator in responsive state)
2. This is an easy fix that we could implement in core, it was just not added in the initial implementation.
3. This is from the original implementation of login but I believe it was meant to be changed. I think it's a good idea to at least document that it can/should be changed.
4. Another easy fix. 
5. this is another easy fix that wouldn't require a lot of effort. The question around these examples is do we want to create a new test page for each example?
