### ISSUE TITLE
User and help menu does not render in mobile view on vertical navigation

### ISSUE THREAD

**Issue by mechevarria** [patternfly/patternfly-3#1126]
When viewing the vertical navigation example, the user menu and help menu are no longer viewable if you switch to a mobile viewport

[https://www.patternfly.org/pattern-library/navigation/vertical-navigation/vertical-navigation-without-icons.html](https://www.patternfly.org/pattern-library/navigation/vertical-navigation/vertical-navigation-without-icons.html)

![screenshot from 2018-08-14 17-02-54](https://user-images.githubusercontent.com/2657771/44118488-506f1c74-9fe4-11e8-97a8-4328fab19feb.png)

**Comment by mcarrano** [comment]
This is intended behavior, @mechevarria . You will find that the Help and User menus are added to the bottom of the primary menu (hamburger menu) when there is no longer space for them in the masthead.

**Comment by mechevarria** [comment]
Now I see it, thanks.  It does not seem like that additional nav items show on a xs viewport are implemented in Patternfly-NG.  I'll have to ask.  Closing this issue
