### ISSUE TITLE
Introduce Progressive Disclosure Example

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-3#1130]
Want to introduce example code to accompany this existing design pattern: https://www.patternfly.org/pattern-library/forms-and-controls/progressive-disclosure

Some initial ideas were lined to this issue in patternfly-design: https://github.com/patternfly/patternfly-design/issues/706

**Comment by LHinson** [comment]
@garrett I just sent you an invite to join PF-Core contributors. Once you accept that, I'll be able to assign you to this issue!
