### ISSUE TITLE
Semantic Release is broken

### ISSUE THREAD

**Issue by dlabrecq** [patternfly/patternfly-3#1138]
The semantic release was recently updated to a later version. However, the Travis build logs output the following error.

`npm ERR! missing script: semantic-release-pre`

See: https://travis-ci.org/patternfly/patternfly/builds/422159968#L1968

See the following PRs for changes:
https://github.com/patternfly/patternfly/commit/54bd6dc6de36c36895239401a5f72837d2c4e43d
https://github.com/patternfly/patternfly/commit/0d60abb9e6aa4effa1ea1e041685957b7b582626

Note: The last successful release was 29 days ago.

**Comment by dgutride** [comment]
Fixed - moving to closed
