### ISSUE TITLE
Datatable code can not be entirely copied.

### ISSUE THREAD

**Issue by i4snow** [patternfly/patternfly-3#115]
hey, when I want to copy the code in "Widget" > "Javascript" > "Data Tables", it could no be entirely copied.

**Comment by i4snow** [comment]
Could you offer a button for copy?

**Comment by rhamilto** [comment]
Hi, @i4snow.  The reference markup for data tables is intentionally truncated so as to make it easier to read and not ridiculously long (you'll note there is an ellipsis before &lt;/tbody&gt;.  If you want an exact copy, try viewing source on https://rawgit.com/patternfly/patternfly/master/tests/datatables.html and copying lines 42-460.

A copy button is a wonderful suggestion.  We're looking at overhauling patternfly.org in the near future, and I'll add that to the list of feature requests.

**Comment by i4snow** [comment]
In Chrome

**Comment by i4snow** [comment]
Thank you @rhamilto. 
I don't mean the code is not enough. What I really is when I want to copy the data table code, but the middle area can't be chosen, which means that if I just drag the middle area for copy by coincidence, it seems like I did nothing. Please see the screenshot attached. 
Thanks

![image](https://cloud.githubusercontent.com/assets/2161137/9866441/f95b8134-5b94-11e5-8e04-f4b8af9401cf.png)

**Comment by rhamilto** [comment]
Ah.  Sorry for the confusion, @i4snow.  

What version of Chrome are you using?  And on which platform (operating system)?

I am unable to reproduce the bug using Chrome Version 45.0.2454.85 (64-bit) on OS X 10.10.5.

![screen shot 2015-09-15 at 9 16 27 am](https://cloud.githubusercontent.com/assets/895728/9877427/c53947a6-5b8a-11e5-9199-e3533f71d104.PNG)
