### ISSUE TITLE
Update to Bootstrap 3.4.0?

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly-3#1158]
[Bootstrap 3.4.0](https://blog.getbootstrap.com/2018/12/13/bootstrap-3-4-0/) was just released. Should we look at updating to this version?

**Comment by srbala** [comment]
@mcoker 

Bootstrap 3.4 added to in https://github.com/patternfly/patternfly/pull/1160
https://github.com/patternfly/patternfly/blob/master/package.json 

Verify this issue still needed, elebrate with more description, otherwise please close this issue
