### ISSUE TITLE
HTML code for launcher home missing

### ISSUE THREAD

**Issue by yakatz** [patternfly/patternfly-3#1163]
Issue #711 was closed because code was added for the Launcher Menu, but there is still no code for the Launcher Home page.

**Comment by LHinson** [comment]
The launcher code is provided specifically for the launcher component, not the home page. The home page is not provided since this is extremely specific to the needs of the application.

**Comment by viniciusferrao** [comment]
Hi Leslie, I came here searching for the code too. The image was only a mock up? If not please reconsider releasing the code. The home is extremely well made and fit a lot of things.
