### ISSUE TITLE
bootstrap-select needs to be updated to 1.13.6

### ISSUE THREAD

**Issue by zregvart** [patternfly/patternfly-3#1167]
* What browser(s), device and OS experience the problem?

Not relevant

* Are you using a PatternFly JS framework implementation [1]?

Not relevant

* What are the steps to reproduce the issue and what is the expected behavior?  For the the fastest support, provide a working demo or minimal reproduction using tools such as [codepen](https://codepen.io/) or [jsfiddle](https://jsfiddle.net/)

Take a look at https://github.com/snapappointments/bootstrap-select/issues/2199

**Tell us more about your product/project and timeline to help prioritize this issue.**
* What product/project does this impact?

Any projects using current released version.

* List product/project release(s) and timelines.

Not sure about this

* Is this a customer reported blocking issue?

Not sure about this

**Comment by atodorov** [comment]
https://app.snyk.io/vuln/SNYK-JS-BOOTSTRAPSELECT-173741 - updating will fix a High priority security issue

**Comment by atodorov** [comment]
@zregvart Why did you close this issue? From what I can see it is still valid and PR #1170 hasn't been merged yet?
