### ISSUE TITLE
Visual differences in DonutCharts title

### ISSUE THREAD

**Issue by vkareh** [patternfly/patternfly-3#1168]
Donut Charts have visual differences between Firefox and Chromium. The title inside the charts on Firefox seem to be missing padding, and it makes it look like it needs some styling. The issue is visible on the https://www.patternfly.org/pattern-library/data-visualization/donut-chart/ page:

Left side is Chromium, right side is Firefox 65.0.2

![Screenshot at 2019-03-11 10-09-27](https://user-images.githubusercontent.com/259780/54130348-9aca5080-43e6-11e9-90c4-7493fdfaf7c3.png)

**For bug reports, please provide as much relevant info as possible:**
* What browser(s), device and OS experience the problem? Firefox 65.0.2 on Fedora 29
* Are you using a PatternFly JS framework implementation [1]? PatternFly-React, but shows up on the patternfly website as well.
* What are the steps to reproduce the issue and what is the expected behavior? Just view any Donut Chart on Firefox

CSS has no effect on this. There are possible hacks we could use by selecting the title text after rendering and moving its position, but it causes other rendering glitches.

I have not been able to find a way to override the title format. And `pfSetDonutChartTitle` doesn't allow to pass any other data to it.

**Comment by jeff-phillips-18** [comment]
Thanks @vkareh, are you interested in contributing the fix?

**Comment by ddelabru** [comment]
The crux of the issue appears to be Firefox handling `dominant-baseline: middle` differently when it's applied to a `<text>` element with nested `<tspan>`s. I'm not much of a CSS/SVG artist, but I'm looking into a way to change the properties on this so the appearance is consistent and continues to look exactly as it does in Chrome now. (Firefox and Chrome render it the same way with `dominant-baseline: alphabetic` or with the property removed altogether, but this results in a wider gap between the "big" and "small" titles.)

**Comment by ddelabru** [comment]
After a little further investigation I think this may have more to do with how Firefox handles `dy` on `tspan` elements in an SVG. The good news is that it looks like the same results can be achieved accross both Firefox and Chrome by simply using `y` on the donut chart title `tspan` elements instead. Will see if I can get a PR together for this.
