### ISSUE TITLE
Patternfly website is unresponsive on click events while exploring the patternfly 4 demos

### ISSUE THREAD

**Issue by riginoommen** [patternfly/patternfly-3#1172]
**For feature requests or enhancements, file an issue against [patternfly-design](https://github.com/patternfly/patternfly-design).**

* What browser(s), device and OS experience the problem?
**Google Chrome Version 74.0.3729.108 (Official Build) (64-bit)
Mac OS 10.14**

* What are the steps to reproduce the issue and what is the expected behavior?  For the the fastest support, provide a working demo or minimal reproduction using tools such as 

**Reproduction Video**
http://www.yourfilelink.com/get.php?fid=2000021

**Browser Console Error**
![Screenshot 2019-05-06 at 7 54 57 PM](https://user-images.githubusercontent.com/3840244/57232027-66b38a80-7039-11e9-9138-d33108c28efd.png)

**Tell us more about your product/project and timeline to help prioritize this issue.**
* Is this a customer reported blocking issue?
Yes while exploring the demos

[1] There are a number of PatternFly JS framework implementations including:
* [PatternFly-React](https://github.com/patternfly/patternfly-react)

Note, if you are leveraging one of the JS framework implementations of PatternFly, please ensure that the issue is a PatternFly-core issue. You may need to file an issue against one of the other repos.

**Comment by dgutride** [comment]
This was fixed in the patternfly/patternfly-org repo - thanks for submitting the issue.
