### ISSUE TITLE
Login - assumtions about dom structure

### ISSUE THREAD

**Issue by pvoborni** [patternfly/patternfly-3#12]
I was implementing login page and encountered several style limitations.
1. Assumption that it will be the top level and only page with this structure in DOM. Its difficult to place the login screen to some containing element and avoid touching html and body element. 
   - `.login-pf body` -> `.login-pf .login-pf-body`
2. Usage of ids instead of classes prevents to have two instances in DOM.
   - `#brand` -> `.login-pf-brand`
   - `#badge` -> `.login-pf-badge`
3. It might be better to have to 2 .rows in .container. First containing  `#brand`  and second containing .login and .details. The semi-transparent background would be transferred to the second. It will allow to remove the -70px relative position from `#badge` a thus remove the `height: 18px` assumption on `#badge img`. In the end  it should allow to use images with variable height without additional styles - good for branding.
4. background images with  non-uniform bottom (more colors than just `@login-bg-color`)  don't look good on tall (screen height > displayed bg img height) and medium width (768px < screen width < 1200px) screens. In this interval the image doesn't cover whole screen so the @login-bg-color color is displayed on the bottom part, creating a hard visible transition. The example PatternFly background doesn't suffer from this issue since it has quite uniform bottom colors making the transition smooth.  I'm not sure what should be the proper fix for other images. Maybe to use better image.

If there is some consensus, I can create patch for issues 1,2,3. The bad part is that these changes are not backwards compatible.

**Comment by kybaker** [comment]
----- Original Message -----

> I was implementing login page and encountered several style limitations.
> 1. Assumption that it will be the top level and only page with this structure
>    in DOM. Its difficult to place the login screen to some containing element
>    and avoid touching html and body element.
>    - `.login-pf body` -> `.login-pf .login-pf-body`
> 2. Usage of ids instead of classes prevents to have two instances in DOM.
>    - `#brand` -> `.login-pf-brand`
>    - `#badge` -> `.login-pf-badge`
> 3. It might be better to have to 2 .rows in .container. First containing
>    `#brand`  and second containing .login and .details. The semi-transparent
>    background would be transferred to the second. It will allow to remove the
>    -70px relative position from `#badge` a thus remove the `height: 18px`
>    assumption on `#badge img`. In the end  it should allow to use images with
>    variable height without additional styles - good for branding.
> 4. background images with  non-uniform bottom (more colors than just
>    `@login-bg-color`)  don't look good on tall (screen height > displayed bg
>    img height) and medium width (768px < screen width < 1200px) screens. In
>    this interval the image doesn't cover whole screen so the @login-bg-color
>    color is displayed on the bottom part, creating a hard visible transition.
>    The example PatternFly background doesn't suffer from this issue since it
>    has quite uniform bottom colors making the transition smooth.  I'm not sure
>    what should be the proper fix for other images. Maybe to use better image.

I will modify the background image so it is a solid color across the bottom. Also I will provide a color for the background which should make the image seamless.

**Comment by rhamilto** [comment]
If you want to take a stab at a pull request, Vopet, it'd be much appreciated.  It probably won't be incorporated until the next major release since the changes are not backward compatible.  We're still trying to finalize our release cadence, but we're looking at quarterly releases.

Thanks!

**Comment by xtrasmal** [comment]
@ everybody:  Override the patternfly css. Make huge images on huge screens and smaller ones on smaller screens. using mediaqueries. 

Anyways. Awesomeness all over over here. I have used a lot of bootstrap skins in the past. Nice to see a theme that is going to be standardized.

![Awesome](http://sc-cdn.scaleengine.net/i/0ca411cac787086e029ec7ef1d2c46ad.png)

Oh triangles for everybody: http://msurguy.github.io/triangles/

**Comment by rhamilto** [comment]
There are no plans to modify the login page at this time.
