### ISSUE TITLE
Buttons in alerts are misaligned

### ISSUE THREAD

**Issue by andreasn** [patternfly/patternfly-3#122]
I have a case where we throw an alert and have a button to resolve it (in this case it needs to start a system service in order to function properly).

I added the button html, added the class pull-right, but it's all misaligned.
Just to make sure it's no css in cockpit that messes it up, I edited an alert on the patternfly widgets page.

![screenshot from 2015-09-22 14-18-38](https://cloud.githubusercontent.com/assets/209895/10018208/292ba93e-6135-11e5-8136-f65122ddf46d.png)

Adding margin-top: -3px; to the element seems to help, but maybe there is a better solution.

**Comment by rhamilto** [comment]
Thanks, @andreasn!

Buttons in alerts is not a use case we'd identified, so it's not too surprising that this is a problem. We'll work on getting a fix in.

**Comment by andreasn** [comment]
Thanks!
