### ISSUE TITLE
Add PatternFly icons character mappings as variables

### ISSUE THREAD

**Issue by rhamilto** [patternfly/patternfly-3#128]
In a manner similar to https://github.com/FortAwesome/Font-Awesome/blob/master/less/variables.less

See https://github.com/openshift/origin/pull/4899#discussion_r40979344

cc: @jwforres

**Comment by jwforres** [comment]
cc @sg00dwin

**Comment by jwforres** [comment]
@rhamilto yes that is exactly what i was talking about :+1:
