### ISSUE TITLE
Provide a zip of patternfly

### ISSUE THREAD

**Issue by thescouser89** [patternfly/patternfly-3#13]
Hi,

I was wondering if it would be possible to provide a tarball or zip of the distribution of patternfly (similar to what Bootstrap offers here: http://getbootstrap.com/getting-started/#download) instead of having to install `bower`.

That would probably be useful for people like me who does not have `npm` or `node` installed on my computer.

**Comment by rhamilto** [comment]
hi, thescouser89.

you can download a zip right here from github.  https://github.com/patternfly/patternfly/archive/master.zip

i got that link from the lower right column of https://github.com/patternfly/patternfly

i hope that helps,
robb.

**Comment by thescouser89** [comment]
Ahh gotcha! Thanks for the link. So I guess I could just use the stuff in the dist folder, and link to these files in my html.
Just another question: will the fonts in the dist folder be included automatically? Or do I need to link to them in my html?

Thanks again for the reply!

**Comment by rhamilto** [comment]
Yeah, if you don't intend to modify PatternFly in any way, you can simply use the contents of /dist.

They will be automatically included as the CSS makes a relative call to them.

Hope that helps.

**Comment by thescouser89** [comment]
Awesome! Perfect! Thanks for replying! :)
