### ISSUE TITLE
FontAwesome path needs updating

### ISSUE THREAD

**Issue by erundle** [patternfly/patternfly-3#132]
Right now the fontAwesome path of "../../components/font-awesome/fonts" is causing some issues if you try and use patternfly.css out of box due to the "../../" You need to make sure your CSS is down 2 levels deep which isn't always possible of you need to override the FontFace Declaration. 

For a 3.0 release I would suggest we copy the FontAwesome fonts to dist/fonts/ via grunt and just change the "@fa-font-path" to just "../fonts". This will make Patternfly much easier to consume

**Comment by rhamilto** [comment]
Agreed.  I've done so in my 3.0.0 dev branch.  :)

**Comment by erundle** [comment]
Awesome!

**Comment by rhamilto** [comment]
This will be fixed by https://patternfly.atlassian.net/browse/PTNFLY-42

**Comment by rhamilto** [comment]
https://github.com/patternfly/patternfly/releases/tag/v3.0.0-alpha

**Comment by rhamilto** [comment]
Fixed with the v3.0.0 release.
