### ISSUE TITLE
Provide a way to easily move the navbar sideways

### ISSUE THREAD

**Issue by thescouser89** [patternfly/patternfly-3#14]
I was thinking something more like this: http://wrapbootstrap.com/preview/WB0573SK0

That could be useful if there are a lot of items in the top navbar, then moving it sideways might make it look cleaner. I might be wrong though!

**Comment by xtrasmal** [comment]
+1.. because I hate Limited Horizontal Space syndrome. 
I actually saw a website last week, which had a scrollbar inside the horizontal menu :) Made me lol.

**Comment by rhamilto** [comment]
Thanks for the suggestion, @thescouser89.  We are not going to pursue changes to the navbar at this time.
