### ISSUE TITLE
Design Kit for Wireframes

### ISSUE THREAD

**Issue by crudbug** [patternfly/patternfly-3#149]
Is there a plan to publish design toolkit for sketch / illustrator/ ? for creating wireframes. This will really help in accelerating workflows. 

http://grommet.io from HP has taken this approach - Design + Develop.

http://grommet.io/docs/design/resources

**Comment by rhamilto** [comment]
@LHinson and @serenamarie125, y'all want to answer this one?

**Comment by serenamarie125** [comment]
@crudbug @rhamilto @LHinson I've created a story in JIRA capturing the issue.  We need to do some further investigation and determine where it fits in our priorities.

@crudbug you can track the story here: https://patternfly.atlassian.net/browse/PTNFLY-785. Thanks for inquiring, this is something that we have discussed.

**Comment by mcarrano** [comment]
For anyone is using Balsamiq Mockups to create wireframes, I have created a
template that includes most common Patternfly widgets as symbols.  I'd be
glad to share that with anyone who is interested.

-Matt

On Sun, Nov 1, 2015 at 10:38 PM, Serena Chechile Doyle <
notifications@github.com> wrote:

> @crudbug https://github.com/crudbug @rhamilto
> https://github.com/rhamilto @LHinson https://github.com/LHinson I've
> created a story in JIRA capturing the issue. We need to do some further
> investigation and determine where it fits in our priorities.
> 
> @crudbug https://github.com/crudbug you can track the story here:
> https://patternfly.atlassian.net/browse/PTNFLY-785. Thanks for inquiring,
> this is something that we have discussed.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/patternfly/patternfly/issues/149#issuecomment-152903894
> .

## 

Matt Carrano
Sr. Interaction Designer
Red Hat, Inc.
mcarrano@redhat.com

**Comment by crudbug** [comment]
@rhamilto  @serenamarie125 thanks for looking into this. We have started an internal project, and this will surely speedup things on the design end. 

@mcarrano can you share the Balsamiq template, it will be a good reference point for the team. 

Thanks,
Alan

**Comment by kirantpatil** [comment]
:100:  :+1:

**Comment by andreasn** [comment]
I have an inkscape svg with some widgets I tend to reuse for my mockups. Doesn't cover everything, but some of it at least.
https://github.com/cockpit-project/cockpit-design/blob/master/widget-template.svg

**Comment by andresgalante** [comment]
I'll close this issue since it's so old. We have a sketch template and we will add it to the website soon. Thanks!

**Comment by mmack** [comment]
Any news on this? Can't find it on the website... @andresgalante

**Comment by mcarrano** [comment]
Templates for Sketch and Balsamiq Mockups can be found here: https://github.com/patternfly/patternfly-design/tree/master/resources/templates  @mmack please let us know if you have any questions or feedback if you use these.

@Mgranfie FYI
