### ISSUE TITLE
Standard dialog patterns

### ISSUE THREAD

**Issue by stefwalter** [patternfly/patternfly-3#161]
Although Patternfly has support for modals, there's no actual dialog patterns. Cockpit has implemented patterns and code for this. You can see basic description here:

https://github.com/cockpit-project/cockpit/wiki/HIG:-Dialogs

Is this something that we can work to include in Patternfly proper?

**Comment by stefwalter** [comment]
This has a purpose, by the way. Openshift Web Console and Cockpit would like to share some dialogs.

**Comment by LHinson** [comment]
This is awesome and we absolutely want to work on getting this work into PatternFly. I've created a story to kick of this effort [1]. Let me take it back to the team to evaluate and identify what the next steps are for getting this into PatternFly. We will be in close communication with you regarding any adjustments that we might want to make to get this to match the current PatternFly format to make sure we are all in agreement. 

Are you and the OpenShift team needing this to be in by a particular date? 

[1] https://patternfly.atlassian.net/browse/PTNFLY-927

**Comment by stefwalter** [comment]
If I had to guess, this will probably become a blocker some time in January. At that point there's a likely effort to bring some of the image registry code being worked on in Cockpit into the Openshift Web Console.

**Comment by andresgalante** [comment]
I'll close this issue since it might not be relevant anymore. @LHinson @stefwalter feel free to open it again if you feel otherwise.
