### ISSUE TITLE
Expanding and collapsing accordions with JS

### ISSUE THREAD

**Issue by skateman** [patternfly/patternfly-3#162]
Hello!

When you try to collapse/expand accordions using their [JS API](http://getbootstrap.com/javascript/#via-javascript-3), reopening the collapsed accordion by using the mouse causes expanding both accordions.

![animated](https://cloud.githubusercontent.com/assets/649130/11558761/ce00236a-99b4-11e5-8155-06146b434ddc.gif)

This causes problems in https://github.com/ManageIQ/manageiq/pull/5693

**Comment by rhamilto** [comment]
Given this appears to be a Bootstrap bug, an issue should be opened at https://github.com/twbs/bootstrap/issues.  I can reproduce at http://getbootstrap.com/javascript/#collapse.

**Comment by andresgalante** [comment]
Was this ever fixed upstream? or only on Bs4?

**Comment by bleathem** [comment]
Closing as out of date.
