### ISSUE TITLE
patternfly new component

### ISSUE THREAD

**Issue by sidahmedbenkhaoua** [patternfly/patternfly-3#166]
hi,
when wa can use the new component of patternfly as liste view toast .... ?
is not in github repository !
thanks

**Comment by rhamilto** [comment]
Hi, @sidahmedbenkhaoua.

You can keep track of what's happening with PatternFly over on the [product backlog](https://patternfly.atlassian.net/issues/?filter=10405).  I gather you're interested in [Toast notifications](https://patternfly.atlassian.net/browse/PTNFLY-526?jql=text%20~%20%22toast%22)?

**Comment by rhamilto** [comment]
Hi, @sidahmedbenkhaoua.

I just merged a [PR for Toast notifications](https://github.com/patternfly/patternfly/pull/170) that will release with v2.9.0 scheduled for tomorrow.
