### ISSUE TITLE
Patternfly is not compatible with less --strict-math=on

### ISSUE THREAD

**Issue by stefwalter** [patternfly/patternfly-3#168]
variables.less from Patternfly 2.8.0 fails to build:

```
ArgumentError: error evaluating function `ceil`: argument must be a number in /data/src/cockpit/pkg/registry/bower_components/patternfly/less/variables.less on line 273, column 69:
272 @dropdown-link-hover-color:                                         @gray-pf;
273 @font-size-h1:                                                      ceil(@font-size-base * 2); // ~24px
274 @font-size-h2:                                                      ceil(@font-size-base * 1.8333); // ~22px
```

We see this problem in Cockpit. We're using less version `2.5.3`

**Comment by stefwalter** [comment]
This failure is due to less strict math. Due to CSS3 offering calc(), and its support being very widespread, we'd like to start to make use of things like this. However in order to do so with less, --strict-math is required.

Patternfly's less files do not build with the strict --strict-math option.

**Comment by rhamilto** [comment]
Thanks for the feedback, @stefwalter.

In investigating this, it looks like we can easily fix any instances of math in PatternFly source less (by wrapping them in parentheses), but there is a [dependency](https://github.com/patternfly/patternfly/blob/master/less/patternfly-additions.less#L16) we're including that [poses a challenge](https://github.com/nostalgiaz/bootstrap-switch/blob/master/src/less/bootstrap3/bootstrap-switch.less#L84).

**Comment by rhamilto** [comment]
https://github.com/rhamilto/patternfly/commit/705887b20cec7506cecdb340ec49db45a89f1a8a enables strict-math and includes edits to the dependency.  I don't love this solution because of the edits to the dependency, but I suppose it's ok?  @jeff-phillips-18 @dtaylor113 @andresgalante

**Comment by stefwalter** [comment]
Nice. Looks like that does the trick.

**Comment by rhamilto** [comment]
@jeff-phillips-18 @dtaylor113 @andresgalante, you guys have thoughts on the proposed fix?

**Comment by jeff-phillips-18** [comment]
Looks OK to me.
