### ISSUE TITLE
question: best strategy for not gluing page content to top?

### ISSUE THREAD

**Issue by andreasn** [patternfly/patternfly-3#174]
When you create a page, if no header or breadcrumb exists, the content of the page will glue to the top. What's the best strategy to avoid this?
In Cockpit, we've been doing a little override on container-fluid and give it a margin-top of 20px, but we want and need to remove this, since it breaks things elsewhere.
The container-cards-pf class could theoretically work, but it feels weird to use it when I don't have cards.
Before I start creating a new custom class and a bunch of additional overrides to tame that, I wanted to check if I had missed any class out there.

![screenshot from 2016-01-18 16-45-19](https://cloud.githubusercontent.com/assets/209895/12395597/e5721c20-be02-11e5-9c98-560902156bab.png)

**Comment by LHinson** [comment]
@andreasn I've added this to our Jira so we can track. You can follow it here: https://patternfly.atlassian.net/browse/PTNFLY-1101 

We'll be in touch!

**Comment by andreasn** [comment]
Thanks!

**Comment by andresgalante** [comment]
Wow, this is old. Bootstrap 4 has [spacer utility classes](http://v4-alpha.getbootstrap.com/utilities/spacing/) to deal with this situations. You are not missing anything, but adding a margin on the menu will create more chaos than happiness.
