### ISSUE TITLE
Backgrounds should be optional

### ISSUE THREAD

**Issue by xtrasmal** [patternfly/patternfly-3#18]
1# Case one
Consider this: 
I do not want a background image, but a color.

Situation:
Open the patteryfly css.. remove the background-image attribute.

Problem:
When updating patternfly, my changes will be overridden 

Temp solution:
I could add my own css, but than it will download the image anyways..eventhough it will not use it. Because it is in the patternfly css which is loaded.
## 

2# Case two
Consider this: 
I want a custom background image.

Situation:
Open the patteryfly directory and replace the image.

Problem:
When updating patternfly, my changes will be overridden.

**Comment by rhamilto** [comment]
Hi, Xander.

If you're looking to override a PatternFly default, the recommended course of action is to compile the PatternFly CSS yourself.  In this case, you'd replace less/login.less with your own customized version.  That way, any updates to PatternFly won't affect your custom build for anything that you've explicitly changed.  I recommend you create your own Bower project with PatternFly as a dependency to do so.

I hope that helps,
Robb.

**Comment by xtrasmal** [comment]
Ok great Im new to bower and will look in to that. Good to hear that.
