### ISSUE TITLE
Bundle JS files like stylesheets and fonts

### ISSUE THREAD

**Issue by skateman** [patternfly/patternfly-3#192]
Is there any reason why the dependent JS files are not included into the repo?

**Comment by dtaylor113** [comment]
Hi,
As of PF v3.0.0.0 The dependencies are no longer committed to the repo. That means you must use Bower to install PatternFly or manually manage the dependencies.   This change was requested by consumers of Patternfly who indicated dependency conflicts within Patternfly and their applications.
Thanks,
- Dave Taylor

**Comment by skateman** [comment]
Hi!
Yes, I've read this but why do you have then a lib folder with all the less dependencies in the repo?
https://github.com/patternfly/patternfly/tree/master/less/lib

**Comment by robinsonaaron** [comment]
I'm wondering about the library less files too. Why don't you reference the less files instead of including them in the repo?

**Comment by rhamilto** [comment]
@skateman, @robinsonaaron, the dependency less files are copied to ease the production of the Red Hat branded version of PatternFly.
