### ISSUE TITLE
A way to initialize nav-pf-vertical-alt from JavaScript

### ISSUE THREAD

**Issue by ghost** [patternfly/patternfly-3#197]
Hello, I'm building an [SPA](https://en.wikipedia.org/wiki/Single-page_application) (using Angular 2) and I'd like to implement the [Vertical Navigation pattern](https://www.patternfly.org/patterns/vertical-with-persistent-secondary/). I've followed https://github.com/patternfly/patternfly/blob/master/tests/layout-alt-fixed-with-footer.html . The problem is that the `.nav-pf-vertical-alt` element is added to the DOM only after the `$(document).ready` handlers are executed. Thus, the navigation is not initialized and the "hamburger" button is not working.

How am I supposed to implement the pattern in my case? My idea is that it would be nice if you could document a JavaScript function which I'd call once I add the `.nav-pf-vertical-alt` element to the DOM. But maybe there is another common practice to handle this situation.

Or maybe I just misunderstood PatternFly at all. Maybe I'm not supposed to reuse the `layout-alt-fixed-with-footer.html` code at all. Maybe its up to me to write an implementation. But why would you distribute PatternFly as a library than... I'm new to web development so please forgive me if my request or my assumptions are wrong.

**Comment by jeff-phillips-18** [comment]
You can initialize the vertical alt layout by calling $().navigation();

However, Patternfly will be releasing a new vertical layout (non 'alt') with persistent secondary nav in 3.1 which will release any day now. You can see the new version of the vertical layout in PR #195.

**Comment by ghost** [comment]
Thanks. Can it be documented somewhere so that I can be sure that it won't change in later minor releases? (Assuming that PatternFly cares about backwards compatibility)

**Comment by jeff-phillips-18** [comment]
The layout-alt components are less supported than the standard Patternfly components. There is no documentation for the Alt layouts on Patternfly.org. These tests pages are for development testing purposes and the supported components can be found on Patternfly.org.

**Comment by ghost** [comment]
OK. Would it make sense to turn this report into a request for support of these components?

**Comment by LHinson** [comment]
Hey @radek-holy. Our apologies about the confusion with the alt nav layout. As @jeff-phillips-18  mentioned, this is not a PatternFly supported version of the nav. My apologies for the confusion - we need to do a better job of indicating what is unofficial test versions vs the PatternFly approved versions. We will be adding a warning to the alt nav page that you found in hopes to provide some clarification. 

You can find documentation for the supported version of our nav here: https://www.patternfly.org/patterns/vertical-with-persistent-secondary/. As @jeff-phillips-18 mentioned, this will be released in the next couple days. 

You are more than welcome to submit a request for support however it would require us revisiting the design and code because we won't support it as is. With the addition of the new nav and due to current priorities and bandwidth, it's not likely that this will be something we can address in the near future. I'm hoping that the new nav fits your needs.

**Comment by ghost** [comment]
Hello. Well, I guess that the supported version could fit my needs, but... What actually do you mean by "supported"? Can you please point me to a clarification? TBH, I thought that the `layout-alt-fixed-with-footer.html` code actually is an implementation of the "vertical-with-persistent-secondary" pattern and thus that the code is supported because the pattern seemed to be supported. But if the code is not supported but the pattern is, what else except [the illustrated document](https://www.patternfly.org/patterns/vertical-with-persistent-secondary/) do you provide for people who would like to implement it?
(Please, don't take me wrong. I'm just a bit confused. I feel I'm just missing some important piece of puzzle...)

**Comment by jeff-phillips-18** [comment]
@radek-holy the layout-alt-fixed-with-footer.html is not an implementation of the Vertical with Persistent Secondary. It is an alternate layout for the standard horizontal navigation and does not include any secondary menu support. It was done as a one-off and not meant for general consumption. As @LHinson said, we need to address this and determine an appropriate way to indicate that.

PR #195 addresses this and will be released shortly. Patternfly.org will often contain patterns that are not yet implemented. Design before development...

Once the vertical navigation with persistent secondary feature is complete, there will be a link to the reference implementation from Patternfly.org. Patternfly.org is the site where you can find the Patternfly supported components.

**Comment by ghost** [comment]
Thank you. I guess I got it now. I am looking forward to the new layout.

So, feel free to close this, or turn this into a request for the new layout, or a request to add a warning to `layout-alt-fixed-with-footer.html`, or a request to support these components, or a request to add a clarification to the Patterns Overview document regarding the fact that not every component shown in the documents is available yet. I can also create separate reports for these requests if you wish.

Thank you and good luck :)

**Comment by jeff-phillips-18** [comment]
While not tracked here, I will be adding the warning to the alt layout pages as well as our standard full page components.
