### ISSUE TITLE
"grunt" command isn't available after following the steps in the README.

### ISSUE THREAD

**Issue by mvollmer** [patternfly/patternfly-3#2]
One way to get it is "sudo npm install -g grunt-cli", but I can't say whether this is the right way.

**Comment by rhamilto** [comment]
Hi, Marius.

Assuming you've successfully installed node.js, Bower, and run the Bower install, you should only need Grunt if you're planning on developing PatternFly itself.  The Bower install will get you all the dependencies need to _use_ Patternfly.

Does that help?
Robb.

**Comment by mvollmer** [comment]
The "bower install" step is already in the "Development" section, so I thought I need to do the rest as well.  For example, it surprises me now that the generated files are actually checked in.  I thought I need to generate them from source.

But, let's pretend that I wanted to do development, and the README nicely takes me by the hands and mentions all steps that I need to do to follow along.  It is a great help for someone like me that is totally new to current best practices in web development. So, I think it should also mention installing "grunt-cli", just to prevent people like me from stumbling.

Thanks!

(I am not asking for help, I try to help make the README better. :-)

**Comment by rhamilto** [comment]
Ah.  I gotcha.  Thanks for the input!  I did add a sentence about being "done" after installing the Bower components.

I think I'll leave out the "grunt-cli" bit for now as it hasn't been necessary so far, and I don't want to confuse those who don't need it.

Thanks again, Marius!
