### ISSUE TITLE
Font-awesome / Glyphicons links in distribution point outside of distribution

### ISSUE THREAD

**Issue by lfryc** [patternfly/patternfly-3#20]
In [dist/css/patternfly.css](https://github.com/patternfly/patternfly/blob/v1.0.2/dist/css/patternfly.css#L5816):

```
@font-face {
  font-family: 'FontAwesome';
  src: url('../../components/font-awesome/fonts/fontawesome-webfont.eot?v=4.0.3');
  ...
}
```

This works during patternfly development, but it does not work when using patternfly as bower dependency, installed in `bower_components` directory (project specific):

```
GET http://localhost:8080/ag-push/bower_components/patternfly/components/font-awesome/fonts/fontawesome-webfont.woff?v=4.1.0 404 (Not Found)
GET http://localhost:8080/ag-push/bower_components/patternfly/components/font-awesome/fonts/fontawesome-webfont.ttf?v=4.1.0 404 (Not Found)
GET http://localhost:8080/ag-push/bower_components/patternfly/components/font-awesome/fonts/fontawesome-webfont.svg?v=4.1.0 404 (Not Found) 
```

**Comment by rhamilto** [comment]
D'oh.  Just kidding!  That doesn't fix it.  Let me dig into this a bit deeper.

**Comment by rhamilto** [comment]
I've been poking at this for a couple days now.  Unfortunately, I don't see a path forward.  PatternFly incorporates LESS/CSS and fonts from Bootstrap and Font Awesome and the pathing to those assets cannot be variable-ized due to a scoping limitation when using variables in import statements in LESS (http://lesscss.org/features/#variables-feature-import-statements).  Unless I'm not seeing something, I think the answer is don't install PatternFly using Bower.  :(

**Comment by lfryc** [comment]
The thing is to come up with anything that will work in dist, say we have:

```
dist/css/patternfly.css
fonts/OpenSans-Bold-webfont.eot
....
```

then this will work from bower, ZIP dist, etc. just fine:

```
@font-face {
    src: url('../fonts/OpenSans-Bold-webfont.eot'
```

Then, you can make it work in development too,
using `connect` configuration and `mountFoulder` function,
you can mount the `bower_components/font-awesome/...` directory (or any other) to exactly the place where it is expected.

What do you think?

---

Another solution could be externalizing fonts.css, so that everyone could use them at own - either use patternfly-bundled fonts or not.

**Comment by vrockai** [comment]
I personally believe it's very important to have functional bower support.

**Comment by lfryc** [comment]
No saying that ZIP distribution can't work as well.

**Comment by rhamilto** [comment]
@lfryc, to recap, there are two issues based on your installation method (zip or git clone vs. bower):  1.  the name of the folder where dependencies are installed (components vs. bower_components).  2.  the location of the patternfly CSS in relation to the external assets it utilizes (e.g., font awesome font files) (root vs. patternfly--one level up or two levels up).  Unfortunately do to a limitation in LESS, variables cannot be used to modify the resulting paths as needed.  I'm not entirely sure I understand your proposal, but it sounds feasible.  An option that I am currently exploring is to add the dependencies to the repo.  So far, it looks promising.  And, as an added bonus, it will alleviate the confusion regarding the need to install the dependencies separately as well as make building RPMs of PatternFly easier (something @gregsheremeta is exploring).

@vrockai, I agree. We just need to figure out how to make it work!  :)

**Comment by vrockai** [comment]
Just for the record: the FA font is not the only dependency from components. The 2nd one is the "glyphicons-halflings-regular" font.
