### ISSUE TITLE
Collapse plugin not present

### ISSUE THREAD

**Issue by rnovacek** [patternfly/patternfly-3#21]
The collapse plugin from Bootstrap seems not to be present in the patternfly.js file. If is a feature then the documentation should mention it and provide simple way how to get standalone collapse plugin.

**Comment by rnovacek** [comment]
Or should be Bootstrap always used together with PatteryFly? I couldn't find this information anywhere.

**Comment by rhamilto** [comment]
PatternFly incorporates Bootstrap's CSS in its CSS, but it does not incorporate Bootstrap's JavaScript (so as to keep the Bootstrap JavaScript modular--see http://getbootstrap.com/javascript/#js-overview).  Suggestions on how to clarify this in the documentation?

**Comment by rnovacek** [comment]
I would just add remark to the beginnings of the these sections
https://www.patternfly.org/widgets/#javascript and
https://www.patternfly.org/widgets/#css, 
stating what you wrote.

**Comment by rhamilto** [comment]
Thanks, Radek.  I've updated https://www.patternfly.org/widgets/ accordingly.
