### ISSUE TITLE
Representation of address ranges, e.g., bytes, KiB, kB, TB as well as input

### ISSUE THREAD

**Issue by mulkieran** [patternfly/patternfly-3#216]
This is related to #210.

I have a sample (Python) implementation of some of these ideas here:
https://github.com/mulkieran/justbytes with documentation here: http://pythonhosted.org/justbytes/.

These are some proposals for the representation of address ranges. I'm starting from the assumption that IEC units are preferred, since I have been told that that is generally the policy and since I agree with that policy.
- The  values should be represented in such a way that the user knows what they mean. There are several parts to this problem, the choice of units, the effects of rounding, and the effects of the base in which the values are represented.
- The choice of units. I concur with the choice of IEC units. The problem is that in order to understand a represented value the user should know what the displayed units mean. Currently, it seems that the official policy to overload the XB format to mean IEC or SI units according to context. Unfortunately, this is likely to lead to confusion for the user. An option, which I prefer, is that the XiB format should be used because it absolutely disambiguates the meaning of the value. If there are reason why that can not be done, something else should be thought of. One heavyweight possibility is to allow a user to configure their choice of unit type. I have not thought of any other possible approach, but it _is_ important to disambiguate.
- The effect of rounding. Generally, address ranges may be presented using a fixed precision. Often this means that the value displayed is not the same as the value represented. I propose that such values be displayed with an accompanying modifier. One modifier could just indicate that the value show is approximate. Alternatively, and with a bit more richness, the less than and greater than symbols could be used to indicate the relationship of the value displayed to the actual value. Further, I propose that these values be made clickable; clicking on a value would cause it to be displayed using the largest unit that allows a non-fractional representation. So, exactly 10894704640 B would be displayed as 10.15 GiB (with the symbol meaning approximation), but clicking on the value would give 10390 MiB, since that value is exact and requires no fractional part. Many people seem to like a fixed precision of two digits after the radix point, probably on the assumption that humans can't handle any more digits.
-  The choice of base. Typically base 10 is used, because of its long historical predominance. This leads to difficulties since a change in IEC unit represented changes the highest order bits of the numeric part of the value which is counter intuitive and hard to work with. The example shows the problem...the leading four digits of the bytes is 1089, of the MiB representation, 1039, of the GiB representation 1015. The use of base-1024 would entirely fix the problem. The number of bytes would be 10,150,0,0; the number of MiB 10,150 and the number of GiB 10.150. Now that's intuitive!

Generally speaking, I feel that if there is no right answer, it makes sense to make some of these choices configurable. I think that the use of base-1024 would catch on very rapidly among those with a better CS or math background because of its ease of use, but could easily scare off others who are unfamiliar with bases other than 10. That makes the choice of base particularly desirable to make configurable.
- User input.

Regarding the proposal in #210, I concur strongly with the choice of making the units a widget, rather than allowing the user to enter the units as text. I also like the slider, because it shows the relation of the value the user specifies to some other significant related quantity. However, it would be nice if somehow
what the quantity that the full length of the slider represents could be represented somehow within the whole slider widget. I also feel that the units would be better represented as a wheel with + and - buttons rather than a list, due to their strong implicit ordering.

If you are consulting the justbytes library for examples, be aware that there is one significant difference between the requirements for the justbytes library and the ideas I have outlined above. The justbytes library also supports computation and, according to its design principles, it allows fractional quantities of bytes and is able to display the exact values of fractional quantities of bytes. So, 1/3 of a KiB is represented in base 10 as 341.(3) KiB where the value in parentheses is understood to repeat infinitely. I do not think that this should arise in a typical GUI so the complexity and generality could be reduced a good deal from the justbytes approach.

**Comment by mulkieran** [comment]
There is a significant difference between rate (bytes per second) and address range (bytes). Rate, whether it is across a network or disk I/O resembles a physical quantity, e.g., gallons per second, and does not have the special requirements for precision and representation that address range has. The reason is that rate is a measure of performance, and its approximate magnitude is what matters, while address ranges are a precise division of a structured entity, an address space and precision is necessary.

**Comment by mulkieran** [comment]
justbytes package now available in Fedora's 22, 23, 24, rawhide.

**Comment by mulkieran** [comment]
When possible, it might be reasonable to avoid input of exact size values altogether. While, in some cases, the _exact_ value entered is exactly what the user gets, in many cases it is not. So, where it is possible to specify the value not as an exact quantity of bytes, but as a proportion of some other relevant quantity, that is, in many cases, a superior solution. So, for example, lvm2, a storage management tool which requires user input to specify the size for many operations, allows a  specification in terms of a percentage of an existing structure it already knows.

So, for that kind of thing, the resulting size can be shown as informationally useful, but the user just specifies a %, like in the mockup below.
![screenshot from 2016-05-04 10-46-38](https://cloud.githubusercontent.com/assets/1218366/15017904/82af8208-11e5-11e6-94a6-ffd38715d563.png)
When allocating space, the user is likely to be thinking in terms of the % of space available or used or what not, so having them enter an absolute size forces them to do an extra computation. Because, in some cases, the underlying app can not guarantee the exact size requested, this seems especially pointless.

**Comment by mulkieran** [comment]
justbytes-gui now available on pypi.

**Comment by andresgalante** [comment]
Thanks a lot for your input. I am going to close this issue for now. If there is a need for a slider for more than one patternfly consumer we can go though the patternfly process to add a new component. Please send an email to the mailing list and we'll discuss it there.

**Comment by mulkieran** [comment]
@andresgalante I'm afraid this sentence "If there is a need for a slider for more than one patternfly consumer we can go though the patternfly process to add a new component." is entirely opaque to me. Could you explain?

**Comment by andresgalante** [comment]
Sorry, I was too vague.
We have a process to add new components to patternfly. It starts with proposing it to the mailing list. If we have more than one +1 then we add to the library. Now that I am writing it, it sounds silly since that fact that you've open this issues means than more than one person want's a slider.

@LHinson Can we create a story to add a slider to patternfly please?

**Comment by mulkieran** [comment]
@LHinson Could you point me at where this might be happening? Thanks!

**Comment by LHinson** [comment]
@andresgalante reopening right now as I haven't made the story yet. 

@mulkieran do you have a test page that you can point me to to check out this implementation that you had in mind?

**Comment by mulkieran** [comment]
I'm sure I don't. I don't run in patternfly circles, I work on lower-level storage tools. But these sometimes require users to specify sizes, and it often seems to me that mistakes are made in choosing the interface to do the specifying. That is why I ended up here, since my understanding is that patternfly is about coming up with some agreed upon standards.

**Comment by LHinson** [comment]
@mulkieran, @andresgalante and I have looked into this and we would like to add a slider to PatternFly. We are asking @jawnsey to send a PR for the slider seen here: https://jsfiddle.net/ez7suLrm/

Would love for you to review that PR, if interested. Thanks again for bringing this to our attention and apologies for the delay in getting it added to PatternFly!

**Comment by mulkieran** [comment]
Hi!

I took a look at the link. I'm not sure how to review...I see two sliders, which can be moved independently of each other. The quantities are meant to be tied together in my conception, so the sliders can not be independent. Is there
a PR as well as a mockup that I can look at?

**Comment by LHinson** [comment]
Hey @mulkieran, the PR has not been sent quite yet but we've asked @jawnsy to submit one.

**Comment by mulkieran** [comment]
@LHinson Can I give you a call about this tomorrow? I'ld say this afternoon, but I'm booked from 2:30 to 5:00, most unusual, and I'm going to be running before then.

**Comment by LHinson** [comment]
Yep, happy to discuss. Will you give me a better understanding of the specifics of what you want to address in the call?

**Comment by mulkieran** [comment]
I'm afraid I don't understand your process well enough to understand what I've gotten started. I'm worried that I'll end up causing something that I never intended.

**Comment by mulkieran** [comment]
@LHinson: Is there an irc channel you could typically be found on? I tried on Gitter.

**Comment by LHinson** [comment]
I'm on slack :/ @mulkieran getting on gitter now.

**Comment by LHinson** [comment]
@mulkieran sorry we kept missing each other some months ago. We are looking to add the slider to PatternFly. You can follow the design story here: https://github.com/patternfly/patternfly-design/issues/334

Implementation stories to follow. Closing this issue here as you can follow along over in patternfly-design. Thanks!
