### ISSUE TITLE
Datetimepicker style is corrupt

### ISSUE THREAD

**Issue by vniko** [patternfly/patternfly-3#230]
The eonasdan-bootstrap-datetimepicker  component doesn't looks  as expected
http://joxi.ru/1A5pLDwhKEezZ2?d=1

If i remove "patternfly-additions.css"
And instead use "eonasdan-bootstrap-datetimepicker/build/css/bootstrap-datetimepicker.css"
Everything looks just fine as expected
http://joxi.ru/V2VK6zMc0W6BxA?d=1

It seems the css overwrite is incorrect.

**Comment by dtaylor113** [comment]
Hi,
This issue was fixed in:

Fix for issue where time picker dropdown not covering content
https://github.com/patternfly/patternfly/commit/06bbae57e070c82851f6c59ed1925c8c9a3b9b5b

It will be available in our next Patternfly release.
Thanks,
- Dave

cc @jeff-phillips-18

**Comment by vniko** [comment]
@dtaylor113  Thank you!
