### ISSUE TITLE
Cyrillic symbols are missing in OpenSans font

### ISSUE THREAD

**Issue by vniko** [patternfly/patternfly-3#231]
Would you include OpenSans fonts with cyrillic glyphs?

**Comment by andresgalante** [comment]
Hi @vniko sorry for the super late reply.
@LHinson We should take a look at this and add it to our backlog. Think about what other glyphs we should consider?

**Comment by LHinson** [comment]
I've create a story in the backlog for this here: https://patternfly.atlassian.net/browse/PTNFLY-1652
