### ISSUE TITLE
Overly specific bower dependencies

### ISSUE THREAD

**Issue by himdel** [patternfly/patternfly-3#233]
Depending on a specific (patch) version of a bower package makes it impossible to use external libraries that depend on one of the patternfly-required libraries unless the version matches exactly.

There is no need for that, for packages that do follow semver, just make the dependency `>~`.

My specific problem is moment - `"moment": "2.11.2"` which should probably depend on `>~ 2.11` (or `>= 2.11.0 && < 2.13`).

**Comment by dtaylor113** [comment]
Hi @dlabrecq,
Can you please look at making this adjustment so it will be included in our next patternfly release?
Thanks,
- Dave

**Comment by dlabrecq** [comment]
I'll plan on changing this to ~2.11

**Comment by ceefour** [comment]
Please either update moment to `~2.12.0` or lax the version dependency as @himdel suggested: >= `2.11.0 && < 2.13`.

What's unfortunate is that https://github.com/Eonasdan/bootstrap-datetimepicker 4.15.35 actually depended on moment `~2.8` :( Latest version is 4.17.37 which [is not yet available in `npm`](https://github.com/Eonasdan/bootstrap-datetimepicker/issues/1522) :(

**Comment by dlabrecq** [comment]
This issue was addressed with PR #248.
