### ISSUE TITLE
bootstrap-treeview depends on bower and phantomjs

### ISSUE THREAD

**Issue by jmikulka** [patternfly/patternfly-3#236]
I'm using npm managed version of PatternFly to avoid need of installing bower. However one of the dependencies (`bootstrap-treeview`) has bower as a dependency. Besides that it also depends on phantomjs which seems to me like overkill. This is present since `patternfly@3.1.0`.

Would it be possible make all dependencies optional (https://docs.npmjs.com/files/package.json#optionaldependencies) and to ship only `dist`?

**Comment by dtaylor113** [comment]
Hi,
We can look into moving bootstrap-treeview into 'optionalDependencies' in the package.json file.

Can you please elaborate on what you mean by: "...ship only dist"? 

We used to ship all the dependencies in a '/components' directory, however this changed in v3.0.0 due to a number of patternfly users having issues with the dependencies we shipped and those same dependencies in their individual applications.  Uses requested we stop shipping patternfly dependencies and have users rely on the NPM and/or Bower to install the dependencies.

Thanks,
- Dave Taylor

**Comment by dtaylor113** [comment]
Hi @dlabrecq,
Can you please look at making this adjustment so it will be included in our next patternfly release?
Thanks,
- Dave

**Comment by dlabrecq** [comment]
I have some questions. Can we talk, @dtaylor113 ?

**Comment by jmikulka** [comment]
Hi @dtaylor113,

correct me if I am wrong but I assume that all necessary PatternFly files (js, css, fonts and images) are installed into the `dist/` (`node_modules/patternfly/dist/` and `bower_components/patternfly/dist/`). If I decide to use datatables or bootstrap-select in my project, I should explicitly install these extra packages alongside PatternFly to avoid installing lots of unused packages.

Hope that clarifies my concerns,
Jiri

**Comment by jmikulka** [comment]
Hi @dlabrecq,

thanks for moving bootstrap-treeview from dependencies to optionalDependencies. I was just wondering if it would make sense to move all but really essential (I assume the only crucial dependencies are jquery and bootstrap) dependencies to optional? 

In my use case I'm using npm to install PatternFly, jQuery, Bootstrap and datatables only. In my html I include only jquery, bootstrap, datatables and patternfly (in this order). Everything works like a charm which means that none of the current PatternFly dependencies is a real dependency but is an optional dependency (except jquery and bootstrap).

Thanks,
Jiri

**Comment by dlabrecq** [comment]
I'll have to defer to Dave/Jeff about making all dependencies (except jQuery and Bootstrap) optional. I don't know if we need to handle the case where dependencies are not available?

You may not be using components that require these dependencies, but that may not be true for all?

**Comment by dlabrecq** [comment]
This issue was addressed with PR #248.
