### ISSUE TITLE
OpenSans should go in components

### ISSUE THREAD

**Issue by gregsheremeta** [patternfly/patternfly-3#24]
I think dist/OpenSans\* should be moved into ./components/opensans/

**Comment by rhamilto** [comment]
Yeah, that's probably the correct call.  I'm not sure how we'd do that an maintain backward compatibility though.  Thoughts?

**Comment by gregsheremeta** [comment]
What would break? People shouldn't link right to the font files, so as long as we change the references in the css ... what am I missing? :)

**Comment by rhamilto** [comment]
Agreed.  They _shouldn't_.  My reservation is I have no idea what they are _actually_ doing.  :)

**Comment by gregsheremeta** [comment]
Other than symlinking, I don't see a way around possibly breaking someone's links :/

**Comment by rhamilto** [comment]
Gonna leave this one as is since I don't want to have to address the legacy issue.  :)
