### ISSUE TITLE
Add a "Showcase / Who uses PatternFly" page

### ISSUE THREAD

**Issue by ceefour** [patternfly/patternfly-3#245]
Should be front and center on the website. To get some rep points.

http://cockpit-project.org would be good here.

**Comment by LHinson** [comment]
It would be nice if we could set something up so that people could submit pull requests to post their examples of patternfly. something like this... http://beautifulopen.com/

What do you think? 

Looping in @andresgalante

**Comment by LHinson** [comment]
I've also added this to our backlog https://patternfly.atlassian.net/browse/PTNFLY-1347

**Comment by andresgalante** [comment]
@ceefour Great idea 👍
