### ISSUE TITLE
Inline code style looks like a warning, feel off brand

### ISSUE THREAD

**Issue by rhamilto** [patternfly/patternfly-3#254]
The [inline code styles inherited from Bootstrap](http://getbootstrap.com/css/#code-inline) seem a bit off brand for PatternFly and almost read as a warning.

![screen shot 2016-04-11 at 4 39 25 pm](https://cloud.githubusercontent.com/assets/895728/14441777/733d356a-0004-11e6-8cdd-a2a264565b3d.PNG)

Perhaps a more subtle approach would be better?  

![screen shot 2016-04-11 at 4 41 52 pm](https://cloud.githubusercontent.com/assets/895728/14441860/f5f5849e-0004-11e6-9ec6-51ca713836ad.PNG)

CSS change for the proposed approach.

![screen shot 2016-04-11 at 4 46 50 pm](https://cloud.githubusercontent.com/assets/895728/14441870/03388624-0005-11e6-8e40-0103a069d2b9.PNG)

Within OpenShift, we're plan to override the inline code styling, but it's probably better to make the adjustment upstream in PatternFly.

I am happy to submit a pull request for this change once it has the blessing of the team.  Just let me know.

cc:  @jwforres, @spadgett, @benjaminapetersen, @sg00dwin

**Comment by andresgalante** [comment]
You are right @rhamilto, it does look off and I am sure Kyle agrees.

It would be great if you send a PR!

**Comment by rhamilto** [comment]
> It would be great if you send a PR!

Done.  #284

**Comment by andresgalante** [comment]
Thanks a lot @rhamilto 😄
