### ISSUE TITLE
style issue with input="number"

### ISSUE THREAD

**Issue by andreasn** [patternfly/patternfly-3#255]
If I add an input with type="number" the spinner controls for the element gets a bit of a weird appearance.

![screenshot from 2016-04-12 11-30-40](https://cloud.githubusercontent.com/assets/209895/14455847/01d5ea72-00a2-11e6-8b6e-8ea83e58db70.png)

This is using Firefox on Fedora 23. There are similar issues with Chrome. Chrome also adds padding on top and bottom.

This piece of css seems to fix that.
`input[type=number] {
  padding: 0 0 0 5px;
}`

https://www.w3.org/TR/html-markup/input.number.html

**Comment by cardosogabriel** [comment]
Hi @andreasn . Unfortunately every browser presents it in a different way. This article show some workarounds, for example removing the controls: https://css-tricks.com/numeric-inputs-a-comparison-of-browser-defaults/
Hope this helps.
