### ISSUE TITLE
Datatables headers merge when using multiple sort columns

### ISSUE THREAD

**Issue by heathtechnical** [patternfly/patternfly-3#260]
As per title, you end up with something like this:

<img width="360" alt="datatables-header-stack" src="https://cloud.githubusercontent.com/assets/8162329/14628550/126488b2-05f7-11e6-980a-2e41ece8a76d.png">

Any clues on how I might fix that?

**Comment by dtaylor113** [comment]
Hi,
What browser are you using?
Thanks,
Dave

**Comment by dtaylor113** [comment]
Also, can you please post a code snippet on how you are specifying the multiple sort columns.
Thanks,
Dave

**Comment by heathtechnical** [comment]
Hi Dave,

I'm using Safari 9 but pretty consistent across browsers - same on IE 11 and Chrome 49.

I can provide code if needed but you can reproduce using the widget demo here:

https://www.patternfly.org/widgets/#data-tables

Shift + click column headers.

**Comment by dtaylor113** [comment]
Hi,
Ok, I was able to reproduce it.  Thanks for discovering this!
We will add this issue to our backlog.
Dave

**Comment by LHinson** [comment]
Thanks @dtaylor113 and @heathtechnical - I've added a bug to our Jira https://patternfly.atlassian.net/browse/PTNFLY-1381
