### ISSUE TITLE
Charts X axis tick labels

### ISSUE THREAD

**Issue by PanSpagetka** [patternfly/patternfly-3#265]
Hi, I integrate PatternFly charts in ManageIQ and I have some problems with labels on X axis when we have lot of data. Try to fix it by myself, but so far i wasnt successful. If you could fix it, so labels would be readable or give me advice how can i fix it.
Here are some screenshots:
![badxlabels](https://cloud.githubusercontent.com/assets/9535558/14779333/f6776652-0ad7-11e6-8da6-925e8919a698.png)
![badxlabels2](https://cloud.githubusercontent.com/assets/9535558/14779334/f740e702-0ad7-11e6-8799-7b8eaef9a4c9.png)
And this is object on which we call c3.generate():

`````` json{"axis":
{"x":{"type":"category","show":true,"categories":["19:54:00","19:54:20","19:54:40","19:55:00","19:55:20","19:55:40","19:56:00","19:56:20","19:56:40","19:57:00","19:57:20","19:57:40","19:58:00","19:58:20","19:58:40","19:59:00","19:59:20","19:59:40","20:00:00","20:00:20","20:00:40","20:01:00","20:01:20","20:01:40","20:02:00","20:02:20","20:02:40","20:03:00","20:03:20","20:03:40","20:04:00","20:04:20","20:04:40","20:05:00","20:05:20","20:05:40","20:06:00","20:06:20","20:06:40","20:07:00","20:07:20","20:07:40","20:08:00","20:08:20","20:08:40","20:09:00"]},
"y":{"show":true}},
"data":{"type":"line","columns":[["1",30961.8538,30966.7676,30966.7676,30966.7676,30961.8538,30966.7676,30966.7676,30966.7676,30966.7676,30966.7676,30966.7676,30966.7676,30961.8538,30966.7676,30966.7676,30961.8538,30961.8538,30966.7676,30961.8538,30961.8538,30961.8538,30961.8538,30961.8538,30961.8538,30961.8538,30966.7676,30966.7676,30966.7676,30961.8538,30961.8538,30961.8538,30966.7676,30966.7676,30966.7676,30966.7676,30966.7676,30966.7676,30966.7676,30961.8538,30961.8538,30966.7676,30966.7676,30966.7676,30966.7676,30966.7676,30966.7676],["2",49138,49138,49138,49138,49138,49138,49138,49138,49138,49138,49138,49138,49138,49138,49138,49138,49138,49138,49138,49138,49138,49138,49138,49138,49138,49138,49138,49138,49138,49138,49138,49138,49138,49138,49138,49138,49138,49138,49138,49138,49138,49138,49138,49138,49138,49138]],
"names":{"1":"Avg Used","2":"Available"}},
"color":{"pattern": ["#0088ce","#cc0000","#3f9c35","#ec7a08","#007a87","#f0ab00","#703fec","#00b9e4","#92d400","#030303"]},
"grid":{"x":{"show":false},"y":{"show":true}},
"legend":{"show":true},"point":{"r":3,"focus": "expand":"r":5}}},"miqChart":"Line","bindto":"#miq_chart_candu_0","size":{}}```
``````

**Comment by jeff-phillips-18** [comment]
You can set the axis.tick.culling fields to limit the number of tick texts shown. See http://c3js.org/reference.html#axis-x-tick-culling  and http://c3js.org/reference.html#axis-x-tick-culling-max

Jeff

**Comment by PanSpagetka** [comment]
Yep, i try it, but result still is not ok. This is how it looks with culling max: 5. The line wrapping doesnt look good.
![maxculling5](https://cloud.githubusercontent.com/assets/9535558/14818382/1ddc27d8-0bbd-11e6-9c45-9aae14f9bf50.png)

**Comment by jeff-phillips-18** [comment]
You could rotate the tick labels so that they would fit in the space provided. See http://c3js.org/reference.html#axis-x-tick-rotate
