### ISSUE TITLE
Add support for consistently styled file upload buttons

### ISSUE THREAD

**Issue by bangert** [patternfly/patternfly-3#269]
http://www.abeautifulsite.net/whipping-file-inputs-into-shape-with-bootstrap-3/

The above site has some useful variations of a nicely styled file upload button which would make a fine addition to patternfly.

Thanks

**Comment by andresgalante** [comment]
Hi @bangert, I am sorry for the late reply.

Thanks for the suggestion, styling file input is always tricky. Do you have a use case for it?

**Comment by bangert** [comment]
In my case, i need to give the user the ability to upload a CSV file, which will allow the mass import of json objects, which my angular app then creates at the backend.

**Comment by andresgalante** [comment]
@bangert I must be honest, I don't like styling input file fields. All the solutions to do it with js or css seems hacky to me. But since you have a usecase, lets take a look at it.

Are you wiling to send a PR with it or do you want us to add it to our backlog?

**Comment by bangert** [comment]
well, in my opinion this particular solution is rather clever and flexible, given the constraints of the system. ;-)
I have no plans of submitting a PR myself. thanks...

**Comment by andresgalante** [comment]
@bangert yes, it is a good solution.I'll look into it.

Thanks a lot!

**Comment by dabeng** [comment]
HI guys, why not introduce[ jquery file upload plugin](http://blueimp.github.io/jQuery-File-Upload/) directly, it has no match.

**Comment by andresgalante** [comment]
@bangert Bootstrap 4 has custom file inputs:
http://v4-alpha.getbootstrap.com/components/forms/#file-browser
We will address this improvement on [PF5 CSS](https://github.com/patternfly/patternfly-atomic) that is based on BS4
