### ISSUE TITLE
Typo in variables.less

### ISSUE THREAD

**Issue by randyrankin** [patternfly/patternfly-3#272]
There is a typo in variables.less on line 119. 

@nav-pf-vertical-**secondayr**-indicator-padding:

Should be 

@nav-pf-vertical-**secondary**-indicator-padding:

**Comment by dlabrecq** [comment]
LGTM

**Comment by randyrankin** [comment]
LGTM meaning it's supposed to be spelled that way?

**Comment by dlabrecq** [comment]
The change looks good to me.

**Comment by andresgalante** [comment]
@randyrankin thanks for spotting it! 😄
