### ISSUE TITLE
Move Datatable To Angular UI

### ISSUE THREAD

**Issue by sherl0cks** [patternfly/patternfly-3#276]
The current datatable implementation uses [jquery datables](https://www.datatables.net/), which is at odds with the other angular components in the framework. It seems to me that patternfly should be using [Angular UI Grid](http://ui-grid.info/) instead.

**Comment by jeff-phillips-18** [comment]
@sherl0cks Did you mean for this issue to be against the angular-patternfly repo?

**Comment by dtaylor113** [comment]
Hi,
patternfly/patternfly uses HTML/CSS/Javascript and jQuery.  patternfly/angular-patternfly contains angular directives for corresponding patternfly layouts and widgets.  We will evaluate using Angular UI Grid when we implement PF datatables in angular-patternfly.  It is in our backlog: https://patternfly.atlassian.net/browse/PTNFLY-883

**Comment by sherl0cks** [comment]
@jeff-phillips-18 not sure, it's possible I got this wrong

@dtaylor113 just so I'm clear, patternfly/patternfly continue to use jQuery datatable, patternfly/angular-patternfly would use angular UI (assuming it is chosen), and end users would be responsible for managing which dependencies get brought in?

**Comment by dtaylor113** [comment]
Hi @sherl0cks , yes that is correct.

**Comment by sherl0cks** [comment]
@dtaylor113 thanks. Closing the issue.
