### ISSUE TITLE
setupVerticalNavigation error

### ISSUE THREAD

**Issue by jhotujec** [patternfly/patternfly-3#290]
Tried to use this: https://rawgit.com/patternfly/patternfly/master/tests/vertical-navigation.html#, it didn't work.

<img width="1098" alt="screen shot 2016-05-18 at 01 35 24" src="https://cloud.githubusercontent.com/assets/784318/15342892/f150a0a8-1c98-11e6-927a-6d693e41e8f2.png">

**Comment by andresgalante** [comment]
@jeff-phillips-18 Do you have a few mins to help @jhotujec please?

**Comment by jeff-phillips-18** [comment]
This is working fine for me.

**Comment by andresgalante** [comment]
@jeff-phillips-18 thanks, works fine here also, and I see no error on my console for:
https://rawgit.com/patternfly/patternfly/master/tests/vertical-navigation.html#

@jhotujec Can you explain a bit more where are you getting that error?

**Comment by jhotujec** [comment]
@jeff-phillips-18 @andresgalante sorry guys, forgot to update patternfly dependencies :/ everything works as expected.
