### ISSUE TITLE
Color of the links on form messages

### ISSUE THREAD

**Issue by andresgalante** [patternfly/patternfly-3#295]
Follows the discussion on: https://github.com/openshift/origin-web-console/pull/18

@rhamilto and the Openshifters spotted that links on form messages are blue:
![unnamed](https://cloud.githubusercontent.com/assets/1832037/15583696/4ae7a7b4-234d-11e6-8501-653d2afa6d7c.png)
They suggested to keep them red with an underline:
![unnamed-1](https://cloud.githubusercontent.com/assets/1832037/15583701/515797d0-234d-11e6-8b40-8b02e6af55b6.png)

To be honest I don't like the red underline and I suggest a darker shade of the same color the message is, for example success message links will be darker green. @sjcox-rh what do you think?

@LHinson Since LizC is working on a form document at the moment, maybe its a good opportunity to take a look at it.

**Comment by rhamilto** [comment]
> To be honest I don't like the red underline and I suggest a darker shade of the same color the message is, for example success message links will be darker green

I trust you guys to come up with the correct solution.  I suggested underline because it leverages a user's existing mental model (links are underlined).  A darker color shade doesn't necessarily suggest a link?

**Comment by sjcox-rh** [comment]
So I keep going back and forth.  Yes underlining it suggests a link but we
don't underline links until the hover state, so I don't want to change that
logic.   I would recommend the darker shade of the message color.  But it
has to be dark enough (without appearing black) that the user can
distinguish that it's different.  And on hover it would be underlined.

Thoughts?
SJ

On Thu, May 26, 2016 at 2:11 PM, Robb Hamilton notifications@github.com
wrote:

> To be honest I don't like the red underline and I suggest a darker shade
> of the same color the message is, for example success message links will be
> darker green
> 
> I trust you guys to come up with the correct solution. I suggested
> underline because it leverages a user's existing mental model (links are
> underlined). A darker color shade doesn't necessarily suggest a link?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/patternfly/patternfly/issues/295#issuecomment-221950125

## 

_Sarah Jane Cox_
User Interaction Designer
User Experience Design Team

Red Hat, Inc.
http://www.redhat.com/about/whoisredhat/redhatstories.html?intcmp=70160000000TB9vAAG&

**Comment by lclay2** [comment]
Quick question, in OS example what happens when you click the link?

**Comment by lclay2** [comment]
Couple thoughts: 
- Where does the link go? If it navigates the user out of the form that might be a surprise, unless it just opens a second window. So maybe show a nav link at the end of the error message with a little "going somewhere else" icon. I attached a quick mockup.
- If it's just opening up a pop-over, or bubble tip of some sort (and not navigating away from the page), then maybe there's a way to indicate that it's actionable but not a nav link. I attached a pic with a dotted line, just brainstorming.
  ![inline-error-link2](https://cloud.githubusercontent.com/assets/10948231/15618564/b40c4b26-241c-11e6-9fa9-8863099151a2.jpg)
  ![inline-error-link3](https://cloud.githubusercontent.com/assets/10948231/15618575/bfc04b98-241c-11e6-99e1-018c8168eaf5.jpg)
  wdyt?
  Liz

**Comment by lclay2** [comment]
P.S. I guess the blue doesn't bother me. ;) I used "Color Oracle" to see if the colors are distinguishable for color blindness and them see to be.

**Comment by andresgalante** [comment]
I must agree with @lclay2 that the blue doesn't bother me either.

**Comment by sjcox-rh** [comment]
Agree with @lclay2 and @andresgalante.  The blue never really bothered me.  As long as we avoid having the whole error message as a link, blue links within errors messages should be fine.  I don't want to go down the rabbit hole that we change the design for this specific use case, and then that triggers special cases for other designs, and so forth...

**Comment by andresgalante** [comment]
@rhamilto if its ok with I'll close the issue and keep the blue links on error messages.

**Comment by rhamilto** [comment]
cc: @jwforres, @spadgett, @benjaminapetersen, @sg00dwin

**Comment by benjaminapetersen** [comment]
Would like to see the darker red suggestion as well if anyone has that handy, then can prob make a call.  The blue isn't bad, though it seems like a lot of color in one block of text... but I'm sure it meets the recommended 3:1 contrast ratio recommended for links & accessibility.

**Comment by LHinson** [comment]
Late to the game here due to vacation but I also agree with @andresgalante @lclay2 and @sjcox-rh that the blue does not bother me.

**Comment by cardosogabriel** [comment]
Super late, but I also agree that the blue is not an issue for me.
