### ISSUE TITLE
table.table-bordered.table-hover tables lose bottom-border on hover

### ISSUE THREAD

**Issue by rhamilto** [patternfly/patternfly-3#296]
Before:

![screen shot 2016-05-26 at 1 56 03 pm](https://cloud.githubusercontent.com/assets/895728/15584711/be6f9be6-2349-11e6-8276-28e93f72fb53.PNG)

See http://rawgit.com/patternfly/patternfly/v3.3.5/tests/tables.html

After:

![screen shot 2016-05-26 at 1 56 14 pm](https://cloud.githubusercontent.com/assets/895728/15584725/cefc9d56-2349-11e6-91e5-df927dbf7b94.PNG)

See http://rawgit.com/patternfly/patternfly/v3.4.0/tests/tables.html

https://github.com/patternfly/patternfly/commit/8f10bfa8870670aeed2f31b95a1aef0e53301f02#diff-a7693b847cd07d7aa4c819d11e5becc1L192 is the offending change.  

Attention:  @cardosogabriel, @andresgalante.

I found this bug when updating OpenShift to v3.4.0.  @jwforres, @spadgett:  is this a blocker for updating?  We use table.table-bordered.table-hover on browse/\* pages in OpenShift.

**Comment by andresgalante** [comment]
@rhamilto thanks, I'll send a PR today

**Comment by jwforres** [comment]
@rhamilto i'd wait for the fix, we've got plenty of time.  i don't think we urgently need anything we'd be picking up from the new version, @spadgett?

**Comment by spadgett** [comment]
> i'd wait for the fix, we've got plenty of time

+1
