### ISSUE TITLE
fonts are too small

### ISSUE THREAD

**Issue by abenari** [patternfly/patternfly-3#3]
I think body font-size=11px is horribly small.
In github, g+ and gmail default theme, it's 13px. In bootstrap-3 default is 14px.
11px is just too small.

**Comment by kybaker** [comment]
We made this decision based on the fact that the content in our apps is usually vast and this allowed us to accommodate more content in general. 11-13px is the standard range so we stuck closer to the smaller side for the body text. We are currently user testing the initial widget/patterns and will make adjustments based on the results.

**Comment by ohadlevy** [comment]
11px on foreman looks pretty bad :) +1 to enlarge it.

**Comment by stianst** [comment]
+1 to larger fonts, it's tiny

**Comment by rhamilto** [comment]
With the release of https://github.com/patternfly/patternfly/releases/tag/v0.2.1, the base font size is now 12px instead of 11px.
