### ISSUE TITLE
Pagination issue on datatable

### ISSUE THREAD

**Issue by droig** [patternfly/patternfly-3#30]
Hi

I think the datatable plugin bundled with patternfly JS has some issues when you configure datatable with "server processing" feature: It wont show appropriate pagination length, buttons and numbers.

Thanks for this awesome work!

**Comment by rhamilto** [comment]
Hi, @droig.

Have you consulted the datatables web site?  http://datatables.net/faqs/index#Server-side-processing  My guess is that this is a configuration issue.

Thanks,
Robb.

**Comment by droig** [comment]
Robb you are right! Sorry... it was my mistake.

**Comment by rhamilto** [comment]
No worries, @droig.  I'm glad you figured it out.  :)
