### ISSUE TITLE
Where is the documentation?

### ISSUE THREAD

**Issue by EmilMoe** [patternfly/patternfly-3#300]
It's good with all your examples, but I can't see documentation anywhere.

**Comment by andresgalante** [comment]
Hi @EmilMoe you can find documentation on https://www.patternfly.org/

We are working on a new website with better docs, it will be out soon.

If you need help implementing PatterFly or any of the patterns, please join the #patternfly channel on irc.freenode.net or [join](https://www.redhat.com/mailman/listinfo/patternfly) and send an email to the PatternFly mailing list patternfly@redhat.com

**Comment by EmilMoe** [comment]
Sorry but I can't find any code reference on your website

**Comment by dtaylor113** [comment]
Hi,
On our website the code examples are in expandable "Reference Markup" section: 

![image](https://cloud.githubusercontent.com/assets/12733153/15744615/eb9c04e6-289a-11e6-889c-c7fbddc54199.png)

**Comment by EmilMoe** [comment]
Thanks, I didn't see that link. However I'm trying to implement your sidebar, but the example is very messed with unnecessary code that makes it hard to know what part of it that is important.

**Comment by andresgalante** [comment]
@EmilMoe which sidebar?
This one on the right: https://rawgit.com/patternfly/patternfly/master/tests/dashboard.html

or the vertical menu? https://rawgit.com/patternfly/patternfly/master/tests/vertical-navigation.html

Until we have better docs, you will probably end up better looking into the test pages: https://rawgit.com/patternfly/patternfly/master/tests/

**Comment by rodwin** [comment]
@andresgalante 
Previous link are now 404. I am also looking for code that I've missed since my sidebar is not working. Looking at this page http://www.patternfly.org/pattern-library/navigation/vertical-navigation/vertical-navigation-without-icons.html, the sidebar menus as well as the toggle menu are not working.
