### ISSUE TITLE
The "Mark All Read" link in the notifications drawer should be fixed at the bottom of the open drawer

### ISSUE THREAD

**Issue by serenamarie125** [patternfly/patternfly-3#306]
"Mark All Read" should be associated with each of the notifications drawers.  

In the current implementation [1], Mark All Read is fixed under the last drawer title.  This is misleading as it only works on the items which are in the open drawer.

The initial intent of this design was to have the Mark All Read link fixed at the bottom of the open drawer.  The design pattern documentation isn't explicit on this, so I think it was difficult to interpret.

@andresgalante @LHinson 

<img width="326" alt="screen shot 2016-06-03 at 4 59 57 pm" src="https://cloud.githubusercontent.com/assets/12504403/15792661/a8a41cd8-29ac-11e6-928c-868012f4aa75.png">

[1] https://rawgit.com/patternfly/patternfly/master/tests/notifications-drawer.html

**Comment by andresgalante** [comment]
@serenamarie125 you are right, the visual story is not clear about the "mark as read" action: https://patternfly.atlassian.net/browse/PTNFLY-1269

The action would look good if we place it inside each accordion since it's too large, @Rohoover can you please review this and provide new mockups?

**Comment by jeff-phillips-18** [comment]
@serenamarie125 @andresgalante @Rohoover  I have an initial pass as the fix. Please take a look at http://rawgit.com/jeff-phillips-18/patternfly/fixes/tests/notifications-drawer.html

**Comment by andresgalante** [comment]
Thanks @jeff-phillips-18 😄!
Since it's the same height as the item in the drawer and has the same gradient background it looks huge, and doesn't represent an action.

**Comment by Rohoover** [comment]
@jeff-phillips-18 

I think the row height and/or color needs to be different. It looks almost like an independent row vs. one being house within the accordion. I will have a mockup for you this AM.

**Comment by jeff-phillips-18** [comment]
Yeah, I was just trying to get the placement and scrolling/sizing correct.

**Comment by andresgalante** [comment]
@jeff-phillips-18 I know, awesome job, the styling part is the easy part.

**Comment by Rohoover** [comment]
Here's the comp. I think removing the grey and keeping it to the same bg color as the rest of the items, and reducing the height should work. Even though the loading more is on the same white background, both only appear together for short periods of time.
![patternfly_toastnotification_tray_markread](https://cloud.githubusercontent.com/assets/18266453/15823219/c439ec8a-2bc7-11e6-8965-5e696a1e33bb.jpg)
