### ISSUE TITLE
Vertical Navigation Page in Beta Site

### ISSUE THREAD

**Issue by Rohoover** [patternfly/patternfly-3#309]
2 bugs for the price of one.

Vertical Navigation Page loads examples from test site. Test site header bar displayed in the example is not correct (screen shot attached). Icons is small, logo/text not in correct position.

Because the example is live, if you click on the patternfly icon, the website reloads on the page (screenshot attached). This could be confusing.

![screen shot 2016-06-07 at 1 15 16 pm](https://cloud.githubusercontent.com/assets/18266453/15867721/7fff0bfe-2cb2-11e6-838e-b0fc36614e94.png)
![screen shot 2016-06-07 at 1 16 24 pm](https://cloud.githubusercontent.com/assets/18266453/15867722/80009b86-2cb2-11e6-83c4-49720ca9bb7b.png)

**Comment by dlabrecq** [comment]
Moved this issue to patternfly-org.

See https://github.com/patternfly/patternfly-org/issues/172
