### ISSUE TITLE
Incorrect border-color for readonly inputs under certain conditions

### ISSUE THREAD

**Issue by rhamilto** [patternfly/patternfly-3#313]
PatternFly [specifies a lighter border color for inputs that are readonly](https://github.com/patternfly/patternfly/blob/master/less/forms.less#L17).  As implemented, this causes problems when readonly inputs are combined with [input-group-addons](http://getbootstrap.com/components/#input-groups-basic) as the border color of the addons do not reflect this change.

<img width="168" alt="screen shot 2016-06-13 at 2 44 09 pm" src="https://cloud.githubusercontent.com/assets/895728/16019718/69062e44-3178-11e6-9c8e-05d2369a80ac.PNG">

Additionally, readonly inputs with input-group-addons _and_ [validation states](http://getbootstrap.com/css/#forms-control-validation) do not reflect the color of the validation state.

![screen shot 2016-06-13 at 2 58 51 pm](https://cloud.githubusercontent.com/assets/895728/16019757/be90badc-3178-11e6-82a9-9ab247dc3bac.PNG)

I suggest the removal of the lighter border color for inputs that are readonly to resolve this issue as Bootstrap (from which PatternFly is inheriting these form styles) does not specify a different border color for disabled inputs.  Otherwise, PatternFly will need to create and maintain the fixes for the aforementioned cases.

The visual difference is minor (see below).

With existing, lighter border color:
![screen shot 2016-06-13 at 3 11 31 pm](https://cloud.githubusercontent.com/assets/895728/16019861/49ce5dca-3179-11e6-83c6-60be4456b4c2.PNG)

Proposed fix:
![screen shot 2016-06-13 at 3 11 16 pm](https://cloud.githubusercontent.com/assets/895728/16019866/53f9e760-3179-11e6-9444-2c56fd8a69d9.PNG)

Pull request with proposed change to follow.

cc:  @benjaminapetersen

**Comment by andresgalante** [comment]
@rhamilto Thanks a lot for taking the time to explain the issue in so much detail.
I agree with your solution and the PR looks ok. @sjcox-rh If you are ok with the change I'll merge it.

Thanks again Robb 😄
