### ISSUE TITLE
There's no documented examples of list view item expansion

### ISSUE THREAD

**Issue by dmsimard** [patternfly/patternfly-3#317]
Hi,

I was looking at how I could accomplish the list view item expansion as shown in this image at https://www.patternfly.org/pattern-library/content-views/list-view/#/api:

![No alt text](https://www.patternfly.org/assets/img/list-view-simple-expansion2.png)

However, there's no code snippet in https://www.patternfly.org/pattern-library/content-views/list-view/#/_code.

Would love to see how we can do that.

Thanks !

**Comment by LHinson** [comment]
@dmsimard right now, only the design is available. We still need to code it. You can track the story here: https://patternfly.atlassian.net/browse/PTNFLY-452 or let us know if you are interested in helping us out by contributing the code :)

**Comment by andresgalante** [comment]
List view expansion is done: https://rawgit.com/patternfly/patternfly/master-dist/dist/tests/list-view-simple-expansion.html
