### ISSUE TITLE
Overlapping toast notifications

### ISSUE THREAD

**Issue by skateman** [patternfly/patternfly-3#323]
Hi guys,

I'm implementing toast notifications into ManageIQ and there is an issue with the overlapping toast notifications.
![screenshot from 2016-06-23 10-40-29](https://cloud.githubusercontent.com/assets/649130/16296997/04ed5018-392f-11e6-93d9-bcf42e9eb29e.png)
If you receive notification messages with similar length, only the one will be visible and it will cover all the others. I think they should appear under each other, ideally with some padding.

**Comment by dtaylor113** [comment]
Hi,
Would inline-notification fit this usecase?
https://www.patternfly.org/pattern-library/communication/inline-notifications/#/api

**Comment by andresgalante** [comment]
@skateman thanks, we just need to remove one of them. I'll do it on my next PR

**Comment by andresgalante** [comment]
@skateman you should not use more than one toast on a page. It's on the specs.
If you need to put more than one, then use the [notification drawer](https://rawgit.com/patternfly/patternfly/master/tests/notifications-drawer.html) click on the bell icon the top right.

**Comment by andresgalante** [comment]
btw, the test page is wrong, I'll remove one of the notifications next time I send a PR

**Comment by skateman** [comment]
@dtaylor113 nope, asynchronous notifications should not be inline. @andresgalante I can't really prevent notifications to happen at the same time. Notifications Drawer is a cool thing for reviewing notifications happened in the past, but it would be nice to inform the user about the notifications in real time.

My concept was to display a toast notification in real time and send it to the drawer too. The toast would disappear in 3-5 seconds, but I wanted to give to the user the chance to mark it as read in that time interval by clicking on the `X` in the toast. Because the notifications are asynchronous, there is a chance that more than one will arrive in the 3-5 sec. time interval and it can cause the issue described above.

**Comment by andresgalante** [comment]
Hi @skateman You are right, and your use case is valid. If you line them up and show them one after the other you would lose the real time feedback a notification should provide.

Maybe we should change toast notification to support more than one in the page. This was a discussion back when we designed it. 

It was decided to [show only one and to recommend to leave them 8 seconds](https://www.patternfly.org/pattern-library/communication/toast-notifications/#/api). 

@LHinson: Can we provide any test or document to back that decision?

**Comment by skateman** [comment]
cc @dclarizio

**Comment by skateman** [comment]
@andresgalante I'm also not sure about positioning the toast notifications to the same place as the notification drawer. It's weird and also possible that a toast will cover the drawer button.

**Comment by jeff-phillips-18** [comment]
We've added this to our usability test application and will be gathering feedback on this at summit.

@beanh66 @serenamarie125

**Comment by andresgalante** [comment]
@jeff-phillips-18 awesome!! thanks a lot

**Comment by LHinson** [comment]
nice +1 @jeff-phillips-18 @serenamarie125 @beanh66 Look forward to seeing the results. We can adjust as needed.

**Comment by hpehl** [comment]
Any updates on this one?

**Comment by andresgalante** [comment]
Hi @hpehl yes, this was address on the latest release:
https://rawgit.com/patternfly/patternfly/master-dist/dist/tests/toast.html

Heads up: You'll need to add a container around the notifications. Check the changes here  #420
