### ISSUE TITLE
List View list-group-item-heading overlap

### ISSUE THREAD

**Issue by jtomasek** [patternfly/patternfly-3#324]
When List View is used in a container which does not span the full screen width (e.g. a sidebar), it's media query related styling is not applied, so it does not behave as expected sometimes.

The specific case of this is that list-group-item-heading does not apply ellipsis title shortening.

![screenshot from 2016-06-27 12-28-05](https://cloud.githubusercontent.com/assets/1121740/16376823/b4fe5c0a-3c62-11e6-8c38-e293ab7401fd.png)

Problem is well described here: https://css-tricks.com/flexbox-truncated-text/

Solution in case of List View is adding following styles:

```
.list-view-pf-main-info {
  min-width: 0;
}
.list-view-pf-body {
  min-width: 0;
}
```

**Comment by andresgalante** [comment]
@jtomasek Hi, sorry for the late reply, I've been away last week. 

Thanks for the PR with the fix 👍
