### ISSUE TITLE
 Vertical Navigation with primary Menuitems: Secondary Menu "flaps" when persisted

### ISSUE THREAD

**Issue by mwmahlberg** [patternfly/patternfly-3#326]
# Steps to reproduce
1. Open the [Vertical Navigation with Persistent Secondary example page with primary icons](https://www.patternfly.org/pattern-library/navigation/vertical-navigation/vertical-navigation.html)
2. _Click_ on `Storage`
3. Persist `Storage` menu by clicking on the left arrow in the secondary menu:  
   ![arrowleft](https://cloud.githubusercontent.com/assets/138420/16389964/bf297424-3ca0-11e6-9a1c-993f550bbe1d.png)
4. Move mouse from the persisted secondary navigation to content and back
   1. Mouse inside persisted secondary menu:
      ![screenshot 2016-06-27 19 56 44](https://cloud.githubusercontent.com/assets/138420/16390121/73175f82-3ca1-11e6-9365-64c9227cfad5.png)
   2. Mouse outside persisted secondary menu:
      ![screenshot 2016-06-27 19 56 44 2](https://cloud.githubusercontent.com/assets/138420/16390154/9d1c81d6-3ca1-11e6-8654-b8cf7b984474.png)
# Environment
- OS: OSX "El Capitan" Version 10.11.5 (15F34)
- Browser: Safari Version 9.1.1 (11601.6.17)
# Notes

This does not apply to a persisted secondary menu when the primary menu has no icons.

**Comment by serenamarie125** [comment]
Markus,

Thanks for sharing this.  This is one of the items which would be fixed
with the proposed solutions & fixes from Jeff Phillips which I mentioned in
an email last Friday.
- Serena

On Mon, Jun 27, 2016 at 11:00 AM, Markus Mahlberg notifications@github.com
wrote:

> Steps to reproduce
> 1. Open the Vertical Navigation with Persistent Secondary example page
>    with primary icons
>    https://www.patternfly.org/pattern-library/navigation/vertical-navigation/vertical-navigation.html
> 2. Click on Storage
> 3. Persist Storage menu by clicking on the left arrow:
>    [image: arrowleft]
>    https://cloud.githubusercontent.com/assets/138420/16389964/bf297424-3ca0-11e6-9a1c-993f550bbe1d.png
> 4. Move mouse from the persisted secondary navigation to content and
>    back
>    1. Mouse inside persisted secondary menu: [image: screenshot
>       2016-06-27 19 56 44]
>       https://cloud.githubusercontent.com/assets/138420/16390121/73175f82-3ca1-11e6-9365-64c9227cfad5.png
>    2. Mouse outside persisted secondary menu: [image: screenshot
>       2016-06-27 19 56 44 2]
>       https://cloud.githubusercontent.com/assets/138420/16390154/9d1c81d6-3ca1-11e6-8654-b8cf7b984474.png
> 
> Notes
> 
> This does not apply to a persisted secondary menu when the primary menu
> has no icons.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> https://github.com/patternfly/patternfly/issues/326, or mute the thread
> https://github.com/notifications/unsubscribe/AL7NU_ZfQ8BweBo_UgWiGtppI_XzJYqnks5qQA_SgaJpZM4I_WWW
> .

## 
- Serena Chechile Doyle
  _UXD | Unified Management Experience_
  _Red Hat_
  _Cell_ 508-769-7715 | _IRC_ - serena | _Skype_ - serenamarie125 | _Twitter_ -
  @serenamarie125

**Comment by mwmahlberg** [comment]
Serena,

I have to admit that I am not on the mailing list – I am mainly a backend guy, and my inbox already scares me in the morning. ;)

Sorry in case I duplicated any work.
- Markus

**Comment by andresgalante** [comment]
this one is fixed, thanks @jeff-phillips-18
