### ISSUE TITLE
Toolbar - filter is not poping out dropdown

### ISSUE THREAD

**Issue by yackitotreeville** [patternfly/patternfly-3#327]
Here is the css I am using in my index.html page

`<link rel="stylesheet" href="bower_components/angular-loading-bar/build/loading-bar.css">
    <link rel="stylesheet" href="bower_components/patternfly/dist/css/patternfly.css">
   <link rel="stylesheet" href="bower_components/patternfly/dist/css/patternfly-additions.css" media="screen, print">
    <link rel="stylesheet" href="bower_components/patternfly/dist/css/styles-additions.css">
   <link rel="stylesheet" href="bower_components/patternfly/dist/css/styles.css">
    <link rel="stylesheet" href="bower_components/angular-patternfly/dist/styles/angular-patternfly.css">`
I am using patternfly 3.5.0

**Comment by andresgalante** [comment]
@yackitotreeville hi, are you having this issue on Patternfly or angular-patternfly?

**Comment by andresgalante** [comment]
I can't reproduce this issue.
