### ISSUE TITLE
Kebab hidden from view in notification drawer

### ISSUE THREAD

**Issue by dlabrecq** [patternfly/patternfly-3#329]
I'm looking at the notification drawer example and see a problem with the kebabs. When I click on a kebab for the last notification, in any section, the kebab is truncated/hidden from view. (Note that I've already scrolled to the bottom of the notification. After clicking the kebab, I'm forced to scroll, once again, to move the menu items into view.) For some notifications, the kebab menu items are barely visible. Seems this needs to be on its own layer or should be scrolled into view?

**Comment by andresgalante** [comment]
Yeah, we know about this one 😞 

@jeff-phillips-18 What where the reasons why we just left it that way?

**Comment by jeff-phillips-18** [comment]
We left it this way because we did not have a reasonable fix. Any suggestions would be welcomed.

**Comment by andresgalante** [comment]
I'll close this issue and follow up on #553
