### ISSUE TITLE
latest datatables reference(1.10), but outdated syntax(1.9) in patternfly

### ISSUE THREAD

**Issue by dabeng** [patternfly/patternfly-3#331]
It's weird to introduce datatables 1.10 into patternfly but use outdated 1.9 syntax

**Comment by dabeng** [comment]
Maybe this upgrade takes our two months but well worth it. Besides, datatables editor should be introduced in too.

**Comment by andresgalante** [comment]
@dabeng We are started an effort to improve tables overall.

@LHinson Can you point @dabeng to the jira issues when we have them?

**Comment by dabeng** [comment]
It's awesome. We have expected this upgrade so long. if needs any help, I could send PR for this upgrade, I'm a big fan of datatables too.

**Comment by andresgalante** [comment]
Data tables are updated. thanks @dabeng
