### ISSUE TITLE
I wanna fix the bug in datepicker of patternfly but where is its source code

### ISSUE THREAD

**Issue by dabeng** [patternfly/patternfly-3#333]
Hi @andresgalante .I wonder which place I can commit my pull request about datepicker.

**Comment by andresgalante** [comment]
I am a bit lost here, whats the issue you want to fix?

**Comment by dabeng** [comment]
![screenshot from 2016-07-07 08-05-24](https://cloud.githubusercontent.com/assets/5689075/16638456/0dc5a400-43ad-11e6-8848-514cc034cc3c.png)
![screenshot from 2016-07-07 08-06-25](https://cloud.githubusercontent.com/assets/5689075/16638460/12ec4402-43ad-11e6-91b5-621d5b7b82b3.png)

You could get the above two snapshots easily if you clicks calendar icon firstly and then clicks input box. I think it's a intolerable bug for users.

**Comment by dlabrecq** [comment]
This particular example is included via a template from patternfly. The source lives in tests-src/widgets/forms/bootstrap-datepicker.html.

I noticed that the input element is not closed in the template, but I also don't see this issue with the patternfly test pages (i.e., https://rawgit.com/patternfly/patternfly/master/tests/bootstrap-datepicker.html).

**Comment by dabeng** [comment]
![screenshot from 2016-07-07 09-44-23](https://cloud.githubusercontent.com/assets/5689075/16640080/cac773f0-43ba-11e6-97f6-4f6b90db93f0.png)

Dear @dlabrecq , could you find that the shadow becomes double dark.

**Comment by dabeng** [comment]
Redundant dropdown menu of datepicker, it does indeed exist.

**Comment by andresgalante** [comment]
@dabeng thanks for the clarification and the detail information. We do have a bug and a strange implementation on the website.
If this is a bug in our implementation, do you want to send a PR to fix it or want us to add it to our back log?

And if it is a bug in the component itself, maybe we can send a PR to the upstream project and update our dependency when they merge it. What do you think?

**Comment by dlabrecq** [comment]
Yes, I see the highlighting darkening as well.

**Comment by dabeng** [comment]
Hi @andresgalante , as a matter of course, I'm glad to send  PR for the bug I found.

**Comment by dabeng** [comment]
Hi @dlabrecq . Could you tell me how to find the folder " tests-src" and I want to know why I got the unrendered page as shown below  when I access test page directly on rawgit.com.

![screenshot from 2016-07-11 14-15-00](https://cloud.githubusercontent.com/assets/5689075/16721590/136acc4e-4706-11e6-9e6f-ab20682caabd.png)

**Comment by andresgalante** [comment]
We have moved the compiled Jekyll tests to dist/tests.

https://rawgit.com/patternfly/patternfly/master/dist/tests/

PR: https://github.com/patternfly/patternfly/pull/344

**Comment by fr0z3nfyr** [comment]
Well, I wanted to post this same issue after seeing the demo on website. Glad to see that it is now fixed and works well in tests. However, [the website](http://www.patternfly.org/pattern-library/forms-and-controls/datepicker) still seems to use old script. Could you please fix it?

**Comment by LHinson** [comment]
@fr0z3nfyr this is fixed on the site now too. see: http://www.patternfly.org/pattern-library/forms-and-controls/datepicker/#/code
