### ISSUE TITLE
It's unacceptable that popover widget  floats randomly after resizing the widnow

### ISSUE THREAD

**Issue by dabeng** [patternfly/patternfly-3#336]
![screenshot from 2016-07-07 08-42-37](https://cloud.githubusercontent.com/assets/5689075/16639187/db5d1646-43b2-11e6-96e9-00b6e041e872.png)
![screenshot from 2016-07-07 08-42-45](https://cloud.githubusercontent.com/assets/5689075/16639190/e4e6527c-43b2-11e6-82aa-4bbab0d75bd7.png)

It's unacceptable that popover widget  floats randomly after resizing the widnow.

**Comment by andresgalante** [comment]
Hi, again thanks for the huge help. 

This is a known issue on bootstrap3, popovers are not responsive. It's fixed on bootstrap 4. When bootstrap 4 has a solid release and we move to it we'll have this problem solved on patternfly.

Do you want to fix it and send a PR to bootstrap? it would be awesome.
