### ISSUE TITLE
Timepicker loses background and border on window resizing

### ISSUE THREAD

**Issue by dabeng** [patternfly/patternfly-3#337]
![screenshot from 2016-07-07 10-29-52](https://cloud.githubusercontent.com/assets/5689075/16640861/440c075c-43c1-11e6-999c-0043d936c24e.png)

**Comment by andresgalante** [comment]
@dabeng I can't reproduce it on the website or on the test page: https://rawgit.com/patternfly/patternfly/master/tests/time-picker.html

What browser are you using?

**Comment by dlabrecq** [comment]
I also cannot reproduce on Firefox, Chrome and Safari.

**Comment by dabeng** [comment]
![chrome](https://cloud.githubusercontent.com/assets/5689075/16675351/ddd564d6-4485-11e6-99ac-468cee3b3cfc.jpg)
![ie](https://cloud.githubusercontent.com/assets/5689075/16675350/dd566ce4-4485-11e6-8cc1-515430b46677.jpg)
![opra](https://cloud.githubusercontent.com/assets/5689075/16675349/dd55c8e8-4485-11e6-9017-f2d02c78a12c.jpg)

Hi @andresgalante @dlabrecq , the problem has nothing to do with specific browser. It's caused by window resizing shown as above.

**Comment by srambach** [comment]
I replicated the behavior in Win 8 Chrome on the Patternfly page. However, on the same browser, it doesn't happen in the Rawgit page. 
I can't replicate it in OSx or Win 10 at all.
![bs_win10_chrome_51 0](https://cloud.githubusercontent.com/assets/19825616/16686297/11f06abe-44df-11e6-827e-b4012e01d6e7.jpg)

**Comment by dabeng** [comment]
Hi guys, I really get the same issue on standalone local test page on Chrome 50, Opera 32 and Firefox 47 under Fedora 22.
![screenshot from 2016-07-11 11-56-26](https://cloud.githubusercontent.com/assets/5689075/16719604/1dd77e02-46f2-11e6-9953-1b46c5ee584a.png)
![screenshot from 2016-07-11 11-56-46](https://cloud.githubusercontent.com/assets/5689075/16719605/1dd99a20-46f2-11e6-99c2-c31126ced8d5.png)

**Comment by LHinson** [comment]
Looks like this is an issue with the pattern page vs an issue with the component. I've created a bug here to address when we can: https://patternfly.atlassian.net/browse/PTNFLY-2178

**Comment by michpetrov** [comment]
To reproduce this you have to get the bottom window border near the bottom of the timepicker, it also happens only when the window height is an odd number of pixels.

The timepicker is trying to reposition itself above the input, however some of the PatternFly styling prevents it from doing so. Either the CSS needs to be fixed or the widget has to be set to always stay under the input. I can send a PR if you tell me which one you prefer.

**Comment by andresgalante** [comment]
@michpetrov Thanks a lot Michael, I think we should fix the CSS so it doesn't prevent the timepicker to open ontop.

It'd be great if you can send a PR, thanks a lot!! 😄
