### ISSUE TITLE
the hover and active status of pagination is too obscure

### ISSUE THREAD

**Issue by dabeng** [patternfly/patternfly-3#340]
![screenshot from 2016-07-07 12-18-32](https://cloud.githubusercontent.com/assets/5689075/16645222/0fe46e84-43e8-11e6-81b5-2f4d86067d2e.png)

With all due respect, the hover and active status is too obscure, could we introduce some bright colors and got a distinct color contrast finally.

**Comment by andresgalante** [comment]
@dabeng  😄 You are been too polite. Thanks for reporting all of this and helping out, you are awesome!
Let me tag the visual designers on this issue: @sjcox-rh Can you please review this one?

**Comment by dabeng** [comment]
Cool! If this issue could be fixed in the future, our project users would not complain that the pagination buttons look like disabled.

**Comment by andresgalante** [comment]
@mcarrano if you think it's worth working on this please create a design story, if not just close this issue.

**Comment by mcarrano** [comment]
It looks like Pagination uses that same hover colors as everything else, so changing this would have far-reaching implications for the overall visual system. That said, I can see how the color change between normal and hover can be very subtle. If we are to make any changes, I think they should be done in the context of the new visual system that @kybaker is working on.  I think it's best to close for now, but thanks for raising this @dabeng .
