### ISSUE TITLE
Is the patternfly-bootstrap-combobox still alive?

### ISSUE THREAD

**Issue by dabeng** [patternfly/patternfly-3#346]
Hi @andresgalante . One week ago, I sent a [PR](https://github.com/patternfly/patternfly-bootstrap-combobox/pull/1) for patternfly-bootstrap-combobox, bu to now, I haven't received any response. Maybe I sent PR to the wrong place?

**Comment by bleathem** [comment]
Thanks for following-up @dabeng. I unfortunately didn't have my github watches setup for that repo.  I do now.

I've replied to your PR, we'll carry-on the conversation over there.  Closing this issue.
