### ISSUE TITLE
rfe: new chart type: control chart

### ISSUE THREAD

**Issue by TomasTomecek** [patternfly/patternfly-3#349]
Hello,

I've just started working on a new tool which should provide various reports in form of charts from trello. One of the requirements of the tool is to provide control chart:

![control chart](http://atlassian.wpengine.netdna-cdn.com/wp-content/uploads/jira_agile_control_chart_add_weekends.png)

This chart is composed of line chart, area chart and arbitrary placed points of various styles (size, color, etc.). Is it possible to do something like that with current version of patternfly?

**Comment by dabeng** [comment]
Hi @TomasTomecek , it's amazing sophisticated chart and I wonder if it can be used without Trello.

**Comment by TomasTomecek** [comment]
Yes, the chart can be used independently, it has no connection to trello nor agile project management.

**Comment by TomasTomecek** [comment]
I'm going to answer myself. Since patternfly uses c3, it's possible to paint such complex chart:
1. _dots_ -- ~~these can be line charts with lines hidden and points customized~~ scatter plot
2. _lines_ -- line charts
3. _area_ -- area chart with line hidden

Hence I'm closing.

EDIT: dots are actually scatter plot

**Comment by bleathem** [comment]
Great, thanks for sharing your solution Tomas.
