### ISSUE TITLE
H2 and H3 styles in Typography Test page is inconsistent with PatternFly Site's Typography page

### ISSUE THREAD

**Issue by jsniezek** [patternfly/patternfly-3#351]
For comparison: see here: https://www.patternfly.org/styles/typography/#_ and here: https://rawgit.com/patternfly/patternfly/master/dist/tests/typography-2.html

**Comment by andresgalante** [comment]
Thanks Joe 😄 

@kybaker Can you please check which one of them is right?

**Comment by andresgalante** [comment]
The rawgit url changed to https://rawgit.com/patternfly/patternfly/master-dist/dist/tests/typography-2.html

![screen shot 2017-02-03 at 4 10 01 pm](https://cloud.githubusercontent.com/assets/1832037/22604633/423ce994-ea2b-11e6-9f2c-5d497b7940ef.png)

This is an issue on the PatternFly Site's.

**Comment by LHinson** [comment]
This page needs a total revamp. I've create a story for this here: https://patternfly.atlassian.net/browse/PTNFLY-2185

Closing this issue here and we will track over in Jira.
