### ISSUE TITLE
Jekyll Version

### ISSUE THREAD

**Issue by jeff-phillips-18** [patternfly/patternfly-3#355]
Currently the README file states that jekyll 2.5.3 should be used when building due to Jekyll issues #4433 and #4442. These issues have been resolved in Jekyll 3.1.4 and I believe we should remove the 2.5.3 requirement and update to the latest jekyll version. Not doing so causes some issues since many folks miss this requirement causing a large number of diffs to the dist/tests files. While the differences are non-functional, it still causes many files to be changed and potentially committed.

**Comment by andresgalante** [comment]
@jeff-phillips-18 thanks a lot!!

**Comment by dlabrecq** [comment]
Curious is anyone has done any testing with the latest Jekyll?

**Comment by jeff-phillips-18** [comment]
I ran through as many different page types in our test pages as I could think of and found no issues.

**Comment by andresgalante** [comment]
@dlabrecq I've built patternfly with the latest version and have been building my blog with that version without issues.

**Comment by dlabrecq** [comment]
Good to know. I'm a bit leery upgrading until after this coming release.

**Comment by jeff-phillips-18** [comment]
@dlabrecq I believe @andresgalante meant "without issues" as he was very happy with the change. I don't seen any reason to hold back since the compiled results are already committed.

**Comment by dlabrecq** [comment]
I will feel more comfortable after going through each build, during the upcoming release and confirming there are no issues between patternfly and pf.org. I'm sure it will be fine.
