### ISSUE TITLE
patternfly components - what is that for?

### ISSUE THREAD

**Issue by Martinsos** [patternfly/patternfly-3#36]
When I install patternfly from bower, there is a components folder inside. What is that for? All of those are stated under devDependencies in bower.json, but it seems to me like all this is needed for patternfly to work. If that is correct, why are they not normal dependencies?

**Comment by gregsheremeta** [comment]
You can use the bower dependencies if you want, but they are also checked into the repository for environments that cannot use bower (i.e. rpmbuild in an enterprise application).

**Comment by Martinsos** [comment]
Thank you, but I am interested what are the real dependencies for patternfly. Is bootstrap dependency for patternfly? Are bootstrap plugins like bootstrap-select dependencies for patternfly?

**Comment by rhamilto** [comment]
Thank you for the feedback, @Martinsos. I've updated the README with a section regarding the dependencies. https://github.com/patternfly/patternfly/blob/master/README.md#dependencies
