### ISSUE TITLE
Latin2 characters are missing from OpenSans font

### ISSUE THREAD

**Issue by vkrizan** [patternfly/patternfly-3#377]
Latin2 characters, such as "č", "ť", "ž", are not included in current OpenSans web font formats.

![opensans-latin2-missing](https://cloud.githubusercontent.com/assets/7695766/17214685/7157b07e-54da-11e6-850c-6b003712fbb6.png)

These characters should be included in "latin-extended" variant, according to [Google Fonts](https://www.google.com/fonts#QuickUsePlace:quickUse/Family:Open+Sans).

**Comment by andresgalante** [comment]
I agree, we should extend open sans. Would you be able to send a PR introducing the new fonts variables?

For the new version of Patternfly, PF5 we are using [Overpass](http://overpassfont.org/) and it renders accents.

**Comment by vkrizan** [comment]
> Would you be able to send a PR introducing the new fonts variables?

I am not sure if I would be able to do that correctly (picking only selected character sets). Maybe copying it from Google Fonts?

For our project, we (I) have converted the whole source TTF to woff2 (only). Resulting format contained every character. Because of that a browser is trimming the character table with a warning "downloadable font: kern: Too large subtable, table discarded".

**Comment by andresgalante** [comment]
Yes, we download it from google fonts, here are the instructions:
https://developers.google.com/fonts/faq
Do you want to try to send the PR with the update?

Let's try top address the trimming issue after we introduce the font so we can test it.

what do you think?

**Comment by vkrizan** [comment]
I can try to (this week maybe).

 Do you know what are the requirements to extend the character set besides:
* Latin Extended (this issue)
* Cyrillic (Issue #231)

**Comment by andresgalante** [comment]
Awesome! thanks a lot @vkrizan
@LHinson are there any other missing characters we want to add?

**Comment by LHinson** [comment]
no, none that I know of! Thanks @vkrizan for the help with this!
