### ISSUE TITLE
Search component example not working well for server side search

### ISSUE THREAD

**Issue by lubomir** [patternfly/patternfly-3#38]
If you have a workflow where you display a page with search form to the user, who fills in their query and submits the form back to the server that returns a new page, there are several issues with the [example code](https://www.patternfly.org/widgets/#search).

1) Clicking the search button does not submit the form. The user has to submit via keyboard. Specifying the button type as `submit` fixes this.
2) If the form is displayed again on the result page, the input field contains submitted text, but the clear button is hidden. This can be fixed by using

``` javascript
$(".search-pf .clear").toggle(!$(this).prev('input').val());
```

instead of the `hide` call which (according to [docs](http://api.jquery.com/hide/)) does not support boolean argument.

**Comment by rhamilto** [comment]
@lubomir Thanks for the feedback and the suggestions!  I will work on incorporating your fixes.  I created this widget without testing it against a live example and overlooked the problems you note.  I'll make an effort to avoid that in the future.
