### ISSUE TITLE
Monospace <pre>, <code> etc... nearly unreadable on linux

### ISSUE THREAD

**Issue by stefwalter** [patternfly/patternfly-3#39]
The patternfly font choice results in an almost unreadable &lt;pre&gt; and &lt;code&gt; tags on linux.

**Comment by stefwalter** [comment]
Two examples on this screenshot:

![screenshot from 2014-10-23 15 54 47](https://cloud.githubusercontent.com/assets/795070/4754216/9985be98-5abc-11e4-9fdd-587451a37b9a.png)

**Comment by stefwalter** [comment]
Code at fault: 

```
components/bootstrap/less/variables.less:@font-family-monospace:   Menlo, Monaco, Consolas, "Courier New", monospace;
```

Putting 'monospace' first, or just removing this altogether makes nice readable monospace text on Linux.

**Comment by stefwalter** [comment]
Cockpit project work around linked above.

**Comment by rhamilto** [comment]
Thanks, @stefwalter!  What flavor linux are you running?  It doesn't look nearly that bad in Fedora 20 for me.

**Comment by stefwalter** [comment]
Pretty fresh install of Fedora 21 with Firefox.

**Comment by rhamilto** [comment]
@stefwalter If you remove "Courier New" from the font family declaration, does that resolve the issue (rather than moving monospace to the beginning)?  If so, I'll commit that change to PatternFly.

**Comment by stefwalter** [comment]
Yes, it does indeed. If I remove "Courier New" it still looks ok, even with monospace at the end.

**Comment by rhamilto** [comment]
Thanks, @stefwalter!  I've committed the fix.
