### ISSUE TITLE
Popup in List View broken on specific selection

### ISSUE THREAD

**Issue by morsik** [patternfly/patternfly-3#399]
![snapshot103](https://cloud.githubusercontent.com/assets/783794/17494916/1fe24ee4-5db7-11e6-813d-9c09bf56c636.png)

When I selected 2nd and 3rd entry, then pressed kebab menu on 1nd entry I got what you see on screenshot.
Happens always when entry below clicked kebabmenu is selected. Similar happens when I select 2nd and 4th and click kebab on 2nd.

Bug is there of course: https://www.patternfly.org/pattern-library/content-views/list-view/

**Comment by LHinson** [comment]
This is also being tracked here: https://patternfly.atlassian.net/browse/PTNFLY-1134

**Comment by junezhang** [comment]
@morsik, Please fetch the latest code, this bug has been fixed.
https://rawgit.com/patternfly/patternfly/master-dist/dist/tests/list-view.html
