### ISSUE TITLE
Integrating a bootstrap template to rails  4 application

### ISSUE THREAD

**Issue by rota90** [patternfly/patternfly-3#40]
Hi,
I am new to ruby on rails  and i want to add a bootstarp theme to my application i downloaded it from here http://startbootstrap.com/
I have this directories /css,  /font-awesome-4.1.0,  /fonts, /js and other HTML files 
Could you please tell me where to put each of these directories to get it work perfectally
Thanks in advance

**Comment by rhamilto** [comment]
Hi @rota90,

I apologize for the delayed response.  I just saw your request.

PatternFly isn't a Bootstrap theme per say, and we don't support the application of PatternFly in the way startbootstrap.com does its themes.  Sorry.

Cheers,
Robb.
