### ISSUE TITLE
Buttons: attribute disabled overrides btn-primary+btn-disabled

### ISSUE THREAD

**Issue by himdel** [patternfly/patternfly-3#405]
A button with `<button class="btn btn-primary btn-disabled">Foo</button>` looks greyish-blue, as it should. But adding the `disabled` attribute (=> `<button class="btn btn-primary btn-disabled" disabled>Foo</button>`) makes the color white, as if `btn-primary` was not there.

I think that's a bug, both should look greyish-blue :).

Applies to all of `<a href="" class="btn .."`, `<input type="button" class="btn .."` and `<button class="btn...`.., a to all the colouful `btn-*` classes..

**Comment by jeff-phillips-18** [comment]
Adding btn-disabled doesn't do anything as that class is not defined as far as I can tell. A disabled button is intentionally set to have background color #fafafa (adding !important).

If you application wants to override that then just add a .btn.disabled selector and set the background color as you wish (also using !imporant or !!important if you can't guarantee order).

@LHinson Can you confirm or deny the intentions for disabled primary buttons' background color?

**Comment by himdel** [comment]
Oh, terribly sorry, I really was convinced that `btn-disabled` was a bootstrap thing, not [manageiq thing](https://github.com/ManageIQ/manageiq/blob/master/app/assets/stylesheets/template.scss#L7-L12).

That said.. [bootstrap docs](http://getbootstrap.com/css/#buttons-disabled) show a button with `btn-primary` and attribute `disabled` (or class `disabled` on anchor elements) with that primary color, and only mention that it doesn't work on IE9. So.. unless it was explicitly your intention to remove that color, could still be a bug..

**Comment by jeff-phillips-18** [comment]
@himdel OK, I will follow up with @LHinson to determine if we intentionally change all disabled buttons to the same shade of white or if it is a bug. Looking back it has been this way since the dawn of time (in this case 2013) so if it is a bug, that's a hell of a catch 😉

**Comment by LHinson** [comment]
Thanks @jeff-phillips-18 @himdel I just synced with @kybaker, the visual design lead, and he has confirmed that is the intended design.

**Comment by kybaker** [comment]
@himdel @LHinson We opted to use the gray instead of the lighter color fill when we got the feedback that the lighter buttons still looked clickable without the context of another filled button. Also the color is meant to draw the eye to reinforce an intended workflow, when the button is disabled the same workflow no longer applies.

**Comment by himdel** [comment]
OK, thanks a lot, I suppose ManageIQ should probably follow then, will pass it on, or do a local override.. :)
