### ISSUE TITLE
Kebab menu in Toast Notifications is not vertically aligned

### ISSUE THREAD

**Issue by jeff-phillips-18** [patternfly/patternfly-3#406]
Looking at the toast notifications with the kebab menu, the menu kebab indicator is not vertically aligned with the text. Adding the kebab menu also increases the height of the toast notification (from 45px to 50px).

**Comment by LHinson** [comment]
I've asked Tao to look at this and filed a bug here: https://patternfly.atlassian.net/browse/PTNFLY-2184

**Comment by zhutaoredhat** [comment]
Before<img width="397" alt="2017-03-01 3 20 29" src="https://cloud.githubusercontent.com/assets/13375283/23449724/b7a360ac-fe92-11e6-846a-daeb2721e0bc.png">
After<img width="391" alt="2017-03-01 3 20 49" src="https://cloud.githubusercontent.com/assets/13375283/23449723/b79efc88-fe92-11e6-8e8d-69f0ed308f4d.png">

Need add: 
.toast-pf .dropdown-kebab-pf .btn-link{
padding:0 10px;
}

**Comment by LHinson** [comment]
Ok thanks @zhutaoredhat. I'll get a developer to look at this.

**Comment by LHinson** [comment]
@dabeng has send a PR to fix this. see: #609
