### ISSUE TITLE
Dropdown chopped if rightmost in .toolbar-pf-action-right

### ISSUE THREAD

**Issue by skateman** [patternfly/patternfly-3#427]
![screenshot from 2016-08-19 19-13-20](https://cloud.githubusercontent.com/assets/649130/17817905/250bd02e-6641-11e6-9c14-a4e76f103cf9.png)

Note: we probably won't have any dropdown at the rightmost position, but it's still a bug in PF.

**Comment by cardosogabriel** [comment]
@skateman , when dropdowns are on the edge of the screen, you probably want them to align to the right (not to the left). To do so, you just need to add the class "dropdown-menu-right", which would result: `<ul class="dropdown-menu dropdown-menu-right">`. 

Check out the result I got:

![Screenshot](https://snag.gy/cwYIob.jpg)
