### ISSUE TITLE
checkboxes and radio buttons not hidpi aware

### ISSUE THREAD

**Issue by andreasn** [patternfly/patternfly-3#44]
Tried patternfly on a HiDPI/Retina screen (3200x1800 on 13") and everything look good, except for the checkboxes and radio buttons, at least on Firefox.

Checkbox from Cockpit:

![screenshot from 2015-01-07 10 52 27](https://cloud.githubusercontent.com/assets/209895/5645432/88658866-966f-11e4-8b53-d860c38b18ff.png)

Radio button from https://www.patternfly.org/wp-content/uploads/patternfly/tests/form.html

![screenshot from 2015-01-07 13 15 33](https://cloud.githubusercontent.com/assets/209895/5645455/c829d042-966f-11e4-99c2-0678943d80d5.png)

**Comment by rhamilto** [comment]
@andreasn, your OS is Linux?  That same form looks fine in Firefox on OS X Yosemite on my MacBook Pro with Retina Display.  My guess is this is an issue with Firefox on your OS.

**Comment by stefwalter** [comment]
Firefox on RHEL/Fedora is one of our our main browser targets for Cockpit. I guess we have to come up with a work around?

**Comment by rhamilto** [comment]
@stefwalter I am unable to reproduce the bug, which makes it hard to troubleshoot.  If I run Firefox in RHEL 7 or Fedora 20 via Parallels with retina resolution enabled on my MacBook, I don't see the issue.  :/  Nothing in PatternFly is manipulating the size of checkboxes or radio buttons.  Does the issue also exist on Bootstrap's site (see http://getbootstrap.com/css/#forms-controls)?

**Comment by andreasn** [comment]
Yeah, this is Fedora 21 with Firefox 34.
I do indeed see the same issue on Bootstrap.

**Comment by andreasn** [comment]
Will test more and look around if this is a known Firefox or Linux bug.

**Comment by andreasn** [comment]
This issue also appears on http://www.w3schools.com/Html/tryit.asp?filename=tryhtml_checkbox so it seems like it's outside of Patternfly's control.
Closing.

**Comment by andreasn** [comment]
Also noted that checkboxes works in other browsers, such as Epiphany on Fedora 21, so will file this as a Firefox bug.

**Comment by rhamilto** [comment]
Thanks, @andreasn!
