### ISSUE TITLE
Blue/black top-border on active items in tertiary navigation

### ISSUE THREAD

**Issue by skateman** [patternfly/patternfly-3#442]
![screenshot from 2016-08-29 13-51-28](https://cloud.githubusercontent.com/assets/649130/18050595/da5f1296-6def-11e6-8b5f-2ca9f9f6b61a.png)

**Comment by jeff-phillips-18** [comment]
This was fixed by https://github.com/patternfly/patternfly/pull/434
Coming soon to theaters near you.
