### ISSUE TITLE
List View Selected Item Hover State is the same as Unselected Item Hover State

### ISSUE THREAD

**Issue by jsniezek** [patternfly/patternfly-3#447]
This behavior caught my eye in the PatternFly List view example. It was surprising to me that when selecting an element, the hover style was the same as it is when an item is deselected. 

I find this a bit disorienting: if you go hover on a selected element, that prominent cue of background color change (back to gray) is so much more apparent than the little checkbox; it gives me a visceral impression that it somehow might have reverted to a deselected state on hover. 

What about a darker blue highlight for selected + hover, or at least something different from the deselected + hover state? See attached image for example.

![selected mouseover use same gray highlight as unselected mouseover](https://cloud.githubusercontent.com/assets/1707469/18140585/34ad6d7a-6f84-11e6-96d9-1a6c3f716d05.png)

**Comment by dabeng** [comment]
Sorry jsniezek. I have different opinion. I think this behavior is exactly best practice rather than something weird. No need to modify it.

**Comment by LHinson** [comment]
@jsniezek we are actually working on a test plan for card view and list view. Here's the story https://patternfly.atlassian.net/browse/PTNFLY-1743 I think we could include this in the test to see how we might need to address from a design perspective.

**Comment by andresgalante** [comment]
I'll close this issue since https://patternfly.atlassian.net/browse/PTNFLY-1743 is done
