### ISSUE TITLE
PatternFly Icons Cheatsheet page has two broken links

### ISSUE THREAD

**Issue by jsniezek** [patternfly/patternfly-3#448]
The links to download the PatternFlyIcons-webfont.ttf and FontAwesome.otf are broken. Please update them to point to the current URLs for these resources.

**Comment by dabeng** [comment]
Could you provide the url of the page?

**Comment by jsniezek** [comment]
For PF icons, looks to now be: https://github.com/patternfly/patternfly/raw/master/src/fonts/PatternFlyIcons-webfont.ttf

Not sure about FA icons link.

**Comment by andresgalante** [comment]
@jsniezek sorry Joe for the delay to reply to this issue. Where is the download link?
