### ISSUE TITLE
Notification drawer tab heading wrapping problem when collapsed

### ISSUE THREAD

**Issue by srambach** [patternfly/patternfly-3#452]
In the notification drawer, when a Notification Tab is collapsed, the caret wraps onto its own line. When expanded, it is beside the title.
https://www.patternfly.org/pattern-library/communication/notification-drawer/#/_code
I see this in Chrome, Firefox, and Safari.

**Comment by srambach** [comment]
![screen shot 2016-09-01 at 11 41 39 am](https://cloud.githubusercontent.com/assets/19825616/18173819/168d3c3e-7039-11e6-8f22-58ee28451cc1.png)

**Comment by dabeng** [comment]
Hi @srambach . This UI bug is caused by the following css code snippets in patternfly-additions.css of patternfly 3.10.0.

``` css
.collapsed {
  width: 75px;
}
```

For the moment, this settings has been removed in current master branch.  After the new version is published, this issue will disappear automatically. :blush:

**Comment by dabeng** [comment]
The duplicate issue([Notification Drawer: Collapsed panel titles wrap to next line](https://github.com/patternfly/patternfly/issues/493)) has been closed. @srambach it seems safe to close your issue.
