### ISSUE TITLE
input boxes with error changes to non-error on hover

### ISSUE THREAD

**Issue by andreasn** [patternfly/patternfly-3#46]
On http://getbootstrap.com/css/#forms-control-validation the input with error is all red, also on hover.
However, with Patternfly, the input changes color on hover. https://www.patternfly.org/widgets/#forms

Should it have a rule about the hover state for the has-error class specifically, so it doesn't get overrun by the regular input boxes hover?

**Comment by rhamilto** [comment]
Thanks, @andreasn.  I've fixed the issue.
