### ISSUE TITLE
inner scrollbar can impact outer scrollbar in notification drawer

### ISSUE THREAD

**Issue by dabeng** [patternfly/patternfly-3#460]
I have a confusion. On horizontal navigation page or vertical navigation page, if we got a global scrollbar, and we move the cursor on over the notification drawer as shown in below snapshots, then we continuously scroll to top edge or scroll to bottom edge, the outer scrollbar will show a response, is this expected behavior?
![screenshot from 2016-09-08 18-01-08](https://cloud.githubusercontent.com/assets/5689075/18345946/702386c8-7583-11e6-96bf-acd69300f15d.png)
![screenshot from 2016-09-08 18-01-15](https://cloud.githubusercontent.com/assets/5689075/18345949/7382650a-7583-11e6-85c8-467725cdf476.png)

**Comment by dabeng** [comment]
Does anybody want to pursue the details with me?

**Comment by andresgalante** [comment]
Hi @dabeng Inner scrolling will cause a treadmill effect, thanks for reporting it.
