### ISSUE TITLE
Cannot programmatically expand patternfly-bootstrap-treeview nodes

### ISSUE THREAD

**Issue by dtaylor113** [patternfly/patternfly-3#464]
Hi,
I added the following code below to .../patternfly/tests/pages/bootstrap-treeview-2.html in an attempt to programmatically expand all the root nodes:

```
     ...
     ...
     '"text": "Parent 5"' +
            '}' +
          ']';

          //Default
          $('#treeview1').treeview({
            collapseIcon: collapseIcon,
            data: defaultData,
            expandIcon: expandIcon,
            nodeIcon: nodeIcon,
            showBorder: false
          });

          // NEW CODE
          var i;
          // get the inital root nodes
          var rootNode = $('#treeview1').treeview('getExpanded');

          // Collapse all
          $('#treeview1').treeview('collapseAll');

          // Expand the root nodes
          for (i = 0; i < rootNode.length; i++) {
            $('#treeview1').treeview('expandNode', [rootNode[i].nodeId]);
          }
          // END NEW CODE

          //Collapsed
          $('#treeview2').treeview({
          ...
          ...
```

I believe the following line is failing:

`$('#treeview1').treeview('expandNode', [rootNode[i].nodeId]);`

I get the following error:

`Uncaught TypeError: Cannot read property 'expanded' of undefined bootstrap-treeview.min.js:1`

This was working in MiQ Self Service GUI, prior to patternfly 3.10.0.  At the moment this is blocking further development!

**Comment by dtaylor113** [comment]
@serenamarie125  Seems like the upgrade to PF 3.10.0 caused the issue we are seeing in the Automated Entry Points treeview :-(

**Comment by dtaylor113** [comment]
Hi, just FYI, in a new directory I issued:

`bower install bootstrap-treeview`

and created a new index.html file with their basic demo code, added my expand code, and it worked without any errors, so it seems like something in patternfly-bootstrap-treeview...unfortunately :cry:

**Comment by dtaylor113** [comment]
@skateman , wonder if this has anything to do with the recent work you did around expanding nodes?
https://github.com/patternfly/patternfly-bootstrap-treeview/pull/7
Thanks,
- Dave

**Comment by skateman** [comment]
No, this is a known issue and this will fix it https://github.com/patternfly/patternfly-bootstrap-treeview/pull/6

**Comment by dtaylor113** [comment]
Great!  Thanks for the reply :-)

**Comment by andresgalante** [comment]
patternfly/patternfly-bootstrap-treeview#6 was merge, I'll close this issue
