### ISSUE TITLE
RFE Being able to search in dropdowns and change selection

### ISSUE THREAD

**Issue by chargio** [patternfly/patternfly-3#469]
When using a dropdown, you can only hit the first letter.

For instance: with a list like this for cost center:
- 100501 - one
- 101502 - two
- 102523 - three
- 103112 -four
- ....
- 13912 - thirty nine
- (2000 in total)

You would have to hit 1 - 39 times to get to the element you are looking for.

It would be great to have a dropdown that allows you to press 112 and choose directly that, or find looking for the description and not the first letter.

So it is a mix of a search and a selection, or you can just find the one you know by heart.

**Comment by serenamarie125** [comment]
@sergio-ocon Did you try bootstrap-combobox? http://www.patternfly.org/pattern-library/widgets/#bootstrap-combobox 

I think that this will work, it filters the list and only shows items with a substring match

**Comment by chargio** [comment]
Yes, that would work.

I wonder if we can use it instead of select in ManageIQ. I have a customer that was asking why we have changed the behaviour of selects... before you could use more keys to choose, now they have 3000 tags and the interface of the dialogue uses a dropdown.... in the past the same dropdown allowed to search for more than one key

**Comment by serenamarie125** [comment]
@sergio-ocon In MIQ for 4.2 they are converting to select with search.  I think happy martin, david halaasz and eric winchell have additional knowledge on that

**Comment by chargio** [comment]
Great!
