### ISSUE TITLE
List View Row Variation #1 (Including donut chart) is broken

### ISSUE THREAD

**Issue by lizsurette** [patternfly/patternfly-3#470]
I was looking to use donut charts within a list view and didn't see an example. After looking closer into the Row Variation #1 it looks like the code is attempting to offer that, but the donut charts aren't showing up. Unfortunately, I can't identify the exact issue :(

https://www.patternfly.org/pattern-library/content-views/list-view/#/_code

**Comment by andresgalante** [comment]
Thanks @lizsurette This has been solved
