### ISSUE TITLE
A click on link buttons or dropdown menu items will result in jumping to the top of page

### ISSUE THREAD

**Issue by dabeng** [patternfly/patternfly-3#475]
You can find this kind of bug on It's an unacceptable for users.

![screenshot from 2016-09-18 11-24-13](https://cloud.githubusercontent.com/assets/5689075/18612687/1521f354-7d26-11e6-848b-027a971d1ba6.png)
![screenshot from 2016-09-18 11-24-29](https://cloud.githubusercontent.com/assets/5689075/18612689/167d0b08-7d26-11e6-9ca5-e2a02a22545c.png)

**Comment by andresgalante** [comment]
It's correct to have a reference `#` for the href on example pages.
