### ISSUE TITLE
There is a typo on the progressbar of card

### ISSUE THREAD

**Issue by dabeng** [patternfly/patternfly-3#476]
![screenshot from 2016-09-18 11-36-01](https://cloud.githubusercontent.com/assets/5689075/18612755/02709664-7d28-11e6-82e3-c0009d7ac9e0.png)

**Comment by andresgalante** [comment]
Is this bug from c3 charts or ours?

**Comment by LHinson** [comment]
This bug is seen here: https://rawgit.com/patternfly/patternfly/master-dist/dist/tests/card-view-card-variations.html
