### ISSUE TITLE
Toast notification is unworthy of the name

### ISSUE THREAD

**Issue by dabeng** [patternfly/patternfly-3#478]
bootstrap alert **+** close button **!=** toast notification. Where is toast effect? How show/hide? What about position of notification? There are still many details we need to take into account. I believe [toastr](http://codeseven.github.io/toastr/demo.html) is a great inspiration.

**Comment by andresgalante** [comment]
Toast notifications have recommendations to be placed on the top right corner and to appear on the screen for 8 seconds:
http://www.patternfly.org/pattern-library/communication/toast-notifications/#/api

The implementation follow that:
https://rawgit.com/patternfly/patternfly/master-dist/dist/tests/toast.html
