### ISSUE TITLE
It's better to let the user resize only the height of <textarea>

### ISSUE THREAD

**Issue by dabeng** [patternfly/patternfly-3#479]
![screenshot from 2016-09-18 14-19-47](https://cloud.githubusercontent.com/assets/5689075/18613400/a214b2b0-7d3f-11e6-9063-dd896fa184f8.png)

**Comment by andresgalante** [comment]
@dabeng you are absolutely right. `resize: vertical` should do it:
https://developer.mozilla.org/en/docs/Web/CSS/resize

Do you want to send a PR with it?
