### ISSUE TITLE
two much blank space. Isn't it?

### ISSUE THREAD

**Issue by dabeng** [patternfly/patternfly-3#480]
![screenshot from 2016-09-18 14-42-53](https://cloud.githubusercontent.com/assets/5689075/18613532/a7bb48fc-7d42-11e6-9731-486279bb59f5.png)

**Comment by andresgalante** [comment]
Hi @dabeng Do you want to send a PR to fix it? maybe it's an issue upstream on d3 and we can send a PR to them directly, what do you think?

**Comment by andresgalante** [comment]
I'd say lets keep things as they are for the are chart
