### ISSUE TITLE
How could I copy popup data items on all charts?

### ISSUE THREAD

**Issue by dabeng** [patternfly/patternfly-3#481]
I have a primary demand for all charts. I wanna copy popup data items( for example "320" shown on the following picture ). Looking forward a simple way.

![screenshot from 2016-09-18 15-18-06](https://cloud.githubusercontent.com/assets/5689075/18613774/d7c9a21a-7d46-11e6-94ea-1ffd5e4ca51e.png)

**Comment by andresgalante** [comment]
Is this an issue of patternfly or C3. If it is on C3, can we close this issue, open one upstream and try to send them a PR?

**Comment by andresgalante** [comment]
I don't think this is something we can work on. The chart is a generated svg. We can eventually send a PR upstream to fix it.
