### ISSUE TITLE
Initial arrow direction is not correct

### ISSUE THREAD

**Issue by dabeng** [patternfly/patternfly-3#482]
![screenshot from 2016-09-18 15-59-16](https://cloud.githubusercontent.com/assets/5689075/18614099/b2d72e30-7d4d-11e6-9c2f-66c94331fc95.png)
![screenshot from 2016-09-18 15-59-21](https://cloud.githubusercontent.com/assets/5689075/18614100/b7894c56-7d4d-11e6-85b4-1726067fd704.png)

**Comment by andresgalante** [comment]
Bootstrap select will change the direction of the open menu from a dropdown to a dropup depending on the position of the page. So the icon is correct since it doesnt know when it will be clicked.
