### ISSUE TITLE
Why not introduce bootstrap carousel into "Wizard" pattern?

### ISSUE THREAD

**Issue by dabeng** [patternfly/patternfly-3#483]
- Compose multiple standalone wizard pages into one page;
- Enable back/next buttons;
- Animate the status line;
- It's better to unify the size of multiple modal windows.

All above is just my personal improvement advice. Does anybody has the similar ideas?

**Comment by LHinson** [comment]
I think the latest updates to the wizard seen here: http://www.patternfly.org/pattern-library/communication/wizard/#/_code addresses your concerns so I'm going to close this one. Thanks @dabeng!
