### ISSUE TITLE
Field level help is too high

### ISSUE THREAD

**Issue by dabeng** [patternfly/patternfly-3#485]
![2016-09-18_20-34-50](https://cloud.githubusercontent.com/assets/5689075/18615714/fe29e25a-7ddf-11e6-8264-c194b33d1aef.jpg)

**Comment by andresgalante** [comment]
Hi @dabeng this only happens on one viewport, it's a bug.

Do you want to send a PR to fix it?

**Comment by andresgalante** [comment]
Is this an issue on the website or on patternfly?
