### ISSUE TITLE
has-warning and btn-warning doesn't match

### ISSUE THREAD

**Issue by andreasn** [patternfly/patternfly-3#49]
On bootstrap.org label-warning uses #F0AD4E and  has-warning input uses the color #8A6D3B
http://getbootstrap.com/components/#labels
http://getbootstrap.com/css/#forms-control-validation

Patternfly use the stronger, more orange #EC7A08 for label-warning, but still use #8A6D3B for the has-warning input.
https://www.patternfly.org/widgets/#labels
https://www.patternfly.org/widgets/#forms

**Comment by andreasn** [comment]
What about using something like #c56e17 for has-warning?

**Comment by kybaker** [comment]
We should use the warning color in the PF palette to be consistent. Border:#ec7a08, Outer-glow:#f4aa00

I did a mockup for it: https://dl.dropboxusercontent.com/u/5892944/Warning-field.png

**Comment by rhamilto** [comment]
@kybaker, we also need to specify a label color.  I'm not sure the default warning color will provide enough contrast when used for text.  See https://www.patternfly.org/wp-content/uploads/patternfly/tests/forms.html for a live example.  Want to specify something?
![screen shot 2015-02-12 at 12 06 27 pm](https://cloud.githubusercontent.com/assets/895728/6172586/c783b3c2-b2af-11e4-9f84-18b1522d468d.PNG)

**Comment by rhamilto** [comment]
It occurred to me to just mock it up.  Thoughts?

![screen shot 2015-02-12 at 12 23 38 pm](https://cloud.githubusercontent.com/assets/895728/6172928/03e31f04-b2b2-11e4-8c08-c14f7b21da44.PNG)

**Comment by kybaker** [comment]
@rhamilto I think it is enough, just as much contrast as the green. Additionally we will not be displaying large paragraphs in this color so fatigue is not an issue.

**Comment by rhamilto** [comment]
Fixed.  https://github.com/patternfly/patternfly/commit/6d945e0a177e37d4d73e0960af00719c177385c2

**Comment by andreasn** [comment]
Thanks for the quick fix!
