### ISSUE TITLE
Needed to extend script references to get Dropdown to work

### ISSUE THREAD

**Issue by lizsurette** [patternfly/patternfly-3#490]
Any code snippets for Dropdown (And where ever the dropdown is used) doesn't have enough to allow dropdown to work. I needed to add separate references to jquery.min.js and bootstrap.min.js to get it to work in my prototype. Script references incase it helps:

```
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
```

**Comment by andresgalante** [comment]
@lizsurette Thanks! They don't but I don't think they should. I'd add a note on the docs that mentions that you'll need js to make it interactive like BS does:
http://getbootstrap.com/components/#dropdowns
