### ISSUE TITLE
really, really long words overflow the inline error notification

### ISSUE THREAD

**Issue by andreasn** [patternfly/patternfly-3#491]
We have an issue in the Image Registry where really long strings overflow the inline notification error.
The error itself warns against names that are 63+ characters long, but if the word is 100+ letters long, that word will overflow the notification itself.

![screenshot from 2016-09-20 12-57-50](https://cloud.githubusercontent.com/assets/209895/18667852/86109e36-7f32-11e6-9eaf-d34ef0cbbf1e.png)

Filed in Cockpit here:
https://github.com/cockpit-project/cockpit/issues/5068

**Comment by andreasn** [comment]
word-wrap: break-word; might be a good solution here.

**Comment by andresgalante** [comment]
@andreasn Thanks a lot for reporting this, would you like to send a PR with the `word-wrap` fix?

**Comment by andreasn** [comment]
Sure. I'll get one together.

**Comment by andresgalante** [comment]
Awesome, you are the best 😄  !

**Comment by andresgalante** [comment]
@andreasn did we ever merge a PR related to this issue?

**Comment by andreasn** [comment]
no, I very much forgot it.
Let me take care of that this week.

**Comment by andresgalante** [comment]
:) thanks you are awesome!
