### ISSUE TITLE
List View: Find widget gets cut off page if content view selection isn't present

### ISSUE THREAD

**Issue by lizsurette** [patternfly/patternfly-3#492]
If the content view type selection is removed, the find widget falls off of the page when clicked. Screenshot:
<img width="995" alt="find bug" src="https://cloud.githubusercontent.com/assets/208455/18675536/a6c31eb8-7f20-11e6-8f37-62bb9e8ab257.png">

**Comment by junezhang** [comment]
@lizsurette Thanks for reporting this issue. I fixed it in this PR #494 . when merged, I will inform you.

**Comment by lizsurette** [comment]
@junezhang thank you so much!

**Comment by junezhang** [comment]
@lizsurette, the PR has been merged, please check it again. Thanks.

**Comment by junezhang** [comment]
HI, Liz, The PR has been merged,  I'd like to close this issue, if anything is wrong, please reopen it. Thanks.

**Comment by lizsurette** [comment]
Thanks @junezhang !
