### ISSUE TITLE
Notification Drawer: Collapsed panel titles wrap to next line

### ISSUE THREAD

**Issue by lizsurette** [patternfly/patternfly-3#493]
Collapsed panel titles within the notification drawer wrap to next line after the arrow. I'm assuming these shouldn't wrap unless the text gets too long.

Screenshot:
<img width="1426" alt="notification drawer bug" src="https://cloud.githubusercontent.com/assets/208455/18676078/67a17c64-7f22-11e6-862e-5d4917ca156a.png">

**Comment by jeff-phillips-18** [comment]
This was fixed in 3.11 by #454

**Comment by lizsurette** [comment]
Upgraded to latest PF and can confirm it's working as expected now :)
