### ISSUE TITLE
Bootstrap Select

### ISSUE THREAD

**Issue by chsreedhar** [patternfly/patternfly-3#499]
I tried same as example given for  [Bootstrap Select](https://www.patternfly.org/pattern-library/widgets/#bootstrap-select) . It is formatting the `<select>` tag but on click, options are not opening. Same is working with bootstrap.js

**Comment by andresgalante** [comment]
Hi @chsreedhar 
I can't reproduce the issue. Bootstrap select is working on the website. Can you please double check?

**Comment by chsreedhar** [comment]
hi @andresgalante 

Code given at [Bootstrap Select](https://www.patternfly.org/pattern-library/widgets/#bootstrap-select) is not working, but live example is working. Same code is working with bootstrap.js insted of patternfly.js
