### ISSUE TITLE
Full page example

### ISSUE THREAD

**Issue by stianst** [patternfly/patternfly-3#5]
A full page/site example is needed. At the very least a cmplete page with navigation, some tables, etc.

**Comment by rhamilto** [comment]
Thank you for the feedback, stianst!  Some full-page examples are definitely on our to do list.  I'll update this thread once we've added them.

**Comment by rhamilto** [comment]
I've added the start of some full page examples to /tests.  I intend to further refine these as we continue to flesh things out, but wanted to go ahead and get a few examples posted.  I hope this helps.

**Comment by stianst** [comment]
That's nice. Thanks

In the future it would be great to see a sample/reference site with all widgets included.
