### ISSUE TITLE
Error in dropdown

### ISSUE THREAD

**Issue by andreasn** [patternfly/patternfly-3#50]
We have a form in Cockpit where if nothing is selected in the dropdown, gives you an error and a small note that you need to select something in this dropdown, similar to the text fields.
This could probably be of use to the rest of patternfly as well.

The css is:
.has-error > .bootstrap-select > button > span {
color: #A94442;
}

**Comment by rhamilto** [comment]
Thanks, @andreasn.  This is a great suggestion.  I'll add this to the PatternFly backlog.

**Comment by rhamilto** [comment]
So that we're consistent with the way validation states work on &lt;select&gt;s, I think we really want something like this.

![screen shot 2015-03-11 at 1 31 07 pm](https://cloud.githubusercontent.com/assets/895728/6602616/f3231646-c7f2-11e4-9a25-d23d95a8d5c1.PNG)

Yea/nay?

**Comment by kybaker** [comment]
This is consistent with the field states which is what we want. Yay

Kyle

----- Original Message -----

**Comment by mcarrano** [comment]
So we're saying that the border color of the dropdown would change just as if it were a text field when there is a validation error?  Yes, that makes sense to me.

Matt

----- Original Message -----

**Comment by andreasn** [comment]
Looks good.

**Comment by rhamilto** [comment]
Added validation states for Bootstrap-selects
https://github.com/patternfly/patternfly/commit/0f6db28656cd74d3835141ab75c836411b0d8b2d
