### ISSUE TITLE
DataTable - Inline actions lose border for ie9

### ISSUE THREAD

**Issue by dlabrecq** [patternfly/patternfly-3#506]
Per code review comments, the inline actions (i.e., button and kebab) are styled like so:
- Height must be 100% of table cell
- Width must be 100% of table cell
- Button and kebab must be centered vertically (e.g., when lines wrap on small screens)
- Button and kebab must show a gradient

The current implementation has the button and kebab separated by two table cells, which share a single table header. Instead of the button and kebab having the .btn-default style, that is placed on the td itself. Thus, giving the appearance that the controls fill the entire table cell, like so:

![screen shot 2016-10-11 at 4 56 36 pm](https://cloud.githubusercontent.com/assets/17481322/19288360/b207bad6-8fd3-11e6-95b7-11d2721654c4.png)

This works on all supported browsers, except ie9 where the gradient overlaps/hides the tds border. (Note that this is a known ie9 bug.) For example:

<img width="312" alt="screen shot 2016-10-11 at 4 35 15 pm" src="https://cloud.githubusercontent.com/assets/17481322/19287899/abf25b44-8fd1-11e6-8fc4-3172e5bf9006.png">

When I avoid setting the gradient's filter on ie9, the tds border will display properly. I've tried several variants of filter:none, ms-filter, etc. to override the filter. However, it seems that once a filter has been set (e.g., even filter:none causes the issue), it cannot be undone.

Note that I also tried applying z-index:-1 to the td tags, which displays border properly. Unfortunately, this also causes the kebab menu to be hidden from view.

Originally, the .btn-default style was omitted from the table's td tags. However, in order for the controls to be centered vertically on Firefox, the tds position must be set to relative while the button and kebab were positioned absolute. In this scenario, the tds must be set to a fixed width; 75px and 25px, respectively. Otherwise, column widths are always 50%.

Unfortunately, this isn't desirable because text could be truncated if more room is needed for the button label (e.g., for localization).

Another possible solution is to omit the gradient from the button and kebab. Then give the td a background color, so it appears that the button and kebab fill the entire table cell. This isn't ideal, but works across all browsers.

**Comment by bleathem** [comment]
Thanks for reporting this @dlabrecq.  I've created a jira bug to track this issue here:
https://patternfly.atlassian.net/browse/PTNFLY-1897

**Comment by dlabrecq** [comment]
Awesome! Hopefully a set of new eyes can help here?

**Comment by andresgalante** [comment]
I'll close it since https://patternfly.atlassian.net/browse/PTNFLY-1897 is Done.
