### ISSUE TITLE
support for modal-sm

### ISSUE THREAD

**Issue by andreasn** [patternfly/patternfly-3#51]
I have a dialog in Cockpit where the default dialog width of 600px is waaay to wide.
Bootstrap have a class called modal-sm that sets the width of the dialog to 300px, but this doesn't seem to work in Patternfly.
Would it be possible to add support for this?
http://getbootstrap.com/javascript/#modals-sizes

**Comment by rhamilto** [comment]
@andreasn, modal sizes definitely work in PatternFly.  Are the contents of your modal forcing its width?

**Comment by andreasn** [comment]
I found the code for it now, and it is indeed there, I was using an old version of patternfly.
Closing.
