### ISSUE TITLE
panel-primary breaks within panel-group

### ISSUE THREAD

**Issue by nireno** [patternfly/patternfly-3#511]
Panels headers with the panel-primary class do not display the proper background-color when wrapped in  a panel-group. I've setup [this jsfiddle example](https://jsfiddle.net/9eokgb52/).

The fiddle shows that the panel only displays the correct border color. The background color on the other hand looks like panel-default even when the panel has a class of panel-primary or panel-warning.

**Comment by NicolaIsotta** [comment]
+1

**Comment by andresgalante** [comment]
@nireno sorry for the delay on the reply. You are right, that's a bug.

Would you be able to send a PR to fix it?

**Comment by andresgalante** [comment]
Thanks a lot @nireno
