### ISSUE TITLE
Sidebar doesn't work properly with tertiary-nav

### ISSUE THREAD

**Issue by skateman** [patternfly/patternfly-3#512]
The `$(document).sidebar()` function isn't implemented for `navbar-pf-vertical` only `navbar-pf`:

![screenshot from 2016-10-17 10-55-26](https://cloud.githubusercontent.com/assets/649130/19431296/3c371a02-9458-11e6-9e87-b3b15fc28ffb.png)

**Comment by andresgalante** [comment]
@jeff-phillips-18 when you have time, can you please take a look at it?

**Comment by skateman** [comment]
@jeff-phillips-18 @andresgalante any news on this?

**Comment by andresgalante** [comment]
This one is fixed

**Comment by andresgalante** [comment]
In order to solve this issue we need to replicate the use case by building a prototype with a vertical nav and a sidebar, identify where the problem is and solve it.

**Comment by skateman** [comment]
@andresgalante this should help you: https://github.com/skateman/patternfly/commit/ced561e011eb6227b3fe5d64a4b628249eacdae0

Actually there are a plenty of issues, the page should look something like:
![screenshot from 2017-09-07 10-49-18](https://user-images.githubusercontent.com/649130/30154557-95a6bfea-93ba-11e7-93ba-5ccdff7f12b8.png)

But would be even better if the accordions below the expanded one would be snapped to the bottom of the page.

**Comment by dabeng** [comment]
Hi @skateman. It seems that pattenfly-functions-sidebar.js is particularly used in vertical navigation layout. IMO, sidebar is more suited to horizontal navigation layout.

@mcarrano @andresgalante  Any thoughts ?

**Comment by martinpovolny** [comment]
I'd like to express my appreciation that someone has picked up this issue since we have been having the problem for quite some time. Actually we reported it on Oct 17, 2016.

More to the point: I failed to find any PF docs on that. I belive it is taken from here: https://bootstrapious.com/p/bootstrap-sidebar. And I see the Sidebar is used in the same orientation as we do (vertical).

So, @dabeng, where does the idea that is should be used in horizontal layout come from?

The problem affects the UX on cca 70% pages of ManageIQ. Sadly we somehow fail to express how important it is for us. Actually we have several open BZ that relate to this issue. Should we link some of the BZs here? Or vice versa?

Thank you for your time!

**Comment by skateman** [comment]
Related MiQ issue: https://github.com/ManageIQ/manageiq-ui-classic/issues/1884
Also we got a BZ where on small screens the sidebar is not being displayed at all: https://bugzilla.redhat.com/show_bug.cgi?id=1389022

**Comment by jeff-phillips-18** [comment]
Taking a look now.

**Comment by skateman** [comment]
Any update on this?

**Comment by LHinson** [comment]
@terezanovotna I see that you are doing a UX review on the MIQ issue. I'd love to sync on this to determine a path forward.

**Comment by LHinson** [comment]
@skateman @martinpovolny I've created an issue against pf-core to create a test page to get this operating correctly. It's a high priority for @dabeng so we can finally get this ball moving in the right direction. 

I'm hoping a test page helps to resolve the issue identified here.

**Comment by LHinson** [comment]
Closing this issue since we have #1118

**Comment by martinpovolny** [comment]
@epwinchell, @skateman : can you verify that the issue is fixed for ManageIQ?

**Comment by martinpovolny** [comment]
At the first look I see there's no resizer in the test page, not sure how much of a problem that is @epwinchell .

**Comment by skateman** [comment]
Well, the demo is nice, but we struggled a lot of implementing it in our codebase. Eventually we gave it up :confused:
