### ISSUE TITLE
Menu glitch after refreshing a page with pinned navbar

### ISSUE THREAD

**Issue by skateman** [patternfly/patternfly-3#517]
Steps to reproduce:
1. Pin a menu item in the navbar
2. Refresh the page
3. Move your mouse quickly to an expandable 1st level navbar item other than the pinned
4. After the pinning is reset, the hovered 1st level navbar item is still visible

![screencast from 2016-10-19 11-48-42](https://cloud.githubusercontent.com/assets/649130/19515900/bae4c622-95f9-11e6-95e3-034d1dc15397.gif)

**Comment by andresgalante** [comment]
Thanks guys 😄

**Comment by skateman** [comment]
I'm still able to reproduce this issue with v3.13:
![screenshot from 2016-10-31 11-20-16](https://cloud.githubusercontent.com/assets/649130/19851025/19bed190-9f5c-11e6-95b5-70d3d659ebed.png)

**Comment by jeff-phillips-18** [comment]
@skateman Can you try to reproduce on http://rawgit.com/jeff-phillips-18/patternfly/tertiary-nav-dist/dist/tests/vertical-navigation-with-tertiary-pins.html ?

**Comment by skateman** [comment]
@jeff-phillips-18 :+1:
