### ISSUE TITLE
Release new version with Google Code Prettify included

### ISSUE THREAD

**Issue by lfryc** [patternfly/patternfly-3#52]
Could you please $SUBJ$? :rocket:

**Comment by rhamilto** [comment]
@lfryc I'm not sure when I'll have time to cut a new release, but GCP is in the master branch.  If you pull the latest, you should get the relevant bits.  How are you consuming PatternFly?  Git, Bower, or RPM?

**Comment by lfryc** [comment]
Bower - sure, I will grab master, just to let you know there is a desire to get the release cut in a foreseeable future :-)

**Comment by rhamilto** [comment]
https://github.com/patternfly/patternfly/releases/tag/v1.1.4

RPM and web site updates to follow.

**Comment by rhamilto** [comment]
RPM available at https://copr.fedoraproject.org/coprs/patternfly/patternfly1/build/83474/

**Comment by lfryc** [comment]
Thanks Robb!
