### ISSUE TITLE
List view compound expansion "x" icon is not clickable when viewport is < 992px wide

### ISSUE THREAD

**Issue by rhamilto** [patternfly/patternfly-3#526]
On https://rawgit.com/patternfly/patternfly/master-dist/dist/tests/list-view-compound-expansion.html with a row expanded and a viewport less than 992px wide, the "x" icon to close the expanded area is not clickable. 

<img width="957" alt="screen shot 2016-11-02 at 10 24 51 am" src="https://cloud.githubusercontent.com/assets/895728/19932456/99ed30c4-a0e6-11e6-8a1e-f7211040ebfd.PNG">

**Comment by LHinson** [comment]
I'm going to close this since it was addressed with #564 Thanks for filing this issue @rhamilto and providing the fix @michpetrov
