### ISSUE TITLE
Broken Webpack compatibility in 3.14.0

### ISSUE THREAD

**Issue by lorthirk** [patternfly/patternfly-3#535]
Hi all. I'm using Patternfly (and Angular-Patternfly, for what it's worth) with Webpack. Up until 3.13.0 everything worked fine, but today upgrading to 3.14.0 I discovered that the `patternfly` global variable isn't exported anymore. Specifically, these lines (patternfly-settings.js:497)

```
if (typeof define === 'function' && define.amd) {
  define("patternfly", function () {
    return patternfly;
  });
} else if ('undefined' !== typeof exports && 'undefined' !== typeof module) {
  module.exports = patternfly;
} else {
  window.patternfly = patternfly;
}
```
Gets translated by Webpack to:
```
if (true) {
  !(__WEBPACK_AMD_DEFINE_RESULT__ = function () {
    return patternfly;
  }.call(exports, __webpack_require__, exports, module), __WEBPACK_AMD_DEFINE_RESULT__ !== undefined && (module.exports = __WEBPACK_AMD_DEFINE_RESULT__));
} else if ('undefined' !== typeof exports && 'undefined' !== typeof module) {
  module.exports = patternfly;
} else {
  window.patternfly = patternfly;
}
```
So anyone who needs the patternfly global variable will fail (e.g.  patternfly-functions.js:223):
```
(function ($) {
  'use strict';
  if (patternfly !== undefined) {
    $.pfBreakpoints = patternfly.pfBreakpoints;  // Fails here
  }
}(jQuery));
```
On a side note I tried to fix this on the Webpack side using [expose-loader](https://github.com/webpack/expose-loader) but being a newbie with Webpack I can't get it to find the patternfly module 😒

**Comment by lorthirk** [comment]
This can be closed, right?

**Comment by dgutride** [comment]
Yes - closing :)
