### ISSUE TITLE
Need to move/remove treeview styles from patternfly-additions.css

### ISSUE THREAD

**Issue by dtaylor113** [patternfly/patternfly-3#540]
Hi,
I believe obsolete treeview styles in patternfly-additions.css is colliding with styles in patternfly-bootstrap-treeview.  If you look at this plnkr: https://plnkr.co/edit/e8pJdZRw3jQzlbR9ximt?p=preview
you'll see that tree node selection highlights and the cursor is a hand pointer.

If you then uncomment <link ..... patternfly-additions.css"> you'll notice that the hand point and node selection highlight/background goes away!

This is because in https://github.com/patternfly/patternfly/blob/master/src/less/bootstrap-treeview.less there is treeview styles, particularly:

```
.treeview {
  .list-group-item {
    ...
    &:hover {
      background: none !important;
    }
    &.node-selected {
      background: none !important;
      border-color: transparent !important;
      color: inherit !important;
    }

```
Which sets the background of a selected node to transparent and elsewhere sets the cursor to default instead of a hand pointer.  

I believe core patternfly should not know about patternfly-bootstrap-treeview, and any treeview styles in the core should be removed, or if correct, moved to the 'patternfly-bootstrap-treeview' repo. 

Thanks,
- Dave

**Comment by andresgalante** [comment]
@priley86 You've been working on treeview, can you please review this issue?

**Comment by andresgalante** [comment]
@priley86 @dtaylor113 any news on this one?

**Comment by andresgalante** [comment]
@dtaylor113 Although you are right and that CSS is not been used, I think it's risky to remove it since a product might be using an old version of treeview. I'd leave it there and and improve treeview on the next version of pf
