### ISSUE TITLE
[Feature Request] - Supporting columns in vertical navigation

### ISSUE THREAD

**Issue by thiagodp** [patternfly/patternfly-3#543]
When the vertical navigation menu expands, it could show more than one column.

Maybe something like this, but without the separation lines:

![image](https://cloud.githubusercontent.com/assets/2997844/20769594/d192bc3e-b729-11e6-8468-fe94061a8758.png)

**Comment by andresgalante** [comment]
Hey @thiagodp I think that's an intresting idea. At the moment we are not intresting in introducing that kind of menu, but we will consider it for later.

Thanks a lot

**Comment by thiagodp** [comment]
Ok. Thanks for considering it for later!

**Comment by thiagodp** [comment]
Hi @andresgalante,

maybe you could keep the issue opened, in order to not forget about it. Could you please do it? Thanks.

PS: [Here a code snippet](http://bootsnipp.com/snippets/featured/large-dropdown-menu) that could help to expedite things.

**Comment by thiagodp** [comment]
Thank you!

**Comment by matthewcarleton** [comment]
Hey @thiagodp we have [this](https://github.com/patternfly/patternfly-design/issues/553) issue open in design so I'm going to close this here. Thanks!

**Comment by thiagodp** [comment]
Hi @matthewcarleton, will this issue be developed there? Whether it will, okay to close it.

**Comment by matthewcarleton** [comment]
Hey @thiagodp the design repo is where it belongs, if it does get developed that's where it will start. If you have any other questions just let me know!

**Comment by thiagodp** [comment]
Okay @matthewcarleton, thx.

**Comment by LHinson** [comment]
Thanks @thiagodp. @matthewcarleton has provided the appropriate issue link to follow so I'm going to close this one.
