### ISSUE TITLE
PF.org: Broken link to "Patternfly Code Guide" in Getting Started -> Contribute

### ISSUE THREAD

**Issue by dtaylor113** [patternfly/patternfly-3#544]
Hi,
Looking here: https://www.patternfly.org/get-started/contribute/

The "Check out our PatternFly Code Guide. " link goes to http://codeguide.patternfly.org/, which results in a error "This site can’t be reached".

**Comment by LHinson** [comment]
This has been addressed so going to close. Thanks for filing @dtaylor113
