### ISSUE TITLE
Selected rows in List View HTML/CSS should be changing the row background color

### ISSUE THREAD

**Issue by serenamarie125** [patternfly/patternfly-3#545]
In the List View, when using multi-selection via checkboxes, "selected" rows should use row shading.  This is implemented in Angular, but not in the html/css.

Design is shown here:
![screen shot 2016-12-01 at 5 09 33 pm](https://cloud.githubusercontent.com/assets/12504403/20814757/0205c87e-b7e9-11e6-9019-69e88b551697.png)

CSS/HTML Example:
![screen shot 2016-12-01 at 5 09 45 pm](https://cloud.githubusercontent.com/assets/12504403/20814755/ff39373e-b7e8-11e6-8230-abe87e67a6e2.png)

**Comment by andresgalante** [comment]
Hi @serenamarie125 I can't reproduce the problem:
https://rawgit.com/patternfly/patternfly/master-dist/dist/tests/list-view.html

Can you send me a url please?
