### ISSUE TITLE
Table View selected & hover visualizations are missing a top border

### ISSUE THREAD

**Issue by serenamarie125** [patternfly/patternfly-3#546]
Although the code isn't on patternfly.org, looking at the test page for Table View https://rawgit.com/patternfly/patternfly/master-dist/dist/tests/table-view.html, the selected and hover visualizations are missing a top border.

Screenshot of the test page
![screen shot 2016-12-01 at 5 11 56 pm](https://cloud.githubusercontent.com/assets/12504403/20814905/a30fdc78-b7e9-11e6-8094-14a9d087c245.png)

Zoomed in a bit
![screen shot 2016-12-01 at 5 13 53 pm](https://cloud.githubusercontent.com/assets/12504403/20814902/9def331a-b7e9-11e6-898a-7b6085583140.png)

**Comment by andresgalante** [comment]
Hi @serenamarie125. Each row has bottom border, we can change the color of it when things are active of hover, but it would requiere some javascript magic to paint the top border since it belongs to the row on the top.

That repaint will have an impact on performance.

**Comment by serenamarie125** [comment]
understood @andresgalante, do we have an idea of what the impact is?  When i filed this, there was a lot of inconsistency with the "blue line", where is shown and not shown in different patterns, which is a worry IMO.

**Comment by andresgalante** [comment]
Yes, you are right, we should have consistency on hovers. There is a story to address that but I can't find it. @LHinson Can you help me find it?

**Comment by LHinson** [comment]
What do you mean you are getting lost in the PatternFly backlog @andresgalante ;) 

The story is here: https://patternfly.atlassian.net/browse/PTNFLY-1483 I can add it to the visual design request spreadsheet. We'll see if they have the bandwidth to pick it up next sprint.

**Comment by andresgalante** [comment]
Let's continue this discussion on the issue. I'll close it.
