### ISSUE TITLE
npm update doesn't promote c3 after 3.16 was released

### ISSUE THREAD

**Issue by lroitman** [patternfly/patternfly-3#550]
I am using patternfly-provided C3 library in my project, and up until now after I updated patternfly through npm update the C3 would be promoted and placed under my node_modules.

Now, when I do npm update the c3 remains under patternfly/node_modules

Is this something you are going to fix soon, or is it how it supposed to provide c3 from now on?

**Comment by lroitman** [comment]
To clarify, the QUICKSTART still suggests to include 3rd party libraries from the root node_modules, like:
```javascript
<!-- C3, D3 - Charting Libraries -->
<script src="node_modules/c3/c3.min.js"></script>
<script src="node_modules/d3/d3.min.js"></script>
```

but the actual location of c3 and d3 modules are under node_modules/patternfly/node_modules/c3 and node_modules/patternfly/node_modules/d3

**Comment by dtaylor113** [comment]
Hi @lroitman ,

I verified this.  I did:

```
mkdir npm-install-pf
cd npm-install-pf
npm install patternfly
```

patternfly@3.16.0 was installed:
```
- node_modules
  - patternfly
    - node_modules
      - c3
      - d3
      - bootstrap
      - datatables
      ...
```
'patternfly' is the only directory/package in the resulting 'node_modules' directory, and in it's 'node_modules' are all the dependent packages.

I then did:

```
mkdir npm-install-pf2
cd npm-install-pf2
npm install patternfly@3.15.0
```

patternfly@3.15.0 was installed:
```
- node_modules
  - patternfly
  - c3
  - d3
  - bootstrap
  - datatables
  ...
```
patternfly 3.15.0 does indeed install all dependent packages in the root of 'node_modules', as opposed to  patternfly 3.16.0 which installs all dependent packages at 'node_modules/patternfly/node_modules'.

Hi @dabeng , I'm not sure if this is a deliberate change, or a result of our recent changes to the patternfly build/release processes.

Thanks,
- Dave

**Comment by lroitman** [comment]
@dtaylor113 Dave, thanks for the clarification! This is exactly what is happening. I think at one point patternfly went for "flat" distribution, where it's dependent packages were installed under parent's node_modules. We changed the necessary paths when including dependent packages at that point, and as a result, after yesterday's update our app doesn't work as expected.

I just need to know if this change was deliberate or not before making further changes 

Thanks a lot for looking into the issue

**Comment by dlabrecq** [comment]
FYI, the npm install of patternfly 3.16.0 includes a shrinkwrap file; thus, npm 3 installs dependencies under the node_modules/patternfly/node_modules directory. Previous versions v3.0.0 - v3.9.0 also included a shrinkwrap file, so npm installs those dependencies under the node_modules/patternfly/node_modules directory as well. The npm install for versions v3.10.0 - v3.15.0 inadvertently omit the shrinkwrap file causing npm to install dependencies in the root node_modules directory.

If you prefer a flat dependency structure, you can define your own dependencies explicitly. That will flatten out the node_modules structure and place C3; for example, in the root node_modules directory.

That said, I believe the npm behavior is correct when a shrinkwrap file is present. I've updated the readme, quick start, and the release notes to reflect this.

See PR: https://github.com/patternfly/patternfly/pull/552

**Comment by lroitman** [comment]
Thanks @dlabrecq for looking at this. Any way is fine, just wanted to understand exactly what patternfly's intention regarding dependencies is.

Make sure QUICKSTART.md is updated as well (see my earlier post, it refers to flattened node_module structure)

**Comment by andresgalante** [comment]
@lroitman Quickstart.md is updated, thanks! and thanks @dlabrecq @dtaylor113
