### ISSUE TITLE
Kebab menu in notification drawer gets cut off

### ISSUE THREAD

**Issue by jgiardino** [patternfly/patternfly-3#553]
The kebab menu in the notification drawer gets cut off by the row with link "Mark All Read".
<img width="325" alt="screen shot 2016-12-12 at 10 06 23 am" src="https://cloud.githubusercontent.com/assets/21063328/21104014/dabb18e2-c052-11e6-8f8c-88aa657d94a3.png">

You can see this behavior in the examples on this page:
http://www.patternfly.org/pattern-library/communication/notification-drawer/#/api
Click the Notifications icon in either example. Then click the kebab in the last notification in a section. The menu gets cut off by the row with link "Mark All Read".

**Comment by andresgalante** [comment]
Thanks @jgiardino 

This is a known issue, the only solution I could think of is to measure the height of the space and open a pop-up if there is not enough space. But that would required a LOT of Js

Can you think of another option?

**Comment by srambach** [comment]
I think there is already some javascript in there that must be adding space at the bottom of the list dynamically, because I think it scrolls further if you try so that you can see the whole menu. I had a similar problem on a paged list where I knew it was going to break on every nth item, so the best I could do was pop up on the nth item instead of down.

**Comment by jeff-phillips-18** [comment]
I don't see that issue in Chrome or Safari, when the kebab menu is shown the notifications area grows and can be scrolled to see the entire menu.

**Comment by andresgalante** [comment]
@jeff-phillips-18 yeap, that's the issue, it is still readable but not great UX.

**Comment by jeff-phillips-18** [comment]
Agreed, I thought the remark was that you couldn't get to it and I saw no scrollbar. Now I realize the image is with the only show scrollbars when scrolling setting.

**Comment by jgiardino** [comment]
I think at the time I posted this issue, since I had the hide scrollbars setting enabled, I didn't realize that I could scroll down to see the contents. I'd have to play around with this to see if I have any suggestions for this, but probably won't have time until the end of the sprint. One immediate thought I have is if we have javascript that increases the height to accommodate the menu, then is it possible to also have it automatically scroll the contents so that the menu is visible?

**Comment by andresgalante** [comment]
Ok, What do you guys want  to do? Should we keep it as it is and find a solution on pf5 or fix it now?

**Comment by LHinson** [comment]
Let's address it in pf5 so closing this issue.
