### ISSUE TITLE
Links on the vertical nav mast head are blue

### ISSUE THREAD

**Issue by andresgalante** [patternfly/patternfly-3#554]
@srambach discovered today that if you add text beside the icons on the vertical nav mast head on the right they show blue instead of light grey:
<img width="370" alt="screen shot 2016-12-19 at 12 26 19 pm" src="https://cloud.githubusercontent.com/assets/1832037/21318041/5ff45a26-c5e6-11e6-98d4-809010c81c22.png">

Here is the mockup:
http://www.patternfly.org/pattern-library/navigation/vertical-navigation/

**Comment by zhutaoredhat** [comment]
Hi @andresgalante I tested this bug just now.
 The PatternFly code structure is`
<a>
<span class="pficon pficon-user"></span>
Here goes text
</a>` 
I think srambach's code is like this "`<span class="pficon pficon-user"></span> <a> Here goes text </a>`" , "`<a></a>`" around "here goes text"

**Comment by junezhang** [comment]
@zhutaoredhat, if using the PatternFly code structure <a> <span class="pficon pficon-user"></span> Here goes text </a>, The "Here goes text" still is blue, not light grey.
<img width="727" alt="screen shot 2017-02-04 at 12 38 16 pm" src="https://cloud.githubusercontent.com/assets/701009/22615767/dcfe6538-ead6-11e6-9b88-cd4a971cd084.png">

In PatternFly, there is the code for the light grey. 
`header .navbar.navbar-default .navbar-right>li>a {
    color: #eee;
    padding: 7px 20px;
}`
But the vertical nav mast head is not following header -> navebar navbar-defaut -> navbar-right 
you can check from this part to see if need to add new setting for the .navbar-right > li>a ?

**Comment by zhutaoredhat** [comment]
@junezhang  You are right!  I think need to add `.navbar-pf-vertical .navbar-nav > li > a{color:#d1d1d1;};  .navbar-pf-vertical .navbar-nav > li:hover a{color:#fff;};`

**Comment by LHinson** [comment]
@zhutaoredhat is this something you can send a PR for?

**Comment by zhutaoredhat** [comment]
Sorry Leslie,

  I don't how to fix this problem in .Less. Need developer's help.

Thanks,
Tao

----- Original Message -----

**Comment by LHinson** [comment]
OK no worries. Thanks @zhutaoredhat.

**Comment by LHinson** [comment]
Closing this one since PR #610 was sent. 

Thanks @dabeng!
