### ISSUE TITLE
Add an example of Stacked Bar Chart

### ISSUE THREAD

**Issue by mresti** [patternfly/patternfly-3#556]
Hi,

I've just started working on a project using Patternfly. One of the requirements of this project is to use Stacked Bar Chart:

![seleccion_092](https://cloud.githubusercontent.com/assets/1193771/21371092/90c55a04-c70f-11e6-9b95-e8075f1d351d.png)

This chart is a bar chart that I had developed using patternfly, but I didn't find in the documentation an example for stacked bar chart (https://www.patternfly.org/pattern-library/data-visualization/bar-chart/#_).

Can I send a PR with an example to use Stacked Bar Chart in projects? 

@sergio-ocon can you help me?

**Comment by chargio** [comment]
What are you missing?

I see an example code here:
https://www.patternfly.org/pattern-library/data-visualization/bar-chart/#_code

**Comment by LHinson** [comment]
@sergio-ocon, @mresti is right. We don't have the version with the stacked bars (a bar with multiple colors)

@mresti Yes! We love to get this added to PatternFly. Thanks for reaching out to us and offering to contribute! Are you interested in contributing the implementation? Would you be willing to help out with design documentation too and sending a PR to our design repo [1]? Happy to help you out in any way that you might need.

[1] https://github.com/patternfly/patternfly-design/tree/master/pattern-library/data-visualization/bar-chart/design

**Comment by mresti** [comment]
@sergio-ocon @LHinson Thanks!!!

@LHinson Yes, I am interested in contributing in this project with the implementation and design documentation. I will send a PR to design repo[1] and a PR to implement repo [2]. 

[1] https://github.com/patternfly/patternfly-design/tree/master/pattern-library/data-visualization/bar-chart/design
[2] https://github.com/patternfly/patternfly

**Comment by LHinson** [comment]
@mresti That's awesome @mresti Reach out to me anytime if you need anything. 

FYI - I just sent an invite to your gmail to our PatternFly slack channel. There is a lot of conversation happening there and would be a good place to reach out to us.

**Comment by LHinson** [comment]
Thanks for your contribution @mresti! Going to close this out now.
