### ISSUE TITLE
Item Heading for Stacked list view overflows

### ISSUE THREAD

**Issue by vkrizan** [patternfly/patternfly-3#559]
If the content of list view heading (`.list-view-pf-stacked .list-group-item-heading`) is longer, then it overflows from the list and pushed additional content to right (`.list-view-pf-additional-info`).

Could it flex (and add ellipsis)?

![screenshot from 2016-12-22 16-30-12](https://cloud.githubusercontent.com/assets/7695766/21430655/57397ef4-c864-11e6-807c-8c8d85e3faa9.png)

**Comment by andresgalante** [comment]
That's strange, it does ellipse:
<img width="748" alt="screen shot 2017-01-06 at 2 18 57 pm" src="https://cloud.githubusercontent.com/assets/1832037/21726333/2089e6c4-d41b-11e6-9a94-7648cbef8090.png">

Can you send me a rawgit or somewhere I can see the code?

**Comment by vkrizan** [comment]
```diff
--- a/tests/pages/_includes/widgets/list-view/list-view-variation-1.html
+++ b/tests/pages/_includes/widgets/list-view/list-view-variation-1.html
@@ -11,7 +11,7 @@
       <div class="list-view-pf-body">
         <div class="list-view-pf-description">
           <div class="list-group-item-heading">
-            Event One
+            Vvveeeeeeeeeerrrrrrrrrrrrrryyyyyyyyyyyyyy loooooooooooooooooooooooooooooooooong EVENT
             <small>Feb 23, 2015 12:32 am</small>
           </div>
           <div class="list-group-item-text">
```

I'm using Firefox 50.1.0. My git HEAD is at 3e66f9d.

**Comment by andresgalante** [comment]
@vkrizan you are right, ellipse doesn't work on firefox. thanks a lot for reporting it 😄
Do you want to fix it and send a PR?

**Comment by vkrizan** [comment]
> Do you want to fix it and send a PR?

Let me try to fix it... =)

**Comment by andresgalante** [comment]
Awesome! so this is a nasty bug. I've checked a bit and it looks like the width: auto is creating some strange spaces. If you remove it the ellipse appears but the width of the div keeps been huge.

good luck and ping me on slack if I can help

**Comment by vkrizan** [comment]
@andresgalante I've create a new PR. It contains only a fix. Should I add more content to test pages?

**Comment by vkrizan** [comment]
Added test page in d14dfb5
