### ISSUE TITLE
RFE: Improve docs to include complete example

### ISSUE THREAD

**Issue by this-tech** [patternfly/patternfly-3#561]
The readme refers to jekyll, but for someone who has never used patternfly, grunt, npm, etc its very confusing to figure out how to make even the most basic of site. 

A reference implementation of a static site using jekyll would be ideal, as the docs and patternfly already render using it.

**Comment by dtaylor113** [comment]
Hi, we only use jekyll to generate our patternfly test pages.   Please see our [Quickstart](https://github.com/patternfly/patternfly/blob/master/QUICKSTART.md) guide on how to integrate patternfly styles and javascript into an already existing site.  
Please see our [Demo App](https://github.com/patternfly/patternfly-demo-app) for a complete example of standalone website using patternfly.
HTH,
- Dave

**Comment by andresgalante** [comment]
Hi @donnydavis it would be great to do a jekyll implementation of patternfly as a basic template, thats on my list of "things I want to do and never find time to start".

Do you want to start it? maybe if it's just the basic settings then we can start building it from there. What do you think?

**Comment by this-tech** [comment]
Something like this 

http://project.fortnebula.com/#

**Comment by andresgalante** [comment]
That is really cool!!!! 👏  

The structure is a bit off and that's why it's not responsive. Do you have a repo? If I find time I can send you a PR.

**Comment by this-tech** [comment]
I surely do
https://github.com/donnydavis/fortnebula.com

This isn't my day job, so don't be too harsh. :)

**Comment by andresgalante** [comment]
@donnydavis I won't and great job! thanks a lot 😄 

@bleathem @LHinson when you have a min take a look at this demo app based on Jekyll

I'll close this issue for now.
