### ISSUE TITLE
need clarification regarding Wizard header height

### ISSUE THREAD

**Issue by gregsheremeta** [patternfly/patternfly-3#571]
On http://www.patternfly.org/pattern-library/communication/wizard/#/_overview

The Overview screenshot of the Wizard has a relatively tall header. It's at least as tall as the side tabs and footer, if not taller. However, when you click Demo, the coded demo has a much shorter header. It doesn't look quite right to me.

Is the screenshot wrong, or the coded demo? What should the header height be?

**Comment by LHinson** [comment]
Hey Greg!

To confirm, I wanted to make sure I understood what you meant by header -
just the gray band (vs the gray band + steps).

If that's correct, the gray header should match the PatternFly modal [1]
and the implementation does match that modal header height. So, in this
case, the implementation is the correct version. It's beneficial to have
the modal header heights to be consistent vs unique header heights per
component that leverages that modal.

That said, do you want to elaborate on why it doesn't look quite right?

[1] http://www.patternfly.org/pattern-library/widgets/#modal

Thanks,
Leslie

**Comment by gregsheremeta** [comment]
Hi Leslie,

Sorry for being unclear. Talking only about the wizard ... the screenshot on patternfly.org and the demo on patternfly.org are inconsistent.

Screenshot:

![selection_097](https://cloud.githubusercontent.com/assets/2248293/22309508/8a06270e-e319-11e6-99c4-13c1e53a7d89.png)

Demo:

![selection_098](https://cloud.githubusercontent.com/assets/2248293/22309512/8f6725ea-e319-11e6-9f8c-7f50505ed38a.png)

The red and green lines I added are copied and pasted. Notice that in the screenshot, the red heights are all the same. In the demo, the top header is shorter by 15ish px.

I think the header in the actual demo/code should be fixed so it's taller and matches the screenshot (which looks way better with the consistent height).

Hope that clarifies.

**Comment by kybaker** [comment]
@gregsheremeta @LHinson Leslie is correct here - the implementation is the correct one which matches the modal.

**Comment by gregsheremeta** [comment]
Ok, I just thought it looked inconsistent in the implementation. The header looks too short to me, shrug.

So are you going to update the screenshot so people aren't confused? I'd consider it a bug in the website.

**Comment by kybaker** [comment]
@gregsheremeta It is a bug, but we will hold off on redesigning it. We will update much of the website imagery and styles including this one when we convert to Overpass soon. This will include sizing and spacing changes.

**Comment by LHinson** [comment]
Thanks @gregsheremeta and @kybaker, I'm going to close this one for now since the imagery is going to get an a general overhaul at a later date. This will be addressed then.
