### ISSUE TITLE
Inconsistent vertical spacing between alerts

### ISSUE THREAD

**Issue by jawnsy** [patternfly/patternfly-3#573]
Alerts have

```css
margin-bottom: 20px;
padding: 11px;
```

However, this leads to inconsistent space between top and bottom (notice how the padding below the heading is smaller than the padding between alerts, or between the alert and the following `<p>` element):

![screenshot from 2017-01-24 11-07-41](https://cloud.githubusercontent.com/assets/52710/22267613/4c743056-e239-11e6-8707-41dc4b40390f.png)

In OpenShift origin, a [special style](https://github.com/openshift/origin-web-console/blob/f8380670ab9bee828a7dc01382b627b2618384ef/app/styles/_core.less#L897-L909) is applied:

```css
margin-bottom: 14px;
margin-top: 7px;
```

It evens things out a little bit, by balancing space between top and bottom:

![screenshot from 2017-01-24 13-34-45](https://cloud.githubusercontent.com/assets/52710/22267795/fcda0a4c-e239-11e6-8728-a8352fe5f7fb.png)

Please consider changing the styles to distribute space better between top/bottom (for example, by using `margin-top` = `margin-bottom` = `10px` instead of `20px` at the bottom.

This problem does not affect the PatternFly demo site because a [site-specific style](https://github.com/patternfly/patternfly.github.io/blob/master/assets/css/patternfly-site.css#L1309-L1313) adds padding between the heading and the first element:

![screenshot from 2017-01-24 13-38-26](https://cloud.githubusercontent.com/assets/52710/22267926/786fa496-e23a-11e6-9429-26b235cdfdf2.png)

**Comment by andresgalante** [comment]
Hey @jawnsy! I see what you mean, PatternFly margins on follows bootstraps, they have a `margin-bottom: 20px`.
If we add a margin top then might act strange when we use them on forms. Let me take a look at this in different scenarios and come back to you.

**Comment by andresgalante** [comment]
Hi @jawnsy I don't think we should change this. At least not on this version.

Adding a margin to the top of any element might break an implementation of patternfly.  But we will consider and test this as we implement alerts on PF5. I'll tag you on that PR.

Thanks a lot for the suggestion

**Comment by jawnsy** [comment]
Fair enough, I understand it might not be something we can change in a minor release due to the potential of breakage. Thanks for your analysis & consideration!
