### ISSUE TITLE
need clarification regarding datagrid row color

### ISSUE THREAD

**Issue by gregsheremeta** [patternfly/patternfly-3#577]
On patternfly.org, there is an inconsistency between the screenshots and demo code for the [Table View](http://www.patternfly.org/pattern-library/content-views/table-view/)

In the screenshot, a selected row is bright blue, whereas in the demo, it remains gray.

Screenshot:
![selection_105](https://cloud.githubusercontent.com/assets/2248293/22397572/69e4a48e-e542-11e6-8c54-df68424bfbc8.png)

Demo:
![selection_104](https://cloud.githubusercontent.com/assets/2248293/22397575/71b55e60-e542-11e6-9706-b13b48b73d35.png)

Which should it be?

**Comment by dtaylor113** [comment]
Hi @gregsheremeta,
Thanks for catching this!  I believe the bright blue selected row color is not being applied in the demo example.  I've created a bug in our backlog to address this:  [PTNFLY-2141](https://patternfly.atlassian.net/browse/PTNFLY-2141).
Thanks,
- Dave

**Comment by LHinson** [comment]
![bitmoji](https://render.bitstrips.com/v2/cpanel/10212734-130956820_16-s4-v1.png?transparent=1&palette=1&width=246)

Thanks @gregsheremeta for reporting this. It should be blue and thanks @dtaylor113 for filing a bug. I've moved this up in the backlog.

**Comment by dabeng** [comment]
I think it's just because current patternfly.org page is missing too much necessary js references as shown below:
![screenshot from 2017-02-07 13-19-20](https://cloud.githubusercontent.com/assets/5689075/22678938/c417a5d6-ecc3-11e6-9c62-244467d15183.png)

**Comment by LHinson** [comment]
Should be resolved with #197

**Comment by LHinson** [comment]
Just checked and this is resolved here: http://www.patternfly.org/pattern-library/content-views/table-view/#/api

Thanks @gregsheremeta and @dabeng! Closing this issue.
