### ISSUE TITLE
Javascript Libraries 

### ISSUE THREAD

**Issue by xtrasmal** [patternfly/patternfly-3#58]
Hi there,

is there a list of javascript libraries that will be included in the future? Things like the c3js library?
I ask this, because it could happen that some systems require documents need to be uploaded, or images even. Imagine a whitelabel enabled reseller SAAS dashboard for instance. 
In that case, what image uploading libraries would one use?

**Comment by rhamilto** [comment]
hi, @xtrasmal.  I don't have a specific answer to your question, but you can see the PatternFly reference implementation backlog at https://trello.com/b/Hz3Nmwk4/patternfly-reference-implementation.  The backlog is where we define what work is planned and includes the known details associated with each feature, enhancement, or bug fix.
