### ISSUE TITLE
Vertical nav widget API?

### ISSUE THREAD

**Issue by gashcrumb** [patternfly/patternfly-3#580]
Hey guys!  Using the vertical nav for our ipaas console, but for some pages we need to toggle the vertical nav depending on the view.  Is there an API for doing that?  Previously I've achieved the desired effect by adding `collapsed` and `collapsed-nav` tags to the relevant elements, but it'd be nicer if I could just toggle it via a javascript call.  Thanks!

**Comment by kahboom** [comment]
Preferably without using jQuery, as we are using Angular 2 and want to avoid having to manipulate the DOM from any logic/functionality.

EDIT: Nvm we are using more jQuery than I thought. I guess there is a lot more cleanup to be done than I originally thought.

**Comment by gashcrumb** [comment]
@kahboom Well, it's a jquery plugin, isn't it?  At least the code that sizes it to the window etc all appears to be, if that's the option I can live with it for now.

**Comment by kahboom** [comment]
We're not using any of the PF JavaScript, just the styling for now, so we're having to add in any functionality ourselves or in using ng-bootstrap. See [here](https://github.com/redhat-ipaas/ipaas-ui/issues/8). Is that what you mean, or am I totally lost?

**Comment by jeff-phillips-18** [comment]
there is an angular patternfly directive for vertical navigation but is for Angular 1. Version 4.x of angular patternfly (currently in alpha) can be upverted to Angular 2 since all the directives have been changed to components. If you are interested in that, then the vertical nav component could be enhanced with this feature but it does not exist at this time.

**Comment by gashcrumb** [comment]
Okay cool.  yeah, I think it'd be a handy feature to have for sure, we'll have to look into pulling in the alpha as well.  I may be able to work around the lack of an API for now, but then using 4.x might be a better use of my time :-)

**Comment by jeff-phillips-18** [comment]
@LHinson Can we add a story to the backlog to add the ability to hide/show the vertical nav bar in the angular patternfly component (at least in 4.x, might want to add to 3.x as well)?

**Comment by LHinson** [comment]
Thanks for bringing this up @gashcrumb Would you be willing to send a PR for this?

**Comment by gashcrumb** [comment]
@LHinson yeah, I could probably do that, give me a bit to grok the code :-)

**Comment by gashcrumb** [comment]
@LHinson actually I should ask, the jquery based one in this repo or the angular-patternfly implementation?  Or both?

**Comment by andresgalante** [comment]
@gashcrumb awesome! Thanks!

**Comment by LHinson** [comment]
@gashcrumb beggers can't be choosers haha. We would take both if you want to send a PR for both!

**Comment by gashcrumb** [comment]
With [this PR](https://github.com/patternfly/patternfly/pull/582) merged I'd consider this closed, one follow on question, when's the next release planned?  :-)

**Comment by bleathem** [comment]
Resolved with #582;
