### ISSUE TITLE
Bootstrap Switch does not work well with inline list

### ISSUE THREAD

**Issue by vkrizan** [patternfly/patternfly-3#581]
When I add a Bootstrap Switch into inline list with a text input, then the switch is shifted down. In FF it shifts about half of the size of the input height. In Chrome it shifts only a few pixels.

Changing `.list-inline > li` `display` to `inline-flex` seems to fix it. However I don't know if that would work on all browser and I am not sure if there is a deeper problem with Bootstrap Switch itself.

```
<ul class="list-inline">
  <li><input type="checkbox" checked></li>
  <li><input type="text" class="form-control"></li>
</ul>
```
Note that `input[type=checkbox]` is initialized as `bootstrapSwitch`

![screenshot from 2017-02-03 14-07-36](https://cloud.githubusercontent.com/assets/7695766/22592523/73624674-ea1a-11e6-871c-284d3f77ba26.png)

**Comment by andresgalante** [comment]
@vkrizan There is something wrong there and I am sure it's in the way switch is build. I'll look into it.

**Comment by dabeng** [comment]
Hi @vkrizan , you need vertical-align property setting. Please review the [Demo](https://codepen.io/dabeng/pen/vjKOxK) on codepen.io

**Comment by vkrizan** [comment]
Thank you @dabeng. That seem to work perfectly.
