### ISSUE TITLE
counting is confused after table-view filtering

### ISSUE THREAD

**Issue by dabeng** [patternfly/patternfly-3#588]
The following bold "15 results" is confused.

![screenshot from 2017-02-13 10-17-06](https://cloud.githubusercontent.com/assets/5689075/22869082/f6de17e6-f161-11e6-8cec-b78018071ed3.png)

**Comment by andresgalante** [comment]
This is probably a design issue. @LHinson and @kybaker can you please check it out?

**Comment by kybaker** [comment]
@andresgalante @dabeng - Yes, just an oversight. The image will need to be updated.

**Comment by kybaker** [comment]
@dabeng @andresgalante - Yes, the numbers are incorrect. The example should say 20 at the top.

**Comment by LHinson** [comment]
@dabeng where did you get this screenshot from?

**Comment by matthewcarleton** [comment]
This seems to be resolved, I've checked it in chrome and it looks good.
