### ISSUE TITLE
How can I have Google Material Design in patterfly?

### ISSUE THREAD

**Issue by AtRaoN** [patternfly/patternfly-3#589]
Do we have any document or standard methods for having Material design in Patterfly?

**Comment by andresgalante** [comment]
Hi @mndotmail Material design and PatternFly are 2 different design systems, you either follow one or the other. They don't compliment each other.

If there is any interaction you like on material that you'd like to see in Patternfly please contact the community on slack or the mailing list to discuss it: https://www.patternfly.org/community/#_
