### ISSUE TITLE
Extended form controls

### ISSUE THREAD

**Issue by xtrasmal** [patternfly/patternfly-3#59]
Hi there,

What libraries are going to be included for extended form controls, like
- range-sliders
- on/off toggle

and other stuff that would be nice in a app where you can scale infrastructure by hand.

**Comment by rhamilto** [comment]
hi, @xtrasmal.  As I mentioned in https://github.com/patternfly/patternfly/issues/58, you can see the backlog at https://trello.com/b/Hz3Nmwk4/patternfly-reference-implementation.  While we have no defined plans for range-sliders or on/off toggles, you're welcome to suggest such things by emailing the community at patternfly@redhat.com.
