### ISSUE TITLE
pficons not loading.

### ISSUE THREAD

**Issue by AtRaoN** [patternfly/patternfly-3#590]
pficons are not loading; I have followed this as well https://github.com/patternfly/patternfly/blob/master/PFICONS.md, though I might have missed anthing. still pficons are not loading.
![git](https://cloud.githubusercontent.com/assets/12978258/22894639/28b9ac72-f233-11e6-9c49-d625f8ab5791.PNG)

**Comment by andresgalante** [comment]
Hey @mndotmail 
Those instructions are to add new icons to Patternfly. What are you trying to achieve? Can you help me reproduce the issue?
thanks!

**Comment by andresgalante** [comment]
To add an icon to your UI, if it's a patternfly icon do it this way:
`<span class="pficon pficon-middleware"></span>`
and if its a fontawesome icon:
`<span class="icon-class">fa-angle-right</span>`

You can see a list of all icons here:
https://www.patternfly.org/styles/icons/

I hope this answer it, if not please reopen the issue.
