### ISSUE TITLE
Datatables scroll bars don´t work

### ISSUE THREAD

**Issue by aaldapa** [patternfly/patternfly-3#592]
https://datatables.net/examples/basic_init/scroll_xy.html

Datatable scroll bars don´t work.

$("#example").DataTable({
	"scrollX": true,
	"scrollY": 200
});

**Comment by andresgalante** [comment]
@dlabrecq Can you please take a look at this?

**Comment by dlabrecq** [comment]
We don't have a design for scrolling, yet. However, the default datatables.net scrolling should still work. 

In the latest table view example, the configuration looks like this:

// DataTable Config
$("#{{include.tableId}}").DataTable({
 ...
  dom: "t",

The dom property tells datatables.net to just show the table. For example, we don't want to show the default pagination controls.

If you change the dom property to "tr", the scroll bars will show. You can find the datatables.net documentation here:

https://datatables.net/reference/option/dom
