### ISSUE TITLE
It's not untouchable to build up native patternfly chart without D3.js and C3.js

### ISSUE THREAD

**Issue by dabeng** [patternfly/patternfly-3#594]
Frankly, charts generated by C3.js are rather ordinary and lack of interactivity and dynamic effects.

Currently, SVG is common and flexible, it's easy to integrated with native js(highcharts doesn't introduce any third-party plugins or libs), jquery, and even popular js frameworks like React ([Demo](http://codepen.io/HunorMarton/pen/ggQGqQ)) and Vue.js ([Demo](https://vuejs.org/v2/examples/svg.html)).

Data visualization is a charming feature and a widespread desire for modern web apps, it's also a wide stretch of virgin land for patternfly.

**Comment by andresgalante** [comment]
Hi @dabeng 
I don't quite understand what are you suggesting. do you want us to do our own charts?
C3 charts are svg based, using D3.
