### ISSUE TITLE
global search on patternfly.org could be improved

### ISSUE THREAD

**Issue by dabeng** [patternfly/patternfly-3#595]
![screenshot from 2017-02-15 10-50-02](https://cloud.githubusercontent.com/assets/5689075/22958981/629c7544-f2f8-11e6-97b9-bb893e79b974.png)

![screenshot from 2017-02-15 10-48-57](https://cloud.githubusercontent.com/assets/5689075/22958977/5c68090e-f2f8-11e6-80ed-9b46f1a248e3.png)

Maybe the latter is more welcomed by users.

**Comment by andresgalante** [comment]
Hi @dabeng can you please move this issue to the website repo please and close this one when you do?
thanks a lot!

**Comment by LHinson** [comment]
@dabeng I'v moved this issue over to patternfly-org here: https://github.com/patternfly/patternfly-org/issues/460

Closing this issue here.
