### ISSUE TITLE
Introducing jsfiddle, codepen or js bin into patternfly.org can facilitate users' tryout of patternfly

### ISSUE THREAD

**Issue by dabeng** [patternfly/patternfly-3#596]
![screenshot from 2017-02-15 11-24-44](https://cloud.githubusercontent.com/assets/5689075/22959454/21f048b4-f2fc-11e6-833e-bb62332ed2f1.png)

Another profit is that the way can save us a lot maintainment efforts.

**Comment by andresgalante** [comment]
I agree, this could be really good. @bleathem what do you think?

**Comment by andresgalante** [comment]
@dabeng can we move this issue to the org repo since it's related to the website? please close this issue once you do it.

And also, this is still a really good idea. 👍

**Comment by andresgalante** [comment]
This is a great idea, but I don't think we can do it till pf next with the showcases. I have it on the todo list
