### ISSUE TITLE
Removal of vendor prefixes from placeholder mixin results in inconsistent styles

### ISSUE THREAD

**Issue by rhamilto** [patternfly/patternfly-3#597]
@priley86's [removal of vendor prefixes in the placeholder mixin](https://github.com/patternfly/patternfly/blame/v3.10.0/less/mixins.less#L78) resulted in the introduction of inconsistent placeholder styles since [all browsers do not yet support un-prefixed placeholder pseudo elements](http://caniuse.com/#feat=css-placeholder).  This is resulting in a [bug in OpenShift](https://github.com/openshift/origin-web-console/issues/1259) where we have inconsistent placeholder text across Chrome, IE/Edge and Firefox, Safari.

Chrome 56 / Firefox 51
![screen shot 2017-02-15 at 1 39 48 pm](https://cloud.githubusercontent.com/assets/895728/22989540/4658b87a-f384-11e6-8050-bbd6c1e15a7c.PNG)

cc: @sg00dwin, @spadgett

**Comment by andresgalante** [comment]
@rhamilto Autoprefixer should be adding them

@priley86 Do you have time to take a look at this one?

**Comment by priley86** [comment]
@rhamilto thanks for reporting this. I did some further digging and it seems that my commit did remove one of the older Firefox prefixes. 

[Before](https://github.com/patternfly/patternfly/blob/fbec1af1c93f6acb1759dc4b02eb63931c17d838/dist/css/patternfly.css#L2596):
```
.form-control::-moz-placeholder {
  color: #999;
  opacity: 1;
}
.form-control:-ms-input-placeholder {
  color: #999;
}
.form-control::-webkit-input-placeholder {
  color: #999;
}
.form-control:-moz-placeholder {
  color: #999;
  font-style: italic;
}
.form-control::-moz-placeholder {
  color: #999;
  font-style: italic;
  opacity: 1;
}
.form-control:-ms-input-placeholder {
  color: #999;
  font-style: italic;
}
.form-control::-webkit-input-placeholder {
  color: #999;
  font-style: italic;
}
```
[After](https://github.com/patternfly/patternfly/blob/master-dist/dist/css/patternfly.css#L2639):
```
.form-control::-moz-placeholder {
  color: #999;
  opacity: 1;
}
.form-control:-ms-input-placeholder {
  color: #999;
}
.form-control::-webkit-input-placeholder {
  color: #999;
}
.form-control::placeholder {
  color: #999;
  font-style: italic;
}
```
 I noted the missing `:-moz-placeholder` which seems to be needed still.

It looks like we can add support for this prefix or any others by adding the target browsers from [Browserlist](https://github.com/ai/browserslist#queries) in Autoprefixer.

I took a stab at this [here](https://github.com/priley86/patternfly/commit/6a3f62a0138be2546783fb5660419f9bbfc8f4de) and it looks like the `:moz-placeholder` prefix is then compiled out.

```
.form-control::-moz-placeholder {
  color: #999;
  opacity: 1;
}
.form-control:-ms-input-placeholder {
  color: #999;
}
.form-control::-webkit-input-placeholder {
  color: #999;
}
.form-control:-moz-placeholder {
  color: #999;
  font-style: italic;
}
.form-control::placeholder {
  color: #999;
  font-style: italic;
}
```
Can you confirm whether this fix will work for you? If not, maybe we can target another browser or tweak the less to support your use case.

**Comment by rhamilto** [comment]
@priley86, this isn't there yet.  `font-style: italic;` is needed inside `.form-control:-ms-input-placeholder` and `.form-control:-ms-input-placeholder` for IE/Edge and Chrome/Safari.

**Comment by priley86** [comment]
@rhamilto i've opened #614. I believe this should resolve the issue. Adding this override explicitly to `.form-control` in `src\less\forms.less` ensures that `.forms-control::placeholder` is output to `patternfly.css` and then autoprefixer can apply its prefixes correctly. This problem stems from the fact that Bootstrap less or other 3rd party less which adds prefixes will be ignored by autoprefixer (b/c it will not prefix a declaration that's already been prefixed). The css once compiled now adds:
```
.form-control::placeholder {
  color: #999;
  font-style: italic;
}
```

Which can be autoprefixed to:
```
.form-control::-webkit-input-placeholder {
  color: #999;
  font-style: italic;
}
.form-control:-moz-placeholder {
  color: #999;
  font-style: italic;
}
.form-control::-moz-placeholder {
  color: #999;
  font-style: italic;
}
.form-control:-ms-input-placeholder {
  color: #999;
  font-style: italic;
}
.form-control::placeholder {
  color: #999;
  font-style: italic;
}
```
Let me know if this resolves the issue @rhamilto.

**Comment by andresgalante** [comment]
I'll close this issue since we are following the discussing on #614

thanks a lot Patrick and Robb!

**Comment by rhamilto** [comment]
Shouldn't this issue stay open until the #614 merges?
