### ISSUE TITLE
very slim dropdown of combobox

### ISSUE THREAD

**Issue by andreasn** [patternfly/patternfly-3#60]
Compared to the bootstrap-select widget the dropdown of the bootstrap-combobox is very slim.
Setting the width of .dropdown-menu to 100% seems to do the trick.

**Comment by andreasn** [comment]
![screenshot from 2015-04-15 13 28 09](https://cloud.githubusercontent.com/assets/209895/7157946/b437cd30-e374-11e4-87cd-586300f2c3c9.png)

**Comment by stefwalter** [comment]
In addition, try resizing your window so that the drop down is near the bottom. All hell breaks loose with scrollbars: 

![screenshot from 2015-04-15 13-48-37](https://cloud.githubusercontent.com/assets/795070/7158066/26275888-e376-11e4-8358-bf5fea9888bc.png)

**Comment by rhamilto** [comment]
@andreasn Good observation.  I've added a card to the backlog for this. https://trello.com/c/wLzWVhEs/61-make-boostrap-combobox-dropdowns-the-full-with-of-the-combobox-so-that-they-re-consistent-with-boostrap-selects

@stefwalter I'm unable to reproduce your bug using https://rawgit.com/patternfly/patternfly/master/tests/bootstrap-combobox.html.  Do you see the same behavior using the aforementioned test page?

**Comment by stefwalter** [comment]
> @stefwalter I'm unable to reproduce your bug using https://rawgit.com/patternfly/patternfly/master/tests/bootstrap-combobox.html. Do you see the same behavior using the aforementioned test page?

Nope, I don't see it there. I do see the pop-under vs. pop-over behavior. Normal browser combo boxes overlap the browser's edge as you would expect. But not sure this can be fixed.

**Comment by rhamilto** [comment]
Fixed.  https://github.com/patternfly/patternfly/commit/1e1336f75560f4de4cc5f31bc70a290ba6340a25
