### ISSUE TITLE
Show/hide functionality does not work on Vertical Nav example code when accessed from web site.

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-3#607]
In the example code found here: http://www.patternfly.org/pattern-library/navigation/vertical-navigation/vertical-navigation.html, clicking on the hamburger icon in the upper left of the masthead does nothing.  Should show or hide the primary navigation.  If primary nav icons are present reduce the primary nave to display icons only.  Test pages work correctly.

**Comment by LHinson** [comment]
This should actually be filed again patternfly-org but that's ok. Also added a bug on jira https://patternfly.atlassian.net/browse/PTNFLY-2245

Another one I was hoping @dabeng could look at. FYI @bleathem

**Comment by dabeng** [comment]
I got [PR](https://github.com/patternfly/patternfly-org/pull/373) for this issue.

**Comment by andresgalante** [comment]
@mcarrano For next time, all issues related to the website should go on the websites repo https://github.com/patternfly/patternfly-org
thanks!

**Comment by LHinson** [comment]
Is addressed by: https://github.com/patternfly/patternfly-org/pull/373#issuecomment-286293855
