### ISSUE TITLE
text-cursor on bootstrap-combobox dropdown

### ISSUE THREAD

**Issue by andreasn** [patternfly/patternfly-3#61]
The cursor changes to `cursor: text;` on the bootstrap-combobox instead  of `cursor: pointer;` like other patternfly dropdowns.

**Comment by andreasn** [comment]
```
.input-group-addon:last-child {
cursor: pointer;
}
```

should fix that.

**Comment by rhamilto** [comment]
@andreasn, the cursor changing on hover of the &lt;input type="text"&gt; of the combobox is by design in order to indicate that input accepts text entry. Changing the cursor would eliminate this affordance.

**Comment by andreasn** [comment]
Returning to this, since I ran into it again today.
On the text part of the dropdown, it would have cursor: text; , only the little dropdown arrow would have cursor: pointer; with the code above. So the accordance would still be there for the part of the widget that accepts text.
![text-n-pointer](https://cloud.githubusercontent.com/assets/209895/7934130/0bcfbf3c-0925-11e5-9afe-6c5a37e9bbb2.png)
