### ISSUE TITLE
Bottom of page Arrow/Link Bar not working on PatternFly.org homepage

### ISSUE THREAD

**Issue by lizsurette** [patternfly/patternfly-3#613]
Seems like clicking the bottom of the page arrow/link bar isn't taking me to the next page on the PatternFly.org homepage. I'm using Chrome Version 56.0.2924.87 (64-bit) if that's helpful.

**Comment by andresgalante** [comment]
Hi @lizsurette This is a bug on the website, can you please open an issue there and link to this issue here so we can close this one?
https://github.com/patternfly/patternfly-org

thanks a lot

**Comment by lizsurette** [comment]
@andresgalante Yes!! Sorry about that :)
