### ISSUE TITLE
Color palette for Inkscape & GIMP

### ISSUE THREAD

**Issue by garrett** [patternfly/patternfly-3#620]
I noticed http://www.patternfly.org/styles/color-palette/ is lacking the Patternfly color palette for free software programs such as Inkscape and GIMP, so I converted the color swatches to the correct format using [SwatchBooker](http://www.selapa.net/swatchbooker/) and added a `Columns` line for GIMP to show all colors in one line (instead of wrapping).

As we use Inkscape for design in the Cockpit project, I have already added the palette to the [cockpit-design](https://github.com/cockpit-project/cockpit-design) repository. The color palette is located at https://raw.githubusercontent.com/cockpit-project/cockpit-design/master/PatternFly_Palette.gpl

### Inkscape

```
mkdir -p ~/.config/inkscape/palettes
cp PatternFly_Palette.gpl ~/.config/inkscape/palettes
```

### GIMP

```
mkdir -p ~/.gimp-2.8/palettes
cp PatternFly_Palette.gpl ~/.gimp-2.8/palettes
```

_Note: the location may change in future GIMP versions; it is (unfortunately) tied to a version number_

### Flatpak versions of Inkscape & GIMP

As Flatpak sandboxes configuration of applications, configuration files are stored elsewhere on the filesystem.

- Inkscape in Flatpak
  ```
  cp PatternFly_Palette.gpl ~/.var/app/org.inkscape.*/config/inkscape/palettes/
  ```
- GIMP in Flatpak
  ```
  cp PatternFly_Palette.gpl ~.var/app/org.gimp.*/config/GIMP/*/palettes/
  ```

_Note: Unlike the non-Flatpak version of the apps, these commands require running Inkscape and GIMP prior to color palette installation, as there are different versions of Inkscape and GIMP in Flatpaks (such as nightly/devel versions as well as possible released versions)._

**Comment by andresgalante** [comment]
Thanks a lot @garrett!
You are right we are missing this. Are you able to send a PR to add this to the website?

**Comment by garrett** [comment]
Hi! Sorry I'm a bit late replying — I meant to do this earlier, but was juggling a lot of stuff (related to RH Summit and all).

I've made a pull request on the website at: https://github.com/patternfly/patternfly-org/pull/412
