### ISSUE TITLE
Problem with use of transform:translate() to animate Modal Dialog position

### ISSUE THREAD

**Issue by EricWittmann** [patternfly/patternfly-3#622]
I recently ran into a problem when using a custom tooltip inside a PF modal dialog.  My custom tooltip gets positioned using `position:absolute` with a `left` and `top` dynamically set based on the mouse position (clientX, clientY).  

This worked well until I tried using it within a modal dialog, at which point the tooltip got positioned relative to the top,left of the dialog!  Confused, I eventually tracked this down to the use of the `transform` CSS property.  Here is a jsfiddle demonstrating the issue:

https://jsfiddle.net/3doxqabm/

Note that the "fixed" tooltip div is actually positioned relative to the parent "dialog" div.  If you remove the `transform: translate(0,0);` property, then everything is positioned as expected.

In PF modal dialogs, the `transform` property is used to animate the dialog so that it slides in from the top.  The side effect of this is that child divs positioned using `position:fixed` will be positioned relative to the modal.  Here is some documentation on the `transform` CSS property:

https://developer.mozilla.org/en-US/docs/Web/CSS/transform

The relevant bit of the documentation (tl;dr;) is this:

"If the property has a value different than none, a stacking context will be created. In that case the object will act as a containing block for position: fixed elements that it contains."

My local solution is to animate the modal dialog using `margin-top` instead of `transform` - so I'm overriding the PF styles to set `transform` to `none` and then changing the `transition` to use `margin-top` instead.  Seems to work just as well and now my tooltip positioning works.

**Comment by andresgalante** [comment]
Hi, This sounds like a Bootstrap issue, right?

You can also remove animations on modals:
https://getbootstrap.com/docs/3.3/javascript/#modals-remove-animation
