### ISSUE TITLE
`list-group-item-header` does not flex items to center

### ISSUE THREAD

**Issue by vkrizan** [patternfly/patternfly-3#626]
`list-group-item-header` in list view with expansion does not make items to flex to vertical center. To reproduce it remove icons from [List View - Simple Expansion test page](https://rawgit.com/patternfly/patternfly/master-dist/dist/tests/list-view-simple-expansion.html).

Fix seems to be simple, by adding `display: flex` to `list-group-item-header`. However, I don't know if that is the right solution.

![screenshot from 2017-04-11 17-01-12](https://cloud.githubusercontent.com/assets/7695766/24915952/eef7e53a-1ed8-11e7-85bb-809fa6af2f05.png)

**Comment by andresgalante** [comment]
Hi @vkrizan We've introduce a new list component to fix the issues with list-view.

it's much cleaner and modular, and it flex much better:
https://rawgit.com/patternfly/patternfly/master-dist/dist/tests/list-pf.html

Please let me know if you can migrate to this new version and if it solves your issues with old list view.

Thanks a lot

**Comment by vkrizan** [comment]
Thanks. Is there documentation for `list-pf` besides test pages? Test pages does not include list with **collapsible** content items (just to make sure they would work together).

FYI: List view at [Patternfly documentation](http://www.patternfly.org/pattern-library/content-views/list-view/#/code) uses previous `list-view-pf` component.

**Comment by andresgalante** [comment]
Nope, sorry there is no docs for this. It's a "do whatever you want" structure. 
The collapsible content is not there, but since it's an empty container you can flex your content or use bootstrap grid or whatever. You can slo do as many nested containers as you want.

Ping me on slack if you have any question and I'll show you around.
