### ISSUE TITLE
Ugly looking alert octagon exclam icons

### ISSUE THREAD

**Issue by stefwalter** [patternfly/patternfly-3#63]
Unfortunately, the alert octagon exclam icons look misaligned and quite amateur when rendered on Linux. I would suggest not using overlay at all to get consistent behavior across browsers and operating systems.

![screenshot from 2015-04-16 10-17-06](https://cloud.githubusercontent.com/assets/795070/7176824/0ec86388-e422-11e4-89a3-5afe042890f1.png)

**Comment by gregsheremeta** [comment]
+1. I also noticed that it looks bad on Linux.

**Comment by kybaker** [comment]
Good catch, we are currently in the process of updating this icon and a few others.

**Comment by rhamilto** [comment]
Added to the backlog:  https://trello.com/c/8j9VetNK/62-improve-appearance-of-pficon-layered-pficon-pficon-error-octagon-pficon-pficon-error-exclamation-on-linux

**Comment by rhamilto** [comment]
The design of the error and warning icons was changed to better align with the ok and info icons as well as render better on Linux.  For backward compatibility, the existing icons were not changed but rather new icons were added to use in place of the existing.
