### ISSUE TITLE
Spinner wobbles and has artifacts

### ISSUE THREAD

**Issue by Fryguy** [patternfly/patternfly-3#633]
I have recorded a video ([here](https://drive.google.com/file/d/0Bw1P84Qm0MZeZTdVdDJKcDhoZEE/view)) of http://www.patternfly.org/pattern-library/widgets/#spinner on Google Chrome 57.0.2987.133 at 125% browser zoom (that's my default zoom).  In the video, the first spinner is relatively normal but you can see the white artifact and the second spinner is wobbly.

@andresgalante as discussed in Slack.

**Comment by andresgalante** [comment]
Thanks for reporting this @Fryguy I would have never noticed it.
I'll label this issue as a bug and come back to it as soon as I can.

**Comment by LHinson** [comment]
Hey @Fryguy, we are scrubbing old issues. I can't see the issue when you're not zoomed in. For that reason, we won't address anything.
