### ISSUE TITLE
Header link inside panel-info is almost unreadable

### ISSUE THREAD

**Issue by NicolaIsotta** [patternfly/patternfly-3#634]
Follow-up of #511
JSFiddle: https://jsfiddle.net/8jp7ep25/1/
The other type of panels, having a much lighter background, don't show this problem.

**Comment by andresgalante** [comment]
Hi @NicolaIsotta, you are right there is no contrast and the colors are wrong. 
Can you send a PR to fix it?

**Comment by NicolaIsotta** [comment]
Sorry, I've never used any css preprocessor and I wouldn't know where to start.
Maybe @nireno can help us, he solved #511 .
