### ISSUE TITLE
Missing working example of list-view with pagination

### ISSUE THREAD

**Issue by bregman-arie** [patternfly/patternfly-3#638]
Hi,

First of all, great project!

Now to the actual issue - I'm trying to have list-view with pagination but:

1. There is no example code in patternfly.org on how to use list-view with pagination
2. The current example in this repository is not really working:

https://rawgit.com/patternfly/patternfly/master-dist/dist/tests/pagination-list-view.html?#

Do you have a working example on how to use list-view with pagination?
Also, is it possible to store and use dataset (json) like in the table example, but with list-view?

**Comment by andresgalante** [comment]
Hi @bregman-arie,

Are you using angular or jquery?

**Comment by bregman-arie** [comment]
Hi @andresgalante 

jquery

**Comment by pthealthtech** [comment]
Hi,

Is there any update to this task? We are also looking for the same example code for pagination in list view?

**Comment by LHinson** [comment]
@bregman-arie @pthealthtech apologies for the long delay. The jquery implementation has not been prioritized to date. Do you plan to continue to use jquery or have you investigated leveraging any of the js implementation frameworks?

**Comment by bregman-arie** [comment]
I'm k with closing this issue. Don't need it anymore

**Comment by LHinson** [comment]
ok thanks @bregman-arie
