### ISSUE TITLE
Toast notifications should be top aligned under the application bar

### ISSUE THREAD

**Issue by serenamarie125** [patternfly/patternfly-3#643]
The toast notifications documentation shows that a toast notification should be top right aligned. I suggest that this be changed to be top aligned under the application bar, and if there is a horizontal bra, should be top aligned under that.

The toast notification covers items on the banner, and among other things blocks the user from accessing the notification drawer, in some cases.  We have received feedback from multiple products on this.

This issue is associated with the patternfly-design issue https://github.com/patternfly/patternfly-design/issues/276

**Comment by mcarrano** [comment]
This looks like a duplicate.  I will close.
