### ISSUE TITLE
Access remote data for advance filter with tableview

### ISSUE THREAD

**Issue by RituVasuja** [patternfly/patternfly-3#646]
i want advance filter on remotely access json , In patternfly json define inside the program .

**Comment by andresgalante** [comment]
@dlabrecq Can you help with this one please?

**Comment by dlabrecq** [comment]
There's no description, so it's not clear what you're trying to do. Are you trying to apply a filter to remote data? Or, are you looking to filter paginated data?

Note that the filter HTML has little to do with the table view component itself, other than to add some extra styling. In fact, the entire toolbar simply sits on top of the table. However, table view provides a default implementation to apply a simple filter, via a JS file named patternfly.dataTables.pfFilter.js. Simply adding that file to the page, adds some basic JS functionality to filter data in the table.

Whether you choose to use that, override it, or create your own custom implementation is your choice. It was intended to be an example showing how the filter pattern is applied and doesn't handle more advanced cases.

Unfortunately, the underlying datatables.net API does not filter remote data. Although, filters can still be applied across paginated data. In order for a filter to be applied, the data must be known to datatables.net (i.e., data must be provided client-side for it to be filterable).

That said, there are various ways to apply a filter. For example, you could add your own filter via the addFilter() function of patternfly.dataTables.pfFilter.js, like so:

dt.table().pfFilter.addFilter({
  column: 2,
  name: "Browser",
  value: "Firefox"
});

Considering you own the filter HTML, you can also skip the default implementation entirely. That is, you can call the datatables.net API directly. Or, use your own custom implementation to apply a server-side filter -- showing the active filter would be up to you.

The filter pattern is provided below.

http://www.patternfly.org/pattern-library/forms-and-controls/filter/#/design

You can read more about how to filter using the datatables.net API here:

https://datatables.net/reference/api/filter()

**Comment by fr0z3nfyr** [comment]
From what I understand, OP is looking for https://datatables.net/reference/api/search().

Anyway, when you say 

> Whether you choose to use that, override it, or create your own custom implementation is your choice. 

how exactly can a function in `patternfly.dataTables.pfFilter.js` be overriden? Let's say `clearFilters()` for example.

**Comment by dlabrecq** [comment]
patternfly.dataTables.pfFilter.js is a dataTables.net extension, so you could extend DataTable.pfFilter for example. However, if you're looking for search, you'll need a custom implementation. For seacrh functionality, it may be best to call the datatables.net APIs directly.
