### ISSUE TITLE
Application Launcher's List View display issues

### ISSUE THREAD

**Issue by dtaylor113** [patternfly/patternfly-3#648]
In list view:

![image](https://cloud.githubusercontent.com/assets/12733153/26160558/9156c800-3aef-11e7-878a-2824d4cf01e8.png)

- Please add some padding between the icon and label.
```
.applauncher-pf-link-icon {
      @media (min-width: @screen-sm-min) {
        padding-right: 10px;
      }
    }
```
- Please align all labels regardless of size/width of icons, or if there some apps which do not have icons defined.  (Image below has padding-right applied)
![image](https://cloud.githubusercontent.com/assets/12733153/26161057/d7cbbf7e-3af0-11e7-8d7f-4502f5458019.png)

Similar to using 'fa-fw'  http://fontawesome.io/examples/  "Fixed Width Icons".  https://github.com/FortAwesome/Font-Awesome/blob/v4.7.0/less/fixed-width.less

**Comment by cdcabrera** [comment]
Sure thing, taking a look.

**Comment by cshinn** [comment]
If we put in a rule that adds padding for items without icons, we end up with a situation where they're all indented even if none of them have icons
![screen shot 2017-05-25 at 9 09 38 am](https://cloud.githubusercontent.com/assets/3300756/26451393/e922e7ae-4129-11e7-995e-2e192a714bda.png)

We can achieve the desired effect by including a placeholder div
![screen shot 2017-05-25 at 8 55 20 am](https://cloud.githubusercontent.com/assets/3300756/26451396/eb9f472a-4129-11e7-8dbf-b22ec9bb8bdb.png)

or we could come up with some kind of crazy selector that would do it, but would be very fragile.

@andresgalante @dtaylor113 @cdcabrera Which do you think is the right approach?
