### ISSUE TITLE
Too much margin after bootstrap-select control

### ISSUE THREAD

**Issue by stefwalter** [patternfly/patternfly-3#65]
The bootstrap-select control has a 10px margin-bottom. This causes help-block not to be displayed together with the control.

![screenshot from 2015-04-29 12-18-36](https://cloud.githubusercontent.com/assets/795070/7388951/df7691a2-ee69-11e4-97a9-bc47e078d40c.png)

**Comment by stefwalter** [comment]
Either one of these should fix the issue:

```
.bootstrap-select.btn-group {
  margin-bottom: 0px !important;
}
```

```
.bootstrap-select.btn-group:not(.input-group-btn) {
  margin-bottom: 0px;
}
```

**Comment by rhamilto** [comment]
Thanks, @stefwalter.  I've added this to the backlog.  https://trello.com/c/oT0vkbr9/67-too-much-margin-after-bootstrap-select-control
