### ISSUE TITLE
List View Outline Code doesn't match Designs

### ISSUE THREAD

**Issue by sjcox-rh** [patternfly/patternfly-3#653]
Fuse used the list view pattern and noticed a mismatch in the design and code. The code displays a blue outline for active items which the design mocks show as a gray outline.

Code Implementation:
<img width="555" alt="screen shot 2017-05-22 at 10 14 22 pm" src="https://cloud.githubusercontent.com/assets/16257540/26339346/3284120a-3f3c-11e7-8b73-a3db96b58792.png">

Designs:
<img width="786" alt="screen shot 2017-05-22 at 10 17 11 pm" src="https://cloud.githubusercontent.com/assets/16257540/26339388/6c579830-3f3c-11e7-9d3a-5a151bde0062.png">

**Comment by LHinson** [comment]
I _think_ this is a bug on the image and we decided to go with the blue since that is consistent for PatternFly. @kybaker can you confirm? If that's indeed the case, I'll file a bug against the design repo. Thanks @sjcox-rh!

**Comment by chirino** [comment]
I think the design looks much better.

**Comment by jeff-phillips-18** [comment]
@kybaker Can you confirm or deny? If grey, can you specify the color value?

**Comment by serenamarie125** [comment]
I think there was an intentional move to a gray outline.  @andresgalante made a specific change for openshift which uses the gray.

**Comment by kybaker** [comment]
@LHinson @sjcox-rh  I created the original gray design and during implementation it got changed. I think that the gray works better especially after seeing the live version in context. I think the shadow in the design is important for setting the hierarchy.
