### ISSUE TITLE
Badge color for icons in the masthead should be blue

### ISSUE THREAD

**Issue by serenamarie125** [patternfly/patternfly-3#656]
Badges which are shown in the masthead should be blue and on the top right corner as shown here:
http://www.patternfly.org/pattern-library/application-framework/masthead/#/design

@LHinson this is a request from oVirt.
Currently in variables.less, @notification-badge-color is set to @brand-danger
It should be pf-blue #0088ce

Note that @jeff-phillips-18 already did this for ManageIQ - you can see the code here: https://github.com/ManageIQ/manageiq-ui-classic/blob/master/app/assets/stylesheets/patternfly_overrides.scss#L96-L109

**Comment by andresgalante** [comment]
This one is done 😄  Thanks a lot @serenamarie125
