### ISSUE TITLE
Sidebar code fails if no navbar

### ISSUE THREAD

**Issue by stefwalter** [patternfly/patternfly-3#66]
In Cockpit we have the navbar in an outer frame, rather than in the document itself. The sidebar logic looks for this before setting the height of `.sidebar-pf`:

```
    if ( $('.navbar-pf .navbar-toggle').is(':hidden') ) {
```

This causes the sidebar not to work, unless we put an invisible hack of a navbar inside the document. Is there a better way to determine whether we're on mobile or not?

**Comment by stefwalter** [comment]
Code in question: https://github.com/patternfly/patternfly/blob/bf6b9f60c5dcab7e69c92202d043d99534126790/dist/js/patternfly.js#L5

**Comment by rhamilto** [comment]
@stefwalter Outer frame as in an html frame or iframe element?

**Comment by stefwalter** [comment]
The sidebar, as well as other content, is in an iframe element that takes up the majority of the browser's viewport. The exception is the navbar.

**Comment by rhamilto** [comment]
> The sidebar, as well as other content, is in an iframe element that takes up the majority of the browser's viewport. The exception is the navbar.

So the navbar is in a separate html document?  If so, the existing solution will not work regardless as it assumes the navbar and sidebar are in the same document.

**Comment by EmilyDirsh** [comment]
The existing test is pretty hack-y anyway. It'd be better to use matchMedia to test for the appropriate breakpoint.

**Comment by rhamilto** [comment]
@stefwalter given your use case, I'm going to close this issue.  I can't imagine we'll want to support splitting the navbar and page contents into separate frames.

**Comment by stefwalter** [comment]
I guess we have to go beyond PatternFly "supports" here.
