### ISSUE TITLE
npm module size doubled (19.2 MB)

### ISSUE THREAD

**Issue by gregsheremeta** [patternfly/patternfly-3#661]
I noticed that between 3.19 and 3.25 that the npm module size shot up. Looks like the font sizes all grew. Perhaps this is by design and not a real issue, in which case feel free to close.

I have a ton of npm modules on my machine, and patternfly is by far the largest of them at almost 20 MB :)

![selection_229](https://cloud.githubusercontent.com/assets/2248293/26762133/80770cec-490a-11e7-89a8-706f9b7fe018.png)

![selection_230](https://cloud.githubusercontent.com/assets/2248293/26762149/f2039344-490a-11e7-851a-bea7a3bb806a.png)

**Comment by gregsheremeta** [comment]
Introduced in commit https://github.com/patternfly/patternfly/commit/c9800ee1a2876aa9accc351ea3618a9173357db0

**Comment by andresgalante** [comment]
Thanks @gregsheremeta We introduce this to add new characters #377

But is a problem. I wonder if open sans can be an opt in and we can use a CDN instead. What do you think?
 
cc @bleathem

**Comment by gregsheremeta** [comment]
I was thinking opt-in a separate opensans npm package, maybe even two (light and full [all the characters]). I guess CDN works, but feels not as polished.

**Comment by cliffpyles** [comment]
@gregsheremeta thanks for bringing this to our attention. I'm making adjustments now.

**Comment by AdamJ** [comment]
The current version (3.45.0) of PatternFly is 16.1 MB zipped, so I will close this issue. If necessary, please open a new issue with a reference to this one.

**Comment by gregsheremeta** [comment]
It used to be only 7. The issue is not fixed, only very slightly alleviated.

**Comment by AdamJ** [comment]
@gregsheremeta The reason why PatternFly is this size is because the distribution now includes both `less` and `sass` files (including dependencies for both versions), compiled CSS for PatternFly, the full tests and a variety of fonts. All of these additions were done by design.

CC: @cliffpyles @andresgalante @dgutride @LHinson

**Comment by gregsheremeta** [comment]
The extra text from sass is trivial. This was something caused by large binaries -- specifically fonts. My argument was that the fonts were too big. Even if that was intentional.

At any rate -- it's better now. 6.8 gzipped from npm / yarn. What happened between 3.27.5 and 3.30.0? Less huge binaries, like fonts, I assume? Did the fonts just shrink?

yarn-offline-cache % ll patternfly*                               
-rw-r--r--. 1 root root 10899184 Apr  6 09:27 patternfly-3.25.0.tgz
-rw-r--r--. 1 root root 10897799 Apr  6 09:27 patternfly-3.25.1.tgz
-rw-r--r--. 1 root root 10972104 Apr  6 09:27 patternfly-3.26.1.tgz
-rw-r--r--. 1 root root 10968514 Apr  6 09:26 patternfly-3.26.6.tgz
-rw-r--r--. 1 root root 11037713 Apr  6 09:30 patternfly-3.27.5.tgz
-rw-r--r--. 1 root root  6086164 Apr  6 09:22 patternfly-3.30.0.tgz
-rw-r--r--. 1 root root  6797493 Apr  6 09:31 patternfly-3.41.6.tgz
-rw-r--r--. 1 root root  6812701 Apr  6 09:26 patternfly-3.42.0.tgz
-rw-r--r--. 1 root root  6831619 Sep 29  2009 patternfly-3.45.0.tgz
