### ISSUE TITLE
OpenSans changed

### ISSUE THREAD

**Issue by gregsheremeta** [patternfly/patternfly-3#662]
Upgraded from 3.19 to 3.25 and noticed the typography changed

Previous (which looks much better, imo)
![selection_233](https://cloud.githubusercontent.com/assets/2248293/26786769/a7a35124-49d5-11e7-9839-3b16bc9bf56f.png)

Current (letters look too short to me)
![selection_234](https://cloud.githubusercontent.com/assets/2248293/26786788/b03f73e4-49d5-11e7-90f7-48fa77efc85d.png)

Suspect https://github.com/patternfly/patternfly/pull/587

**Comment by gregsheremeta** [comment]
ping @LHinson @bleathem

**Comment by LHinson** [comment]
Hey @gregsheremeta 

@bleathem is on PTO over the next couple weeks. Let me and @andreasn touch base with him on this one when he returns and we'll figure out how to solve it. Apologies for the delay.

**Comment by cliffpyles** [comment]
@gregsheremeta thanks for bringing this to our attention. I'm making adjustments now.

**Comment by LHinson** [comment]
@cliffpyles can you confirm that this issue is resolved with #812? If so, will you close this?

**Comment by dgutride** [comment]
@gregsheremeta  - closing based on commits from Cliff above, please contact if you need to reopen
