### ISSUE TITLE
alignment of kebab dropdown menu callout

### ISSUE THREAD

**Issue by jgiardino** [patternfly/patternfly-3#663]
The callout (i.e. triangle pointing up) of the dropdown menu is not aligned with the kebab icon when the following conditions are true:

- kebab comes after a button
- buttons and kebab are not in a toolbar
- menu is NOT right-aligned (e.g. `ul.dropdown-menu` does not include the class `dropdown-menu-right`)

An example of this implementation can be seen in the [PF-React repo storybook for the kebab](https://jtomasek.github.io/patternfly-react/?knob-Label=Danger%20Will%20Robinson%21&knob-Right%20aligned=false&selectedKind=DropdownKebab&selectedStory=kebab&full=0&down=1&left=1&panelRight=0&downPanel=kadirahq%2Fstorybook-addon-knobs)

**Comment by andresgalante** [comment]
@jgiardino Do you have time to send a PR to pf to fix this?
