### ISSUE TITLE
Postinstall NPM Script Recursively Firing Jekyll Install

### ISSUE THREAD

**Issue by cdcabrera** [patternfly/patternfly-3#664]
The postinstall NPM script unnessarily runs Jekyll and Bundler when Patternfly is included as a dependency. Possible solutions:

- Remove NPM ```postinstall```
- Or provide additional checks inside ```postinstall```

Additional distribution clean up could also help improve/streamline installs

@bleathem

**Comment by bleathem** [comment]
There is a grunt task that runs bundler:
```
bundleInstall: {
        cmd: 'bundle',
        args: [
          'install'
        ]
      }
```

So I would advocate removing it from the npm postinstall.
