### ISSUE TITLE
{{site.baseurl}} config attribute can't be '/'

### ISSUE THREAD

**Issue by jniederm** [patternfly/patternfly-3#667]
commit daba0aa3f9f1489ef777658 introduces {{site.baseurl}} config attribute. If value of this attribute is `/` then loading of svg assets is broken.

see https://github.com/patternfly/patternfly/blob/daba0aa3f9f1489ef777658c462a37db32dd99eb/tests/pages/_includes/widgets/layouts/nav-vertical-notification-drawer.html#L10 that will resolve to https://github.com/patternfly/patternfly.github.io/blob/333ae7fe9e4a9002db2fa7cbf1f2035fe1f94fd4/pattern-library/navigation/vertical-navigation/vertical-navigation.html#L63. That is e.g. `//assets/img/logo-alt.svg` that can't be resolved.

@bleathem

**Comment by michpetrov** [comment]
Related: patternfly/patternfly-design#270

**Comment by bleathem** [comment]
Don't set `{{site.baseurl}` to `/`.  Rather, set it to a path eg. `/patternfly-org` or to an empty string.

**Comment by michpetrov** [comment]
@bleathem it cannot be set to an empty string - [Gruntfile.js#21](https://github.com/patternfly/patternfly-org/blob/master/Gruntfile.js#L21) (yet for some reason it is on patternfly.org, resulting in bad URLs)

**Comment by bleathem** [comment]
I meant the {{site.baseurl}} configured in the [Jekyll config](https://github.com/patternfly/patternfly-org/blob/master/source/_config.yml#L5).  The derived value in the Gruntfile may indeed be incorrect.

When you say it cannot be an empty string, what value are you referring to?

Re-opening this issue while we investigate.

**Comment by michpetrov** [comment]
I mean the final value that Jekyll uses to generate the URLs, because grunt will at the very least prepend `/` (which I think breaks some URLs when you're testing things locally), secondly `navbar-logo-icon` and the like already start with a slash, so you're ending up with double `//assets/img/logo.svg` (which is a problem on the live site).

**Comment by bleathem** [comment]
This is resolved with https://github.com/patternfly/patternfly-org/pull/427.  Thanks for narrowing down the issue @michpetrov.
