### ISSUE TITLE
Content jumps when opening a dialog

### ISSUE THREAD

**Issue by andreasn** [patternfly/patternfly-3#67]
The content of the browser jumps a bunch of pixels to the right when a dialog opens.
![content-shift](https://cloud.githubusercontent.com/assets/209895/7490745/5ce2c466-f3e3-11e4-9a8e-79948520ddb4.png)

**Comment by rhamilto** [comment]
This is a bug in Bootstrap 3.1.1, which is the version PatternFly is currently using.  https://github.com/twbs/bootstrap/issues/9855  Updating to Bootstrap >= 3.2 resolves the bug.  Given upgrading Bootstrap could have unknown consequences, we'll have to wait to upgrade until we can fully test any possible resulting issues.

**Comment by rhamilto** [comment]
Added to backlog. https://trello.com/c/YM5awliO/68-update-bootstrap-to-3-2-or-greater-to-resolve-modal-bug

**Comment by andreasn** [comment]
Thanks!

**Comment by rhamilto** [comment]
This is fixed by the update to Bootstrap 3.3.4.
