### ISSUE TITLE
Paginate Multi Data Tables

### ISSUE THREAD

**Issue by andrewasem** [patternfly/patternfly-3#682]
Ao trabalhar com vários Data Table em uma mesma tela e fazer uso de uma do recurso de paginar faz com que todos os datatable sejam paginados ao mesmo tempo.

Para isto se faz necessário alterar a função  "fnUpdate" `for (i = 0; i < ien; i += 1) {
        	  $(an).find('.paginate_input').val(iCurrentPage);
        	  $(an).find('.paginate_of b').html(iPages);

            // Add / remove disabled classes from the static elements
            if (oPaging.iPage === 0) {
            	$(an).find('li.first', an[i]).addClass('disabled');
            	$(an).find('li.prev', an[i]).addClass('disabled');
            } else {
            	$(an).find('li.first', an[i]).removeClass('disabled');
            	$(an).find('li.prev', an[i]).removeClass('disabled');
            }

            if (oPaging.iPage === oPaging.iTotalPages - 1 || oPaging.iTotalPages === 0) {
            	$(an).find('li.next', an[i]).addClass('disabled');
            	$(an).find('li.last', an[i]).addClass('disabled');
            } else {
            	$(an).find('li.next', an[i]).removeClass('disabled');
            	$(an).find('li.last', an[i]).removeClass('disabled');
            }
          }`

Será necessário adicionar a `$(an).find('` para identificar qual o datatable está sendo clicado para paginar.

**Comment by andresgalante** [comment]
Ola @andrewasem tudo bem? Você pode mandar um PR com isto?
Hi @andrewasem can you please send a PR to fix this?

**Comment by dabeng** [comment]
I came across the same issue when I contributed code to PELC. I'll try to send a PR : )

**Comment by andresgalante** [comment]
I'll close this issue since #185 solves it
