### ISSUE TITLE
Notification drawer should have pin button

### ISSUE THREAD

**Issue by KwisatzHaderach** [patternfly/patternfly-3#683]
It's kind of confusing at first (and inconvenient later) that the notification drawer is not closed by clicking anywhere else in the site.
It might be better to have some pin button there so it's on the user if he wants to keep the drawer there or not.

**Comment by serenamarie125** [comment]
We are doing some tests related to this specific issue

**Comment by LHinson** [comment]
@serenamarie125 any updates regarding the testing you have done on this?

**Comment by andresgalante** [comment]
Hi, I'll close this issue, if you think there is a general enough usecase for a pin for notification drawer that we should cover on Patternfly please create a design story and reopen this one.
