### ISSUE TITLE
API to hide/show main menu removed?

### ISSUE THREAD

**Issue by gashcrumb** [patternfly/patternfly-3#691]
Hi!  I had added a little API to hide and show the main navigation widget in this pr:

https://github.com/patternfly/patternfly/pull/582

For this issue:

https://github.com/patternfly/patternfly/issues/580

But I just updated the version of patternfly to the 3.25.1 and had this issue reported:

https://github.com/syndesisio/syndesis-ui/issues/638

From what I can tell in the latest code none of my changes were carried forward?  Is there some other way to achieve the desired behavior?

**Comment by gashcrumb** [comment]
@bleathem any word on this one?  This regression messes up the main views in our app...

**Comment by bleathem** [comment]
Sorry abuot this @gashcrumb.  your contribution seems to have gotten lost with the patternfly-functions.js split.  I've created a new PR (#695) re-introducing your contribution.

**Comment by gashcrumb** [comment]
Awesome, thanks!

**Comment by LHinson** [comment]
@bleathem @gashcrumb can we close this issue since #695 has been merged?

**Comment by gashcrumb** [comment]
Yep, sorry, thanks!

**Comment by LHinson** [comment]
No worries! Just didn't want to prematurely close anything @gashcrumb
