### ISSUE TITLE
Empty State Component: Secondary buttons too close together

### ISSUE THREAD

**Issue by dlabrecq** [patternfly/patternfly-3#699]
The secondary action buttons are too close together. Need to add more padding to match the PatternFly design.

Patternfly implementation:
<img width="421" alt="screen shot 2017-07-26 at 10 09 50 am" src="https://user-images.githubusercontent.com/16257540/28634625-a1ff0116-71ec-11e7-840b-51435695053e.png">

PatternFly-design:
<img width="377" alt="screen shot 2017-07-26 at 10 09 55 am" src="https://user-images.githubusercontent.com/16257540/28634635-a9df8a04-71ec-11e7-8456-8fde2839079f.png">

**Comment by dlabrecq** [comment]
FYI @sjcox-rh

**Comment by dlabrecq** [comment]
Reported by @sjcox-rh

**Comment by andresgalante** [comment]
Hi, @sjcox-rh are you looking for a 14px spacing between each btn on the empty state component?
How is that consistent with other instances of group of btns in other components?

**Comment by sjcox-rh** [comment]
@andresgalante I just noticed that in the implementation for patternfly-ng, the secondary buttons appeared much closer together than in the PatternFly design (shown above) Not sure what the exact pixel is as far as spacing, just wanted to make sure that the spacing between buttons was consistent across all repos.

Thanks!

**Comment by LHinson** [comment]
Given that we do not have an established spacing definitions for PatternFly to date, I suggest leaving implementation as is. In the future, spacing guides will provide clarification on implementation. We will not address this at this time. Thanks @sjcox-rh @dlabrecq
