### ISSUE TITLE
mixed IE8 support

### ISSUE THREAD

**Issue by gregsheremeta** [patternfly/patternfly-3#70]
PatternFly says

```
Since PatternFly is based on Bootstrap, PatternFly supports the same browsers as Bootstrap
```

This includes IE8.

However, the dependency tree pulls in jquery > 2, which is not IE8 compatible.

PatternFly should explicitly pull in jquery < 2.

**Comment by rhamilto** [comment]
Good point, @gregsheremeta!  I've set PatternFly to explicitly use 1.11.3 as it was inheriting 2.x from Bootstrap.
