### ISSUE TITLE
Date picker

### ISSUE THREAD

**Issue by stianst** [patternfly/patternfly-3#71]
Add a pattern/widget for inputting dates and times

**Comment by rhamilto** [comment]
Thanks, @stianst.  There is a Trello card for this feature at https://trello.com/c/sOdlDeVm/51-date-picker if you want to keep track of this feature request.

**Comment by stianst** [comment]
@rhamilto until this is added we've considered using https://angular-ui.github.io/bootstrap/ - one issue with eternicode/bootstrap-datepicker might be angularjs support

**Comment by stianst** [comment]
@rhamilto any clue when this will be added?

**Comment by xtrasmal** [comment]
Surely it would be better to use a solution that is not based on Angular or any other javascript framework. As we speak, there is something going on in front-end land. Angular is hitting the point where it's releasing version 2.0. Which is a complete overhaul. 
While this is happening, people around the world are looking for new frameworks to try out, before making commitment to Angular 2.0.  
ReactJS and MeteorJS are frameworks that are in the elevator going up. It's attracting a lot of attention and it's going to be a very good bet. It supports full duplex async better then Angular and that is a big plus. 
So do not bet on Angular OR bet on Angular 2.0 components only.

**Comment by stianst** [comment]
No-one suggested it to require any specific framework. However, I need it to work in AngularJS and ideally I don't want to do the wrappers required myself. So using libraries where there already are wrappers for AngularJS is preferred IMO.

**Comment by rhamilto** [comment]
Given PatternFly is a jQuery-dependent library and is still supporting less than modern browsers, we've chosen to implement Bootstrap-datepicker (see https://github.com/patternfly/patternfly/commit/96ab74d2948c4641befca41e120d1bd1f589b2ce).  That said, https://github.com/patternfly/angular-patternfly is looking to cover the needs of those of you using Angular 1.x.

**Comment by erundle** [comment]
I am working on an angular directive to wrap this component as we speak so I will be looking to release it as part of angular-patternfly shortly
