### ISSUE TITLE
HTML code for launcher home missing?

### ISSUE THREAD

**Issue by gregnolle** [patternfly/patternfly-3#711]
Apologies if I've missed this somewhere, but I can't find any HTML code for the "Launcher Home" screen in the Launcher pattern. There's a screenshot in the Overview and Design sections for the pattern, but the Code section only seems to cover login and the launcher menu.

**Comment by andresgalante** [comment]
Hi @gregnolle 
You are right it is missing, we haven't done the code yet.

Is this something you'd like to contribute? If you do I can definitely help you.

Thanks!

**Comment by gregnolle** [comment]
Ok thanks for the update. If we end up implementing the screen ourselves then I'll see if we can contribute back.

**Comment by LHinson** [comment]
@gregnolle Launcher is now available for PF-Core. Check it out here: http://www.patternfly.org/pattern-library/application-framework/launcher/#code

Closing this issue since it's been addressed.
