### ISSUE TITLE
Notifications drawer in horizontal layout is misaligned on mobile and doesn't match the design guides

### ISSUE THREAD

**Issue by gregnolle** [patternfly/patternfly-3#713]
The notifications drawer implementation does not match the design guide screenshots under "Responsive State". In particular:

- Bell icon isn't visible in the toolbar in mobile mode (it gets put in the hamburger menu)
- When the hamburger menu is hidden, the drawer gets hidden, and when you then reopen the hamburger menu the notifications drawer is visible again. I guess this is because the drawer has been put in the navbar collapse div.
- The full width of the screen isn't used
- The top of the drawer isn't aligned with the bottom of the nav bar.

Screenshot attached for reference (taken from the tests page).

![screen shot 2017-08-16 at 17 14 22](https://user-images.githubusercontent.com/6773397/29373751-0eb315a2-82a7-11e7-85af-c32d157aa70f.png)

**Comment by LHinson** [comment]
Hey @gregnolle I've just linked to the PR that is up to address some of these issues for vertical navigation. We have upcoming work queued to address this for horizontal.
