### ISSUE TITLE
Code missing for "Tree List View" pattern

### ISSUE THREAD

**Issue by gregnolle** [patternfly/patternfly-3#714]
Another pattern that is documented but seems to be missing the code. Sorry to keep raising these sort of issues but I'm not sure how else to track the availability (I couldn't find any other issue about this).

If there's a roadmap that I've missed for patterns that are documented but not implemented yet, then by all means please close this and point me in that direction.

**Comment by LHinson** [comment]
Hey @gregnolle 

There is a few things going on here. 
1. In general, our process is iterative so there are times when documentation makes it up on the site prior to the code. That said, we can do a better job of explaining that process and will look to make changes to articulate that. 
2. Tree List view is a contribution from patternfly-ng. You can view a demo of that implementation and code here: https://rawgit.com/patternfly/patternfly-ng/master-dist/dist-demo/#/treelist We have a to-do to get this introduced as CSS to patternfly-patternfly. I'm still coordinating on that effort.

**Comment by LHinson** [comment]
@gregnolle Closing this issue as Tree List View is now available 
See: http://www.patternfly.org/pattern-library/content-views/tree-list-view/#code
