### ISSUE TITLE
Angular PatternFly Charts Less Not in PatternFly

### ISSUE THREAD

**Issue by cdcabrera** [patternfly/patternfly-3#718]
The current Angular PatternFly ```charts.less``` isn't within PatternFly in its active state. Not necessarily understanding the history behind this decision need weigh in on moving this Less, or aspects of this file, over to core. 

This decision currently affects an open PR where only a precise aspect ,concerning Donut Charts, has been updated, and there is an open question of should we move just this "precise aspect" or all of ```charts.less``` over to core.

The current ```Charts.less```
- https://github.com/patternfly/angular-patternfly/blob/master/src/charts/charts.less

The open PR:
- https://github.com/patternfly/angular-patternfly/pull/570
  - [Less change per PR 570](https://github.com/patternfly/angular-patternfly/pull/570/files#diff-77cda1182bf17b807037ae998c7ad2b7)

**Comment by dtaylor113** [comment]
There is some donut chart less/css already be in patternfly:  https://rawgit.com/patternfly/patternfly/master-dist/dist/tests/donut-charts.html.   We need to verify that angular-patternfly is using the correct donut styles as determined by pf core.  If there are some extra css/less styles that angular-patternfly's donut component requires, then it should either be moved to core, or if it's just for a-pf, remain in a-pf repo.

**Comment by dtaylor113** [comment]
My vote would be to evaluate/move styles of a chart, one at a time.  Ie. Donut, then Utilization, then Trend, etc..
