### ISSUE TITLE
Ending the serve task leaves processes running (port 9000)

### ISSUE THREAD

**Issue by benjaminapetersen** [patternfly/patternfly-3#719]
Running ~~npm run serve~~ `npm run start`:

```bash
Running "connect:server" (connect) task
Started connect web server on http://localhost:9000
```

But then after killing the process & switching to another project that also uses a `connect` server:

```bash
Fatal error: Port 9000 is already in use by another process.
```

Would probably be best if the server shut down completely.  I'm not sure atm what is causing this, will try to dig a little more & report some more detail.

**Comment by andresgalante** [comment]
@benjaminapetersen this is super annoying, are you able to send a PR to fix it?

**Comment by benjaminapetersen** [comment]
@andresgalante assign me the issue and I can take a look.  I prob can't this afternoon, but happy to give it a go.  I just don't want to forget.

**Comment by LHinson** [comment]
Nice, thanks @benjaminapetersen!

**Comment by andresgalante** [comment]
@benjaminapetersen thanks a lot you are the best :)

**Comment by benjaminapetersen** [comment]
In the weeds on some test updates, but have this in my queue!

**Comment by benjaminapetersen** [comment]
This appears to have been resolved already:

- ran `npm run start` locally in Patternfly (serves on `localhost:9000`)
- `ctrl + c` to kill the server process
- switched to origin-web-console
- ran `grunt serve`  (also serves on `localhost:9000`)

No longer a conflict on server port.  I think we can close this issue, perhaps a previous dependency update resolved it?

**Comment by andresgalante** [comment]
Thanks a lor @benjaminapetersen !
