### ISSUE TITLE
Vertical navigation is not keyboard accessible

### ISSUE THREAD

**Issue by rhamilto** [patternfly/patternfly-3#723]
[Vertical navigation](https://rawgit.com/patternfly/patternfly/master-dist/dist/tests/vertical-navigation-with-secondary.html) is not [keyboard accessible](http://webaim.org/techniques/keyboard/).  The addition of href attributes to the &lt;a&gt; in the test pages will partially resolve this issue.  However, secondary and tertiary nav menus will remain inaccessible to keyboard navigation at desktop resolutions without additional changes.  

In [adopting PatternFly's vertical nav in OpenShift](https://github.com/openshift/origin-web-console/pull/1932), this issue results in a regression from our current nav which is fully keyboard accessible.

cc: @spadgett, @ncameronbritt, @serenamarie125, @jeff-phillips-18

**Comment by LHinson** [comment]
Thanks @rhamilto. @matthewcarleton has a story to address the href attributes first. See: https://patternfly.atlassian.net/browse/PTNFLY-2533

We will look at the secondary and tertiary after the above is complete.

**Comment by LHinson** [comment]
@jgiardino will be picking up this story to add further enhancements related to the secondary and tertiary menus. https://patternfly.atlassian.net/browse/PTNFLY-2537

FYI @rhamilto

**Comment by andresgalante** [comment]
@LHinson the CSS part of PR #766 is ready to merge, we need to include the Javascript for it.

**Comment by LHinson** [comment]
@andresgalante I see some open questions on the PR. Are you sure it's ready to merge?

**Comment by matthewcarleton** [comment]
#766 Relates to this and another open issue #839  
Should we consider prioritizing it to get it merged @LHinson? 
@jgiardino suggested breaking it out to deal with these specific issues so that could be an option as well.

**Comment by jgiardino** [comment]
I think the css updates in #766 addresses the issues in #839 
I'm hesitant to really do anything more in the html other than just making the <a> keyboard accessible.

**Comment by jgiardino** [comment]
This is primarily a design and JS issue. I suggest pairing :pear: up a designer and JS dev to investigate a solution that's possible in all the JS repos.

I removed the `css` label since css updates related to keyboard navigation can be included for issue #839.

**Comment by LHinson** [comment]
Closing per a conversation with Robb. Thanks for taking a look at those.
