### ISSUE TITLE
Stylelint rule deprecation

### ISSUE THREAD

**Issue by AdamJ** [patternfly/patternfly-3#729]
In Stylelint, the rule "declaration-block-no-ignored-properties" is deprecated, as of version 8.0.

Though PatternFly uses grunt-stylelint v.0.7.0, which does not use stylelint v8.0, should PatternFly be upgraded to properly handle deprecated rulesets?

The current version of grunt-stylelint is v0.9.0, which uses stylelnit v8.0.0.

**Comment by andresgalante** [comment]
Hey @mindreeper2420 you are right 👍 Can please you send a PR with a fix for this?

**Comment by TheRealJon** [comment]
https://github.com/patternfly/patternfly/pull/929

**Comment by AdamJ** [comment]
Somehow I missed the comment from @andresgalante to update grunt-stylelint. Is removing the rule set better, or upgrading the packages?

**Comment by TheRealJon** [comment]
I think we need to do both. If it's deprecated, it would need to be removed/replaced with a similar rule regardless. I could add a version bump for grunt-stylelint to the PR.

**Comment by AdamJ** [comment]
I'm on board with bumping the versions too - I believe there are also additional rules that the newer version allows that could then (possibly) be added, if desired.

**Comment by TheRealJon** [comment]
Yeah, the PR could be a WIP until we get the rules set the way we want.

**Comment by TheRealJon** [comment]
Looks like `declaration-block-no-ignored-properties` was deprecated in 7.8. Reason given:
> could not reliably account for replaced elements
