### ISSUE TITLE
Include HTML templates that address common scenarios

### ISSUE THREAD

**Issue by augustogoulart** [patternfly/patternfly-3#732]
# Proposal
Include HTML templates that address common scenarios, like article pages, landing pages, product page, etc.
### Examples:
[Foundation HTML templates](http://foundation.zurb.com/templates.html)
[Materialize HTML templates](http://materializecss.com/getting-started.html)
### To make easier to adopt Patternly
Starter templates are an easy way for newcomers to get started. Foundation has done a nice work in this area and I believe that when the project provides an initial backbone for new projects, it makes the developer's life easier and the adoption rate tends to grow.
### To make easier to sell Patternfly
When I say "to sell" here I'm referring to sell the idea of using Patternfly for managers and clients. When you have starter templates to immediately show and make changes, it becomes easier to convince people that one particular tool is better than another and reaffirm the developer's decision to use it.

**Comment by andresgalante** [comment]
Hi! Thanks! this a really important thing to do. You'll find some templates here:
https://rawgit.com/patternfly/patternfly/master-dist/dist/tests/

You are planning to have better ones for the next version of patternfly
