### ISSUE TITLE
Wizard classes set the sidebar width based on resolution but does not update the content margin accordingly.

### ISSUE THREAD

**Issue by jeff-phillips-18** [patternfly/patternfly-3#734]
Since the sidebar width changes but the content margin does not, extra space is used unnecessarily in the content area. The test pages use javascript to update the margin, this is not listed as being a necessary step for adopters.

Would be nice to use flexbox and remove the left-margin all together.

**Comment by LHinson** [comment]
Closing this issue here since #735 addresses it.
