### ISSUE TITLE
Hyphenated variables and multiple inclusion do not work (application launcher)

### ISSUE THREAD

**Issue by michpetrov** [patternfly/patternfly-3#738]
The issue seems to be caused by liquid, pages built with jekyll are ok.

Application launcher uses hyphenated variables in include:

    {% include widgets/navigation/horizontal-primary-nav-bar.html launcher-icons=true launcher-grid=true navindex=1 %}

which are re-included in `horizontal-primary-nav-bar.html`:

    {% include widgets/framework/application-launcher.html launcher-icons=include.launcher-icons launcher-grid=include.launcher-grid %}

As far as I can tell on the first page the variable `include.launcher-grid` doesn't exist, instead of it there is `include.grid` so the second inclusion is broken. However even fixing the variable names doesn't work, it looks like re-including a variable turns it into a Promise and the variable is inaccessible at the time of the build.

**Comment by andresgalante** [comment]
@michpetrov thanks for reporting it, would you be able to send a PR with a fix for it?

**Comment by michpetrov** [comment]
@andresgalante I'll take another look at it but as I said the variable names are not the main problem and I'm not sure you can propagate the value through multiple includes.
