### ISSUE TITLE
pficon-service has poor complex typography

### ISSUE THREAD

**Issue by stefwalter** [patternfly/patternfly-3#74]
The pficon-service icon has complex double lines, and path overlaps, which cause it to render poorly at anything but the largest scales.

**Comment by stefwalter** [comment]
@serenamarie125 @abonas CC.

**Comment by stefwalter** [comment]
Example of rendering:

![screenshot from 2015-06-05 22-00-38](https://cloud.githubusercontent.com/assets/795070/8014151/98baab68-0bce-11e5-9eb5-dc215113e84d.png)

**Comment by stefwalter** [comment]
Example of a fixed icon:

![layer1](https://cloud.githubusercontent.com/assets/795070/8014183/dd0371c4-0bce-11e5-81e8-8f98e6590390.png)

**Comment by serenamarie125** [comment]
@stefwalter , i'm checking with Kyle now.  I think that treatment was added intentionally, but will find out and get back to you.  The original icon was fixed, but it was modified.

**Comment by kybaker** [comment]
@serenamarie125 the fixed icon stefwalter showed above is how it should look and how I built it. My guess is the issue he pointed out is an artifact of rendering the font.

https://dl.dropboxusercontent.com/u/5892944/service.svg

**Comment by serenamarie125** [comment]
@stefwalter , sorry for the bad info.  Does this happen when you are using any of our other pficons?

**Comment by rhamilto** [comment]
This was a problem with the source artwork (svg) where the shapes were not combined.

![screen shot 2015-06-05 at 5 30 00 pm](https://cloud.githubusercontent.com/assets/895728/8015846/660267de-0baa-11e5-8942-a0fdae735a76.PNG)

I've corrected the source artwork and re-generated the font.

![screen shot 2015-06-05 at 5 35 43 pm](https://cloud.githubusercontent.com/assets/895728/8015861/8f63913e-0baa-11e5-8ab0-69b7bb5e8316.PNG)

All should be good now.  Thanks, @stefwalter!

**Comment by serenamarie125** [comment]
thanks @rhamilto !

**Comment by stefwalter** [comment]
Thanks @rhamilto for the quick fix.
