### ISSUE TITLE
[RFE] vertical nav - support custom hover and hide delays

### ISSUE THREAD

**Issue by gregsheremeta** [patternfly/patternfly-3#744]
vertical nav - support custom hover and hide delays.

Instead of adding hoverDelay and hideDelay parameters to the setupVerticalNavigation function, consider stabilizing this plugin's API using the options pattern:
https://learn.jquery.com/plugins/basic-plugin-creation/#accepting-options

**Comment by andresgalante** [comment]
Thanks @gregsheremeta for the suggestion.

@jeff-phillips-18 What do you think?

**Comment by jeff-phillips-18** [comment]
Sounds like a reasonable thing to do.

**Comment by ares** [comment]
:+1:

**Comment by gregsheremeta** [comment]
I can submit a PR

**Comment by andresgalante** [comment]
@gregsheremeta it be awesome if you can fix it :) thanks a lot
