### ISSUE TITLE
Timepicker bug

### ISSUE THREAD

**Issue by deernano** [patternfly/patternfly-3#745]
The live example of Timepicker is not working in the code tab.
When clicking the text field, there is no drop-down shows. 
Please refer to :http://www.patternfly.org/pattern-library/forms-and-controls/timepicker/#/api

![timepickerbug](https://user-images.githubusercontent.com/5396309/30328323-88c13dbe-9801-11e7-950e-ea26541f7f4a.jpg)

**Comment by deernano** [comment]
@andresgalante @bleathem 
Hi Andres and Brain, I was trying to do the task of moving Timepicker to widget page, before I started to do that, I found that the code of Timepicker is not working.  Could you help to have a look on that? Thank you~

**Comment by LHinson** [comment]
@deernano This actually needs to be a bug against patternfly-org because the time picker is working in the test page here: https://rawgit.com/patternfly/patternfly/master-dist/dist/tests/time-picker.html

There is something funky going on with it specifically in patternfly-org. That said, this page will be removed. I wonder if it works on the widgets page?

**Comment by jeff-phillips-18** [comment]
Console errors:
```
moment.min.js Failed to load resource: the server responded with a status of 404 (Not Found)
bootstrap-datetimepicker.js Failed to load resource: the server responded with a status of 404 (Not Found)
moment.min.js Failed to load resource: the server responded with a status of 404 (Not Found)
bootstrap-datetimepicker.js Failed to load resource: the server responded with a status of 404 (Not Found)
(index):628 Uncaught TypeError: $(...).datetimepicker is not a function
    at HTMLDocument.<anonymous> ((index):628)
    at i (jquery.min.js:2)
    at Object.fireWith [as resolveWith] (jquery.min.js:2)
    at Function.ready (jquery.min.js:2)
    at HTMLDocument.J (jquery.min.js:2)
```

**Comment by deernano** [comment]
@LHinson The timepicker on test page is not working as well. Before we move the timepicker to the widget page. We might need to fix it. Not sure how to move now, need to view the code afterwards~

**Comment by LHinson** [comment]
@deernano 

When I click on the time picker on patternfly.org [1], I don't get a drop down. 
When I test it on our rawgit page [2], I do see the drop down. 

Will you specify what bugs you are seeing on the test page? 

[1] http://www.patternfly.org/pattern-library/forms-and-controls/timepicker/#/api
[2] https://rawgit.com/patternfly/patternfly/master-dist/dist/tests/time-picker.html

**Comment by dabeng** [comment]
@bleathem , please review the PR -- https://github.com/patternfly/patternfly-org/pull/464

**Comment by deernano** [comment]
@dabeng Thank you xuebin

**Comment by andresgalante** [comment]
Thanks!
