### ISSUE TITLE
Documentation / example updates

### ISSUE THREAD

**Issue by starryeyez024** [patternfly/patternfly-3#747]
Just a couple suggestions on things I noticed when reading through the get started docs that I thought might be useful to other newbies. :)

* In the getting started doc, it would be useful to ask folks to run grunt or grunt build first, then grunt server, then open localhost:9000 to see examples since it does not auto-launch
* Mini Card with status - has mismatched description vs. percentage on bar (10 vs 25%)
* The docs do not explicitly say which version of Bootstrap is being used. The "Get bootstrap" link should link directly to Bootstrap 3
* I know this is still under construction but the [design status](http://www.patternfly.org/patternfly-design/status/) page is a fabulous resources to share out
* This [Patternfly Demo app](https://rawgit.com/patternfly/patternfly-demo-app/master/dist/index.html) is also super useful, you might want to link to this on patternfly.org or at least in the get started docs

**Comment by bleathem** [comment]
Great, thanks for the feedback @starryeyez024!  cc: @LHinson
