### ISSUE TITLE
class*="-exclamation" affects other stylesheets

### ISSUE THREAD

**Issue by stefwalter** [patternfly/patternfly-3#75]
The following rule in `less/icons.less` affects other projects classes and seems to be needlessly broad:

```
[class*="-exclamation"] {
  color: #fff;
}
```

In particular in Cockpit it makes certain things show up in white as they change state.

**Comment by rhamilto** [comment]
Thanks again, @stefwalter.  This is fixed.

**Comment by stefwalter** [comment]
Thanks!
