### ISSUE TITLE
Wizard steps layout broken at exactly 480px wide viewport

### ISSUE THREAD

**Issue by rhamilto** [patternfly/patternfly-3#754]
![screen shot 2017-09-18 at 8 45 54 am](https://user-images.githubusercontent.com/895728/30542597-04f2aa76-9c4e-11e7-8f0e-c2d163063338.PNG)

cc:  @matthewcarleton, @jeff-phillips-18, @spadgett

**Comment by matthewcarleton** [comment]
Thanks @rhamilto I'll take a look at this today.
