### ISSUE TITLE
The notifications .fa-bell icon changes position whether the badge circle is displayed or not

### ISSUE THREAD

**Issue by sg00dwin** [patternfly/patternfly-3#756]
In the OpenShift web console, the notifications badge is only displayed when there are unread messages. When it appears and disappears the bell icon moves horizontally. This is because the `.badge` does not use absolute position and is in flow within `.nav-item-iconic` block.

example
![pf-notification-badge-issue](https://user-images.githubusercontent.com/1874151/30550570-d2f6df7a-9c65-11e7-8b34-ee0726288cb5.gif)

cc @rhamilto

**Comment by rhamilto** [comment]
Absolutely positioning the badge is one possible fix.  That's the override we're using in OpenShift.

**Comment by LHinson** [comment]
Hey @sg00dwin, agreed this should be resolved... Would you be interested in contributing this fix?

**Comment by sg00dwin** [comment]
Hi @LHinson, I can work on a fix. I currently have another pr open that's involves the notification badge https://github.com/patternfly/patternfly/pull/748, which hopefully would get merged in first, so there's no conflicts.

**Comment by LHinson** [comment]
Awesome, thanks @sg00dwin! @andresgalante is going to review #748 to get that pushed along.
