### ISSUE TITLE
Wizard steps layout breaks if more than four steps

### ISSUE THREAD

**Issue by rhamilto** [patternfly/patternfly-3#758]
The addition of "Step Five" causes "Step Three" to wrap to two lines at viewport width of 481px.

![screen shot 2017-09-18 at 3 44 06 pm](https://user-images.githubusercontent.com/895728/30561381-d2ebce96-9c88-11e7-8de1-9a7b2483b3c4.PNG)

Parenthetically, @serenamarie125 supplied [designs for the OpenShift web console that may include more or less than six steps](https://github.com/serenamarie125/openshift-origin-design/blob/46a0e3f67100ff168a996b7c02d33aeb3a65df79/web-console/5-components/order-from-catalog.md#steps-visualization-when-there-are-5-or-less-steps), and outlined steps indicator behavior that differs from the wizard as it exists today.  In order to realize the designs as outlined, the following changes need to be made:

1.  The breakpoint for the presentation of steps to change to desktop presentation needs to change from 480px to 768px.
1.  For desktop resolutions, if more than 6 steps are present, only the active step's label should display.

@serenamarie125, @jeff-phillips-18, I was under the impression these changes were already in flight in PatternFly.  We either need these changes in PatternFly stat or we have to roll a custom implementation in the OpenShift web console.  Please advise.  cc: @spadgett

**Comment by andresgalante** [comment]
Thanks Robb,

@matthewcarleton can you please add the change on .1 to #755 

@srambach do you think something like you did with those steps component can be done here for Robbs second point?

**Comment by matthewcarleton** [comment]
Hey Robb, 

Are you testing on my branch? 
https://rawgit.com/matthewcarleton/patternfly/wizard-754-dist/dist/tests/wizard.html

The breakpoint should be at 992px.

**Comment by rhamilto** [comment]
> Are you testing on my branch?
https://rawgit.com/matthewcarleton/patternfly/wizard-754-dist/dist/tests/wizard.html

No.  I was using master and did not see an open issue.

**Comment by matthewcarleton** [comment]
Robb, ah ok. Ya I've switched the breakpoints based on the issue in https://github.com/patternfly/patternfly/issues/754

**Comment by jeff-phillips-18** [comment]
@rhamilto For the angular-patternfly wizard, we have added an option 'activeStepTitleOnly'. Since the names for each step could vary in length, we did not want to set a hard step count limit but rather leave the decision to the particular wizard.

Setting the activeStepTitleOnly option to true will show only the title for the currently active step.

**Comment by spadgett** [comment]
> @rhamilto For the angular-patternfly wizard, we have added an option 'activeStepTitleOnly'. Since the names for each step could vary in length, we did not want to set a hard step count limit but rather leave the decision to the particular wizard.

In general, it'd be nice to control settings like this using CSS media queries. At some screen widths, you might need active title only, but at wider widths all titles fit OK. When set as an attribute on an Angular component, it's difficult to change without adding JavaScript resize listeners, which is klunky.

**Comment by serenamarie125** [comment]
@rhamilto @spadgett this element of the design was added to OpenShift last minute, and was not yet supported by PatternFly, as we discussed a week or two back.  As @jeff-phillips-18  mentioned, for now we have added the ability to use this solution on a per wizard basis.  At a later time, it would be great if someone contributed an enhancement

**Comment by jeff-phillips-18** [comment]
@spadgett I'm not sure any media query could determine when the titles fit and when they don't. It would depend on the titles and the size of the dialog containing the wizard.

**Comment by spadgett** [comment]
@jeff-phillips-18 Right, it wouldn't be one size fits all. You'd need to let consumers choose the breakpoint for a given wizard. If documented CSS classes were added to active and inactive titles, then consumers could hide/show the titles at a breakpoint using CSS. (Maybe they already are, and we can use this. But ideally it would be treated as an API so that the class names didn't change.)

The benefit is that the CSS solution is responsive without messy JS event listeners.

**Comment by andresgalante** [comment]
For now I'll close this issue since it's fixed #755 but we need to work on the steps to make them more flexible.
