### ISSUE TITLE
Wizard without .modal-title results in doubled top border at 480px or less

### ISSUE THREAD

**Issue by rhamilto** [patternfly/patternfly-3#760]
To make the bug easier to see in the following screenshot, I've changed the border color of .modal-content and .wizard-pf-steps-indicator to red.

![screen shot 2017-09-19 at 9 38 12 am](https://user-images.githubusercontent.com/895728/30595195-7c9364dc-9d1e-11e7-8a64-e5289b82eb26.PNG)

The bug in OpenShift web catalog is much more evident as the catalog modal currently lacks a CSS declaration the wizard overlay is inheriting from Bootstrap, but I will fix that in the catalog.

![screen shot 2017-09-19 at 9 42 09 am](https://user-images.githubusercontent.com/895728/30596149-4e0bb094-9d21-11e7-8b66-a3d6e72f5fc4.PNG)

**Comment by LHinson** [comment]
@rhamilto ah yes, I see what you are saying here! Want to submit a PR to fix and get this resolved quickly?

**Comment by matthewcarleton** [comment]
@rhamilto are you removing .modal-header altogether to get this result?

**Comment by rhamilto** [comment]
> @rhamilto are you removing .modal-header altogether to get this result?

Yes as that's the way it works in angular-patternfly.
![screen shot 2017-09-19 at 1 22 24 pm](https://user-images.githubusercontent.com/895728/30605855-b2c1309c-9d3d-11e7-946d-83ed48f3d536.PNG)

**Comment by rhamilto** [comment]
Fixed by https://github.com/patternfly/patternfly/pull/755
