### ISSUE TITLE
Fix the html lint errors in the `showcases` branch

### ISSUE THREAD

**Issue by bleathem** [patternfly/patternfly-3#761]
The new CSS and jQuery showcases generate html that produces errors when verified using the htmllint tool.

To see the errors, replace line 285 with line 284 in the `Gruntfile.js` and run `grunt showcaseBuild htmlhint`
https://github.com/patternfly/patternfly/blob/showcases/Gruntfile.js#L285

**Comment by bleathem** [comment]
@amarie401 & @asonawan can you create PRs addressing this issue for your respective showcases?  Plesae be sure to work from the `patternfly/showcases` branch

**Comment by andresgalante** [comment]
@amarie401 & @asonawan  do you have any update on this?

**Comment by amarie401** [comment]
@andresgalante the html lint errors for the jquery showcase have been fixed. Not sure if @asonawan has already fixed the CSS ones yet though.

**Comment by LHinson** [comment]
The CSS and jquery showcase is an effort that we decided to no longer pursue due to bandwidth therefore i"m closing this issue as it's no longer relevant.
