### ISSUE TITLE
Vertical nav is expanded first and then collapsed after refresh

### ISSUE THREAD

**Issue by amirfefer** [patternfly/patternfly-3#767]
When vertical navigation  is collapsed  (minimized view), and refreshing the page, it starting in expand mode and changing back to minimize.

![sep 25 2017 6-19 pm - edited](https://user-images.githubusercontent.com/11807069/30816353-7045d214-a21e-11e7-825f-9cb107838f09.gif)

**Comment by Rohoover** [comment]
It should probably remain in its original state. I'll bring this up with the PF team.

**Comment by Rohoover** [comment]
It should probably remain in it's origin state.

**Comment by andresgalante** [comment]
Hi @amirfefer Do you have time to send a PR to fix it? If not I'll add it to our backlog.

**Comment by serenamarie125** [comment]
@LHinson, can we get this on the PF backlog?  Both CloudForms and Satellite are being impacted by this issue.

**Comment by jeff-phillips-18** [comment]
@amirfefer You might try starting off with 'hide-nav-pf' on the 'nav-pf-vertical' and 'container-pf-nav-pf-vertical' elements, and add: 

```
.container-pf-nav-pf-vertical.hide-nav-pf {
  visibility: hidden !important;
}
```

This way none of it shows until we know how to display the nav.

**Comment by jeff-phillips-18** [comment]
@amirfefer I've edited the above comment to include some necessary CSS.

**Comment by serenamarie125** [comment]
@ohadlevy do you think we could get someone to test Jeff's suggestion?

**Comment by dgutride** [comment]
@LHinson @jeff-phillips-18  - is this a js issue or does your comment above provide sufficient information on how to work through this?

**Comment by dabeng** [comment]
IMO, in the context of jQuery, there is no appropriate timing to change the classList of vertical navigation sidebar before rendering according to localStorage settings. But this will be a easy task in the context of React or Vue.js.

On the other side, I have a trick solution for this issue:
1. add classname "hidden"  to sidebar and main-content

2. add class ".collapsed" and ".collapsed-nav" to sidebar and main-content according to localStorage settings

3. remove classname "hidden" from sidebar and main-content

Here's the [demo](https://rawgit.com/dabeng/patternfly/remove-flash-dist/dist/tests/vertical-navigation-primary-only.html) page

@amarie401 @jeff-phillips-18 @dgutride Any thoughts ?

**Comment by jeff-phillips-18** [comment]
IMO, the CSS change I mentioned above could be done in PF. Applications using local storage to set the nav state to the previous state should then, as I mention above as well, simply start with the `hide-nav-pf` class on the vertical nav and container components.

**Comment by dabeng** [comment]
Hi @jeff-phillips-18 . Do you mean that we should abandon `vertical-navigation-primary-only-no-cache.html` and `vertical-navigation-primary-only-sessionstorage.html`

**Comment by dabeng** [comment]
Hi @jeff-phillips-18 I have refactored the  [demo page](https://rawgit.com/dabeng/patternfly/remove-flash-dist/dist/tests/vertical-navigation-primary-only.html) and replaced class `hidden` with `hide-nav-pf`.
New patch is [here](https://github.com/dabeng/patternfly/commit/f1ddc35e0d6903a4b3722336075723e3c12793ce).

**Comment by jeff-phillips-18** [comment]
@dabeng please put up a PR with the changes so that it can be reviewed.

**Comment by LHinson** [comment]
Closing issue since PR #1114 has been merged.
