### ISSUE TITLE
Please publish package to npmjs.com

### ISSUE THREAD

**Issue by akurdyukov** [patternfly/patternfly-3#77]
I'd like to use only npm in my project. Please publish patternfly to npmjs.com. It seems to be easy: https://gist.github.com/coolaj86/1318304

**Comment by erundle** [comment]
I pushed up patternfly 1.3.0 https://www.npmjs.com/package/patternfly

This should work since we have all of our dependencies committed in the components directory. Please take a look and let me know if this works for you.

**Comment by rhamilto** [comment]
Completed with https://github.com/patternfly/patternfly/commit/5b761bfdb7abb314e795de5aed3ee287f550b656
