### ISSUE TITLE
Notification drawer close button lacks a hover state, expand/collapse icon has different hover state

### ISSUE THREAD

**Issue by rhamilto** [patternfly/patternfly-3#774]
![screen shot 2017-10-06 at 2 45 55 pm](https://user-images.githubusercontent.com/895728/31293507-69fab05c-aaa5-11e7-9260-4318867c758b.PNG)

It seems like the default solution for close buttons in PatternFly is to have a less opaque icon that turns fully opaque on hover (e.g., alerts, modals).

![screen shot 2017-10-06 at 2 52 33 pm](https://user-images.githubusercontent.com/895728/31293685-076a476c-aaa6-11e7-9195-876c1d899870.PNG)

Additionally, the expand left/collapse right icon turns blue on hover, which is different visual treatment.  

![screen shot 2017-10-06 at 2 53 21 pm](https://user-images.githubusercontent.com/895728/31293709-263bbb58-aaa6-11e7-9f98-cdc69352fba2.PNG)

I would think these controls would have a similar treatment given their context (the header of the notification drawer).

cc: @sg00dwin, @spadgett

**Comment by andresgalante** [comment]
This is related to #775.
@LHinson I've create a story to fix consistency on close icons:
https://patternfly.atlassian.net/browse/PTNFLY-2591

Let's work on it.
