### ISSUE TITLE
Wizard close button is different than modal close button

### ISSUE THREAD

**Issue by rhamilto** [patternfly/patternfly-3#775]
![screen shot 2017-10-06 at 3 08 16 pm](https://user-images.githubusercontent.com/895728/31294291-4e214096-aaa8-11e7-9496-c97c1a3ffb1a.PNG)
![screen shot 2017-10-06 at 3 08 28 pm](https://user-images.githubusercontent.com/895728/31294293-4f7b623c-aaa8-11e7-907e-c5c92b6ef171.PNG)

Presumably these should be the same since they offer the same functionality?  The larger click target on the modal is better IMO.

cc:  @sg00dwin, @spadgett

**Comment by andresgalante** [comment]
Yes, you are right, they should be the same. @LHinson lets work on this.
