### ISSUE TITLE
List View expansion - minor issue

### ISSUE THREAD

**Issue by fr0z3nfyr** [patternfly/patternfly-3#778]
Click right on the caret symbol that shows `expanded`/`collapsed` state of a list item. The item won't expand, click anywhere else on the list and expansion/collapse works as expected.

Looks to me like a click event on `.list-group-item-header` is handled but a click on `.list-view-pf-expand` is being prevented for some reason. haven't got time to look into the code personally. Thought of bringing this to notice.

**Comment by jeff-phillips-18** [comment]
@fr0z3nfyr Where are you experiencing this?

**Comment by fr0z3nfyr** [comment]
@jeff-phillips-18 Hi, I was away for a while, so couldn't check the progress on this issue. You can check this behavior on any test implementation. For immediate reference, visit the [official demo page](http://www.patternfly.org/pattern-library/content-views/list-view/#/code) and attempt to expand/collapse a list item by clicking right on &rsaquo;/v icons to reproduce the issue.

**Comment by jeff-phillips-18** [comment]
This appears to only be an issue on patternfly.org. It works fine at https://rawgit.com/patternfly/patternfly/master-dist/dist/tests/list-view-simple-expansion.html

**Comment by LHinson** [comment]
In that case, it should be closed here and opened on [patternfly-org](https://github.com/patternfly/patternfly-org) Would you mind filing this issue over there @fr0z3nfyr?

**Comment by michpetrov** [comment]
The issue has been reported on patternfly-org: patternfly/patternfly-org#408 (However it needs a fix here, I've already submitted a PR)

**Comment by LHinson** [comment]
Got it. Thanks @michpetrov I've asked @cliffpyles and @amarie401 to review. Thanks for your help :)

**Comment by LHinson** [comment]
Closing this issue since its been addressed! Thanks for sending the PR @michpetrov!
