### ISSUE TITLE
`grunt serve` results in 404

### ISSUE THREAD

**Issue by rhamilto** [patternfly/patternfly-3#784]
If `grunt serve` is run without first running `grunt` or `grunt build`, there are no test pages to serve and the browser renders a 404 page (`Cannot GET /`).  Either the instructions should be updated to reflect the need to run a build first or the serve task should be updated to include build.

**Comment by matthewcarleton** [comment]
@bleathem what are your thoughts on this?

**Comment by benjaminapetersen** [comment]
I would agree with @rhamilto, with the addition that:

```bash 
grunt serve    # will build first by default 
grunt serve --skipRebuild    # flag would allow you to skip the rebuild to save some time
```

**Comment by dabeng** [comment]
I sent PR #1087 to fix this issue.
