### ISSUE TITLE
Vertical navigation and rest of the menu inconsistency

### ISSUE THREAD

**Issue by ares** [patternfly/patternfly-3#790]
I find the inconsistency between vertical nav and other menus unexpected. Where some menus appear just after hovering (vert nav) the rest must be clicked first. One can observe that at https://www.patternfly.org/pattern-library/navigation/vertical-navigation/vertical-navigation.html

**Comment by matthewcarleton** [comment]
Thanks @ares that's an interesting point. @andresgalante what are your thoughts on this?

**Comment by andresgalante** [comment]
I agree there is an inconsistency on the behaviour. @mcarrano Can I assign this issue to you?

**Comment by LHinson** [comment]
@andresgalante I've filed an issue on patternfly-design. @mcarrano will help to get this in the pipeline to address from a design standpoint first and then we can update code. See: https://github.com/patternfly/patternfly-design/issues/461

**Comment by rhamilto** [comment]
For what it's worth, Red Hat QE also noted an issue with hover to open vertical nav menus.  See https://bugzilla.redhat.com/show_bug.cgi?id=1491622  cc: @spadgett

**Comment by LHinson** [comment]
ok thanks @rhamilto I'm going to add this comment over to the design issue as well.

**Comment by matthewcarleton** [comment]
@LHinson I'm going to close this and we can continue with the issue you've created in design. Thanks!

**Comment by LHinson** [comment]
Just to loop back around on this issue.... the design issue is closed as well. While it may be inconsistent, the hover allows a user quick access to menu items. For that reason, the inconsistency is considered intentional and there will be no change at to the nav at this time.

**Comment by matthewcarleton** [comment]
Oh that's my fault, I didn't see that it was closed. Thanks for the update @LHinson
