### ISSUE TITLE
Configuration and events on treegrid

### ISSUE THREAD

**Issue by fr0z3nfyr** [patternfly/patternfly-3#797]
Are there any plans on enhancing treegrid widget to support configuration and detect events similar to [this jQuery plugin](http://maxazan.github.io/jquery-treegrid/) by [@maxazan](https://github.com/maxazan). 

I used this jQuery library in past but then gave up in favor of `dataTables` and then finally `patternfly` to stick with UI/UX. I was thinking of forking the plugin and customizing it to fit `patternfly`. However, it made sense to first ask here if there are any plans in this direction. 
Cheers!

**Comment by dgutride** [comment]
hi @fr0z3nfyr  - sorry for the delay - at this point, we don't have any significant plans to enhance the jquery widgets within patternfly.  If you are using the treeview and have an idea on how to improve it that you'd like to contribute - it would be good to see if that's a good fit.

**Comment by LHinson** [comment]
This seems to have gotten stale. Closing but feel free to open a new issue if need be @fr0z3nfyr
