### ISSUE TITLE
the login page styles for alerts are implemented differently from the design

### ISSUE THREAD

**Issue by sharvit** [patternfly/patternfly-3#804]
The design page shows the notification between the logo and the form while they are style normally:
http://www.patternfly.org/pattern-library/application-framework/login-page/#/design

In the `login.less` there is an override for the default alert styles so they became transparent and with a white text color:
https://github.com/patternfly/patternfly/blob/master/src/less/login.less#L52-L55

This is how the example actually look when i add the alert into the html:
![login patternfly](https://user-images.githubusercontent.com/1262502/31998159-774e0398-b997-11e7-8162-c86436185f4f.png)

**Comment by andresgalante** [comment]
@mcarrano can you please decide what to do on this issue? should we keep it as it is or change it to follow the docs?

**Comment by mcarrano** [comment]
My personal preference is to make these consistent with the design. I don't feel like the colors work very well on top of the black.  But would also like to get @kybaker 's opinion.

Do you know if we deviated from the original design for a specific reason, @andresgalante ?

**Comment by andresgalante** [comment]
This was introduce 3years ago, tbh I don't know the background. But we can easily remove those styles and make it look as the design specs.

I'll send a PR to fix it.
