### ISSUE TITLE
Release notes occasionally missing items or are incorrectly numbered

### ISSUE THREAD

**Issue by rhamilto** [patternfly/patternfly-3#815]
The switch to semantic versioning is great as releases occur more frequently; however, I have noticed a couple of issues:

1.  If commit messages are not formatted correctly (e.g., https://github.com/patternfly/patternfly/commit/d7e9eb95a1477462c8baa04cf322360a01832f49), commits fail to appear in the release notes.  The implication of this is one has to go browse the commits for the release to determine if there are additional changes in the release that need to be regression tested when adopting a new release.
1.   If commit messages contain the wrong type or no type, the release version could be incorrect (e.g., https://github.com/patternfly/patternfly/releases/tag/v3.27.1 as a result of https://github.com/patternfly/patternfly/pull/716/commits/2660c5eabd0f92e6016553ae9d7dffeab77bce08)

Ensuring the commit messages are right should be easy enough to address in code review; however, I think someone should still be verifying the release notes.

And I think `<a name"3.x.x">` should be removed from the release notes template as I'm guessing it's incomplete markup, not to mention [named anchors are obsolete](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a#Obsolete).

cc: @spadgett

**Comment by dgutride** [comment]
Closing - reviewed the last 10 releases and commit messages are being used correctly by the team (there is another issue to fix the extra anchor tag that we'll address with a semantic release version)
