### ISSUE TITLE
Restrict :hover styling to non-touch devices?

### ISSUE THREAD

**Issue by rhamilto** [patternfly/patternfly-3#822]
https://github.com/openshift/origin-web-console/issues/2438 is one example in the OpenShift console where :hover styles create a usability problem in iOS.  Other examples include the vertical nav and notification drawer.  It appears that the best way to resolve these bugs is to restrict :hover styling to non-touch devices.

**Comment by LHinson** [comment]
Thanks for looking at these issue. Closing per our conversation.
