### ISSUE TITLE
[RFE] open notification drawer should highlight the notifications icon

### ISSUE THREAD

**Issue by gregsheremeta** [patternfly/patternfly-3#828]
[RFE] open notification drawer should highlight the notifications icon

We are using the notification drawer pattern:
![selection_247](https://user-images.githubusercontent.com/2248293/32508688-165be9a2-c3b9-11e7-9f18-1cc7e72b50ff.png)

With multiple icons in the masthead, it's easy to forget / lose track of which icon you need to click to close the drawer.
![selection_245](https://user-images.githubusercontent.com/2248293/32508722-3a5bbed6-c3b9-11e7-9e7d-6d13d79ac39a.png)

The launcher pattern, however, does show such an indication:
![selection_246](https://user-images.githubusercontent.com/2248293/32508751-51635148-c3b9-11e7-834f-f766943891a9.png)
http://www.patternfly.org/pattern-library/application-framework/launcher/

I suggest a standardization such that all icons in the masthead that currently have some action ongoing (i.e. an open drawer, menu, etc.) have a highlighted icon and, if it makes sense in that context, an up "arrow" in the box outline that points at the icon (not sure of the technical term for that).

**Comment by LHinson** [comment]
@gregsheremeta I completely agree. I'm going to file a design doc bug as well and we'll get this updated. Thanks!

**Comment by matthewcarleton** [comment]
@LHinson do you know the status of this issue?

**Comment by LHinson** [comment]
@andresgalante I remember you got blocked on his one. Will you specify what you need to complete this?

**Comment by LHinson** [comment]
@kybaker per the story here: https://patternfly.atlassian.net/browse/PTNFLY-2654, @andresgalante notes that: 

> The vertical nav masthead has a lighter shade of gray as as background than the horizontal nav masthead. Therefore when I use the same color for the hover, it's almost unnoticeable on the vertical nav. 

![screen shot 2017-12-01 at 2 45 47 pm](https://user-images.githubusercontent.com/7924406/36734774-8226069a-1ba2-11e8-8f62-67be567b13d7.png)

Will you please advise?

**Comment by kybaker** [comment]
@andresgalante I would be in favor of adjusting the hover state to make it more visible. You will have to try a few in the code to see what works best.

**Comment by mcoker** [comment]
This was addressed in https://github.com/patternfly/patternfly/issues/1030 (PR https://github.com/patternfly/patternfly/pull/1055) if you want to review. 

URLs:
* https://rawgit.com/patternfly/patternfly/master-dist/dist/tests/notification-drawer-horizontal-nav.html
* https://rawgit.com/patternfly/patternfly/master-dist/dist/tests/notification-drawer-vertical-nav.html

cc @mcarrano

**Comment by mcarrano** [comment]
Yes, I agree that this has been addressed with latest masthead changes and should probably be closed out.

**Comment by LHinson** [comment]
Thanks @michael-coker @mcarrano. I'm closing then!
