### ISSUE TITLE
Notification Drawer: HTML/CSS example is missing hover states

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-3#829]
Per this issue: https://github.com/patternfly/patternfly-org/issues/487, the Notification Drawer implementation is missing hover states when you mouse over rows in the list.  The correct implementation can be seen in the AngularJS reference implementation here: http://www.patternfly.org/pattern-library/communication/notification-drawer/#/code/angular.

**Comment by andresgalante** [comment]
Fixed on #974
