### ISSUE TITLE
The recommendations for primary button placement are inconsistent

### ISSUE THREAD

**Issue by ares** [patternfly/patternfly-3#830]
Hello,

we found that patternfly recommendations suggest having primary button aligned to left in form while in modal window it recommends primary button to be aligned to right - http://www.patternfly.org/pattern-library/forms-and-controls/buttons-on-forms/

We discussed it today with few devs here and we find this quite confusing. I understand that we wanted this to be aligned with elements above but we'd prefer having the primary button always at the same place, ideally on right side.

/cc @iNecas @xprazak2

**Comment by mcarrano** [comment]
@ares I appreciate your feedback, but this was a conscious decision based on the idea that right aligned buttons don't work so well on responsive forms where the buttons can become too distant from the body of the form. Keeping the buttons left aligned with the elements above allows the user's eye to travel naturally to the primary action at the bottom of the form.

**Comment by iNecas** [comment]
Please not that this is not about (if I understand it correctly) the alignment to the form, but rather order of 
Ok/cancel vs. Cancel/Ok

**Comment by ares** [comment]
Yes and also the fact it's different order in regular form and modal window.

**Comment by matthewcarleton** [comment]
I'm going to move this over to design to continue the discussion. Thanks!
