### ISSUE TITLE
Rubygems and rails asset pipeline support in the SASS version

### ISSUE THREAD

**Issue by skateman** [patternfly/patternfly-3#832]
The new native sass doesn't have support for rubygems and the rails asset pipeline. This will require some changes in the conversion:
* Provide a top-level `_patternfly-sprockets.scss` similarly to the [old code](https://github.com/patternfly/patternfly-sass/blob/master/assets/stylesheets/_patternfly-sprockets.scss) mimicking [bootstrap-sass](https://github.com/twbs/bootstrap-sass/blob/master/assets/stylesheets/_bootstrap-sprockets.scss)
* Update the variables that are [referring to a path](https://github.com/patternfly/patternfly-sass/blob/master/assets/stylesheets/patternfly/_variables.scss#L42)
* Update each [path for files](https://github.com/patternfly/patternfly-sass/blob/master/assets/stylesheets/patternfly/_fonts.scss#L11) referenced in SASS
* Add the gemspec and rails engine files

**Comment by TheRealJon** [comment]
Will be closed by PR #840
