### ISSUE TITLE
Arrow button not always visible in 2nd level pinnable menu

### ISSUE THREAD

**Issue by Layla-P** [patternfly/patternfly-3#837]
When using the pinnable vertical navigation component, the blue circle with the arrow icon on is only visible once the menu has been click (ie. not visible in hover)
This causes the title and the links to appear mis-aligned.
However, this issue appears to be a bit sporadic.

**Comment by jeff-phillips-18** [comment]
The menu is pinnable only when it contains the active navigation item. Otherwise it would show a pinned menu with no selection.

**Comment by Layla-P** [comment]
Ok, but the headers look misaligned when it's not visible:
<img width="245" alt="menu" src="https://user-images.githubusercontent.com/15874598/32831981-efcbc6f6-c9f1-11e7-8509-27f2813156a0.png">

**Comment by matthewcarleton** [comment]
I'm going to move this over to design to get their input on it. Thanks @Layla-P
