### ISSUE TITLE
Labels (in forms) have too much emphasis

### ISSUE THREAD

**Issue by garrett** [patternfly/patternfly-3#838]
While reviewing Cockpit UI, Andreas and I noticed there were inconsistencies here and there in form labels, and wanted to unify them across Cockpit.

[In the discussion](https://github.com/cockpit-project/cockpit/issues/8018), we looked at the way labels are implemented in various frameworks and OSes. 

PatternFly's form labels are uniquely bold, which call a lot of attention to themselves.

## Comparison

Here's a comparison of different styleguides across frameworks & desktops:

| | PatternFly | Bootstrap | GNOME | macOS | Windows | KDE | Material (Google) |
|---:|---|---|---|---|---|---|---|
| _Placement_ | side (usually), above also | top (usually), side also | side | side | above | side | side (usually), above also |
| _Alignment_ | right | left | right | right | left | right | left |
| _Colon_ | no | no | no | yes | no | yes | no |
| _Bold_ | yes | no | no | no | no | no | no |
| _Grey_ | no | no | yes | no | no | no | yes |
| _Guidelines_ | [PatternFly](http://www.patternfly.org/pattern-library/) | [Bootstrap](http://getbootstrap.com/docs/4.0/components/forms/) | [GNOME](https://developer.gnome.org/hig/stable/visual-layout.html.en) | [macOS](https://developer.apple.com/macos/human-interface-guidelines/fields-and-labels/labels/) | [UWP](https://docs.microsoft.com/en-us/windows/uwp/design/layout/forms) | [KDE](https://community.kde.org/KDE_Visual_Design_Group/HIG/Alignment) | [Material](https://material.io/guidelines/) |

The most common attributes across the table above are:

1. Side placement (usually)
2. Right aligned labels
3. Not bold
4. Usually some form of differentiation (grey, colon, or, in PatternFly's case: bold)

---

So @andreasn and I were wondering:

1. Is there a reason why PatternFly uses bold labels in forms?
2. Would PatternFly consider modifying the visual style of the form labels so they don't visually outrank the content they represent?

**Comment by matthewcarleton** [comment]
Hey @Garrett I'm going to send this over to design to get review. Thanks!
