### ISSUE TITLE
Underlined links in vertical navigation

### ISSUE THREAD

**Issue by michpetrov** [patternfly/patternfly-3#839]
Links in the primary column have an underline that extends to the icon. Only appears when the link is focused and not hovered over.

![screenshot from 2017-11-13 16-12-57](https://user-images.githubusercontent.com/1999074/32733707-5b531be4-c890-11e7-87d7-b5f6900f0819.png)

I can submit a PR but I'm not sure what the expected look is. Remove the underline altogether, remove it just from the icon, some third option? The links in the other columns look the opposite - underline on hover but not on focus.

**Comment by matthewcarleton** [comment]
@jgiardino This was something that came up with the accessibility work you were doing right? Do you have any thoughts on this?

**Comment by jgiardino** [comment]
Yes, this work is already included in this PR: #766 
The css updates address the issue described here, but also generally addresses issues with indicating which menu item has focus for keyboard accessibility.
 
But this PR also includes more updates than just the css updates, to better support screen readers too. 

Should the css updates just be split out into a separate PR?

**Comment by matthewcarleton** [comment]
thanks @jgiardino, I don't think that's necessary. @andresgalante what do you think?
