### ISSUE TITLE
Improvement : A yeoman generator app 

### ISSUE THREAD

**Issue by fabm22** [patternfly/patternfly-3#84]
The idea behind patternfly is a missing block the current web is (was) missing. So it's great having such approach promoting latest web technologies in a cohesive UX way.

Following the "best practices" approach patternfly promotes, it would be a good idea I think to have a yeoman generator (actually 2 if we count a angularJS one) (http://yeoman.io/generators/) to generate an app and possibly some common variations through options in the command line. Would be named something like

generator-patternfly
generator-patternfly-ng  or  generator-patternfly-angular  for a AngularJs one 

What do you think?

**Comment by rhamilto** [comment]
@fabm22, a similar request was made over email.  We're planning to discuss it sometime next week.  Would you like to join the conversation?

**Comment by rhamilto** [comment]
This work is planned.  Watch https://github.com/patternfly/generator-patternfly as development will happen there.

**Comment by fabm22** [comment]
Amazing !
