### ISSUE TITLE
Embedded Wizard: HTML/CSS is needed

### ISSUE THREAD

**Issue by jgiardino** [patternfly/patternfly-3#841]
The [design documentation for the Wizard](http://www.patternfly.org/pattern-library/communication/wizard/) shows an example of an embedded wizard.

This issue is to track the implementation of the html and css for the embedded wizard design.

**Comment by priley86** [comment]
This implementation has been started in PatternFly React [here](https://github.com/patternfly/patternfly-react/pull/69)

I am posting the temporary CSS that was used. It was not completed, but just posting it here so I don't lose it when it comes back time to review this again...
```
.wizard-pf-header {
  background-color: #f5f5f5;
  border-bottom: none;
  padding: 10px 18px;
}
.wizard-pf-title {
  font-size: 13px;
  font-weight: 700;
}
.wizard-pf-footer {
  padding: 14px 15px 17px;
  text-align: right;
  & .btn + .btn {
    margin-left: 5px;
    margin-bottom: 0;
  }
  & > .btn {
    padding-left: 10px;
    padding-right: 10px;
    & > .fa-angle-left {
      margin-right: 5px;
    }
    & > .fa-angle-right {
      margin-left: 5px;
    }
  }
}
```

**Comment by LHinson** [comment]
@jgiardino as you've noticed, closing a few issues in here --- let me know if you have any concerns!
