### ISSUE TITLE
Need a slimmer dialog variant

### ISSUE THREAD

**Issue by andreasn** [patternfly/patternfly-3#842]
The 600px wide modal-dialog is too wide for some situations, so in Cockpit we did a little bit of extra css to create a 400px variant using a class. I was speaking to @jgiardino the other day, and she happened to need a 400px dialog in Composer. Hence I wanted to see if it makes sense to put that extra css in Patternfly.
I know about the bootstrap modal-sm class, but that gives a 300px dialog, so maybe it would make sense to call this dialog modal-md?

css would pretty much be:
```
.modal-md {
  width: 400px;
}
```

**Comment by matthewcarleton** [comment]
Thanks @andreasn this makes sense to me. I'd like to get @andresgalante thoughts on this first before we introduce it.

**Comment by andresgalante** [comment]
Hi @andreasn I think that including a new size for modals might be too much.

Can you help me understand the usecase where you need a md size modal?

**Comment by LHinson** [comment]
looping back around on this one @andreasn @jgiardino. Were you able to proceed with standard PF dialog boxes? If not, see andres' above question. Thanks so much.

**Comment by LHinson** [comment]
I'm going to close this one for now but definitely reach out if we need to discuss more. Thanks!
