### ISSUE TITLE
Close (X) icon should toggle button for popovers

### ISSUE THREAD

**Issue by ncameronbritt** [patternfly/patternfly-3#846]
Closing a [popover](http://www.patternfly.org/pattern-library/widgets/#popover) via the X icon (the first two examples) does not reset the toggle button. As a consequence, if a user clicks the button to see the popover again after dismissing it with the X, nothing happens. Two clicks are required to see the popover again.

Not sure if this behavior is limited to the pf site.

**Comment by jeff-phillips-18** [comment]
Happens on the test page as well: https://rawgit.com/patternfly/patternfly/master-dist/dist/tests/popovers.html

**Comment by michpetrov** [comment]
It's caused by a bug in Bootstrap (twbs/bootstrap#16732).

**Comment by dabeng** [comment]
@jeff-phillips-18 @michpetrov @matthewcarleton  I tried to refactor the js code snippets on patternfly/tests/pages/_includes/widgets/forms/field-level-help.html. Here's the **[Demo](https://rawgit.com/dabeng/patternfly/popover-close-dist/dist/tests/popovers.html)** page.
```js
  // Initialize Popovers
  $(document).ready(function() {
    $('[data-toggle=popover]').popovers()
      .on('hidden.bs.popover', function (e) {
        $(e.target).data("bs.popover").inState.click = false;
      });
  });
```
Do this solution make sense ?

**Comment by jeff-phillips-18** [comment]
@dabeng Works for me.

**Comment by matthewcarleton** [comment]
@dabeng looks good to me, nice work!

**Comment by dabeng** [comment]
Hi @jeff-phillips-18 @matthewcarleton , please review the related PRs :)
