### ISSUE TITLE
Documentation does not have Less/Sass build instructions for downstream products

### ISSUE THREAD

**Issue by TheRealJon** [patternfly/patternfly-3#847]
Currently, there are no instructions on how to configure and build for consumers who are importing PatternFly Less. There has been recent confusion about the file structure and how dependencies work in our distribution, so some clarification may be necessary.

1. Explain that the `dist/dependencies` folder is **not** used by PatternFly but is included for edge cases where our standard distribution might not work for a consumer. 

2. Describe how the consumer should configure their build tool to include `node_modules` in their search path when building less or sass, and how this allows the import statements in PatternFly Less to be resolved. Possibly include examples or links for some common build tools like Grunt, Gulp, and Webpack.

3. Ensure that it is clear that only files in the `dist/` folder should be consumed (not `src/`) since src was not meant for consumption and has been removed as of v3.30.0.

**Comment by matthewcarleton** [comment]
@TheRealJon can we close this now?

**Comment by TheRealJon** [comment]
@matthewcarleton Yes! I'm pretty sure we can
