### ISSUE TITLE
Unmet dependencies in the SASS implementation

### ISSUE THREAD

**Issue by skateman** [patternfly/patternfly-3#848]
Some dependencies don't provide SASS files, therefore, it's not possible to produce a CSS output. In the `patternfly-sass` repo I sorted this out by converting these dependencies and shipping them together with the package in a [separate folder](https://github.com/patternfly/patternfly-sass/tree/master/assets/stylesheets/patternfly/lib).

**Comment by jeff-phillips-18** [comment]
Do we really need to provide these? Applications can include the css directly if the are using these components. Are these using any variables that we want to be updatable? 

Copying and converting will restrict consumers to the version that we have converted. I think it better to allow the consumer to simply include the css as they see fit.

**Comment by skateman** [comment]
@jeff-phillips-18 that's okay if it's about CSS, but we pull in some LESS/SASS rules and variables and use/override them...

**Comment by TheRealJon** [comment]
@skateman, @jeff-phillips-18 Yes, we do need the Sass from these dependencies, [but I already took care of this](https://github.com/patternfly/patternfly/pull/821/files?diff=unified#diff-35b4a816e0441e6a375cd925af50752cR319) issue in PR #821. There are specifically 3 dependencies that don't provide Sass: bootstrap-combobox, bootsrap-datepicker, and d bootstrap-switch. As part of the sass conversion, I am converting the Less in these dependencies and providing them in the `dist/sass/dependencies` folder, where they are imported in the main broker file. The licenses for these dependencies are already included in [OPEN_SOURCE_LICENSES.txt](https://github.com/patternfly/patternfly/blob/master/OPEN_SOURCE_LICENCES.txt)

**Comment by TheRealJon** [comment]
This issue should be closed by PR #840

**Comment by kirantpatil** [comment]
May I know the installation steps for rails ?

Since README is still pointing to the [Sass-based Rails Gem](https://rubygems.org/gems/patternfly-sass) and its latest supported version 3.23.2

**Comment by andresgalante** [comment]
I'll close it since  #840 was merged
