### ISSUE TITLE
Pure CSS UI lib

### ISSUE THREAD

**Issue by dabeng** [patternfly/patternfly-3#849]
@LHinson  @andres @patrick, There will be a great prospect if we adding a pure css UI library where all the components are implemented with pure css code excluding js code. Maybe the scope of this library is limited. After all, advanced and complicated components need js code to add sophisticated behaviors and functionalities. But light weight and easy-to-use are exactly the killer features of this pure css lib. In fact, you can easily find a lot of equivalents of pure css solutions for our usual js components. For example, pure css tooltip, loading spinner, dropdown menu, sidebar, accordion, tabs ……Pure.css(https://purecss.io/), Balloon.cc(https://kazzkiq.github.io/balloon.css/) are nice examples.

**Comment by dabeng** [comment]
This idea came into my mind when I was contributing tooltip PR to patternfly-react repo. Perhaps you guys are also interested in it.

**Comment by andresgalante** [comment]
Hi @dabeng that's a good idea. PF next will be not have JS on core. we'll leave it to the react or ang implementations.

**Comment by dabeng** [comment]
Hi @andresgalante. What I describe above are all CSS features and demands, I'm confused by your comments 

> PF next will be not have JS on core. we'll leave it to the react or ang implementations.

Could you give a bit more details?
