### ISSUE TITLE
Single file version

### ISSUE THREAD

**Issue by skateman** [patternfly/patternfly-3#85]
So after 2 days of experimenting I've decided to give up on merging the `patternfly.less` and `patternfly-additions.less` files. @rhamilto I need one file, maybe `patternfly-single.less` which I can convert to SASS without having any static SASS in my code.

**Comment by rhamilto** [comment]
@skateman, will you still be able to output multple CSS files to avoid the IE9 limitation?

**Comment by skateman** [comment]
@rhamilto yes
