### ISSUE TITLE
Exclamation mark encoding on IE

### ISSUE THREAD

**Issue by survi91** [patternfly/patternfly-3#850]
Hi, 

I created a toast notification with following random string : 
Li!cense&#33; '!!!!!!!!!!!!!' lim&#33;mit r?e$ac*h(ed &#33;&#33;asdasdas

It turns out there is a problem with the way IE renders exclamation mark in toast notification. The other symbols in the string are displayed correctly. 

I am running IE (version 11.726.15063.0). The problem does not happen on FF neither on Chrome.

Attaching a print screen:
![toast_error](https://user-images.githubusercontent.com/33836678/33176360-b2173438-d056-11e7-8efc-22922e1fc6c4.png)

Do you think this is an issue or some misconfiguration on my side ?

**Comment by andresgalante** [comment]
Hi @survi91 Whats the encoding meta on your HTML? is it utf-8?

**Comment by matthewcarleton** [comment]
hi @survi91 were you able to follow up on this? Would like to help further upon your response.

**Comment by dabeng** [comment]
Hi @survi91 I wonder if you got correct render results when you access https://rawgit.com/patternfly/patternfly/master-dist/dist/tests/toast.html

**Comment by LHinson** [comment]
This issue has gotten stale and have heard no reply therefore I'm closing. @survi91 feel free to open another issue if need be!
