### ISSUE TITLE
Firefox errors

### ISSUE THREAD

**Issue by dlabrecq** [patternfly/patternfly-3#860]
The PatternFly test pages are generating a ton of errors in the Firefox console related to patternfly.min.css and patternfly-additions.min.css. This is carried forward/seen with other example apps for Angular PatternFly, RCUE, patternFly-ng, etc.

For example:

Error in parsing value for ‘-webkit-text-size-adjust’.  Declaration dropped.
patternfly.min.css:5:134
Unknown pseudo-class or pseudo-element ‘-webkit-inner-spin-button’.  Ruleset ignored due to bad selector.
patternfly.min.css:5:1409
Unknown pseudo-class or pseudo-element ‘-webkit-search-cancel-button’.  Ruleset ignored due to bad selector.
patternfly.min.css:5:1584
Unknown property ‘orphans’.  Declaration dropped.
patternfly.min.css:5:2476
Unknown property ‘widows’.  Declaration dropped.
patternfly.min.css:5:2486
Error in parsing value for ‘outline’.  Declaration dropped.
patternfly.min.css:5:15351
Error in parsing value for ‘outline’.  Declaration dropped.
...

More...

![screen shot 2017-11-30 at 3 23 01 pm](https://user-images.githubusercontent.com/17481322/33453115-7778099c-d5e2-11e7-940f-9ff75a498798.png)

**Comment by jeff-phillips-18** [comment]
I'm not seeing this with last patternfly in Firefox 57.0.1 (64-bit)

**Comment by dlabrecq** [comment]
I'm still seeing this with Firefox 57.0.4 (64-bit)

**Comment by dlabrecq** [comment]
Best seen with the patternfly test pages, but I see it with the patternfly-ng and angular patternfly demos as well.

**Comment by dtaylor113** [comment]
I'm not seeing this on FF v57.0b12 (Fedora/Linux 64-bit) using `https://rawgit.com/patternfly/patternfly/master-dist/dist/tests/`
No errors in console.

**Comment by michpetrov** [comment]
The errors come from CSS features that are not supported by Firefox (likewise Chrome has issues with Firefox/IE features although it isn't this loud about it), the only way to get rid of those would be to serve the browser a separate stylesheet.

**Comment by dlabrecq** [comment]
Resetting Firefox seems to resolve the issue. It wasn't just clearing the cache, but the "refresh firefox" in the about:support dialog. This is more of a profile reset, which forced me to reload my plugins, add-ons, etc.
