### ISSUE TITLE
Inconsistent style between sm and md listview icons

### ISSUE THREAD

**Issue by gregsheremeta** [patternfly/patternfly-3#864]
Inconsistent style between sm and md listview icons. This appears to be a css bug.

https://github.com/patternfly/patternfly/blob/fc906858d354ba7b1bd4b0e0f17e721abe0c0215/src/less/list-view.less
Line 206

&.list-view-pf-icon-sm {
  border: 2px solid @list-view-accented-border;

compiles to

.list-view-pf-left .fa.list-view-pf-icon-sm, .list-view-pf-left .pficon.list-view-pf-icon-sm {
    border: 2px solid #39a5dc;

The -md version doesn't have this blue border, and instead has a gray background.

They should be the same (other than size).

Screenshot:
medium network icon:
![selection_343](https://user-images.githubusercontent.com/2248293/33508987-e185d74e-d6cb-11e7-8d52-bc44182d1f08.png)

small network icon:
![selection_342](https://user-images.githubusercontent.com/2248293/33508992-e8573b44-d6cb-11e7-96a9-1afe08c26484.png)

**Comment by gregsheremeta** [comment]
cc @serenamarie125 @kybaker

**Comment by andresgalante** [comment]
Hi @gregsheremeta you are right, it's not correct, but I don't see how we can fix this without generating breaking changes to users using the -md size

**Comment by gregsheremeta** [comment]
@kybaker said it was the -sm blue that was incorrect

**Comment by andresgalante** [comment]
well, either way, if we change the `-sm` we'll creating a regression for the ones using it, right?

**Comment by gregsheremeta** [comment]
Depends on your definition of regression :) @kybaker said -sm should never have been blue, so it'll be fixing that

**Comment by matthewcarleton** [comment]
@gregsheremeta @andresgalante can we close this? It seems like it would introduce a breaking change which should be avoided.

**Comment by gregsheremeta** [comment]
No, IMO it should be fixed. We've hacked around it in oVirt, and I made a TODO in our code to remove the hack when the PatternFly bug is fixed.

When you release the fix, make sure people know about this potential break in the release notes. If you prefer, wait for a major version (3 -> 4 or whatever)

**Comment by serenamarie125** [comment]
@matthewcarleton I don't think we should be closing this.  It should be addressed in the next major release if it's a breaking change.

**Comment by matthewcarleton** [comment]
@LHinson should this be added to our milestone?

**Comment by LHinson** [comment]
Greg has found a work around in product for this one. Going to close.
