### ISSUE TITLE
Wizard: show keyboard focus in the steps

### ISSUE THREAD

**Issue by jgiardino** [patternfly/patternfly-3#869]
When I use the keyboard to navigate the steps in the [wizard](https://rawgit.com/patternfly/patternfly/master-dist/dist/tests/wizard.html), it is difficult to know which step has focus.

Note: In the [core test page](https://rawgit.com/patternfly/patternfly/master-dist/dist/tests/wizard.html), I'm not able to place focus on a primary step, but in the [pf-react implementation](https://github.com/patternfly/patternfly-react/pull/69), I can and in this example focus is visible.

**Comment by matthewcarleton** [comment]
Hey @jgiardino can you confirm I am looking at the right thing? This is what I see when I tab.
<img width="1064" alt="screen shot 2018-01-25 at 1 16 22 pm" src="https://user-images.githubusercontent.com/287880/35402160-1252f59c-01d2-11e8-94e2-d62c64782d0e.png">

**Comment by jgiardino** [comment]
I just checked. I do see focus now in the primary steps for both the core and react implementations. Focus doesn't work well with the secondary navigation, though (maybe that's what I meant to say instead of "primary"). In core, I see an underline like "1A. _Details" but other than that there's no change. In react, I see absolutely no change.

**Comment by matthewcarleton** [comment]
ah ok. Ya I checked in Safari and the underlines aren't there at all. Definitely something that should added. I'll put something together and get you to review when it's done, if you don't mind. Thanks!
