### ISSUE TITLE
Provide code samples / documentation for advanced form usage

### ISSUE THREAD

**Issue by lancejjohnson** [patternfly/patternfly-3#871]
Several sections of the Patternfly documentation on http://www.patternfly.org/pattern-library provide code samples for example usage of particular patternfly features. Very few of the features under the form section provide code samples. For example, the ["Progressive Disclosure"](http://www.patternfly.org/pattern-library/forms-and-controls/progressive-disclosure/) feature appears very useful but there is no documentation or code samples on how to use it. This doesn't appear to be a Bootstrap feature either, so there is no documentation provided by Bootstrap. Code samples / documentation on how to use form features would be very helpful.

**Comment by matthewcarleton** [comment]
Thanks @lancejjohnson. We are in the process of addressing this issue for patternfly.org. I'm going to close this and move it over to the org repo to properly track it.
