### ISSUE TITLE
Release notes include broken HTML markup

### ISSUE THREAD

**Issue by rhwood** [patternfly/patternfly-3#876]
Since 3.26.3, the release notes have included a broken HTML markup fragment ```<a name"VERSION">``` where VERSION is the current version. This probably just needs to be removed.

**Comment by LHinson** [comment]
this was a bug with the semantic release https://github.com/semantic-release/semantic-release/issues/363

we should fix globally

**Comment by AdamJ** [comment]
PatternFly-ng already uses the latest major release, so there will be no corresponding PR for that repo.

**Comment by LHinson** [comment]
Thanks @mindreeper2420 I'm going to close this.
