### ISSUE TITLE
[SASS] Invalid sass mixin breaks login page, container background-color absent 

### ISSUE THREAD

**Issue by AllenBW** [patternfly/patternfly-3#879]
`fade($color-pf-white, 5.5%)` [is not a valid option](http://sass-lang.com/documentation/Sass/Script/Functions.html), recommend using `rgba($color-pf-white, .055)`

[Offending code is here](https://github.com/patternfly/patternfly/blob/master/src/sass/converted/patternfly/_variables.scss#L88)

**Comment by AllenBW** [comment]
@jeff-phillips-18 or @dgutride can ya'll assign this to me?

**Comment by TheRealJon** [comment]
Resolved by PR #883. Sass conversion was ignoring less fade() functions that used decimal percentages. A new rule was added to ensure decimal percentages are now handled and properly converted to the sass rgba() function.
