### ISSUE TITLE
navbar-brand-icon and navbar-brand-name CSS classes don't limit image height

### ISSUE THREAD

**Issue by abkieling** [patternfly/patternfly-3#882]
Images used as logo or brand name of a page using vertical navigation are not limited to the expected maximum height (35px) and the page layout breaks. It would be good to add the `max-height: 35px;` rule to the `navbar-brand-icon` and `navbar-brand-name` CSS classes.

**Comment by matthewcarleton** [comment]
hey @akieling this has been resolved in #922
