### ISSUE TITLE
Selectpicker with placeholder indistinguishable from disabled selectpicker

### ISSUE THREAD

**Issue by himdel** [patternfly/patternfly-3#888]
After upgrading from 3.23 to 3.31, all our selectpickers look disabled :(.

non-disabled with placeholder in 3.23:

![localhost_3000_catalog_explorer 2](https://user-images.githubusercontent.com/289743/34044463-f914772c-e19c-11e7-9c7c-35ddc1447241.png)

non-disabled with placeholder now:

![localhost_3000_catalog_explorer](https://user-images.githubusercontent.com/289743/34044310-687b1ea0-e19c-11e7-9a71-52264504f6e7.png)

disabled:

![localhost_3000_catalog_explorer 1](https://user-images.githubusercontent.com/289743/34044399-b9df2be2-e19c-11e7-8885-908ee6f5cb8a.png)

Looks like the culprit is:

```
.bootstrap-select > .dropdown-toggle.bs-placeholder, .bootstrap-select > .dropdown-toggle.bs-placeholder:hover, .bootstrap-select > .dropdown-toggle.bs-placeholder:focus, .bootstrap-select > .dropdown-toggle.bs-placeholder:active {
    color: #999;
}
```

Cc @serenamarie125 

As per @mcarrano and @kybaker  here are the design directions:
when nothing is selected, the text is italicized, but not gray. When disabled, the text is gray. So you could potentially have a selection but also gray out the control.

**Comment by himdel** [comment]
Strictly speaking the 2 are not identical .. only indistinguishable :).

**Comment by serenamarie125** [comment]
oh my @himdel this isn't good!
@matthewcarleton @LHinson is this something we can look into?

**Comment by epwinchell** [comment]
> After upgrading from 3.23 to 3.31, all our selectpickers look disabled :(.

@himdel They look normal on my system. Where are you seeing this?


![screen shot 2017-12-15 at 10 01 44 am](https://user-images.githubusercontent.com/1287144/34047671-fe28f51c-e17e-11e7-8f32-80865d6aa9cf.png)

**Comment by himdel** [comment]
Thanks! :)

I think this is especially problematic when the whole form is just a selectpicker in the beginning..

![localhost_3000_catalog_explorer 3](https://user-images.githubusercontent.com/289743/34048275-09651132-e1ab-11e7-992e-d3d483ef3b15.png)

**Comment by himdel** [comment]
One tip.. Not sure if the problem comes more from the fact that the text is gray, or from the fact that so is the chevron..

(Also, visually it feels like even the border is grayer but that may be an illusion.)

**Comment by andresgalante** [comment]
Hi @himdel this is an old issue, was this fixed? I can't reproduce it, here is what we get in patternfly:
https://rawgit.com/patternfly/patternfly/master-dist/dist/tests/bootstrap-select.html

**Comment by himdel** [comment]
@andresgalante Yes, the issue is still present on the link you just posted :)

compare the Disabled select, with the Multiple Select select.

Both are completely grey, including the chevron. There is a slight shading difference, but ... it just looks disabled.

**Comment by himdel** [comment]
If you want to indicate that "Nothing selected" is special, I would suggest keeping the exact same style for the component as if it was enabled, *except* for just the text itself.

Right now, the "Multiple Select" comonent has:

* gray "Nothing Selected" as in disabled
* gray open chevron, as in disabled
~~* gray button border, as in disabled~~ (it just looks that way?, both are `#bbb`)
* 3d shading, unlike in disabled

IMO only the text itself should be grey, the rest of the component should not be changed.

**Comment by serenamarie125** [comment]
@andresgalante @LHinson is this something we can look into?  If so, I'd assume we need visual help first?

**Comment by matthewcarleton** [comment]
@serenamarie125 @himdel Looking into this now :)

**Comment by matthewcarleton** [comment]
@serenamarie125 @LHinson I agree. If we want to make this change we'll need some design input. I'm going to move this over to design to make sure it gets the proper attention. Thanks @himdel

**Comment by matthewcarleton** [comment]
after discussing this with design we've received direction. I'm reopening this issue. See notes above for design direction.

**Comment by himdel** [comment]
Thanks :). From the other issue, I can't tell if you're going to italicize the disabled version or the placeholder version, but I'm fine with either :)
