### ISSUE TITLE
Why is moment.js pinned at minor level rather than major?

### ISSUE THREAD

**Issue by ekohl** [patternfly/patternfly-3#892]
92cf2415923e499b4d2b7db05a08d5291774a11b added the dependency on moment but pins it at the minor level. Is there a reason not to pin at the major version? So ```^2.14.1``` rather than ```~2.14.1```.

**Comment by ohadlevy** [comment]
@jeff-phillips-18 any idea how to help @ekohl? thanks :)

**Comment by jeff-phillips-18** [comment]
I will take a pass at updating some of the underlying dependencies.
