### ISSUE TITLE
DataTables with checkbox Filter

### ISSUE THREAD

**Issue by tuxgasy** [patternfly/patternfly-3#895]
Hi,

I saw in the [documentation](http://www.patternfly.org/pattern-library/forms-and-controls/checkbox-filter/) that it'is possible to create a checkbox filter. But I do not see how to implement it.

**Comment by TheRealJon** [comment]
@tuxgasy The documentation on Patternfly.org is still a work in progress, but if you look at the file `patternfly.dataTables.pfFilter.js` in the `dist/js` directory of our package, there is a pretty detailed comment block at the top with examples of how to use this feature.

**Comment by dgutride** [comment]
Thanks @TheRealJon - moving to closed based on the above answer, @tuxgasy: please reopen or ask a new question if you need more assistance.
