### ISSUE TITLE
[docs] bad example for list-view

### ISSUE THREAD

**Issue by paoloantinori** [patternfly/patternfly-3#904]
https://www.patternfly.org/pattern-library/content-views/list-view/#/code/html-css

`Row Variation #5 displays like this:`

![screenshot from 2018-01-10 11-40-02](https://user-images.githubusercontent.com/1520602/34768406-04c3df32-f5fb-11e7-8e64-a21abaf73c9f.png)

On Fedora with Firefox 57.0.4, while fullscreen on a 1920x1080 resolution

**Comment by andresgalante** [comment]
@paoloantinori thanks a lot for reporting this issue. List view is correct: https://rawgit.com/patternfly/patternfly/master-dist/dist/tests/list-view-rows.html

This issue is due to collapsing styles on pf.org. I'll open an issue there and reference to this one.
