### ISSUE TITLE
Unable to locate Bootstrap or Font Awesome files on builds

### ISSUE THREAD

**Issue by AdamJ** [patternfly/patternfly-3#909]
When consuming PatternFly in the current iteration, builds cannot find the bootstrap.less file. The `patternfly.less` file, located in `node_modules/patternfly/dist/less` is looking for `bootstrap/less/bootstrap.less`, which does not exist.

Is there specific documentation for PatternFly that states A) why the `patternfly.less` file is looking in this particular path for a dependency when that path doesn’t appear valid, and B) how one can fix this issue?

**Comment by michpetrov** [comment]
Check your `node_modules`, that's where the less files are being pulled from, if they are not there it's probably an issue with your installation.

**Comment by AdamJ** [comment]
@michpetrov Installation is correct - nothing has been modified from what the package provides. This is what the directory looks like:
<img width="347" alt="screen shot 2018-01-12 at 8 28 18 am" src="https://user-images.githubusercontent.com/4032718/34877123-aec94cd8-f772-11e7-91ff-8b46f4a99964.png">

There is no `bootstrap/less` directory inside of the `dependencies` folder, which is where the `patternfly.less` file is looking for `bootstrap.less`.

I've removed and reinstalled all of the packages, with no positive affect.

**Comment by michpetrov** [comment]
No, `patternfly.less` is not looking into the `dependencies` folder, I do not know why that folder is being created but it's not for build purposes. (It might be the intent but the current build is pulling `boostrap.less` from `node_modules/bootstrap/less`.)

**Comment by AdamJ** [comment]
@michpetrov Correct, it is not looking in the `dependencies` folder - that was an error in typing. Older versions of PatternFly placed the files in different locations.

**Comment by jeff-phillips-18** [comment]
It should be finding it in the project's node_modules directory if correctly configured.

**Comment by AdamJ** [comment]
@jeff-phillips-18 as a story to update documentation/configuring has been created (https://github.com/patternfly/patternfly/issues/847), I'll close this and keep an eye on that. Thanks!
