### ISSUE TITLE
'patternfly-sass' gem version pointing to  '~> 2.2'

### ISSUE THREAD

**Issue by kirantpatil** [patternfly/patternfly-3#912]
Hi,

patternfly-sass gem is pointing to gem 'patternfly-sass', '~> 2.2'.

Is it correct, since patternfly-sass version is 3.37.0 ?

Thanks,

**Comment by TheRealJon** [comment]
@kirantpatil the patternfly-sass Ruby gem is currently at release 3.37.2. The ruby gem releases are kept in tandem with Patternfly releases. If you have this version constraint defined in your gemfile, it should be updated to `gem "patternfly-sass", "~> 3.37.0"`

**Comment by LHinson** [comment]
Thanks @TheRealJon for helping us out on this one. I'm going to close this issue. @kirantpatil feel free to follow up if need be!
