### ISSUE TITLE
Unable to @import patternfly when installed as gem

### ISSUE THREAD

**Issue by wgordon17** [patternfly/patternfly-3#915]
I have tried numerous @import options when install as gem, but none of them seem to work. It appears that perhaps the `dist/` directory structure doesn't match the expected `vendor/assets` directory structure as originally used in https://github.com/patternfly/patternfly-sass/tree/master/assets

**Comment by jeff-phillips-18** [comment]
@skateman Can you help @wgordon17 out?

**Comment by skateman** [comment]
@wgordon17 does this mean that you found a solution?

**Comment by wgordon17** [comment]
Yes, it also means I feel incredibly stupid! Restarting rails fixed the
issue...but it took me 30 mins to try that.
