### ISSUE TITLE
awkward file name `Logo_Horizontal_Reversed.svg alias`

### ISSUE THREAD

**Issue by martinpitt** [patternfly/patternfly-3#917]
Version 3.37.1 (and possibly earlier ones) now contain this file:

    ./node_modules/patternfly/dist/img/Logo_Horizontal_Reversed.svg alias

This looks like a bug in the dist/ generation scripts, and not actually intended. The embedded space causes all sorts of funny effects, like rpmbuild yelling

    error: File must begin with "/": alias

**Comment by TheRealJon** [comment]
@matthewcarleton It looks like this file was added to our source as part of PR https://github.com/patternfly/patternfly/pull/885. Could you clarify? Maybe accidental?

**Comment by matthewcarleton** [comment]
@TheRealJon oh hmmm, ya that is odd. It's shouldn't be in there. Not sure how that got created.
