### ISSUE TITLE
ListView close button in expansion area interferes with expansion content

### ISSUE THREAD

**Issue by jeff-phillips-18** [patternfly/patternfly-3#919]
The close button is overlaid on the expansion content which causes issues when there is content in that space.

See https://github.com/patternfly/patternfly-react/issues/153 for original details.

**Comment by matthewcarleton** [comment]
[This](https://github.com/patternfly/patternfly-design/pull/544) has been opened to address this issue.

**Comment by matthewcarleton** [comment]
Based on the new design docs, for this to be optional we will have to refactor the css. This will get added in the backlog.

**Comment by LHinson** [comment]
story link is here: https://patternfly.atlassian.net/browse/PTNFLY-2806
