### ISSUE TITLE
Issues with  navbar-brand-icon and navbar-brand-txt styling in vertical navigation

### ISSUE THREAD

**Issue by jeff-phillips-18** [patternfly/patternfly-3#920]
The navbar-brand-icon does not set a height therefore if an image with > 35px in height is used the masthead height grows and does not work properly with the left vertical nav menus.

The navbar-brand-txt does not set a line-height and the text does not align vertically. Setting a line-height of 34px aligns it correctly.

I'm not sure if this effects horizontal nav as well.

**Comment by matthewcarleton** [comment]
hey @jeff-phillips-18 so are you thinking a max-height:35px; on the image and a line-height of 34px on the text?

**Comment by mturley** [comment]
This is now being resolved as part of #922
