### ISSUE TITLE
css issue with table view on patternfly-sass 3.37.1

### ISSUE THREAD

**Issue by kirantpatil** [patternfly/patternfly-3#923]
Hi,

I used table view code from http://www.patternfly.org/pattern-library/content-views/table-view/.

I am getting css issue as shown below attached image.

![screenshot-2018-1-22 hocc 1](https://user-images.githubusercontent.com/1178055/35216579-1331d276-ff8e-11e7-8a0b-ae811fcd06cf.png)

**Comment by TheRealJon** [comment]
@kirantpatil could you clarify what you mean by patternfly-sass? The patternfly-sass npm package is no longer maintained, but there is still a ruby gem which should remain in tandem with this repo. Or are you referring to the Sass in this repo?

**Comment by dtaylor113** [comment]
@TheRealJon, @kirantpatil might mean that he is using the sass we now auto-generate from our less files:  https://github.com/patternfly/patternfly/tree/master-dist/dist/sass

**Comment by TheRealJon** [comment]
I assume that this is the case, but the wording of the issue title is a little confusing. I just wanted to make sure before trying to help.

**Comment by dtaylor113** [comment]
:+1:

**Comment by kirantpatil** [comment]
I am using [patternfly-sass](https://rubygems.org/gems/patternfly-sass) gem.

**Comment by TheRealJon** [comment]
@kirantpatil Are you using the latest release of this gem (3.37.2)? Also, could you post an example of the html structure that causes this issue so that we can test and try to duplicate?

**Comment by kirantpatil** [comment]
@TheRealJon,

I upgraded to patternfly-sass (3.37.4) and still issue persist.

### Please find the below code 
#### index.html.erb
------------------
```

<div class="container" style= "padding-top: 40px;width:1250px; pdding-left:20px;">
<div class=" col-sm-12 col-md-12">
<div class="card-pf card-pf-accented card-pf-aggregate-status white">
<div class="card-pf-body white">
<div class="row">
  <div class="col-sm-4" style="width:3.33%">
  <%=link_to "New Case",new_incident_path, class:"btn btn-danger btn-lg",style: "color:white;" %>
</div>
</div>
  <br/>

<table class="table table-striped table-bordered" id="myTable">
  <thead >
    <tr class="c3">
      <td colspan="12" class="text-center" style='text-transform:uppercase'><b>EXISTING CASE DETAILS </b>
      </td>
    </tr>
    <tr>
      <th class="c2">Case ID</th>
      <th class="c2">Sub Id</th>
      <th class="c2">Sub Name</th>
```
#### main.js
------------

```
$('#myTable').DataTable( {
        "order": [[ 0, "desc" ]]
    } );

```


To verify I downgraded to other patternfly version and with 3.10.0 I don't see this css issue. Below is attached screenshot with v3.10.0.

![screenshot-2018-1-24 hocc](https://user-images.githubusercontent.com/1178055/35316651-d6949eae-00f8-11e8-81c6-dc235f8fdd75.png)

**Comment by TheRealJon** [comment]
@kirantpatil I can't seem to duplicate this issue. A few points:

1. You are wrapping your table in a `card-pf-aggregate-status` element which is an unusual use of this design pattern. See http://www.patternfly.org/pattern-library/cards/aggregate-status-card. I'm not sure if this could be having some unexpected side effects.

1. I noticed you are using the classes "c3" and "c2" on some of the table elements. Is it possible that there are some rules that are overriding patternfly?

1. Can you use your browser inspector to narrow down which css rules are causing the header rows to be taller?

**Comment by kirantpatil** [comment]
If I add records to it then the headers will start to shrink to display the rows as below.

Shall I close this issue ?

![image](https://user-images.githubusercontent.com/1178055/35614623-bef4ed6a-0695-11e8-95b9-4c1637d19354.png)

**Comment by kirantpatil** [comment]
I am using Firefox version 58 which is latest.

**Comment by TheRealJon** [comment]
@kirantpatil Were you able to pinpoint any CSS rules that are affecting the table styles? I have been unable to duplicate the issue, so I can't verify that this is a PatternFly problem.

**Comment by kirantpatil** [comment]
Sorry I am not good at CSS. I tried but couldn't figure out. To verify, I can host the app in aws and provide you app login details. Is it ok for you ?

Please send me testmail to kirantpatil@gmail.com

**Comment by LHinson** [comment]
hey @kirantpatil, is it possible for you to produce a URL to show the issue that you are trying to resolve?

**Comment by kirantpatil** [comment]
@LHinson, let me host it and share the link.

Please share your gmailid to kirantpatil@gmail.com, and I will send URL with credentials to login.

**Comment by LHinson** [comment]
@kirantpatil I hope you were able to find some CSS expertise to help you! I'm going to close this issue against PatternFly since this is not a PF bug, rather specific to your implementation.
