### ISSUE TITLE
examples not working with hyphenated variables

### ISSUE THREAD

**Issue by michpetrov** [patternfly/patternfly-3#924]
Same problem as #738, I haven't properly checked other pages. This affects expand/collapse functionality and error feedback (both in forms.html) but only in a local build using liquid.

There is also another problem with [navbar-vertical.html](https://github.com/patternfly/patternfly/blob/74cdae7f189969478663d88b5801efc2a57e51cd/tests/pages/_includes/widgets/layouts/navbar-vertical.html#L42-L44). Even with the variable fixed the notification drawer stays hidden because the page doesn't include the bell button, e.g. [here](http://rawgit.com/patternfly/patternfly/master-dist/dist/tests/vertical-navigation-with-tertiary-no-icons.html). I'm not sure what the purpose of [this code](https://github.com/patternfly/patternfly/blob/74cdae7f189969478663d88b5801efc2a57e51cd/tests/pages/_includes/widgets/navigation/vertical-navigation.html#L2-L6) is, since the drawer gets included either way.

This should be all, I haven't found any other hyphenated variables. (Interestingly things like `page.notification-drawer` work fine with hyphens.)

**Comment by dgutride** [comment]
@michpetrov  - is your commit a fix for this, if so - would you like to create a PR for it?

**Comment by michpetrov** [comment]
@dgutride hm, I don't know why I didn't submit that, I'll recheck the codebase and submit it

**Comment by LHinson** [comment]
Thanks @michpetrov!
