### ISSUE TITLE
DataTables lengthMenu support

### ISSUE THREAD

**Issue by skateman** [patternfly/patternfly-3#93]
http://datatables.net/reference/option/lengthMenu

**Comment by rhamilto** [comment]
@skateman, can you elaborate on what is needed?  PatternFly includes DataTables 1.10.7, which supports the lengthMenu option.

**Comment by skateman** [comment]
This option is missing from the patternfly version:
![screenshot from 2015-08-13 16-20-04](https://cloud.githubusercontent.com/assets/649130/9252182/64fb424e-41d7-11e5-98ff-d4c26891a2d0.png)

**Comment by rhamilto** [comment]
Ah.  Thanks for clarifying, @skateman! 

PatternFly's recommended implementation of datatables excludes the length option.  However, it's easily added by initializing data tables using your own js.  

See https://github.com/patternfly/patternfly/blob/master/dist/js/patternfly.js#L82 and http://legacy.datatables.net/ref#sDom for details on how to change the configuration of the data tables header.
