### ISSUE TITLE
There is a UI mess on List View page

### ISSUE THREAD

**Issue by dabeng** [patternfly/patternfly-3#931]
<img width="1600" alt="screen shot 2018-01-24 at 3 44 12 pm" src="https://user-images.githubusercontent.com/5689075/35320147-c9633374-011d-11e8-8921-f18a140334c7.png">

**Comment by michpetrov** [comment]
Reported (and closed) previously: #904

**Comment by matthewcarleton** [comment]
@dabeng I'm going to close this one, it belongs in .org which was already created here [#505](https://github.com/patternfly/patternfly-org/issues/505)
