### ISSUE TITLE
There is an unexpected space between table header and table body

### ISSUE THREAD

**Issue by dabeng** [patternfly/patternfly-3#932]
<img width="1220" alt="screen shot 2018-01-24 at 4 18 11 pm" src="https://user-images.githubusercontent.com/5689075/35322782-71f607f2-0126-11e8-808a-971784931e92.png">

**Comment by matthewcarleton** [comment]
Thanks for posting this @dabeng. It looks like this only exists on the examples so this should be moved to the patternfly.org repo.

**Comment by mcarrano** [comment]
This seems like a new issue as I have never seen this before. Anyone have any idea what's going on here and why? @cliffpyles @amarie401

**Comment by dabeng** [comment]
Hi @mcarrano , I find the cause of this issue. Let's discuss it on https://github.com/patternfly/patternfly-org/issues/514
