### ISSUE TITLE
patternfly blog login page doesn't look good

### ISSUE THREAD

**Issue by dabeng** [patternfly/patternfly-3#935]
<img width="1600" alt="screen shot 2018-01-25 at 6 32 59 pm" src="https://user-images.githubusercontent.com/5689075/35383921-b4d7889c-01fe-11e8-9824-84b030281723.png">

**Comment by matthewcarleton** [comment]
@dabeng this should be in .org, I've opened an issue there.

**Comment by dabeng** [comment]
Hi @matthewcarleton , I think this issue belongs to [patternfly-blog](https://github.com/patternfly/patternfly-blog), there isn't any issues on that repo since creating it , so I have to report this issue to here.

**Comment by matthewcarleton** [comment]
Hey @dabeng no problem. I believe this was addressed in the issue on the .org repo [here](https://github.com/patternfly/patternfly-org/issues/513)
