### ISSUE TITLE
can not find "conduct guidelines for this repository"

### ISSUE THREAD

**Issue by dabeng** [patternfly/patternfly-3#936]
<img width="872" alt="screen shot 2018-01-25 at 6 38 58 pm" src="https://user-images.githubusercontent.com/5689075/35384157-62a3a14a-01ff-11e8-8916-79f5c245e832.png">

<img width="857" alt="screen shot 2018-01-25 at 6 39 08 pm" src="https://user-images.githubusercontent.com/5689075/35384164-677cf02c-01ff-11e8-93d0-65c2c6c765da.png">

<img width="838" alt="screen shot 2018-01-25 at 6 39 30 pm" src="https://user-images.githubusercontent.com/5689075/35384172-6b7bdf44-01ff-11e8-8fdf-762a23932263.png">

**Comment by LHinson** [comment]
@dabeng it's great that you are filing issues to make us aware how we need to update PatternFly. I would like to see you follow up these issues with PRs to help contribute to a fix.

**Comment by dabeng** [comment]
Hi @LHinson . Once we verify the issue is a valuable feature improvement or real bug, I'm glad to commit according PR.
