### ISSUE TITLE
jQuery.fn.resize() event shorthand is deprecated

### ISSUE THREAD

**Issue by abkieling** [patternfly/patternfly-3#939]
Based on the [jQuery Migrate Plugin documentation](https://github.com/jquery/jquery-migrate/blob/master/warnings.md#jqmigrate-jqueryfnclick-event-shorthand-is-deprecated), event shorthands should be replaced with `.on()` and `.trigger()` methods.

The PatternFly code uses the window `resize()` shortcut method in the following places:
https://github.com/patternfly/patternfly/blob/c214e177ce9e7426431238e8b3db0fa39f27ab0a/src/js/patternfly-functions-fixed-heights.js#L84
https://github.com/patternfly/patternfly/blob/c214e177ce9e7426431238e8b3db0fa39f27ab0a/src/js/patternfly-functions-sidebar.js#L25

**Comment by dabeng** [comment]
+1 . For now, the jquery dependency of patternfly-core is upgraded to verison 3.2.1. We'd better to use recommendation syntax - `.on( "resize", handler )`

https://github.com/jquery/jquery-migrate/blob/master/warnings.md#jqmigrate-jqueryfnclick-event-shorthand-is-deprecated

@jeff-phillips-18 @cliffpyles  Any thoughts ?

**Comment by dgutride** [comment]
@dabeng @cliffpyles @jeff-phillips-18  - @dabeng's recommendation seems like a reasonable change to make and schedule for

**Comment by jeff-phillips-18** [comment]
Agreed

**Comment by dabeng** [comment]
The related [PR](https://github.com/patternfly/patternfly/pull/1089) has been sent.

**Comment by LHinson** [comment]
This PR has been merged so closing this issue!
