### ISSUE TITLE
Inconsistency between HTML/CSS and React Implementation for field level help

### ISSUE THREAD

**Issue by jgiardino** [patternfly/patternfly-3#943]
We have a [PR in patternfly-react](https://github.com/patternfly/patternfly-react/pull/179) for adding a FieldLevelHelp component based on the [patternfly design documentation](https://rawgit.com/dabeng/patternfly-org/dt-space-dist/_site/pattern-library/forms-and-controls/help-on-forms/), but there isn't an html/css implementation for us to follow. 

There are a couple of issues I've noticed in the current patternfly-react implementation:
1. When the help icon has focus, the outline is really close to the text.
2. In the horizontal form, when the icon is included for a field, the field label is no longer right-aligned with the other labels as the design documentation shows. 

![image](https://user-images.githubusercontent.com/21063328/35595364-783841ee-05e4-11e8-82bd-8bc9f39c7268.png)

**Comment by andresgalante** [comment]
This element was part of patternfly at one point, I don't know why or when it was removed. I suspect the code is still in the codebase but I couldn't digg it up :(

**Comment by LHinson** [comment]
I also could not find the implementations on our test pages. I've added this as a PF Scrum issue https://patternfly.atlassian.net/browse/PTNFLY-2804

**Comment by matthewcarleton** [comment]
Hey @LHinson @jgiardino this is still on the test pages but it's in a strange place. https://rawgit.com/patternfly/patternfly/master-dist/dist/tests/popovers.html

**Comment by LHinson** [comment]
@amarie401 see the link above and scroll all the way to the bottom of the page. That is where you will find field level help. Will you help to get this posted to the site?

**Comment by amarie401** [comment]
@matthewcarleton @LHinson where exactly on the site does this need to go under? I see that it is currently under the popover examples.

**Comment by LHinson** [comment]
@amarie401 it goes on the code page here: https://rawgit.com/dabeng/patternfly-org/dt-space-dist/_site/pattern-library/forms-and-controls/help-on-forms/

**Comment by amarie401** [comment]
Got it @LHinson thanks!

**Comment by amarie401** [comment]
As I was looking through the code it appears this is already on the site. Is there something I'm missing? @LHinson 

http://www.patternfly.org/pattern-library/forms-and-controls/help-on-forms/#code

https://github.com/patternfly/patternfly-design/commit/df3e7e1d1e8c745f10d208f7a7dd90347f65d2e6

**Comment by jgiardino** [comment]
Hey @amarie401, 

The example we have on pf.org is from the patternfly-react implementation, but we don't have a core html/css implementation. The items noted in this issue were some things that I noticed with the pf-react version that didn't sync very well with the design. I was hoping with this issue that we could get the html/css version as we want it to be while addressing the issues that I noted, and then we could revisit the pf-react version as needed.

**Comment by amarie401** [comment]
Ah I see, @jgiardino 
I was tasked with adding the test page example for this to the website but it appears that it is already there once I started digging through the code in pf-org so I wasn't sure if I was missing something. If there are any future changes to the html/css in core then it should update on the site. Since the example from the test pages is already on the website I will un-assign myself from that task @LHinson.

**Comment by jgiardino** [comment]
I'm sorry, my brain is partly shutdown for the day. I totally misread that pf.org page as "this is the example being pulled in from pf-react". 

Yeah, I'm not sure that anything else needs to happen to pull the core example in.

I'd say the items noted in the original issue description are still valid, unless we want to close it as a "will fix in pf next" issue, which is fine with me too.

**Comment by mcarrano** [comment]
@jgiardino I'm a little confused about this one. We do have core HTML/CSS for this here: http://www.patternfly.org/pattern-library/forms-and-controls/help-on-forms/#code In looking at the React implementation, the only deviation I see is that the info icon should not be blue until the user hovers on it. This was a recent change. I can't seem to produce the condition you show in the issue description with the blue focus rectangle.

**Comment by jgiardino** [comment]
Maybe the designs were recently updated? I totally remember that all the label text was right-aligned with the help icon hanging out in the space between the labels and inputs. But now they're not. And I think at the time, there wasn't a code example that we could find.

I'll close this issue. And I added this one for patternfly-react updates: https://github.com/patternfly/patternfly-react/issues/354

**Comment by jgiardino** [comment]
After chatting with Jeff, we realized there are a couple of differences between what we have in pf-react and core.

In pf-react:

1. element is a button
2. popover displays on click/Enter key

In core:

1. element is an anchor
2. popover displays on focus

Our preference is to keep the pf-react html and behavior for the following reasons:

1. Using a button as the tooltip toggle is semantically correct. Links should be used for linking to other pages or sections of content.
2. Displaying the tooltip popover on click/Enter enables keyboard access to the popover if it includes links to additional information. The current implementation of the tooltip in pf-react isn't ideal, since the popover doesn't come after the toggle in the DOM and requires tabbing through other contents on the page to finally get to it, but it at least is accessible.

But we'd like to adjust the spacing so that the icon isn't immediately next to the label when the focus ring is visible. The pf core implementation includes this spacing using a white space character in the markup, but our preference is to define the spacing with css. Does it make sense to reopen this issue to address this item from the original issue description, and update the css to address the spacing?:

> 1. When the help icon has focus, the outline is really close to the text.


Here are some screencaps of the two implementations:

**pf-react**
![image](https://user-images.githubusercontent.com/21063328/40782866-ae83d79e-64ae-11e8-8a86-160548eb4e84.png)

**pf core**
![image](https://user-images.githubusercontent.com/21063328/40782880-c03361f8-64ae-11e8-9fd3-e9ca25a920f8.png)

**Comment by LHinson** [comment]
@jgiardino and this one
