### ISSUE TITLE
pfToolbar Button Alignment Wrapping Issue

### ISSUE THREAD

**Issue by jcaianirh** [patternfly/patternfly-3#946]
When wrapping, the buttons in a pfToolbar should become left justified when shrunk to < 768 pixels rather than have a small left indent as seen in the example below:

![patternflycoretoolbarbuttonwrap](https://user-images.githubusercontent.com/35978579/35704353-37b6f5e0-076d-11e8-9166-6876ab0bdd5c.png)

This stems from the original issue in angular-patternfly located here:
https://github.com/patternfly/angular-patternfly/issues/681

**Comment by andresgalante** [comment]
Hi @jcaianirh this is not happening on patternfly CSS https://rawgit.com/patternfly/patternfly/master-dist/dist/tests/toolbar.html

Are you sure the angular implementation is correctly reproducing the HTML?

**Comment by LHinson** [comment]
Hey @jcaianirh, let us know if this ends up being a PatternFly issue and we'll be happy to address. For now, I'm closing.
