### ISSUE TITLE
TreeGrid table is slow with large datasets 

### ISSUE THREAD

**Issue by jamesnetherton** [patternfly/patternfly-3#947]
I'm working with a TreeGrid table which has around 600 items. It's quite slow to do the initial tree view render and when subsequently expanding or collapsing any of the tree nodes.

After a brief bit of profiling, it seems much of the time is being spent [here](https://github.com/patternfly/patternfly/blob/master/src/js/patternfly-functions-tree-grid.js#L10).

Does it need to use `closest`? Parent is the id attribute of some `<tr>` element that should be considered the parent tree node. Isn't this unique? If so, instead of `closest`, maybe we use `parent = $(parent)`. It performs much better.

**Comment by dabeng** [comment]
Hi @jamesnetherton , I agree with you. `rows.closest(parent)` will bring performance impact. It's better to replace `rows.closest(parent)` with `$(parent)`

@dlabrecq @jeff-phillips-18 @cliffpyles  Any thoughts ?

**Comment by dlabrecq** [comment]
Not certain $(parent) is the correct syntax here, but .parent() should return the direct parent of a node. You can also do something more like $(“child”).parent();

**Comment by jamesnetherton** [comment]
Not sure `$(parent)` or `$("child").parent() ` is correct either. Parent is set like this:

```javascript
var parent = node.attr('data-parent');
```
A typical value will look like `#some-parent-id`. We just need to do an element look up against that value.   So `$(parent)` should be ok (I think). I hacked my local copy of patternfly.js to use this and it seems to be working fine.

**Comment by dabeng** [comment]
@LHinson @cliffpyles I did a [testing](https://codepen.io/dabeng/pen/xWRXyX) with Chrome DevTools. The Demo TreeGrid Table has more than 400 rows. I found that it will take 1000 ms to collapse the child rows of "Parent 1".

![treegrid table testing](https://user-images.githubusercontent.com/5689075/37580640-d534cc58-2b7f-11e8-9dbf-9738db21ece6.gif)

<img width="671" alt="screen shot 2018-03-19 at 2 07 14 pm" src="https://user-images.githubusercontent.com/5689075/37580730-3fbcbb58-2b80-11e8-9a77-b2f74b35e93c.png">

**Comment by dabeng** [comment]
[TreeGrid Table Testing2](https://codepen.io/dabeng/pen/wmopwd) works well as expected.

<img width="672" alt="screen shot 2018-03-19 at 2 08 23 pm" src="https://user-images.githubusercontent.com/5689075/37580825-b428f6b4-2b80-11e8-8a5d-05700c9fb3aa.png">

The testing2 adopted the following modification:
`rows.closest(parent) => $(parent)`

**Comment by dabeng** [comment]
@dlabrecq @LHinson @cliffpyles feel free to check out the demos, e.g. expand or collapse nested rows.

- [TreeGrid Table Testing](https://codepen.io/dabeng/pen/xWRXyX)
-  [TreeGrid Table Testing2](https://codepen.io/dabeng/pen/wmopwd)

**Comment by dgutride** [comment]
@dabeng - let's use the test 2 code you wrote and move to $(parent) - the performance improvement is significant.  In my tests - when parent evaluates to a selector (not a row id) - it works, so only replacing the .closest() function with the $(parent) selector is correct

**Comment by dgutride** [comment]
@LHinson  - reassigning back to @dabeng with comments,  we can move forward with his prototype code

**Comment by LHinson** [comment]
Thanks @dgutride and @dabeng

**Comment by dabeng** [comment]
Hi @dgutride , please review this PR - https://github.com/patternfly/patternfly/pull/1054

**Comment by LHinson** [comment]
This PR has been merged so I'm closing here. Thanks @dabeng @dgutride
