### ISSUE TITLE
conflicting guidelines about breadcrumbs

### ISSUE THREAD

**Issue by andreasn** [patternfly/patternfly-3#949]
We wanted to make sure we used the correct breadcrumb bar in Cockpit, but upon closer inspection, it seems there are two different ones in Patternfly. Slightly different from each other.
Breadcrumb on Widgets page http://www.patternfly.org/pattern-library/widgets/#breadcrumbs
Breadcrumb on Navigation page http://www.patternfly.org/pattern-library/navigation/breadcrumbs/

What one is correct, and should the incorrect one be removed?

**Comment by mcarrano** [comment]
It looks like the difference here is in styling where the basic Bootstrap breadcrumb uses a double ">" and the Bootstrap pattern page a single ">".  So I assuming the question is whether to use "first level >> second level >> current page" or 'first level > second level > current page'. Is that your question @andreasn ? 

@kybaker any thoughts on which visual styling we should be using? I don't think it was intentional to make these different.

**Comment by andreasn** [comment]
@mcarrano yes, that and if we should use the divider or not. (number 5 [here](http://www.patternfly.org/pattern-library/navigation/breadcrumbs/#design)
It also seems like the code example on the [react code example page](https://rawgit.com/patternfly/patternfly-react/gh-pages/index.html?selectedKind=Breadcrumb&selectedStory=Breadcrumb&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybooks%2Fstorybook-addon-knobs) looks different from what's shown on [the design page](http://www.patternfly.org/pattern-library/navigation/breadcrumbs/#design).

**Comment by kybaker** [comment]
@mcarrano @andreasn This is an example of PatternFly exposing all bootstrap widgets by default and later documenting them in another place. But in this case they are using very similar styling. We should be using the single arrow for both. You could also show the breadcrumb in the container or not depending on the layout so both are correct from that perspective.

**Comment by mcarrano** [comment]
Thanks, @kybaker If that's the case, then our sample code should also change to reflect that. Is this something we can update @andresgalante ?  This change should also be mirrored in the React repo. @priley86 FYI

**Comment by LHinson** [comment]
@matthewcarleton to follow up with @kybaker on this to confirm the double arrow approach. If so, here are our next steps: 

We will mark the breadcrumb widget as deprecated on the site to avoid further confusion and point to the breadcrumbs pattern page as the single point of truth. That way, we will not break anyone using the double arrow. Also, a bug should be filed against react.

**Comment by kybaker** [comment]
@LHinson @matthewcarleton @mcarrano After reconsidering this issue we are in agreement that it makes sense to take the time to correct this issue and move toward a breadcrumb with a single arrow.
