### ISSUE TITLE
Tree List View with Muti-Child Expansion

### ISSUE THREAD

**Issue by beanh66** [patternfly/patternfly-3#950]
We have a request for the [Tree List View with Multi-Child Expansion](http://www.patternfly.org/pattern-library/content-views/tree-list-view/#design) in Angular. Currently there is no implementation for PF Core, so if possible, we would be looking to get this into core and then follow up with the Angular implementation.  The ADS Team in IT is looking for this component. See related Angular issue here: https://github.com/patternfly/angular-patternfly/issues/702

@dtaylor113 @matthewcarleton @LHinson  FYI

**Comment by LHinson** [comment]
@beanh66 The current pf-list implementation [1] does support the addition of nested rows. That said, after reviewing the implementation, we found that there is a discrepancy between the design and the implementation that we must resolve. I will be leaving for PTO and back the week of 2/19 and have scheduled a meeting for that week to discuss best next steps. Apologies for the delay here but at least wanted to make it known we are working to get this resolved in the coming weeks. 

Let me know if there is any concerns. 

[1] https://rawgit.com/patternfly/patternfly/master-dist/dist/tests/list-pf.html

**Comment by LHinson** [comment]
After our meeting today, we have determined that the design documentation with nested rows will remain until a mobile strategy is defined for PatternFly. You should be all set with the core implementation therefore I would like to close this issue @beanh66. Please let me know if there are any concerns with this.

**Comment by beanh66** [comment]
@LHinson I created this issue originally because I don't see anything on the PF site as far as a core implementation goes: http://www.patternfly.org/pattern-library/content-views/tree-list-view/#code. If there is already an implementation, can we get it up on the main code page?

**Comment by LHinson** [comment]
I've added this to the PF Scrum backlog to contribute to the core code https://patternfly.atlassian.net/browse/PTNFLY-2780

**Comment by LHinson** [comment]
@dabeng is currently working on contributing this

**Comment by beanh66** [comment]
Thanks @LHinson!

**Comment by dabeng** [comment]
Hi @beanh66 @mindreeper2420 @michael-coker , please review demo page:

- [Tree List View - Single Child Expansion](https://rawgit.com/dabeng/patternfly/tree-list-view-dist/dist/tests/tree-list-view-single-child-expansion.html)
- [Tree List View - Multiple Child Expansion](https://rawgit.com/dabeng/patternfly/tree-list-view-dist/dist/tests/tree-list-view-multiple-child-expansion.html)

**Comment by matthewcarleton** [comment]
Thanks for doing this @dabeng. This shows the issue we have with smaller screens though. @LHinson have we agreed to just move forward with this not being responsive?

**Comment by LHinson** [comment]
@matthewcarleton yes, until we have a mobile strategy in place, this will remain as the design specifies.

**Comment by mcoker** [comment]
There is a `z-index` issue with the kebab menu in selected rows. Otherwise it looks good to me.

![screen shot 2018-03-05 at 9 16 52 am](https://user-images.githubusercontent.com/35148959/36982651-f7607fbe-2055-11e8-997f-14eba3124d35.png)
![screen shot 2018-03-05 at 9 16 29 am](https://user-images.githubusercontent.com/35148959/36982653-f7871962-2055-11e8-973b-9c1610e8e68d.png)

**Comment by matthewcarleton** [comment]
@michael-coker can you provide browser/version you are seeing this in? I tried in Safari, Firefox, Chrome and don't get the same result. 

@LHinson 👍

**Comment by mcoker** [comment]
@matthewcarleton Chrome 64.0.3282.186 (Mac). It only happens when the row is selected.

**Comment by matthewcarleton** [comment]
@michael-coker ah that's what I was missing

**Comment by beanh66** [comment]
Thanks @dabeng, looks good. @dtaylor113 please take a look as well.

**Comment by dtaylor113** [comment]
LGTM, although is this supposed to work with https://rawgit.com/patternfly/patternfly/master-dist/dist/tests/list-view-compound-expansion.html ?  I could see someone wanting to add open/close arrows on those middle icons and counts.

**Comment by LHinson** [comment]
@dtaylor113 there is no design documentation specifying how that particular design would work. See: http://www.patternfly.org/pattern-library/content-views/tree-list-view/#overview

For that reason, I'm considering it separate and out of scope for this PR.

**Comment by dabeng** [comment]
Hi @michael-coker @matthewcarleton , I have made a update to fix the z-index issue. Could you review the demo page again ?

**Comment by mcoker** [comment]
@dabeng LGTM!

**Comment by LHinson** [comment]
Closing this issue since it was addressed by #980 and can be viewed here: http://www.patternfly.org/pattern-library/content-views/tree-list-view/#code
