### ISSUE TITLE
Card Title Overwrites Default Heading Styles

### ISSUE THREAD

**Issue by AdamJ** [patternfly/patternfly-3#956]
In a Card, the class `.card-pf-title` overwrites the default HTML heading styles for PatternFly. This appears to be the only place that overwrites the default HTML elements - all other places (in the list views, empty states, etc.) use styled `<div>` tags.

This overwrite is causing issues when the [typography](http://www.patternfly.org/styles/typography/) page states one style, but the cards have another.

**Comment by LHinson** [comment]
@mindreeper2420 when say "causing issues" can you be specific about what those issues are? I didn't know if there was an issue beyond that it just doesn't match what is stated in the typography page. Thanks for clarifying!

**Comment by AdamJ** [comment]
@LHinson Would "causing confusion" be more appropriate? There have been a few instances where designs reference the typography page to use a specific heading style but when the Card Titles don't match that, there is confusion as to what is the appropriate style.

I.E. The Typography page has `<h2>` as `font-size: 22px`, yet the `<h2>` within the Card Title is overwritten to be `font-size: 16px`

**Comment by LHinson** [comment]
OK thanks @mindreeper2420 

Let me validate the size, I do believe this was intentional. Assuming that's correct, I'll add a bug to patternfly-design to identify the the rhyme and reason for this on the pattern documentation. 

I'll get back to you!

**Comment by LHinson** [comment]
I'm going to close this issue but please let me know if you have any concerns
