### ISSUE TITLE
Info Tip should not dismiss when clicking on it.

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-3#957]
Info tips should only close when either clicking outside the area of the tip window or by an action taken via clicking on an element inside the tip (i.e. a close button). This is not true for the current example. See https://rawgit.com/patternfly/patternfly/master-dist/dist/tests/infotip.html

**Comment by Mgranfie** [comment]
@mcarrano would the dismissal also include, if a content item, like an action item in the tip? It looks like one of these items would be clickable, navigable and then it would close on clicking of a line item, not the background.

**Comment by mcarrano** [comment]
Yes, one could put an action inside the tip to close it, but it should not close just by clicking on the tip/background itself.

**Comment by LHinson** [comment]
In addition to the click behavior, there is more issues with info tip.... 

1. Info Tip is a confusing name as this is a variation of the drop down. 
2. We should visit the design to determine if we are using (i) icon is being used appropriately. 

These are all breaking changes therefore lumping them into the "Next Major Release" milestone so we can coordinate on all these changes.

**Comment by dabeng** [comment]
Hi @mcarrano I'm afraid that this is a default behavior of bootstrap dropdown. IMO, the simple solution is to prevent "the click inside dropdown-menu" event bubble. For more details, please refer to this [question](https://stackoverflow.com/a/32922725/5890833) on stackoverflow.

**Comment by LHinson** [comment]
@mcarrano I'm going to close this for now as this is a breaking change to PF3 that I'd like to avoid. I see the related react PR was merged therefore don't believe this is blocking anything. Reach out to me with any questions / comments.
