### ISSUE TITLE
Replace 'pf-red-100' with 'pf-red-300' when used in core PatternFly examples.

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-3#958]
An issue was filed against patternfly-design noting that pf-red-100 should not be used for error indicators as this is the Red Hat brand color. See https://github.com/patternfly/patternfly-design/issues/558 for more details.

Want to replace instances where 'pf-red-100' is used with 'pf-red-300' in code examples and test pages.

**Comment by mcarrano** [comment]
@matthewcarleton this issue was raised from the design side and you can see @kybaker 's comments there. Can you take a look at this to see what it would take to make these updates? Glad to pull together a meeting with you, Kyle, and I if it will help. Thnx.

**Comment by matthewcarleton** [comment]
Hey @mcarrano we can do this, but it will be a breaking change. Are we ok with that @LHinson?

**Comment by LHinson** [comment]
I'm ok with this breaking change however we have a number of things that we want to consider for short term visual changes therefore I would like to wait to understand those first and coordinate around that so we can group any and all breaking changes together. @mcarrano @matthewcarleton 

@mcarrano I believe this topic is on deck for the next pf-design meeting?

**Comment by LHinson** [comment]
@kybaker and the visual design team have a current effort to ensure that the PatternFly color palette is in sync with brand for pf-next. We will punt this issue for that major release so closing there.
