### ISSUE TITLE
Notification drawer wastes space by showing up at fixed height

### ISSUE THREAD

**Issue by KwisatzHaderach** [patternfly/patternfly-3#959]
When notification drawer doesn't contain enough items, it still draws itself over the whole page.
It might be better to draw it only as high as it's necessary to display all visible items and not below that.
![notif_drawer](https://user-images.githubusercontent.com/2510105/36431017-c468b4e0-1656-11e8-88d3-cc8a441712f1.png)

**Comment by matthewcarleton** [comment]
thanks @KwisatzHaderach. I think this would be more of a patternfly design issue though so I'm moving it over there.
