### ISSUE TITLE
Tooltip location is far from the pointer on the donut charts demo page

### ISSUE THREAD

**Issue by ncameronbritt** [patternfly/patternfly-3#963]
On the [donut chart demo page](https://rawgit.com/patternfly/patternfly/master-dist/dist/tests/donut-charts.html) the tool tip appears quite far away from the pointer. See below:
![screen shot 2018-02-23 at 2 13 13 pm](https://user-images.githubusercontent.com/8974593/36612165-c2764946-18a3-11e8-9b43-beecd4a445ff.png)

The issue seems to affect the 2nd, 3rd, and 4th examples on that page.

**Comment by ncameronbritt** [comment]
cc @TheRealJon

**Comment by michpetrov** [comment]
Looks like the chart container has to be a block element, I'll fix it.
