### ISSUE TITLE
Cannot deploy PatternFly (bower) to webjars.org 

### ISSUE THREAD

**Issue by dlabrecq** [patternfly/patternfly-3#964]
PatternFly is typically deployed to webjars.org via Travis scripts run during the semantic release. However, I was also not able to deploy manually via webjars.org -- anyone can deploy. In either scenario, I encounter the same error.

The error message states that the following repos have non-spec-compliant licenses:

- https://github.com/spencewood/google-code-prettify.git
- https://github.com/patternfly/patternfly-bootstrap-combobox.git
- https://github.com/DataTables/ColVis.git

Looking at the packages myself and I see that:

- google-code-prettify  has no license at all in bower.json
- patternfly-bootstrap-combobox has "Apache 2.0" in bower,json, but should be "Apache-2.0"
- datatables-colvis has an MIT license

Note that the npm package still deploys fine. Although, folks may prefer the bower deploy because that contains all our source code, unlike the npm package?

That said, I've disabled the bower deploy (for the semantic release) until the license issues are resolved. The bower deploy wastes a lot of time to waiting for webjars.org to find compatible licenses. 

To test if the license issues have been resolved, deploy manually on webjars.org.

**Comment by dgutride** [comment]
Requires investigation to understand the level of effort involved

**Comment by dgutride** [comment]
Spoke with Dan  -closing until the community indicates there is a need for this (been more than six months since it worked so nobody must be using it).
