### ISSUE TITLE
Change image paths on single sign on to be dynamic for org to consume

### ISSUE THREAD

**Issue by amarie401** [patternfly/patternfly-3#968]
I am in the process of adding the single-sign-on code example to pf-org using the `login-single-sign-on.html` as an include. Currently the google drive svg, gmail svg, and google calendar svg have paths of:

`{{site.assets-base}}/img/google-drive.svg"`
`{{site.assets-base}}/img/gmail.svg`
`{{site.assets-base}}/img/google-calendar.svg`

pf-org cannot find this path because it points to `/patternfly-org/img/{name}.svg` instead of `/patternfly-org/assets/img/{name}.svg` 

Images inside of org are in an assets directory. To solve this issue and make it more dynamic for org to consume, they each would need to be changed to something like this for example: `{{site.assets-base}}/{{site.google-drive}}"` then create a google-drive variable in the `_config.yml` file and have it point to `google-drive: /img/google-drive.svg` which would then allow me in pf-org to add the svg's to the `assets/img` directory and in the `_config.yml` file have it point to `google-drive: assets/img/google-drive.svg` so that it associates that variable to the correct path that pf-org can recognize

I had to do this with `brand-horizontal` when using the html from `login-basic.html` in this [PR](https://github.com/patternfly/patternfly-org/pull/526/files#diff-e6422af2c5a3ea680839278540cfdf29R14)

I can take on this issue if you want @matthewcarleton @cliffpyles.

**Comment by matthewcarleton** [comment]
Hey @amarie401 if you have the time and want to take care of it that would be great, thanks!

**Comment by andresgalante** [comment]
The code looks ok, thanks a lot @amarie401 

@LHinson if we are ok showing copyrighted logos, please merge it
