### ISSUE TITLE
Update img paths on login social accounts

### ISSUE THREAD

**Issue by amarie401** [patternfly/patternfly-3#972]
Similar to issue #968 to update the image paths of the login components to be more dynamic for org to consume.

Need to update: 
https://rawgit.com/patternfly/patternfly/master-dist/dist/tests/login-social-account.html

@matthewcarleton does Login Social Account (two column) also need to be updated?

Thanks!

**Comment by matthewcarleton** [comment]
Hey @amarie401, ya it's basically the same just a second column of the same markup. Let me know if you need any help with it.

**Comment by amarie401** [comment]
Since we aren't showing login social account on the current website, there will be no need to update the image path for this. I'm going to go ahead and close this issue, if there is a decision to include this example on the website at some point then we can reopen this.
