### ISSUE TITLE
Disabled pager does not show `not-allowed` cursor

### ISSUE THREAD

**Issue by AllenBW** [patternfly/patternfly-3#975]
<img width="1920" alt="screen shot 2018-03-05 at 2 24 02 pm" src="https://user-images.githubusercontent.com/6640236/36995006-e163a882-2080-11e8-8438-2149b61d50f2.png">

☝️ look, see? Its not a disabled cursor 😭 on drats, doesn't show the cursor, well... just know... it doesn't show `not-allowed`

Offending line is here:
https://github.com/patternfly/patternfly/blob/master/src/less/pager.less#L35

**Comment by jeff-phillips-18** [comment]
Would be nice to have styling to allow the use of a button rather than an anchor as well.
