### ISSUE TITLE
Consistent readme.md across PatternFly's primary component repos 

### ISSUE THREAD

**Issue by LHinson** [patternfly/patternfly-3#978]
PatternFly should have a standard approach / template for the information seen in the readme.md. To address this issues requires looking all the readmes across the following repos: 
* patternfly/patternfly
* patternfly/ng
* patternfly/angular
* patternfly/react

The result should be a proposal for a consistent readme that contains like information across.

**Comment by stacymcauliffe** [comment]
- [ ] Review and compare contrib guidelines for the different repos
- [ ] Review and compare readmes for the different repos
- [ ] Recommend a standard approach for both documents - what info should be included where
- [ ] Determine next steps to create consistency across repos

**Comment by stacymcauliffe** [comment]
Created some slides with observations - last slide contains recommendations. @LHinson let me know if you want to create a new issue for updates or touch base briefly and talk about this work and how it impact PF3 and related work that will need to happen for PF4.

https://docs.google.com/presentation/d/1sJj9yJyie3UATgk6bciNI3LadjqduVaLYS0XUFnK17k/edit?usp=sharing
