### ISSUE TITLE
Context selector dropdown presentation differs from dropdown

### ISSUE THREAD

**Issue by rhamilto** [patternfly/patternfly-3#981]
Context selector dropdown
![screen shot 2018-03-07 at 10 38 09 am](https://user-images.githubusercontent.com/895728/37101616-fd392324-21f3-11e8-8e9f-7f19343767b0.PNG)

Dropdown
![screen shot 2018-03-07 at 10 38 29 am](https://user-images.githubusercontent.com/895728/37101622-003c44ac-21f4-11e8-8461-53fcaa7fd74a.PNG)

Presumably the dropdowns should have the same presentation since they perform similar functions?

* padding around items
* hover color'

Attn: @LHinson

**Comment by LHinson** [comment]
Thanks @rhamilto! @matthewcarleton is going to take this one.
