### ISSUE TITLE
Pattern enhancement - Cards with no data available

### ISSUE THREAD

**Issue by jgiardino** [patternfly/patternfly-3#982]
The need for a card with no data available came up in the following PR: 
https://github.com/patternfly/patternfly-react/pull/212

Also, this patternfly issue is somewhat related: https://github.com/patternfly/patternfly-design/issues/588

For now in pf-react, we're using the empty state pattern inside the card, with some style changes for the context of the card (see examples pasted below). But these implementations don't align very well with the "No Data Available" example in the [design documentation](http://www.patternfly.org/pattern-library/cards/base-card/#design).

Can the css for cards be extended to support the examples shown in the design documentation, including the following use cases?:

- A card has no data and the user can add data (i.e. empty state with an action)
- A card has no data and the user cannot add data (i.e. empty state without an action)

![image](https://user-images.githubusercontent.com/21063328/37096774-b91b6a50-21e7-11e8-9f11-5c017bbeec7e.png)

**Comment by LHinson** [comment]
@mcarrano any concern with proceeding with this implementation? Do we also need an issue for design docs?

**Comment by mcarrano** [comment]
@jgiardino @LHinson There is currently an open issue in patternfly-design here: https://github.com/patternfly/patternfly-design/issues/623. @sjcox-rh is assigned to work on that. We should just make sure this implementation is in sync with SJ's design.

Note also that the above issue references an empty state in Card View which is distinct from empty dashboard cards. There is another open design issue #619 that references that case which is mot currently being worked on.

**Comment by LHinson** [comment]
OK, starting with the dashboard emtpy state design make sense. Let's hold off on this implementation. Thanks @mcarrano
