### ISSUE TITLE
Vertical Navigation on mobile has hamburger left aligned while Horizontal has it right aligned

### ISSUE THREAD

**Issue by lizsurette** [patternfly/patternfly-3#998]
Is it intentional that if we use Horizontal navigation, the hamburger icon should be right aligned vs to the left of the branding as it's called out in Vertical navigation? Just trying to be sure I'm following PatternFly standards.

**Comment by mcarrano** [comment]
@lizsurette We wanted to make Horizontal Nav consistent, but decided that the code rework was more than we wanted to bite off. Am I correct in that @matthewcarleton . Most of our newer designs are using Vertical Nav so we made a conscious decision not not invest much energy here.

Can you tell me more what's behind this question? Do you have a team looking to consume the current PF core implementation for this?

**Comment by lizsurette** [comment]
That makes total sense @mcarrano. The TripleO UI still uses Horizontal Nav and as I was fixing a bug with the mobile size view and the hamburger menu, I noticed the descrepancy and just wanted to follow up and make sure I was following the correct PatternFly recommendation.

**Comment by matthewcarleton** [comment]
yup, that is correct. I believe we talked this through a couple months ago and came to that conclusion @mcarrano.

**Comment by lizsurette** [comment]
Sounds great. Thanks guys I will close!
